# Persian translation of anaconda to Persian.
# Copyright (C) 2003, 2004 Abbas Izad
# Copyright (C) 2004 Hedayat Vatankhah
# Copyright (C) 2005, 2006 Sharif FarsiWeb, Inc.
# This file is distributed under the same license as the anaconda package.
# Abbas Izad <abbasizad@hotmail.com>, 2003, 2004.
# Hedayat Vatankhah <hedavat@mail15.com>, 2004.
# Roozbeh Pournader <roozbeh@farsiweb.info>, 2005, 2006.
# Hamed Malek <hamed@farsiweb.info>, 2005.
# Meelad Zakaria <meelad@farsiweb.info>, 2005, 2006.
# Elnaz Sarbar <elnaz@farsiweb.info>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: anaconda\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-03-27 15:38-0400\n"
"PO-Revision-Date: 2006-05-13 15:09+0330\n"
"Last-Translator: Meelad Zakaria <meelad@farsiweb.info>\n"
"Language-Team: Persian\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../anaconda:266 ../anaconda:312
#, fuzzy, python-format
msgid "Error processing %%ksappend lines: %s"
msgstr "خطا در باز کردن پروندهٔ راه‌اندازی %s:‏ %s"

#: ../anaconda:269 ../anaconda:315
#, python-format
msgid "Unknown error processing %%ksappend lines: %s"
msgstr ""

#: ../anaconda:283 ../anaconda:327 ../cmdline.py:86 ../gui.py:1251
#: ../text.py:543
#, python-format
msgid ""
"The following error was found while parsing your kickstart configuration:\n"
"\n"
"%s"
msgstr ""
"خطای زیر هنگام تجزیهٔ پیکربندی kickstart پیدا شد:\n"
"\n"
"‏%s"

#: ../anaconda:449
msgid "Press <enter> for a shell"
msgstr ""

#: ../anaconda:458
#, fuzzy
msgid "Fatal Error"
msgstr "خطا"

#: ../anaconda:459
#, fuzzy, python-format
msgid ""
"You do not have enough RAM to install %s on this machine.\n"
"\n"
"Press <return> to reboot your system.\n"
msgstr "شما برای نصب %s روی این رایانه به اندازهٔ کافی حافظهٔ RAM ندارید."

#: ../anaconda:464 ../rescue.py:285 ../rescue.py:311 ../rescue.py:324
#: ../rescue.py:397 ../rescue.py:406 ../text.py:694
#: ../textw/constants_text.py:44 ../loader/cdinstall.c:228
#: ../loader/cdinstall.c:232 ../loader/cdinstall.c:248
#: ../loader/cdinstall.c:251 ../loader/cdinstall.c:445
#: ../loader/cdinstall.c:452 ../loader/cdinstall.c:517
#: ../loader/dirbrowser.c:145 ../loader/driverdisk.c:98
#: ../loader/driverdisk.c:243 ../loader/driverdisk.c:274
#: ../loader/driverdisk.c:305 ../loader/driverdisk.c:340
#: ../loader/driverdisk.c:359 ../loader/driverdisk.c:371
#: ../loader/driverdisk.c:379 ../loader/driverdisk.c:539
#: ../loader/driverdisk.c:576 ../loader/driverselect.c:81
#: ../loader/driverselect.c:205 ../loader/hdinstall.c:143
#: ../loader/hdinstall.c:289 ../loader/hdinstall.c:352
#: ../loader/hdinstall.c:384 ../loader/hdinstall.c:454
#: ../loader/hdinstall.c:497 ../loader/hdinstall.c:510 ../loader/kbd.c:138
#: ../loader/kickstart.c:132 ../loader/kickstart.c:142
#: ../loader/kickstart.c:185 ../loader/kickstart.c:284
#: ../loader/kickstart.c:375 ../loader/kickstart.c:553 ../loader/lang.c:115
#: ../loader/lang.c:378 ../loader/loader.c:402 ../loader/loader.c:438
#: ../loader/loader.c:481 ../loader/loader.c:502 ../loader/loader.c:519
#: ../loader/loader.c:556 ../loader/loader.c:1203 ../loader/loader.c:1378
#: ../loader/mediacheck.c:46 ../loader/mediacheck.c:85
#: ../loader/mediacheck.c:92 ../loader/mediacheck.c:101 ../loader/method.c:279
#: ../loader/method.c:353 ../loader/modules.c:335 ../loader/modules.c:347
#: ../loader/net.c:564 ../loader/net.c:937 ../loader/net.c:1541
#: ../loader/net.c:1564 ../loader/net.c:1808 ../loader/net.c:1830
#: ../loader/net.c:1842 ../loader/nfsinstall.c:91 ../loader/nfsinstall.c:248
#: ../loader/nfsinstall.c:267 ../loader/nfsinstall.c:335
#: ../loader/telnetd.c:92 ../loader/urlinstall.c:83 ../loader/urlinstall.c:107
#: ../loader/urlinstall.c:175 ../loader/urlinstall.c:418
#: ../loader/urlinstall.c:427 ../loader/urlinstall.c:436 ../loader/urls.c:292
#: ../loader/urls.c:328 ../loader/urls.c:334 ../loader/urls.c:346
msgid "OK"
msgstr "تأیید"

#: ../anaconda:471
msgid ""
"You do not have enough RAM to use the graphical installer.  Starting text "
"mode."
msgstr ""
"برای استفاده از نصب کنندهٔ گرافیکی به قدر کافی حافظهٔ RAM ندارید. حالت متنی "
"آغاز می‌شود."

#: ../anaconda:534
msgid "Starting graphical installation..."
msgstr "نصب گرافیکی آغاز می‌شود..."

#: ../anaconda:823
#, fuzzy
msgid "Would you like to use VNC?"
msgstr "می‌خواهید چه‌کار کنید؟"

#: ../anaconda:824
msgid ""
"Text mode provides a limited set of installation options.  It does not allow "
"you to specify your own partitioning layout or package selections.  Would "
"you like to use VNC mode instead?"
msgstr ""

#: ../anaconda:852
msgid "Install class forcing text mode installation"
msgstr "ردهٔ نصبی‌ای که نصب در حالت متنی را اجباری می‌کند"

#: ../anaconda:871
msgid "Graphical installation not available...  Starting text mode."
msgstr "نصب گرافیکی ممکن نیست...  حالت متنی آغاز می‌شود."

#: ../anaconda:879
msgid "DISPLAY variable not set. Starting text mode!"
msgstr ""

#: ../anaconda:1047
msgid "reipl configuration successful => reboot"
msgstr ""

#: ../anaconda:1050
msgid "reipl configuration failed => halt"
msgstr ""

#: ../backend.py:144
#, fuzzy, python-format
msgid "Upgrading %s\n"
msgstr "در حال ارتقاء دادن %s-%s-%s.%s.\n"

#: ../backend.py:146
#, fuzzy, python-format
msgid "Installing %s\n"
msgstr "_نصب %s"

#: ../backend.py:166
msgid "Copying File"
msgstr "در حال نسخه‌برداری از پرونده"

#: ../backend.py:167
msgid "Transferring install image to hard drive..."
msgstr "در حال انتقال تصویر نصب به دیسک‌سخت..."

#: ../backend.py:177
#, fuzzy
msgid ""
"An error occurred transferring the install image to your hard drive.  This "
"is probably due to bad media."
msgstr ""
"هنگام انتقال تصویر نصب به دیسک‌سخت شما خطایی رخ داد. احتمالاً دیسک‌تان جا ندارد."

#: ../backend.py:181
msgid ""
"An error occurred transferring the install image to your hard drive. You are "
"probably out of disk space."
msgstr ""
"هنگام انتقال تصویر نصب به دیسک‌سخت شما خطایی رخ داد. احتمالاً دیسک‌تان جا ندارد."

#: ../backend.py:185 ../image.py:285 ../livecd.py:189 ../livecd.py:382
#: ../partIntfHelpers.py:202 ../text.py:460 ../text.py:464
#: ../yuminstall.py:371 ../yuminstall.py:664 ../yuminstall.py:779
#: ../yuminstall.py:1056 ../yuminstall.py:1124 ../yuminstall.py:1312
#: ../yuminstall.py:1337 ../iw/autopart_type.py:100 ../iw/autopart_type.py:199
#: ../iw/autopart_type.py:328 ../iw/autopart_type.py:331
#: ../iw/autopart_type.py:360 ../iw/osbootwidget.py:209
#: ../iw/osbootwidget.py:218 ../iw/raid_dialog_gui.py:700
#: ../iw/raid_dialog_gui.py:739 ../iw/task_gui.py:63 ../iw/task_gui.py:161
#: ../iw/task_gui.py:292 ../iw/task_gui.py:414 ../textw/netconfig_text.py:271
#: ../textw/partition_text.py:178 ../textw/partition_text.py:184
#: ../textw/partition_text.py:206 ../textw/upgrade_text.py:175
#: ../textw/upgrade_text.py:182 ../storage/__init__.py:268
#: ../storage/__init__.py:1423 ../storage/__init__.py:1439
#: ../loader/cdinstall.c:228 ../loader/cdinstall.c:517
#: ../loader/driverdisk.c:98 ../loader/driverdisk.c:305
#: ../loader/driverdisk.c:340 ../loader/driverdisk.c:371
#: ../loader/driverdisk.c:379 ../loader/driverdisk.c:443
#: ../loader/hdinstall.c:143 ../loader/hdinstall.c:352
#: ../loader/hdinstall.c:454 ../loader/hdinstall.c:497
#: ../loader/hdinstall.c:510 ../loader/kickstart.c:284 ../loader/lang.c:115
#: ../loader/loader.c:402 ../loader/loader.c:519 ../loader/loader.c:1203
#: ../loader/mediacheck.c:46 ../loader/mediacheck.c:85
#: ../loader/mediacheck.c:92 ../loader/method.c:279 ../loader/method.c:353
#: ../loader/nfsinstall.c:248 ../loader/nfsinstall.c:267
#: ../loader/telnetd.c:92 ../loader/urlinstall.c:83 ../loader/urlinstall.c:107
#: ../loader/urlinstall.c:175 ../loader/urls.c:328 ../loader/urls.c:334
msgid "Error"
msgstr "خطا"

#: ../bootloader.py:43 ../bootloader.py:198 ../image.py:82
#: ../partedUtils.py:169 ../partedUtils.py:199 ../partedUtils.py:835
#: ../partedUtils.py:985 ../upgrade.py:298 ../yuminstall.py:1510
#: ../yuminstall.py:1539 ../iw/autopart_type.py:209 ../iw/blpasswidget.py:151
#: ../iw/upgrade_swap_gui.py:192 ../iw/upgrade_swap_gui.py:200
#: ../iw/upgrade_swap_gui.py:207 ../textw/upgrade_text.py:187
#: ../storage/devicetree.py:125 ../storage/devicetree.py:150
msgid "Warning"
msgstr "اخطار"

#: ../bootloader.py:44
#, fuzzy
msgid ""
"Your filesystems have already been activated.  You cannot go back past this "
"point.\n"
"\n"
"Would you like to continue with the installation?"
msgstr ""
"گزینه‌های افرازبندی‌ای که انتخاب کرده‌اید از قبل فعال شده‌اند. دیگر نمی‌توانید به "
"صفحهٔ ویرایش دیسک بازگردید. آیا می‌خواهید روند نصب را ادامه دهید؟"

#: ../bootloader.py:48 ../exception.py:468 ../exception.py:485
#: ../exception.py:508 ../exception.py:523 ../exception.py:548 ../gui.py:1256
#: ../gui.py:1384 ../gui.py:1461 ../image.py:91 ../livecd.py:196
#: ../livecd.py:389 ../packages.py:127 ../packages.py:135 ../packages.py:143
#: ../packages.py:151 ../packages.py:163 ../packages.py:172 ../packages.py:180
#: ../packages.py:189 ../upgrade.py:100 ../upgrade.py:120 ../upgrade.py:253
#: ../yuminstall.py:783 ../yuminstall.py:863 ../yuminstall.py:869
#: ../yuminstall.py:1027 ../yuminstall.py:1052 ../yuminstall.py:1112
#: ../yuminstall.py:1307 ../yuminstall.py:1344 ../storage/__init__.py:85
#: ../storage/__init__.py:1508
#, fuzzy
msgid "_Exit installer"
msgstr "نصب کنندهٔ %s"

#: ../bootloader.py:48 ../image.py:92 ../image.py:248 ../kickstart.py:1214
#: ../kickstart.py:1253 ../partedUtils.py:988 ../upgrade.py:100
#: ../upgrade.py:120 ../yuminstall.py:1117 ../iw/partition_gui.py:1036
#: ../storage/__init__.py:1509
msgid "_Continue"
msgstr "_ادامه"

#: ../bootloader.py:105 ../platform.py:90 ../platform.py:253
#: ../platform.py:297 ../platform.py:358
msgid "RAID Device"
msgstr "دستگاه RAID"

#: ../bootloader.py:134
msgid "Bootloader"
msgstr "بارکنندهٔ راه‌انداز"

#: ../bootloader.py:134
msgid "Installing bootloader..."
msgstr "در حال نصب بارکنندهٔ راه‌انداز..."

#: ../bootloader.py:199
msgid ""
"No kernel packages were installed on your system.  Your boot loader "
"configuration will not be changed."
msgstr ""
"هیچ‌کدام از بسته‌ها‌ی هسته روی سیستم شما نصب نشده است. پیکربندی بارکنندهٔ "
"راه‌انداز شما تغییر داده نخواهد شد."

#: ../cmdline.py:55
msgid "Completed"
msgstr "تمام شد"

#: ../cmdline.py:63
msgid "In progress...   "
msgstr "در حال پیشرفت...   "

#: ../cmdline.py:98
msgid "Can't have a question in command line mode!"
msgstr "در حالت سطر فرمان نمی‌شود سؤال پرسید!"

#: ../constants.py:74
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report"
msgstr ""

#: ../constants.py:80
msgid " with the provider of this software."
msgstr ""

#: ../constants.py:84
#, fuzzy, python-format
msgid " against anaconda at %s"
msgstr "در حال خواندن به‌هنگام‌سازی‌های آناکوندا..."

#: ../exception.py:391
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""

#: ../exception.py:394
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in anaconda:\n"
"\n"
"%s"
msgstr ""

#: ../exception.py:398
#, fuzzy
msgid "Unable To File Bug"
msgstr "حذف ممکن نیست"

#: ../exception.py:404
#, fuzzy
msgid "Bug Filing Not Supported"
msgstr "پشتیبانی نمی‌شود"

#: ../exception.py:405
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr ""

#: ../exception.py:411
#, fuzzy
msgid "Invalid Bug Information"
msgstr "اطلاعات IP‏ نامعتبر است"

#: ../exception.py:412
msgid "Please provide a valid username, password, and short bug description."
msgstr ""

#: ../exception.py:424
#, fuzzy
msgid "Unable To Login"
msgstr "ویرایش ممکن نیست"

#: ../exception.py:425
#, python-format
msgid ""
"There was an error logging into %s using the provided username and password."
msgstr ""

#: ../exception.py:462
msgid "Bug Created"
msgstr ""

#: ../exception.py:463
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""

#: ../exception.py:479
#, fuzzy
msgid "Bug Updated"
msgstr "به‌هنگام‌سازی"

#: ../exception.py:480
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""

#: ../exception.py:504 ../exception.py:519 ../exception.py:544
msgid "Dump Written"
msgstr "تخلیه نوشته شد"

#: ../exception.py:505 ../exception.py:520
msgid ""
"Your system's state has been successfully written to the disk. The installer "
"will now exit."
msgstr ""

#: ../exception.py:511 ../exception.py:528 ../exception.py:551
msgid "Dump Not Written"
msgstr ""

#: ../exception.py:512 ../exception.py:529
msgid "There was a problem writing the system state to the disk."
msgstr ""

#: ../exception.py:535 ../exception.py:558 ../rescue.py:201
#: ../yuminstall.py:1022
#, fuzzy
msgid "No Network Available"
msgstr "دستگاه‌های شبکه‌ای"

#: ../exception.py:536 ../exception.py:559
msgid ""
"Cannot save a bug report since there is no active networking device "
"available."
msgstr ""

#: ../exception.py:545
msgid ""
"Your system's state has been successfully written to the remote host.  The "
"installer will now exit."
msgstr ""

#: ../exception.py:552
msgid "There was a problem writing the system state to the remote host."
msgstr ""

#: ../gui.py:106
msgid "An error occurred copying the screenshots over."
msgstr "هنگام نسخه‌برداری از عکس‌های ‌صفحه خطایی رخ داد."

#: ../gui.py:117
msgid "Screenshots Copied"
msgstr "عکس‌های ‌صفحه نسخه‌برداری شد"

#: ../gui.py:118
msgid ""
"The screenshots have been saved into the directory:\n"
"\n"
"\t/root/anaconda-screenshots/\n"
"\n"
"You can access these when you reboot and login as root."
msgstr ""
"عکس‌های صفحه در شاخهٔ زیر ذخیره شده‌اند:\n"
"\n"
"‏\t/root/anaconda-screenshots/\n"
"\n"
"شما می‌توانید با راه‌اندازی مجدد و ورود به سیستم به عنوان root به آنها دست "
"یابید."

#: ../gui.py:161
msgid "Saving Screenshot"
msgstr "در حال ذخیرهٔ عکس‌صفحه"

#: ../gui.py:162
#, python-format
msgid "A screenshot named '%s' has been saved."
msgstr "عکس‌صفحه‌ای به نام «%s» ذخیره شد."

#: ../gui.py:165
msgid "Error Saving Screenshot"
msgstr "خطا در ذخیرهٔ عکس‌صفحه"

#: ../gui.py:166
msgid ""
"An error occurred while saving the screenshot.  If this occurred during "
"package installation, you may need to try several times for it to succeed."
msgstr ""
"هنگام ذخیرهٔ عکس‌صفحه خطایی رخ داد. اگر خطا هنگام نصب بسته رخ داده است، شاید "
"لازم باشد چندین بار تلاش کنید تا موفق شوید."

#: ../gui.py:546 ../text.py:500
#, fuzzy
msgid "Installation Key"
msgstr "روش نصب"

#: ../gui.py:617 ../text.py:308
msgid ""
"Choose a passphrase for your encrypted devices. You will be prompted for the "
"passphrase during system boot."
msgstr ""

#: ../gui.py:636 ../gui.py:644 ../text.py:346 ../text.py:356
#, fuzzy
msgid "Error with passphrase"
msgstr "خطا در گذرواژه"

#: ../gui.py:637 ../text.py:347
#, fuzzy
msgid "The passphrases you entered were different.  Please try again."
msgstr "گذرواژه‌هایی که وارد کردید فرق داشتند. لطفاً دوباره تلاش کنید."

#: ../gui.py:645
#, fuzzy
msgid "The passphrase must be at least eight characters long."
msgstr "طول گذرواژه باید حداقل شش نویسه باشد."

#: ../gui.py:679 ../text.py:380
#, python-format
msgid ""
"Device %s is encrypted. In order to access the device's contents during "
"installation you must enter the device's passphrase below."
msgstr ""

#: ../gui.py:736
#, python-format
msgid "Bugzilla (%s)"
msgstr ""

#: ../gui.py:766
#, fuzzy
msgid "No devices found"
msgstr "گرداننده‌ای پیدا نشد"

#: ../gui.py:873 ../gui.py:1461 ../partIntfHelpers.py:149
#: ../partIntfHelpers.py:304 ../text.py:98 ../text.py:99
#: ../textw/constants_text.py:48 ../loader/dirbrowser.c:145
#: ../loader/driverdisk.c:244 ../loader/kickstart.c:375 ../loader/loader.c:438
#: ../loader/loader.c:556
msgid "Cancel"
msgstr "انصراف"

#: ../gui.py:885 ../gui.py:886 ../gui.py:998 ../gui.py:999
#: tmp/anaconda.glade.h:2
msgid "_Debug"
msgstr "_اشکال‌زدایی"

#: ../gui.py:1049 ../gui.py:1051 ../gui.py:1458 ../livecd.py:113
#, fuzzy
msgid "Exit installer"
msgstr "نصب کنندهٔ %s"

#: ../gui.py:1051 ../text.py:283 ../text.py:291
msgid "Debug"
msgstr "اشکال‌زدایی"

#: ../gui.py:1053 ../text.py:287
msgid "Exception Occurred"
msgstr "استثنایی رخ داد"

#: ../gui.py:1253 ../text.py:545
msgid "Error Parsing Kickstart Config"
msgstr "خطا در تجزیهٔ پیکربندی kickstart"

#: ../gui.py:1293
msgid "default:LTR"
msgstr "default:RTL"

#: ../gui.py:1373 ../text.py:659
msgid "Error!"
msgstr "خطا!"

#: ../gui.py:1374 ../text.py:660
#, python-format
msgid ""
"An error occurred when attempting to load an installer interface component.\n"
"\n"
"className = %s"
msgstr ""
"هنگام تلاش برای بار کردن مؤلفهٔ واسط نصب خطایی رخ داد.\n"
"\n"
"className = %s"

#: ../gui.py:1379 ../image.py:164 ../image.py:194 ../packages.py:428
#: ../packages.py:433
msgid "_Exit"
msgstr "_خروج"

#: ../gui.py:1380 ../image.py:164 ../image.py:194 ../livecd.py:196
#: ../yuminstall.py:656 ../yuminstall.py:1052 ../yuminstall.py:1112
#: ../yuminstall.py:1307
msgid "_Retry"
msgstr "_دوباره سعی شود"

#: ../gui.py:1383 ../packages.py:432
msgid "The installer will now exit..."
msgstr "حالا برنامه نصب خارج می‌شود..."

#: ../gui.py:1386 ../packages.py:435
msgid "Your system will now be rebooted..."
msgstr "حالا سیستم شما مجدداً راه‌اندازی می‌شود..."

#: ../gui.py:1387 ../image.py:248 ../packages.py:436 ../partedUtils.py:987
#: ../yuminstall.py:1360
msgid "_Reboot"
msgstr "_راه‌اندازی مجدد"

#: ../gui.py:1389
#, fuzzy
msgid "Exiting"
msgstr "خروج"

#: ../gui.py:1459
#, fuzzy
msgid "Are you sure you wish to exit the installation?"
msgstr "آیا مطمئنید می‌خواهید جلد منطقی «%s» را حذف کنید؟"

#: ../gui.py:1468
#, python-format
msgid "%s Installer"
msgstr "نصب کنندهٔ %s"

#: ../gui.py:1475
msgid "Unable to load title bar"
msgstr "بار کردن نوار عنوان ممکن نیست"

#: ../gui.py:1531
msgid "Install Window"
msgstr "پنجرهٔ نصب"

#: ../image.py:83
#, python-format
msgid ""
"The ISO image %s has a size which is not a multiple of 2048 bytes.  This may "
"mean it was corrupted on transfer to this computer.\n"
"\n"
"It is recommended that you exit and abort your installation, but you can "
"choose to continue if you think this is in error."
msgstr ""

#: ../image.py:156
msgid "Couldn't Mount ISO Source"
msgstr ""

#: ../image.py:157
#, python-format
msgid ""
"An error occurred mounting the source device %s.  This may happen if your "
"ISO images are located on an advanced storage device like LVM or RAID, or if "
"there was a problem mounting a partition.  Click exit to abort the "
"installation."
msgstr ""

#: ../image.py:185
msgid "Missing ISO 9660 Image"
msgstr ""

#: ../image.py:186
#, python-format
msgid ""
"The installer has tried to mount image #%s, but cannot find it on the hard "
"drive.\n"
"\n"
"Please copy this image to the drive and click Retry.  Click Exit to abort "
"the installation."
msgstr ""

#: ../image.py:241
msgid "Required Install Media"
msgstr "رسانهٔ نصب مورد نیاز"

#: ../image.py:242
#, fuzzy, python-format
msgid ""
"The software you have selected to install will require the following %s %s "
"discs:\n"
"\n"
"%s\n"
"Please have these ready before proceeding with the installation.  If you "
"need to abort the installation and exit please select \"Reboot\"."
msgstr ""
"نرم‌افزارهایی که شما برای نصب انتخاب کرده‌اید به سی‌دی‌های زیر نیاز خواهند "
"داشت:\n"
"\n"
"%s\n"
"لطفاً قبل از ادامهٔ نصب آنها را آماده داشته باشید. اگر احتیاج به قطع کردن نصب "
"و راه‌اندازی مجدد دارید لطفاً روی دکمهٔ «راه‌اندازی مجدد» کلیک کنید."

#: ../image.py:248 ../livecd.py:388 ../packages.py:382 ../packages.py:433
#: ../packages.py:436 ../upgrade.py:252 ../yuminstall.py:783
#: ../yuminstall.py:869 ../yuminstall.py:1344 ../yuminstall.py:1360
msgid "_Back"
msgstr "_عقب"

#: ../image.py:286
#, fuzzy, python-format
msgid ""
"An error occurred unmounting the disc.  Please make sure you're not "
"accessing %s from the shell on tty2 and then click OK to retry."
msgstr ""
"هنگام پیاده کردن سی‌دی خطایی رخ داد. لطفاً مطمئن شوید که شما از طریق پوسته روی "
"tty2 به %s دست‌یابی ندارید و سپس برای تلاش مجدد روی دکمهٔ «تأیید» کلیک کنید."

#: ../installclass.py:71
msgid "Install on System"
msgstr "نصب روی سیستم"

#: ../iutil.py:740
#, python-format
msgid "Error: On open, cannot set reIPL method to %s (%s: %s)"
msgstr ""

#: ../iutil.py:748
#, python-format
msgid "Error: On write, cannot set reIPL method to %s (%s: %s)"
msgstr ""

#: ../iutil.py:755
#, python-format
msgid "Error: On close, cannot set reIPL method to %s (%s: %s)"
msgstr ""

#: ../iutil.py:765 ../iutil.py:817
#, python-format
msgid "Error: %s splits into %s but not like we expect"
msgstr ""

#: ../iutil.py:778
#, python-format
msgid "Error: Could not set %s as reIPL device (%s)"
msgstr ""

#: ../iutil.py:787
#, python-format
msgid "Error: Could not reset loadparm (%s)"
msgstr ""

#: ../iutil.py:796
#, python-format
msgid "Warning: Could not reset parm (%s)"
msgstr ""

#: ../iutil.py:806
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from DASD device %s to continue "
"installation"
msgstr ""

#: ../iutil.py:834
#, python-format
msgid "Error: reading FCP property %s for reIPL (%s)"
msgstr ""

#: ../iutil.py:847
#, python-format
msgid "Error: writing FCP property %s for reIPL (%s)"
msgstr ""

#: ../iutil.py:860
#, python-format
msgid "Error: writing default FCP property %s for reIPL (%s)"
msgstr ""

#: ../iutil.py:870
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from FCP %(device)s with WWPN %"
"(wwpn)s and LUN %(lun)s to continue installation"
msgstr ""

#: ../iutil.py:877
msgid ""
"After shutdown, please perform a manual IPL from the device now containing /"
"boot to continue installation"
msgstr ""

#: ../iutil.py:887
msgid "Could not get information for mount point /boot or /"
msgstr ""

#: ../iutil.py:897
msgid "Error determining mount point type"
msgstr ""

#: ../iutil.py:901
msgid "The mount point /boot or / is on a disk that we are not familiar with"
msgstr ""

#: ../kickstart.py:96
#, fuzzy, python-format
msgid ""
"There was an error running the kickstart script at line %s.  You may examine "
"the output in %s.  This is a fatal error and your install will be aborted.  "
"Press the OK button to exit the installer."
msgstr ""
"در اجرای کدنوشتک خطایی پیش آمد. می‌توانید خروجی را در %s بررسی کنید. این خطا "
"مهلک است و نصب شما قطع خواهد شد.\n"
"\n"
"برای راه‌اندازی مجدد سیستم روی دکمهٔ «تأیید» کلیک کنید."

#: ../kickstart.py:111 ../kickstart.py:113
msgid "Scriptlet Failure"
msgstr "خرابی کدنوشتک"

#: ../kickstart.py:1155 ../kickstart.py:1172
msgid "Running..."
msgstr ""

#: ../kickstart.py:1156
msgid "Running post-install scripts"
msgstr ""

#: ../kickstart.py:1173
msgid "Running pre-install scripts"
msgstr ""

#: ../kickstart.py:1205
msgid "Missing Package"
msgstr "بستهٔ ناموجود"

#: ../kickstart.py:1206
#, python-format
msgid ""
"You have specified that the package '%s' should be installed.  This package "
"does not exist. Would you like to continue or abort your installation?"
msgstr ""
"شما مشخص کرده‌اید که بستهٔ «%s» نصب شود. این بسته وجود ندارد. مایلید ادامه دهید "
"یا نصب خود را قطع می‌کنید؟"

#: ../kickstart.py:1212 ../kickstart.py:1251
msgid "_Abort"
msgstr "_قطع شود"

#: ../kickstart.py:1213 ../kickstart.py:1252
#, fuzzy
msgid "_Ignore All"
msgstr "نادیده گرفته شود"

#: ../kickstart.py:1243
msgid "Missing Group"
msgstr "گروه ناموجود"

#: ../kickstart.py:1244
#, python-format
msgid ""
"You have specified that the group '%s' should be installed. This group does "
"not exist. Would you like to continue or abort your installation?"
msgstr ""

#: ../kickstart.py:1350
#, python-format
msgid ""
"Your kickstart file is missing required information that anaconda cannot "
"prompt for.  Please add the following sections and try again:\n"
"%s"
msgstr ""

#: ../livecd.py:108
#, fuzzy
msgid "Unable to find image"
msgstr "تصویر نصب %s پیدا نشد"

#: ../livecd.py:109
#, python-format
msgid ""
"The given location isn't a valid %s live CD to use as an installation source."
msgstr ""

#: ../livecd.py:171
#, fuzzy
msgid "Copying live image to hard drive."
msgstr "در حال انتقال تصویر نصب به دیسک‌سخت..."

#: ../livecd.py:190
msgid ""
"There was an error installing the live image to your hard drive.  This could "
"be due to bad media.  Please verify your installation media.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"require reinstallation."
msgstr ""

#: ../livecd.py:220
#, fuzzy
msgid "Doing post-installation"
msgstr "نصب %s %s"

#: ../livecd.py:221
msgid ""
"Performing post-installation filesystem changes.  This may take several "
"minutes..."
msgstr ""

#: ../livecd.py:383
#, python-format
msgid ""
"The root filesystem you created is not large enough for this live image "
"(%.2f MB required)."
msgstr ""

#: ../network.py:58
#, fuzzy
msgid "Hostname must be 255 or fewer characters in length."
msgstr "نام‌میزبان باید ۶۴ نویسه یا کوتاه‌تر باشد."

#: ../network.py:64
#, fuzzy
msgid ""
"Hostname must start with a valid character in the ranges 'a-z', 'A-Z', or '0-"
"9'"
msgstr "نام‌میزبان باید با نویسه‌ایی معتبر در محدودهٔ «a-z» یا «A-Z» آغاز شود"

#: ../network.py:69
#, fuzzy
msgid ""
"Hostnames can only contain the characters 'a-z', 'A-Z', '0-9', '-', or '.'"
msgstr "نام‌میزبان فقط می‌تواند شامل نویسه‌های «a‐z»، «A‐Z»، '-' یا «.» باشد"

#: ../network.py:178
#, fuzzy
msgid "IP address is missing."
msgstr "نشانی IP وجود ندارد"

#: ../network.py:182
#, fuzzy
msgid ""
"IPv4 addresses must contain four numbers between 0 and 255, separated by "
"periods."
msgstr "نشانی‌های IP باید حاوی اعداد بین ۰ و ۲۵۵ باشند"

#: ../network.py:185
#, fuzzy, python-format
msgid "'%s' is not a valid IPv6 address."
msgstr "%s نام میزبان معتبری نیست."

#: ../network.py:187
#, fuzzy, python-format
msgid "'%s' is an invalid IP address."
msgstr "%s نام میزبان معتبری نیست."

#: ../packages.py:122
#, fuzzy
msgid "Device Resize Failed"
msgstr "در حال بازیابی"

#: ../packages.py:123
#, fuzzy, python-format
msgid "An error was encountered while resizing device %s."
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../packages.py:130
#, fuzzy
msgid "Device Creation Failed"
msgstr "سوار کردن شکست خورد"

#: ../packages.py:131
#, fuzzy, python-format
msgid "An error was encountered while creating device %s."
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../packages.py:138
msgid "Device Removal Failed"
msgstr ""

#: ../packages.py:139
#, fuzzy, python-format
msgid "An error was encountered while removing device %s."
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../packages.py:146
msgid "Device Setup Failed"
msgstr ""

#: ../packages.py:147
#, fuzzy, python-format
msgid "An error was encountered while setting up device %s."
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../packages.py:158
#, fuzzy
msgid "Resizing Failed"
msgstr "در حال بازیابی"

#: ../packages.py:159
#, fuzzy, python-format
msgid "There was an error encountered while resizing the device %s."
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../packages.py:166
#, fuzzy
msgid "Migration Failed"
msgstr "سوار کردن شکست خورد"

#: ../packages.py:167
#, fuzzy, python-format
msgid "An error was encountered while migrating filesystem on device %s."
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../packages.py:175
#, fuzzy
msgid "Formatting Failed"
msgstr "در حال قالب‌بندی"

#: ../packages.py:176
#, fuzzy, python-format
msgid "An error was encountered while formatting device %s."
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../packages.py:184
msgid "Storage Activation Failed"
msgstr ""

#: ../packages.py:185
#, fuzzy
msgid "An error was encountered while activating your storage configuration."
msgstr ""
"خطای زیر هنگام تجزیهٔ پیکربندی kickstart پیدا شد:\n"
"\n"
"‏%s"

#: ../packages.py:353
#, fuzzy
msgid "Invalid Key"
msgstr "رشتهٔ IP‏ نامعتبر"

#: ../packages.py:354
#, fuzzy
msgid "The key you entered is invalid."
msgstr "مقداری که وارد کرده‌اید عدد معتبری نیست."

#: ../packages.py:379 ../rescue.py:248 ../rescue.py:250
#: ../textw/upgrade_text.py:133 ../loader/cdinstall.c:248
#: ../loader/cdinstall.c:251 ../loader/method.c:326
msgid "Skip"
msgstr "پرش"

#: ../packages.py:382
#, fuzzy
msgid "_Skip"
msgstr "پرش"

#: ../packages.py:414 ../packages.py:437
msgid "Warning! This is pre-release software!"
msgstr "اخطار! این نرم‌افزار نسخهٔ آزمایشی است!"

#: ../packages.py:415
#, python-format
msgid ""
"Thank you for downloading this pre-release of %s.\n"
"\n"
"This is not a final release and is not intended for use on production "
"systems.  The purpose of this release is to collect feedback from testers, "
"and it is not suitable for day to day usage.\n"
"\n"
"To report feedback, please visit:\n"
"\n"
"   %s\n"
"\n"
"and file a report against '%s'.\n"
msgstr ""
"از بارگیری این نسخهٔ آزمایشی %s متشکریم.\n"
"\n"
"این نسخه، نسخهٔ نهایی نیست و برای استفاده در سیستم‌های کاری منظور نشده است. "
"هدف از این انتشار جمع‌آوری بازخورد از آزمایش‌کنندگان است، و برای استفادهٔ "
"روزمره مناسب نیست.\n"
"\n"
"برای گزارش بازخورد، لطفاً به:\n"
"\n"
"‏‎   %s\n"
"\n"
"مراجعه کنید و گزارشی برای «%s» ثبت کنید.\n"

#: ../packages.py:428
msgid "_Install anyway"
msgstr "_با این وجود نصب شود"

#: ../partIntfHelpers.py:41
msgid "Please enter a volume group name."
msgstr "لطفاً نام گروه جلد را وارد کنید."

#: ../partIntfHelpers.py:45
msgid "Volume Group Names must be less than 128 characters"
msgstr "نام گروه جلد باید کمتر از ۱۲۸ نویسه داشته باشد"

#: ../partIntfHelpers.py:48
#, python-format
msgid "Error - the volume group name %s is not valid."
msgstr "خطا ‐ نام گروه جلد %s معتبر نیست."

#: ../partIntfHelpers.py:53
msgid ""
"Error - the volume group name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""
"خطا ‐ نام گروه جلد دارای نویسه‌های غیرمجاز یا فاصله است. نویسه‌های مورد قبول "
"حروف لاتینی، ارقام، «.» یا «_» هستند."

#: ../partIntfHelpers.py:63
msgid "Please enter a logical volume name."
msgstr "لطفاً نام جلد منطقی را وارد کنید."

#: ../partIntfHelpers.py:67
msgid "Logical Volume Names must be less than 128 characters"
msgstr "نام جلدهای منطقی باید کمتر از ۱۲۸ نویسه داشته باشند"

#: ../partIntfHelpers.py:71
#, python-format
msgid "Error - the logical volume name %s is not valid."
msgstr "خطا ‐ نام جلد منطقی %s معتبر نیست."

#: ../partIntfHelpers.py:77
msgid ""
"Error - the logical volume name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""
"خطا ‐ نام جلد منطقی دارای نویسه‌های غیرمجاز یا فاصله است. نویسه‌های مورد قبول "
"حروف لاتینی، اعداد، «.» یا «_» هستند."

#: ../partIntfHelpers.py:101
#, python-format
msgid ""
"The mount point %s is invalid.  Mount points must start with '/' and cannot "
"end with '/', and must contain printable characters and no spaces."
msgstr ""

#: ../partIntfHelpers.py:108
msgid "Please specify a mount point for this partition."
msgstr "لطفاً یک نقطهٔ سوار کردن برای این افراز مشخص کنید."

#: ../partIntfHelpers.py:121 ../partIntfHelpers.py:128
msgid "Unable To Delete"
msgstr "حذف ممکن نیست"

#: ../partIntfHelpers.py:122
msgid "You must first select a partition to delete."
msgstr "باید اول افرازی را برای حذف انتخاب کنید."

#: ../partIntfHelpers.py:145 ../partIntfHelpers.py:303
#: ../iw/lvm_dialog_gui.py:747
msgid "Confirm Delete"
msgstr "تصدیق حذف"

#: ../partIntfHelpers.py:146
#, fuzzy, python-format
msgid "You are about to delete all partitions on the device '%s'."
msgstr "شما در آستانهٔ حذف همهٔ افرازهای روی دستگاه «‎/dev/%s» هستید."

#: ../partIntfHelpers.py:149 ../partIntfHelpers.py:304
#: ../iw/lvm_dialog_gui.py:750 ../iw/lvm_dialog_gui.py:1261
#: ../iw/osbootwidget.py:102 ../iw/partition_gui.py:1333
msgid "_Delete"
msgstr "_حذف"

#: ../partIntfHelpers.py:169
msgid "Notice"
msgstr "توجه"

#: ../partIntfHelpers.py:170
#, python-format
msgid ""
"The following partitions were not deleted because they are in use:\n"
"\n"
"%s"
msgstr ""
"افرازهای زیر حذف نشدند چون از آنها استفاده می‌شود:\n"
"\n"
"‏%s"

#: ../partIntfHelpers.py:185
msgid "Format as Swap?"
msgstr "به شکل حافظهٔ مبادله قالب‌بندی شود؟"

#: ../partIntfHelpers.py:186
#, fuzzy, python-format
msgid ""
"%s has a partition type of 0x82 (Linux swap) but does not appear to be "
"formatted as a Linux swap partition.\n"
"\n"
"Would you like to format this partition as a swap partition?"
msgstr ""
"‏‎/dev/%s دارای نوع افراز 0x82 (مبادله لینوکس) است ولی به‌نظر نمی‌رسد که به "
"عنوان افراز حافظهٔ مبادلهٔ لینوکس قالب‌بندی شده باشد.\n"
"\n"
"آیا می‌خواهید این افراز را به عنوان افراز حافظهٔ مبادله قالب‌بندی کنید؟"

#: ../partIntfHelpers.py:201
#, fuzzy, python-format
msgid "You need to select at least one hard drive to install %s."
msgstr "باید حداقل یک دیسک‌سخت انتخاب کنید تا %s روی آن نصب شود."

#: ../partIntfHelpers.py:206
#, fuzzy
msgid ""
"You have chosen to use a pre-existing partition for this installation "
"without formatting it. We recommend that you format this partition to make "
"sure files from a previous operating system installation do not cause "
"problems with this installation of Linux. However, if this partition "
"contains files that you need to keep, such as home directories, then "
"continue without formatting this partition."
msgstr ""
"شما استفاده از یک افراز موجود را بدون قالب‌بندی کردن آن برای نصب انتخاب "
"کرده‌اید. توصیه می‌کنیم برای اطمینان از این که پرونده‌های نصب قبلی سیستم عامل "
"باعث اشکالاتی برای این نصب لینوکس نگردند، این افراز را قالب‌بندی کنید. با این "
"وجود، اگر این افراز شامل پرونده‌هایی است که می‌خواهید نگه دارید، مثل شاخه‌های "
"آغازه، در این صورت می‌توانیدکار را بدون قالب‌بندی این افراز ادامه دهید."

#: ../partIntfHelpers.py:214
msgid "Format?"
msgstr "قالب‌بندی شود؟"

#: ../partIntfHelpers.py:214 ../iw/partition_gui.py:1034
msgid "_Modify Partition"
msgstr "_تغییر افراز"

#: ../partIntfHelpers.py:214
msgid "Do _Not Format"
msgstr "قالب‌بندی _نشود"

#: ../partIntfHelpers.py:222
msgid "Error with Partitioning"
msgstr "خطا در افرازبندی"

#: ../partIntfHelpers.py:223
#, python-format
msgid ""
"The following critical errors exist with your requested partitioning scheme. "
"These errors must be corrected prior to continuing with your install of %s.\n"
"\n"
"%s"
msgstr ""
"خطاهای بحرانی زیر در شِمای افرازبندی درخواست شدهٔ شما وجود دارند.\n"
"پیش از ادامه به نصب %s این خطاها باید تصحیح شوند.\n"
"\n"
"‏%s"

#: ../partIntfHelpers.py:237
msgid "Partitioning Warning"
msgstr "اخطار افرازبندی"

#: ../partIntfHelpers.py:238
#, python-format
msgid ""
"The following warnings exist with your requested partition scheme.\n"
"\n"
"%s\n"
"\n"
"Would you like to continue with your requested partitioning scheme?"
msgstr ""
"اخطارهای زیر در شِمای افرازبندی درخواست شدهٔ شما وجود دارند.\n"
"\n"
"‏%s\n"
"\n"
"آیا می‌خواهید با شِمای افرازبندی درخواستی‌تان ادامه دهید؟"

#: ../partIntfHelpers.py:252 ../iw/partition_gui.py:643
msgid ""
"The following pre-existing partitions have been selected to be formatted, "
"destroying all data."
msgstr ""
"افرازهای از پیش موجود زیر برای قالب‌بندی انتخاب شده‌اند، همهٔ داده‌ها از بین "
"خواهد رفت."

#: ../partIntfHelpers.py:255
msgid ""
"Select 'Yes' to continue and format these partitions, or 'No' to go back and "
"change these settings."
msgstr ""
"برای ادامه دادن و قالب‌بندی این افرازها روی دکمهٔ «بله»، و برای عقب رفتن و "
"تغییر این تنظیمات روی دکمهٔ «خیر» کلیک کنید."

#: ../partIntfHelpers.py:261
msgid "Format Warning"
msgstr "اخطار قالب‌بندی"

#: ../partIntfHelpers.py:287
#, python-format
msgid ""
"You are about to delete the volume group \"%s\".\n"
"\n"
"ALL logical volumes in this volume group will be lost!"
msgstr ""
"شما در آستانهٔ حذف گروه جلدی «%s» هستید.\n"
"\n"
"تمام جلد‌های منطقی در این گروه جلدی از دست خواهند رفت!"

#: ../partIntfHelpers.py:291
#, python-format
msgid "You are about to delete the logical volume \"%s\"."
msgstr "شما در آستانهٔ حذف جلد منطقی «%s» هستید."

#: ../partIntfHelpers.py:294
msgid "You are about to delete a RAID device."
msgstr "شما در آستانهٔ حذف دستگاه RAID هستید."

#: ../partIntfHelpers.py:296
#, fuzzy, python-format
msgid "You are about to delete the %s partition."
msgstr "شما در آستانهٔ حذف افراز ‎/dev/%s هستید."

#: ../partIntfHelpers.py:300
#, fuzzy, python-format
msgid "You are about to delete the %s %s"
msgstr "شما در آستانهٔ حذف افراز ‎/dev/%s هستید."

#: ../partIntfHelpers.py:311
msgid "Confirm Reset"
msgstr "تصدیق برگرداندن به حالت پیش‌فرض"

#: ../partIntfHelpers.py:312
msgid ""
"Are you sure you want to reset the partition table to its original state?"
msgstr "آیا مطمئنید که می‌خواهید جدول افرازها را به وضعیت اولیهٔ خود بازگردانید؟"

#: ../partedUtils.py:108 ../iw/partition_gui.py:779 ../iw/partition_gui.py:927
msgid "None"
msgstr "هیچ‌کدام"

#: ../partedUtils.py:170
#, python-format
msgid ""
"The device %s is LDL formatted instead of CDL formatted.  LDL formatted "
"DASDs are not supported for usage during an install of %s.  If you wish to "
"use this disk for installation, it must be re-initialized causing the loss "
"of ALL DATA on this drive.\n"
"\n"
"Would you like to reformat this DASD using CDL format?"
msgstr ""
"دستگاه %s به جای قالب‌بندی CDL، قالب‌بندی LDL شده است. استفاده از DASD های با "
"قالب‌بندی LDL در طول نصب %s پشتیبانی نمی‌شود. اگر می‌خواهید از این دیسک برای "
"نصب استفاده کنید، باید آن را دوباره راه‌اندازی کرد که باعث از دست رفتن همهٔ "
"داده‌های روی این دیسک‌گردان می‌شود.\n"
"\n"
"آیا می‌خواهید این DASD را با استفاده از قالب CDL دوباره قالب‌بندی کنید؟"

#: ../partedUtils.py:200
#, fuzzy, python-format
msgid ""
"/dev/%s currently has a %s partition layout.  To use this drive for the "
"installation of %s, it must be re-initialized, causing the loss of ALL DATA "
"on this drive.\n"
"\n"
"Would you like to re-initialize this drive?"
msgstr ""
"‏‎/dev/%s در حال حاضر یک چیدمان افراز %s دارد. برای استفاده از این دیسک برای "
"نصب %s، باید آن را دوباره راه‌اندازی کرد که باعث از رفتن همهٔ داده‌های روی آن "
"می‌شود.\n"
"\n"
"آیا می‌خواهید این دیسک‌گردان را قالب‌بندی کنید؟"

#: ../partedUtils.py:209 ../storage/devicetree.py:130
msgid "_Ignore drive"
msgstr "دیسک‌گردان _نادیده گرفته شود"

#: ../partedUtils.py:210 ../storage/devicetree.py:131
msgid "_Re-initialize drive"
msgstr ""

#: ../partedUtils.py:740
msgid "Initializing"
msgstr "راه‌اندازی"

#: ../partedUtils.py:741
#, python-format
msgid "Please wait while formatting drive %s...\n"
msgstr "لطفاً در مدت قالب‌بندی دیسک‌گردان %s صبر کنید...\n"

#: ../partedUtils.py:826
#, fuzzy, python-format
msgid ""
"The partition table on device %s (%s %-0.f MB) was unreadable.\n"
"\n"
"To create new partitions it must be initialized, causing the loss of ALL "
"DATA on this drive.\n"
"\n"
"This operation will override any previous installation choices about which "
"drives to ignore.\n"
"\n"
"Would you like to initialize this drive, erasing ALL DATA?"
msgstr ""
"جدول افرازبندی در دستگاه %s ‏(%s) غیر قابل خواندن است. برای ایجاد افرازهای "
"جدید  باید راه‌اندازی شود، که باعث از دست رفتن همهٔ داده‌های روی این دیسک‌گردان "
"خواهد شد.\n"
"\n"
"این عملیات بر همهٔ انتخاب‌های پیشین نصب شما دربارهٔ این که کدام دیسک‌گردان‌ها "
"نادیده گرفته شوند پیشی خواهد گرفت.\n"
"\n"
"آیا می‌خواهید این دیسک‌گردان را با پاک کردن همهٔ داده‌ها راه‌اندازی کنید؟"

#: ../partedUtils.py:978
#, python-format
msgid ""
"The drive /dev/%s has more than 15 partitions on it.  The SCSI subsystem in "
"the Linux kernel does not allow for more than 15 partitons at this time.  "
"You will not be able to make changes to the partitioning of this disk or use "
"any partitions beyond /dev/%s15 in %s"
msgstr ""

#: ../partedUtils.py:1058 ../storage/__init__.py:851
msgid "No Drives Found"
msgstr "دیسک‌گردانی پیدا نشد"

#: ../partedUtils.py:1059 ../storage/__init__.py:852
msgid ""
"An error has occurred - no valid devices were found on which to create new "
"file systems. Please check your hardware for the cause of this problem."
msgstr ""
"خطایی رخ داد ‐ دستگاه معتبری برای ایجاد سیستم‌های پرونده‌ای جدید پیدا نشد. "
"لطفاً برای پیدا کردن علت این مشکل سخت‌افزارتان را بررسی کنید."

#: ../platform.py:91 ../platform.py:94 ../platform.py:254 ../platform.py:298
#: ../platform.py:359 ../platform.py:362
msgid "Master Boot Record (MBR)"
msgstr "رکورد راه‌اندازی اصلی (MBR)"

#: ../platform.py:93 ../platform.py:361
msgid "First sector of boot partition"
msgstr "اولین بخش افراز راه‌انداز"

#: ../platform.py:165
#, fuzzy
msgid "EFI System Partition"
msgstr "ویرایش افراز"

#: ../platform.py:256
msgid "PPC PReP Boot"
msgstr "راه‌اندازی PPC PReP"

#: ../platform.py:300 ../platform.py:303
msgid "Apple Bootstrap"
msgstr "راه‌اندازی Apple"

#: ../rescue.py:167
msgid "When finished please exit from the shell and your system will reboot."
msgstr ""
"پس از پایان کارتان لطفاً از پوسته خارج شوید تا سیستم‌تان مجدداً راه‌اندازی شود."

#: ../rescue.py:174
msgid "Unable to find /bin/sh to execute!  Not starting shell"
msgstr ""

#: ../rescue.py:193
msgid "Setup Networking"
msgstr "برپاسازی شبکه"

#: ../rescue.py:194
msgid "Do you want to start the network interfaces on this system?"
msgstr "آیا می‌خواهید واسط‌های شبکه را روی این سیستم آغاز کنید؟"

#: ../rescue.py:195 ../textw/constants_text.py:56 ../loader/driverdisk.c:483
#: ../loader/driverdisk.c:493 ../loader/hdinstall.c:231
msgid "Yes"
msgstr "بله"

#: ../rescue.py:195 ../rescue.py:197 ../textw/constants_text.py:60
#: ../loader/driverdisk.c:483 ../loader/driverdisk.c:493
msgid "No"
msgstr "خیر"

#: ../rescue.py:202
msgid ""
"Unable to activate a networking device.  Networking will not be available in "
"rescue mode."
msgstr ""

#: ../rescue.py:237 ../rescue.py:306 ../rescue.py:317 ../rescue.py:392
msgid "Rescue"
msgstr "نجات"

#: ../rescue.py:238
#, python-format
msgid ""
"The rescue environment will now attempt to find your Linux installation and "
"mount it under the directory %s.  You can then make any changes required to "
"your system.  If you want to proceed with this step choose 'Continue'.  You "
"can also choose to mount your file systems read-only instead of read-write "
"by choosing 'Read-Only'.\n"
"\n"
"If for some reason this process fails you can choose 'Skip' and this step "
"will be skipped and you will go directly to a command shell.\n"
"\n"
msgstr ""
"محیط نجات اکنون تلاش می‌کند نصب لینوکس شما را پیدا کند و ‌آن را در شاخهٔ %s "
"سوار کند. پس از آن می‌توانید تغییرات لازم را در سیستم خود ایجاد کنید. اگر "
"می‌خواهید این کار را انجام دهید روی دکمهٔ «ادامه» کلیک کنید. همچنین می‌توانید  "
"با کلیک کردن روی دکمهٔ «فقط‌خواندنی»، سیستم‌های پرونده‌ای‌تان را به جای "
"خواندنی‌نوشتنی، فقط‌خواندنی سوار کنید.\n"
"\n"
"اگر به دلیلی این روند شکست خورد می‌توانید روی دکمهٔ «پرش» کلیک کنید و این مرحله "
"نادیده گرفته خواهد شد و شما مستقیماً به پوستهٔ سطر فرمان خواهید رفت.\n"
"\n"

#: ../rescue.py:248 ../iw/partition_gui.py:547 ../storage/__init__.py:135
#: ../storage/devicetree.py:78 ../loader/cdinstall.c:206
#: ../loader/cdinstall.c:214 ../loader/driverdisk.c:444
msgid "Continue"
msgstr "ادامه"

#: ../rescue.py:248 ../rescue.py:253
msgid "Read-Only"
msgstr "فقط‌خواندنی"

#: ../rescue.py:282
msgid "System to Rescue"
msgstr "نجات سیستم"

#: ../rescue.py:283
#, fuzzy
msgid "Which device holds the root partition of your installation?"
msgstr "افراز ریشهٔ نصب شما در کدام افراز قرار دارد؟"

#: ../rescue.py:285 ../rescue.py:289 ../text.py:664 ../text.py:666
msgid "Exit"
msgstr "خروج"

#: ../rescue.py:307
msgid ""
"Your system had dirty file systems which you chose not to mount.  Press "
"return to get a shell from which you can fsck and mount your partitions.  "
"The system will reboot automatically when you exit from the shell."
msgstr ""
"سیستم شما سیستم‌های پرونده‌ای کثیفی داشت که شما سوار کردن‌شان را انتخاب نکردید. "
"برای دسترسی به پوسته‌ای که بتوانید از آن fsck کنید و افرازهایتان را سوار کنید "
"کلید ورود را فشار دهید. هنگامی که از پوسته خارج شوید سیستم به طور خودکار "
"مجدداً راه اندازی خواهد شد."

#: ../rescue.py:318
#, python-format
msgid ""
"Your system has been mounted under %s.\n"
"\n"
"Press <return> to get a shell. If you would like to make your system the "
"root environment, run the command:\n"
"\n"
"\tchroot %s\n"
"\n"
"The system will reboot automatically when you exit from the shell."
msgstr ""
"سیستم شما زیر %s سوار شده است.\n"
"\n"
"برای دسترسی به پوسته <ورود> را فشار دهید. اگر می‌خواهید سیستم تبدیل به محیط "
"rootشود، فرمان زیر را اجرا کنید:\n"
" \n"
"‏\tchroot %s\n"
"\n"
"هنگامی که از پوسته خارج شوید سیستم به طور خودکار مجدداً راه اندازی خواهد شد."

#: ../rescue.py:393
#, python-format
msgid ""
"An error occurred trying to mount some or all of your system. Some of it may "
"be mounted under %s.\n"
"\n"
"Press <return> to get a shell. The system will reboot automatically when you "
"exit from the shell."
msgstr ""
"هنگام تلاش برای سوار کردن بعضی یا همهٔ سیستم شما خطایی رخ داد. ممکن است "
"مقداری از آن زیر %s سوار شده باشد.\n"
"\n"
"برای دسترسی به پوسته <ورود> را فشار دهید. هنگامی که از پوسته خارج شوید سیستم "
"به طور خودکار مجدداً راه اندازی خواهد شد."

#: ../rescue.py:402
msgid "Rescue Mode"
msgstr "حالت نجات"

#: ../rescue.py:403
msgid ""
"You don't have any Linux partitions. Press return to get a shell. The system "
"will reboot automatically when you exit from the shell."
msgstr ""
"شما هیچ افراز لینوکسی‌ای ندارید. برای دسترسی به پوسته کلید ورود را فشار دهید. "
"هنگامی که از پوسته خارج شوید سیستم به طور خودکار مجدداً راه اندازی خواهد شد."

#: ../rescue.py:416
#, python-format
msgid "Your system is mounted under the %s directory."
msgstr "سیستم شما در شاخهٔ %s سوار شد."

#: ../text.py:196 ../text.py:280 ../text.py:293 tmp/exnSave.glade.h:7
msgid "Save"
msgstr "ذخیره"

#: ../text.py:199
msgid "Save to local disk"
msgstr ""

#: ../text.py:200
#, python-format
msgid "Send to bugzilla (%s)"
msgstr ""

#: ../text.py:201
msgid "Send to remote server (scp)"
msgstr ""

#: ../text.py:215 ../text.py:228
msgid "User name"
msgstr "نام کاربر"

#: ../text.py:217 ../text.py:230
msgid "Password"
msgstr "گذرواژه"

#: ../text.py:219
msgid "Bug Description"
msgstr ""

#: ../text.py:232
msgid "Host (host:port)"
msgstr ""

#: ../text.py:234
#, fuzzy
msgid "Destination file"
msgstr "سوار کردن شکست خورد"

#: ../text.py:313
msgid "Passphrase for encrypted device"
msgstr ""

#: ../text.py:326
msgid "Also add this passphrase to all existing encrypted devices"
msgstr ""

#: ../text.py:357
#, fuzzy, python-format
msgid "The passphrase must be at least %d characters long."
msgstr "طول گذرواژه باید حداقل شش نویسه باشد."

#: ../text.py:387 tmp/lukspassphrase.glade.h:6
msgid "Passphrase"
msgstr ""

#: ../text.py:395 tmp/lukspassphrase.glade.h:7
msgid "This is a global passphrase"
msgstr ""

#: ../text.py:461 ../text.py:465
#, fuzzy
msgid "Repository editing is not available in text mode."
msgstr "نصب گرافیکی ممکن نیست...  حالت متنی آغاز می‌شود."

#: ../text.py:505
#, fuzzy, python-format
msgid "Please enter your %(instkey)s"
msgstr "لطفاً نام گروه جلد را وارد کنید."

#: ../text.py:522 tmp/instkey.glade.h:6
#, no-c-format, python-format
msgid "Skip entering %(instkey)s"
msgstr ""

#: ../text.py:570 ../loader/lang.c:63 ../loader/loader.c:215
#, fuzzy, c-format, python-format
msgid "Welcome to %s for %s"
msgstr "به %s خوش آمدید"

#: ../text.py:572
#, python-format
msgid "Welcome to %s"
msgstr "به %s خوش آمدید"

#: ../text.py:574
msgid ""
"  <Tab>/<Alt-Tab> between elements   |  <Space> selects   |  <F12> next "
"screen"
msgstr "  <Tab>/<Alt-Tab> بین اجزا   |  <Space> انتخاب   |  <F12> صفحهٔ بعد"

#: ../text.py:664 ../loader/net.c:111 ../loader/net.c:454 ../loader/net.c:510
#: ../loader/net.c:655 ../loader/net.c:663 ../loader/net.c:1086
#: ../loader/net.c:1093
msgid "Retry"
msgstr "دوباره سعی شود"

#: ../text.py:690
msgid "Cancelled"
msgstr "لغو شد"

#: ../text.py:691
msgid "I can't go to the previous step from here. You will have to try again."
msgstr "نمی‌توان از اینجا به مرحلهٔ قبلی رفت. مجبورید دوباره امتحان کنید."

#: ../upgrade.py:92 ../upgrade.py:113
msgid "Proceed with upgrade?"
msgstr "با ارتقاء ادامه داده شود؟"

#: ../upgrade.py:93
#, python-format
msgid ""
"You have choosen the upgrade for %s architecture, but the installed system "
"is for %s architecture. \n"
"\n"
msgstr ""

#: ../upgrade.py:97
#, fuzzy, python-format
msgid "Would you like to upgrade  the installed system to the %s architecture?"
msgstr "می‌خواهید سیستم پرونده‌ای این افراز چطور آماده شود؟"

#: ../upgrade.py:114
msgid ""
"The file systems of the Linux installation you have chosen to upgrade have "
"already been mounted. You cannot go back past this point. \n"
"\n"
msgstr ""
"سیستم‌های پرونده‌ای نصب لینوکسی که برای ارتقاء انتخاب کرده‌اید از قبل سوار "
"شده‌اند. بعد از این مرحله دیگر نمی‌توانید به عقب برگردید.\n"
"\n"

#: ../upgrade.py:118
msgid "Would you like to continue with the upgrade?"
msgstr "آیا مایلید به ارتقاء دادن ادامه دهید؟"

#: ../upgrade.py:239
msgid "Mount failed"
msgstr "سوار کردن شکست خورد"

#: ../upgrade.py:240
#, fuzzy, python-format
msgid ""
"The following error occurred when mounting the file systems listed in /etc/"
"fstab.  Please fix this problem and try to upgrade again.\n"
"%s"
msgstr ""
"یک یا چندین سیستم پرونده‌ای فهرست شده در ‎/etc/fstab در سیستم لینوکس شما را "
"نمی‌توان سوار کرد. لطفاً این اشکال را رفع کنید و دوباره برای ارتقاء تلاش کنید."

#: ../upgrade.py:247
#, fuzzy
msgid "Upgrade root not found"
msgstr "ارتقائی که آغاز شود"

#: ../upgrade.py:248
msgid ""
"The root for the previously installed system was not found.  You can exit "
"installer or backtrack to choose installation instead of upgrade."
msgstr ""

#: ../upgrade.py:271
msgid ""
"The following files are absolute symbolic links, which we do not support "
"during an upgrade. Please change them to relative symbolic links and restart "
"the upgrade.\n"
"\n"
msgstr ""
"پرونده‌های زیر پیوندهای نمادی مطلق هستند که در حین ارتقاء پشتیبانی نمی‌شوند. "
"لطفاً آنها را به پیوندهای نمادی نسبی تغییر دهید و ارتقاء را از نو آغاز کنید.\n"
"\n"

#: ../upgrade.py:277
msgid "Absolute Symlinks"
msgstr "پیوندهای نمادی مطلق"

#: ../upgrade.py:288
msgid ""
"The following are directories which should instead be symbolic links, which "
"will cause problems with the upgrade.  Please return them to their original "
"state as symbolic links and restart the upgrade.\n"
"\n"
msgstr ""
"آنچه در زیر آمده شاخه‌هایی هستند که باید پیوند نمادی می‌بودند، و باعث مشکلاتی "
"در ارتقاء دادن خواهند شد. لطفاً آنها را به وضعیت اصلی خود یعنی پیوند نمادی "
"برگردانید و ارتقاء را از نو آغاز کنید.\n"
"\n"

#: ../upgrade.py:294
msgid "Invalid Directories"
msgstr "شاخه‌های نامعتبر"

#: ../upgrade.py:299
#, python-format
msgid "%s not found"
msgstr "‏%s پیدا نشد"

#: ../vnc.py:136
#, python-format
msgid "%s %s installation on host %s"
msgstr "نصب %s %s در میزبان %s"

#: ../vnc.py:138
#, python-format
msgid "%s %s installation"
msgstr "نصب %s %s"

#: ../vnc.py:165
#, python-format
msgid "Attempting to connect to vnc client on host %s..."
msgstr "در حال تلاش برای وصل شدن به کارگیر vnc در میزبان %s..."

#: ../vnc.py:179
msgid "Connected!"
msgstr "وصل شد!"

#: ../vnc.py:182
msgid "Will try to connect again in 15 seconds..."
msgstr "۱۵ ثانیهٔ دیگر باز برای اتصال تلاش خواهد شد..."

#: ../vnc.py:188
#, fuzzy, python-format
msgid "Giving up attempting to connect after %d tries!\n"
msgstr "بعد از ۵۰ بار تلاش برای وصل شدن از این کار چشم پوشی شد!\n"

#: ../vnc.py:197
#, python-format
msgid "Please manually connect your vnc client to %s to begin the install."
msgstr "برای شروع نصب، لطفاً کارگیر vnc خود را دستی به %s متصل کنید."

#: ../vnc.py:199
msgid "Please manually connect your vnc client to begin the install."
msgstr "برای شروع نصب، لطفاً کارگیر vnc خود را دستی متصل کنید."

#: ../vnc.py:202
msgid "Starting VNC..."
msgstr "در حال آغاز VNC..."

#: ../vnc.py:227
msgid "The VNC server is now running."
msgstr "کارگزار VNC در حال اجرا است."

#: ../vnc.py:240
msgid ""
"\n"
"\n"
"You chose to connect to a listening vncviewer. \n"
"This does not require a password to be set.  If you \n"
"set a password, it will be used in case the connection \n"
"to the vncviewer is unsuccessful\n"
"\n"
msgstr ""

#: ../vnc.py:245
#, fuzzy
msgid ""
"\n"
"\n"
"WARNING!!! VNC server running with NO PASSWORD!\n"
"You can use the vncpassword=<password> boot option\n"
"if you would like to secure the server.\n"
"\n"
msgstr ""
"\n"
"\n"
"اخطار!!! کارگزار VNC دارد بدون گذرواژه اجرا می‌شود!\n"
"اگر مایل به امن کردن کارگزار هستید، می‌توانید از گزینهٔ راه‌اندازی\n"
"‏‪vncpassword=<گذرواژه>‬ استفاده کنید.\n"

#: ../vnc.py:249
msgid ""
"\n"
"\n"
"You chose to execute vnc with a password. \n"
"\n"
msgstr ""

#: ../vnc.py:251
#, fuzzy
msgid ""
"\n"
"\n"
"Unknown Error.  Aborting. \n"
"\n"
msgstr "خطای نامعلوم"

#: ../vnc.py:273 ../vnc.py:366
msgid "VNC Configuration"
msgstr "پیکربندی VNC"

#: ../vnc.py:276 ../vnc.py:370
msgid "No password"
msgstr "بدون گذرواژه"

#: ../vnc.py:278 ../vnc.py:373
msgid ""
"A password will prevent unauthorized listeners connecting and monitoring "
"your installation progress.  Please enter a password to be used for the "
"installation"
msgstr ""
"گذرواژه مانع از آن خواهد شد که شنوندگان تأیید هویت نشده متصل شوند و پیشرفت "
"نصب شما را ببینند. لطفاً گذرواژه‌ای برای استفاده در نصب وارد کنید."

#: ../vnc.py:286 ../vnc.py:381 ../textw/userauth_text.py:47
msgid "Password:"
msgstr "گذرواژه:"

#: ../vnc.py:287 ../vnc.py:382 ../textw/userauth_text.py:49
msgid "Password (confirm):"
msgstr "گذرواژه (تکرار):"

#: ../vnc.py:305 ../vnc.py:404 ../textw/userauth_text.py:70
msgid "Password Mismatch"
msgstr "گذرواژه مطابقت نمی‌کند"

#: ../vnc.py:306 ../vnc.py:405 ../textw/userauth_text.py:71
msgid "The passwords you entered were different. Please try again."
msgstr "گذرواژه‌های که وارد کردید متفاوت بودند. لطفاً دوباره تلاش کنید."

#: ../vnc.py:311 ../vnc.py:410 ../textw/userauth_text.py:66
msgid "Password Length"
msgstr "طول گذرواژه"

#: ../vnc.py:312 ../vnc.py:411
msgid "The password must be at least six characters long."
msgstr "طول گذرواژه باید حداقل شش نویسه باشد."

#: ../vnc.py:334
msgid "Unable to Start X"
msgstr "آغاز X ممکن نیست"

#: ../vnc.py:336
msgid ""
"X was unable to start on your machine.  Would you like to start VNC to "
"connect to this computer from another computer and perform a graphical "
"install or continue with a text mode install?"
msgstr ""
"آغاز ‏X روی رایانهٔ شما ممکن نبود. می‌خواهید VNC را آغاز کنید تا این رایانه را "
"به رایانهٔ دیگری متصل کنید و نصب گرافیکی انجام دهید، یا این که نصب را در حالت "
"متنی ادامه می‌دهید؟"

#: ../vnc.py:355
msgid "Start VNC"
msgstr "آغاز VNC"

#: ../vnc.py:356 ../vnc.py:358
msgid "Use text mode"
msgstr "استفاده از حالت متنی"

#: ../yuminstall.py:79
#, python-format
msgid "%s MB"
msgstr "‏%s مگابایت"

#: ../yuminstall.py:82
#, python-format
msgid "%s KB"
msgstr "‏%s کیلوبایت"

#: ../yuminstall.py:85
#, python-format
msgid "%s Byte"
msgstr "‏%s بایت"

#: ../yuminstall.py:87
#, python-format
msgid "%s Bytes"
msgstr "‏%s بایت"

#: ../yuminstall.py:131
msgid "Processing"
msgstr "در حال پردازش"

#: ../yuminstall.py:132
msgid "Preparing transaction from installation source..."
msgstr ""

#: ../yuminstall.py:163
#, fuzzy, python-format
msgid "<b>Installing %s</b> (%s)\n"
msgstr "_نصب %s"

#: ../yuminstall.py:212
#, python-format
msgid "%s of %s packages completed"
msgstr ""

#: ../yuminstall.py:222
msgid "Finishing upgrade"
msgstr ""

#: ../yuminstall.py:223
msgid "Finishing upgrade process.  This may take a little while..."
msgstr ""

#: ../yuminstall.py:293 ../iw/task_gui.py:301
#, fuzzy
msgid "Error Setting Up Repository"
msgstr "برچسب راه‌اندازی نامعتبر"

#: ../yuminstall.py:294 ../iw/task_gui.py:302
#, fuzzy, python-format
msgid ""
"The following error occurred while setting up the installation repository:\n"
"\n"
"%s\n"
"\n"
"Please provide the correct information for installing %s."
msgstr ""
"خطاهای زیر هنگام افرازبندی دیسک شما رخ داد:\n"
"\n"
"‏%s\n"
"\n"
"برای راه‌اندازی مجدد سیستم خود روی دکمهٔ «تأیید» کلیک کنید."

#: ../yuminstall.py:353
#, fuzzy
msgid "Change Disc"
msgstr "تعویض سی‌دی"

#: ../yuminstall.py:354
#, python-format
msgid "Please insert %s disc %d to continue."
msgstr "برای ادامه لطفاً دیسک %s شمارهٔ %d را وارد کنید."

#: ../yuminstall.py:364
#, fuzzy
msgid "Wrong Disc"
msgstr "سی‌دی اشتباه است"

#: ../yuminstall.py:365
#, fuzzy, python-format
msgid "That's not the correct %s disc."
msgstr "این سی‌دی درست %s نیست."

#: ../yuminstall.py:372
#, fuzzy
msgid "Unable to access the disc."
msgstr "دست‌یابی به سی‌دی ممکن نیست."

#: ../yuminstall.py:530
#, python-format
msgid "Repository %r is missing name in configuration, using id"
msgstr ""

#: ../yuminstall.py:654 ../yuminstall.py:656
msgid "Re_boot"
msgstr "_راه‌اندازی مجدد"

#: ../yuminstall.py:654
#, fuzzy
msgid "_Eject"
msgstr "بیرون دادن سی‌دی"

#: ../yuminstall.py:665
#, python-format
msgid ""
"The file %s cannot be opened.  This is due to a missing file, a corrupt "
"package or corrupt media.  Please verify your installation source.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"likely require reinstallation.\n"
"\n"
msgstr ""

#: ../yuminstall.py:708
#, fuzzy
msgid "Retrying"
msgstr "در حال بازیابی"

#: ../yuminstall.py:708
msgid "Retrying download..."
msgstr ""

#: ../yuminstall.py:780
#, fuzzy, python-format
msgid ""
"There was an error running your transaction for the following reason: %s\n"
msgstr ""
"نام میزبان «%s» به دلایل زیر معتبر نیست:\n"
"\n"
"‏%s"

#: ../yuminstall.py:815 ../yuminstall.py:816
msgid "file conflicts"
msgstr ""

#: ../yuminstall.py:817
msgid "older package(s)"
msgstr ""

#: ../yuminstall.py:818
msgid "insufficient disk space"
msgstr ""

#: ../yuminstall.py:819
msgid "insufficient disk inodes"
msgstr ""

#: ../yuminstall.py:820
msgid "package conflicts"
msgstr ""

#: ../yuminstall.py:821
msgid "package already installed"
msgstr ""

#: ../yuminstall.py:822
msgid "required package"
msgstr ""

#: ../yuminstall.py:823
msgid "package for incorrect arch"
msgstr ""

#: ../yuminstall.py:824
msgid "package for incorrect os"
msgstr ""

#: ../yuminstall.py:838
msgid "You need more space on the following file systems:\n"
msgstr ""

#: ../yuminstall.py:851
#, fuzzy, python-format
msgid ""
"There were file conflicts when checking the packages to be installed:\n"
"%s\n"
msgstr "چه نوع رسانه‌ای حاوی بسته‌هایی است که باید نصب شوند؟"

#: ../yuminstall.py:854
#, fuzzy, python-format
msgid ""
"There was an error running your transaction for the following reason(s): %"
"s.\n"
msgstr ""
"نام میزبان «%s» به دلایل زیر معتبر نیست:\n"
"\n"
"‏%s"

#: ../yuminstall.py:861 ../yuminstall.py:866
msgid "Error Running Transaction"
msgstr ""

#: ../yuminstall.py:1023
msgid ""
"Some of your software repositories require networking, but there was an "
"error enabling the network on your system."
msgstr ""

#: ../yuminstall.py:1057
msgid ""
"Unable to read group information from repositories.  This is a problem with "
"the generation of your install tree."
msgstr ""

#: ../yuminstall.py:1095
msgid "Retrieving installation information..."
msgstr ""

#: ../yuminstall.py:1097
#, fuzzy, python-format
msgid "Retrieving installation information for %s..."
msgstr "در حال فرستادن درخواست برای اطلاعات IP‏ برای %s..."

#: ../yuminstall.py:1099
msgid "Installation Progress"
msgstr ""

#: ../yuminstall.py:1112 ../textw/constants_text.py:64
msgid "Edit"
msgstr "ویرایش"

#: ../yuminstall.py:1125 ../yuminstall.py:1313
#, python-format
msgid ""
"Unable to read package metadata. This may be due to a missing repodata "
"directory.  Please ensure that your install tree has been correctly "
"generated.\n"
"\n"
"%s"
msgstr ""

#: ../yuminstall.py:1176 ../iw/GroupSelector.py:485
msgid "Uncategorized"
msgstr ""

#: ../yuminstall.py:1338
#, python-format
msgid ""
"Your selected packages require %d MB of free space for installation, but you "
"do not have enough available.  You can change your selections or exit the "
"installer."
msgstr ""

#: ../yuminstall.py:1357
msgid "Reboot?"
msgstr "راه‌اندازی مجدد؟"

#: ../yuminstall.py:1358
msgid "The system will be rebooted now."
msgstr "سیستم اکنون مجدداً راه‌اندازی خواهد شد."

#: ../yuminstall.py:1511
#, python-format
msgid ""
"You appear to be upgrading from a system which is too old to upgrade to this "
"version of %s.  Are you sure you wish to continue the upgrade process?"
msgstr ""
"به نظر می‌رسد سیستم شما قدیمی‌تر از آن است که بتوان آن را به این نسخهٔ %s "
"ارتقاء داد. مطمئنید که می‌خواهید روند ارتقاء را ادامه دهید؟"

#: ../yuminstall.py:1540
#, fuzzy, python-format
msgid ""
"The arch of the release of %s you are upgrading to appears to be %s which "
"does not match your previously installed arch of %s.  This is likely to not "
"succeed.  Are you sure you wish to continue the upgrade process?"
msgstr ""
"به نظر می‌رسد سیستم شما قدیمی‌تر از آن است که بتوان آن را به این نسخهٔ %s "
"ارتقاء داد. مطمئنید که می‌خواهید روند ارتقاء را ادامه دهید؟"

#: ../yuminstall.py:1591
msgid "Post Upgrade"
msgstr ""

#: ../yuminstall.py:1592
msgid "Performing post upgrade configuration..."
msgstr ""

#: ../yuminstall.py:1594
msgid "Post Install"
msgstr "پس از نصب"

#: ../yuminstall.py:1595
msgid "Performing post install configuration..."
msgstr "در حال انجام پیکربندی پس از نصب..."

#: ../yuminstall.py:1820
msgid "Install Starting"
msgstr "نصب آغاز می‌شود"

#: ../yuminstall.py:1821
msgid "Starting install process.  This may take several minutes..."
msgstr ""

#: ../yuminstall.py:1859
msgid "Dependency Check"
msgstr "بررسی وابستگی"

#: ../yuminstall.py:1860
msgid "Checking dependencies in packages selected for installation..."
msgstr "در حال بررسی وابستگی‌ها در بسته‌های انتخاب شدهٔ برای نصب..."

#: ../iw/GroupSelector.py:147
#, python-format
msgid "Packages in %s"
msgstr ""

#: ../iw/GroupSelector.py:424
#, python-format
msgid "Optional packages selected: %d of %d"
msgstr ""

#: ../iw/GroupSelector.py:425
#, python-format
msgid "<i>%s</i>"
msgstr ""

#: ../iw/account_gui.py:52
#, fuzzy
msgid "Root _Password:"
msgstr "_گذرواژهٔ root: "

#: ../iw/account_gui.py:54
#, fuzzy
msgid "_Confirm:"
msgstr "_تکرار گذرواژه: "

#: ../iw/account_gui.py:97
msgid "Caps Lock is on."
msgstr ""

#: ../iw/account_gui.py:107 ../iw/account_gui.py:115 ../iw/account_gui.py:122
#: ../iw/account_gui.py:144 ../textw/userauth_text.py:74
msgid "Error with Password"
msgstr "خطا در گذرواژه"

#: ../iw/account_gui.py:108
msgid ""
"You must enter your root password and confirm it by typing it a second time "
"to continue."
msgstr ""
"برای ادامه باید گذرواژهٔ root خود را وارد کنید و با وارد کردن آن برای بار دوم "
"آن را تصدیق کنید."

#: ../iw/account_gui.py:116
msgid "The passwords you entered were different.  Please try again."
msgstr "گذرواژه‌هایی که وارد کردید فرق داشتند. لطفاً دوباره تلاش کنید."

#: ../iw/account_gui.py:123
msgid "The root password must be at least six characters long."
msgstr "طول گذرواژهٔ root باید حداقل شش نویسه باشد."

#: ../iw/account_gui.py:132 ../textw/userauth_text.py:83
#, fuzzy
msgid "Weak Password"
msgstr "گذرواژه"

#: ../iw/account_gui.py:133 ../textw/userauth_text.py:84
#, fuzzy, python-format
msgid ""
"Weak password provided: %s\n"
"\n"
"Would you like to continue with this password?"
msgstr "آیا مایلید به ارتقاء دادن ادامه دهید؟"

#: ../iw/account_gui.py:145 ../textw/userauth_text.py:75
#, fuzzy
msgid ""
"Requested password contains non-ASCII characters, which are not allowed."
msgstr ""
"گذرواژهٔ درخواست شده دارای نویسه‌های غیراَسکی است که استفاده از آنها در گذرواژه "
"مجاز نیست."

#: ../iw/autopart_type.py:101
msgid ""
"No partitions are available to resize.  Only physical partitions with "
"specific filesystems can be resized."
msgstr ""

#: ../iw/autopart_type.py:124
#, fuzzy
msgid "Resize FileSystem Error"
msgstr "در حال قالب‌بندی سیستم پرونده‌ای ‎%s..."

#: ../iw/autopart_type.py:125 ../iw/autopart_type.py:134
#, python-format
msgid "%s: %s"
msgstr ""

#: ../iw/autopart_type.py:133
msgid "Resize Device Error"
msgstr ""

#: ../iw/autopart_type.py:208
msgid ""
"Do you really want to boot from a disk which is not used for installation?"
msgstr ""

#: ../iw/autopart_type.py:285
#, fuzzy
msgid "Invalid Initiator Name"
msgstr "نام نامعتبر گروه جلد"

#: ../iw/autopart_type.py:286
#, fuzzy
msgid "You must provide an initiator name."
msgstr "باید نام کارگزاری وارد کنید."

#: ../iw/autopart_type.py:321
msgid "Error with Data"
msgstr ""

#: ../iw/autopart_type.py:398 ../iw/autopart_type.py:399
msgid "Rescanning disks"
msgstr ""

#: ../iw/autopart_type.py:452 ../textw/partition_text.py:63
#, fuzzy
msgid "Use entire drive"
msgstr "دیسک‌گردان _نادیده گرفته شود"

#: ../iw/autopart_type.py:453 ../textw/partition_text.py:64
msgid "Replace existing Linux system"
msgstr ""

#: ../iw/autopart_type.py:454
#, fuzzy
msgid "Shrink current system"
msgstr "کلید رمزنگاری"

#: ../iw/autopart_type.py:455 ../textw/partition_text.py:65
#, fuzzy
msgid "Use free space"
msgstr "فضای آزادی وجود ندارد"

#: ../iw/autopart_type.py:456
msgid "Create custom layout"
msgstr ""

#: ../iw/blpasswidget.py:47
msgid "_Use a boot loader password"
msgstr "_استفاده از گذرواژهٔ بارکنندهٔ راه‌انداز"

#: ../iw/blpasswidget.py:48
#, fuzzy
msgid ""
"A boot loader password prevents users from changing kernel options, "
"increasing security."
msgstr ""
"گذرواژهٔ بارکنندهٔ راه‌انداز مانع از آن می‌شود که کاربران گزینه‌های رد شده به "
"هسته را تغییر دهند. برای امنیت بیشتر سیستم، توصیه می‌شود گذرواژه‌ای تعیین کنید."

#: ../iw/blpasswidget.py:79
msgid "Change _password"
msgstr "تغییر _گذرواژه"

#: ../iw/blpasswidget.py:102
msgid "Enter Boot Loader Password"
msgstr "گذرواژهٔ بارکنندهٔ راه‌انداز را وارد کنید"

#: ../iw/blpasswidget.py:108
msgid ""
"Enter a boot loader password and then confirm it.  (Note that your BIOS "
"keymap may be different than the actual keymap you are used to.)"
msgstr ""
"گذرواژه‌ای برای بارکنندهٔ راه‌انداز وارد کنید و سپس آن را در فیلد بعدی تکرار "
"کنید. (توجه کنید که نقشه‌کلید BIOS شما ممکن است با نقشه‌کلید واقعی که به آن "
"عادت دارید تفاوت داشته باشد.)"

#: ../iw/blpasswidget.py:115
msgid "_Password:"
msgstr "_گذرواژه:"

#: ../iw/blpasswidget.py:121
msgid "Con_firm:"
msgstr "ت_کرار:"

#: ../iw/blpasswidget.py:142
msgid "Passwords don't match"
msgstr "گذرواژه‌ها مطابقت نمی‌کنند"

#: ../iw/blpasswidget.py:143
msgid "Passwords do not match"
msgstr "گذرواژه‌ها مطابقت نمی‌کنند."

#: ../iw/blpasswidget.py:152
#, fuzzy
msgid ""
"Your boot loader password is shorter than six characters.  We recommend a "
"longer boot loader password.\n"
"\n"
"Would you like to continue with this password?"
msgstr ""
"گذرواژهٔ بارکنندهٔ راه‌انداز شما کمتر از شش نویسه است. ما گذرواژهٔ طولانی‌تری "
"برای بارکنندهٔ راه‌انداز توصیه می‌کنیم.\n"
"\n"
"آیا می‌خواهید با همین گذرواژه ادامه دهید؟"

#: ../iw/bootloader_main_gui.py:36
msgid "Boot Loader Configuration"
msgstr "پیکربندی بارکنندهٔ راه‌انداز"

#: ../iw/bootloader_main_gui.py:179 ../iw/bootloader_main_gui.py:184
#: ../iw/bootloader_main_gui.py:221
#, fuzzy, python-format
msgid "_Install boot loader on /dev/%s."
msgstr "در حال نصب بارکنندهٔ راه‌انداز..."

#: ../iw/bootloader_main_gui.py:227
#, fuzzy
msgid "_Change device"
msgstr "تعویض سی‌دی"

#: ../iw/congrats_gui.py:33
msgid "Congratulations"
msgstr "تبریک"

#: ../iw/congrats_gui.py:74 ../textw/complete_text.py:39
#, fuzzy, python-format
msgid ""
"Congratulations, your %s installation is complete.\n"
"\n"
msgstr ""
"تبریک،  نصب %s شما تمام شد.\n"
"\n"
"‏%s%s"

#: ../iw/congrats_gui.py:77 ../textw/complete_text.py:42
msgid "Shutdown"
msgstr ""

#: ../iw/congrats_gui.py:79 ../textw/complete_text.py:44
#, fuzzy
msgid "Please shutdown to use the installed system.\n"
msgstr "برای شروع نصب لطفاً به %s متصل شوید..."

#: ../iw/congrats_gui.py:81 ../textw/complete_text.py:46
#, fuzzy
msgid "Please reboot to use the installed system.\n"
msgstr "برای شروع نصب لطفاً به %s متصل شوید..."

#: ../iw/congrats_gui.py:86 ../textw/complete_text.py:51
msgid ""
"Note that updates may be available to ensure the proper functioning of your "
"system and installation of these updates is recommended after the reboot."
msgstr ""

#: ../iw/congrats_gui.py:90 ../textw/complete_text.py:55
#, python-format
msgid ""
"Congratulations, your %s installation is complete.\n"
"\n"
"Please reboot to use the installed system.  Note that updates may be "
"available to ensure the proper functioning of your system and installation "
"of these updates is recommended after the reboot."
msgstr ""

#: ../iw/examine_gui.py:37
msgid "Upgrade Examine"
msgstr "آزمایش ارتقاء"

#: ../iw/examine_gui.py:59
#, python-format
msgid "_Install %s"
msgstr "_نصب %s"

#: ../iw/examine_gui.py:61
msgid ""
"Choose this option to freshly install your system. Existing software and "
"data may be overwritten depending on your configuration choices."
msgstr ""
"برای نصب تازه روی سیستم‌تان این گزینه را انتخاب کنید. بسته به انتخاب‌های "
"پیکربندی شما، ممکن است نرم‌افزارها و داده‌های موجود رونویسی شوند."

#: ../iw/examine_gui.py:65
msgid "_Upgrade an existing installation"
msgstr "_ارتقاء دادن نصب موجود"

#: ../iw/examine_gui.py:67
#, fuzzy, python-format
msgid ""
"Choose this option if you would like to upgrade your existing %s system.  "
"This option preserves the existing data on your drives."
msgstr ""
"اگر می‌خواهید سیستم %s موجود خود را ارتقاء دهید این گزینه را انتخاب کنید. این "
"گزینه داده‌های موجود در دیسک‌گردان‌های شما را حفظ خواهد کرد."

#: ../iw/examine_gui.py:116
msgid "The following installed system will be upgraded:"
msgstr "سیستم نصب‌شدهٔ زیر ارتقاء داده خواهد شد:"

#: ../iw/examine_gui.py:129
msgid "Unknown Linux system"
msgstr "سیستم لینوکس ناشناس"

#: ../iw/language_gui.py:33 ../textw/language_text.py:46
msgid "Language Selection"
msgstr "انتخاب زبان"

#: ../iw/language_gui.py:81 ../textw/language_text.py:47 ../loader/lang.c:376
msgid "What language would you like to use during the installation process?"
msgstr "در طی روند نصب می‌خواهید از چه زبانی استفاده کنید؟"

#: ../iw/lvm_dialog_gui.py:120 ../iw/lvm_dialog_gui.py:166
#: ../iw/lvm_dialog_gui.py:178 ../iw/lvm_dialog_gui.py:217
#: ../iw/lvm_dialog_gui.py:293 ../iw/lvm_dialog_gui.py:613
msgid "Not enough space"
msgstr "فضای کافی وجود ندارد"

#: ../iw/lvm_dialog_gui.py:121
msgid ""
"The physical extent size cannot be changed because otherwise the space "
"required by the currently defined logical volumes will be increased to more "
"than the available space."
msgstr ""
"نمی‌توان اندازهٔ گسترهٔ فیزیکی را تغییر داد چون در این صورت فضای مورد نیاز "
"جلد‌های منطقی مشخص شدهٔ کنونی به بیشتر از فضای موجود افزایش خواهد یافت."

#: ../iw/lvm_dialog_gui.py:130
msgid "Confirm Physical Extent Change"
msgstr "تصدیق تغییر گسترهٔ فیزیکی"

#: ../iw/lvm_dialog_gui.py:131
#, fuzzy
msgid ""
"This change in the value of the physical extent will require the sizes of "
"the current logical volume requests to be rounded up in size to an integer "
"multiple of the physical extent.\n"
"\n"
"This change will take effect immediately."
msgstr ""
"برای انجام این تغییر در مقدار گسترهٔ فیزیکی لازم خواهد بود که اندازه‌های "
"درخواست شدهٔ فعلی برای ‌جلد‌های منطقی به مضرب صحیحی از گسترهٔ فیزیکی به بالا گرد "
"شوند.\n"
"\n"
"این تغییر بلافاصله اثر خواهد کرد."

#: ../iw/lvm_dialog_gui.py:140 ../iw/lvm_dialog_gui.py:200
msgid "C_ontinue"
msgstr "ا_دامه"

#: ../iw/lvm_dialog_gui.py:167
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected (%"
"10.2f MB) is larger than the smallest physical volume (%10.2f MB) in the "
"volume group."
msgstr ""
"نمی‌توان اندازهٔ گسترهٔ فیزیکی را تغییر داد چون مقدار انتخاب شده (%10.2f "
"مگابایت) بزرگتر از کوچکترین جلد فیزیکی در گروه جلدی (%10.2f مگابایت) است."

#: ../iw/lvm_dialog_gui.py:179
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected (%"
"10.2f MB) is too large compared to the size of the smallest physical volume "
"(%10.2f MB) in the volume group."
msgstr ""
"نمی‌توان اندازهٔ گسترهٔ فیزیکی را تغییر داد چون مقدار انتخاب شده (%10.2f "
"مگابایت) در مقایسه با اندازهٔ کوچکترین جلد فیزیکی در گروه جلدی (%10.2f "
"مگابایت) خیلی بزرگ است."

#: ../iw/lvm_dialog_gui.py:193
msgid "Too small"
msgstr "خیلی کوچک است"

#: ../iw/lvm_dialog_gui.py:194
msgid ""
"This change in the value of the physical extent will waste substantial space "
"on one or more of the physical volumes in the volume group."
msgstr ""
"این تغییر در مقدار گسترهٔ فیزیکی فضای قابل توجهی را در یک یا چند جلد فیزیکی "
"در گروه جلدی تلف خواهد کرد."

#: ../iw/lvm_dialog_gui.py:218
#, python-format
msgid ""
"The physical extent size cannot be changed because the resulting maximum "
"logical volume size (%10.2f MB) is smaller than one or more of the currently "
"defined logical volumes."
msgstr ""
"نمی‌توان اندازهٔ گسترهٔ فیزیکی را تغییر داد چون حداکثر جلد منطقی نتیجه شده (%"
"10.2f مگابایت) از یک یا چند جلد فیزیکی تعیین شدهٔ فعلی کوچکتر خواهد شد."

#: ../iw/lvm_dialog_gui.py:294
msgid ""
"You cannot remove this physical volume because otherwise the volume group "
"will be too small to hold the currently defined logical volumes."
msgstr ""
"نمی‌توانید این جلد فیزیکی را حذف کنید چون در این صورت گروه جلدی کوچکتر از آن "
"خواهد شد که بتواند جلد‌های منطقی تعیین شدهٔ فعلی را نگه دارد."

#: ../iw/lvm_dialog_gui.py:371
msgid "Make Logical Volume"
msgstr "ساختن جلد منطقی"

#: ../iw/lvm_dialog_gui.py:373
#, python-format
msgid "Edit Logical Volume: %s"
msgstr "ویرایش جلد منطقی: %s"

#: ../iw/lvm_dialog_gui.py:407 ../iw/partition_dialog_gui.py:306
#: ../iw/raid_dialog_gui.py:364
msgid "_Mount Point:"
msgstr "_نقطهٔ سوار کردن:"

#: ../iw/lvm_dialog_gui.py:415 ../iw/raid_dialog_gui.py:373
msgid "_File System Type:"
msgstr "نوع  سیستم پرونده‌ای:"

#: ../iw/lvm_dialog_gui.py:425 ../iw/raid_dialog_gui.py:383
msgid "Original File System Type:"
msgstr "نوع سیستم پرونده‌ای اصلی:"

#: ../iw/lvm_dialog_gui.py:430 ../iw/raid_dialog_gui.py:388
msgid "Unknown"
msgstr "نامعلوم"

#: ../iw/lvm_dialog_gui.py:436 ../iw/partition_dialog_gui.py:351
#: ../iw/raid_dialog_gui.py:394
msgid "Original File System Label:"
msgstr "برچسب سیستم پرونده‌ای اصلی:"

#: ../iw/lvm_dialog_gui.py:444
msgid "_Logical Volume Name:"
msgstr "نام جلد _منطقی:"

#: ../iw/lvm_dialog_gui.py:452
msgid "Logical Volume Name:"
msgstr "نام جلد منطقی:"

#: ../iw/lvm_dialog_gui.py:460 ../iw/partition_dialog_gui.py:361
msgid "_Size (MB):"
msgstr "ا_ندازه (مگابایت):"

#: ../iw/lvm_dialog_gui.py:465
msgid "Size (MB):"
msgstr "اندازه (مگابایت):"

#: ../iw/lvm_dialog_gui.py:474
#, python-format
msgid "(Max size is %s MB)"
msgstr "(حداکثر اندازه %s مگابایت است)"

#: ../iw/lvm_dialog_gui.py:495 ../iw/partition_dialog_gui.py:413
#: ../iw/partition_ui_helpers_gui.py:322 ../iw/raid_dialog_gui.py:345
#, fuzzy
msgid "_Encrypt"
msgstr "کلید رمزنگاری"

#: ../iw/lvm_dialog_gui.py:540
msgid "Illegal Logical Volume Name"
msgstr "نام غیرمجاز جلد منطقی"

#: ../iw/lvm_dialog_gui.py:555
msgid "Illegal logical volume name"
msgstr "نام غیرمجاز جلد منطقی"

#: ../iw/lvm_dialog_gui.py:556
#, python-format
msgid "The logical volume name \"%s\" is already in use. Please pick another."
msgstr ""
"نام جلد منطقی «%s» از قبل مورد استفاده است، لطفاً یک نام دیگر انتخاب کنید."

#: ../iw/lvm_dialog_gui.py:584
msgid "Mount point in use"
msgstr "نقطهٔ سوار کردن مورد استفاده است"

#: ../iw/lvm_dialog_gui.py:585
#, fuzzy, python-format
msgid "The mount point \"%s\" is in use. Please pick another."
msgstr "نقطهٔ سوار کردن «%s» مورد استفاده است، لطفاً یکی دیگر انتخاب کنید."

#: ../iw/lvm_dialog_gui.py:600
msgid "Illegal size"
msgstr "اندازهٔ غیرمجاز"

#: ../iw/lvm_dialog_gui.py:601
msgid "The requested size as entered is not a valid number greater than 0."
msgstr "اندازهٔ درخواست شدهٔ وارد شده یک عدد معتبر بزرگتر از ۰ نیست."

#: ../iw/lvm_dialog_gui.py:614
#, python-format
msgid ""
"The current requested size (%10.2f MB) is larger than the maximum logical "
"volume size (%10.2f MB). To increase this limit you can create more Physical "
"Volumes from unpartitioned disk space and add them to this Volume Group."
msgstr ""

#: ../iw/lvm_dialog_gui.py:708
msgid "No free slots"
msgstr "شکاف آزادی وجود ندارد"

#: ../iw/lvm_dialog_gui.py:709
#, python-format
msgid "You cannot create more than %s logical volumes per volume group."
msgstr "نمی‌توانید در هر گروه جلد بیش از %s جلد منطقی ایجاد کنید."

#: ../iw/lvm_dialog_gui.py:715
msgid "No free space"
msgstr "فضای آزادی وجود ندارد"

#: ../iw/lvm_dialog_gui.py:716
#, fuzzy
msgid ""
"There is no room left in the volume group to create new logical volumes. To "
"add a logical volume you must reduce the size of one or more of the "
"currently existing logical volumes"
msgstr ""
"جایی برای ایجاد جلد منطقی در گروه جلدی باقی نمانده است. برای اضافه کردن یک "
"جلد منطقی باید اندازهٔ یک یا چند جلد منطقی موجود فعلی را کم کنید."

#: ../iw/lvm_dialog_gui.py:748
#, fuzzy, python-format
msgid "Are you sure you want to delete the logical volume \"%s\"?"
msgstr "آیا مطمئنید می‌خواهید جلد منطقی «%s» را حذف کنید؟"

#: ../iw/lvm_dialog_gui.py:861
msgid "Invalid Volume Group Name"
msgstr "نام نامعتبر گروه جلد"

#: ../iw/lvm_dialog_gui.py:870
msgid "Name in use"
msgstr "نام مورد استفاده است"

#: ../iw/lvm_dialog_gui.py:871
#, python-format
msgid "The volume group name \"%s\" is already in use. Please pick another."
msgstr "نام گروه جلد «%s» از قبل مورد استفاده است. لطفاً نام دیگری انتخاب کنید."

#: ../iw/lvm_dialog_gui.py:1095
msgid "Not enough physical volumes"
msgstr "جلد‌های فیزیکی کافی وجود ندارند"

#: ../iw/lvm_dialog_gui.py:1096
msgid ""
"At least one unused physical volume partition is needed to create an LVM "
"Volume Group.\n"
"\n"
"Create a partition or RAID array of type \"physical volume (LVM)\" and then "
"select the \"LVM\" option again."
msgstr ""
"حداقل یک افراز استفاده نشدهٔ جلد فیزیکی برای ایجاد یک گروه جلدی LVM لازم "
"است.\n"
"\n"
"یک افراز یا آرایهٔ RAID از نوع «جلد فیزیکی (LVM)» ایجاد کنید و سپس دوباره "
"گزینهٔ «LVM» را انتخاب کنید."

#: ../iw/lvm_dialog_gui.py:1107
msgid "Make LVM Volume Group"
msgstr "ساختن گروه جلد LVM"

#: ../iw/lvm_dialog_gui.py:1110
#, python-format
msgid "Edit LVM Volume Group: %s"
msgstr "ویرایش گروه جلد LVM: %s"

#: ../iw/lvm_dialog_gui.py:1112
msgid "Edit LVM Volume Group"
msgstr "ویرایش گروه جلد LVM"

#: ../iw/lvm_dialog_gui.py:1128
msgid "_Volume Group Name:"
msgstr "نام گروه _جلد:"

#: ../iw/lvm_dialog_gui.py:1136
msgid "Volume Group Name:"
msgstr "نام گروه جلد:"

#: ../iw/lvm_dialog_gui.py:1144
msgid "_Physical Extent:"
msgstr "گسترهٔ _فیزیکی:"

#: ../iw/lvm_dialog_gui.py:1159
msgid "Physical Volumes to _Use:"
msgstr "جلد‌های فیزیکی مورد ا_ستفاده:"

#: ../iw/lvm_dialog_gui.py:1165
msgid "Used Space:"
msgstr "فضای استفاده شده:"

#: ../iw/lvm_dialog_gui.py:1182
msgid "Free Space:"
msgstr "فضای آزاد:"

#: ../iw/lvm_dialog_gui.py:1200
msgid "Total Space:"
msgstr "فضای کل:"

#: ../iw/lvm_dialog_gui.py:1235
msgid "Logical Volume Name"
msgstr "نام جلد منطقی"

#: ../iw/lvm_dialog_gui.py:1238 ../iw/partition_gui.py:366
#: ../iw/upgrade_swap_gui.py:140 ../textw/upgrade_text.py:118
msgid "Mount Point"
msgstr "نقطهٔ سوار کردن"

#: ../iw/lvm_dialog_gui.py:1241 ../iw/partition_gui.py:371
msgid "Size (MB)"
msgstr "اندازه (مگابایت)"

#: ../iw/lvm_dialog_gui.py:1255 ../iw/osbootwidget.py:94
msgid "_Add"
msgstr "ا_ضافه کردن"

#: ../iw/lvm_dialog_gui.py:1258 ../iw/osbootwidget.py:98
#: ../iw/partition_gui.py:1332
msgid "_Edit"
msgstr "_ویرایش"

#: ../iw/lvm_dialog_gui.py:1273
#, fuzzy
msgid "_Logical Volumes"
msgstr "جلد‌های منطقی"

#: ../iw/netconfig_dialog.py:193 ../textw/netconfig_text.py:36
#, python-format
msgid ""
"An error occurred converting the value entered for \"%s\":\n"
"%s"
msgstr ""
"در تبدیل مقدار وارد شده برای «%s» خطایی رخ داد:\n"
"‏%s"

#: ../iw/netconfig_dialog.py:195 ../iw/netconfig_dialog.py:204
#: ../textw/netconfig_text.py:35 ../textw/netconfig_text.py:40
msgid "Error With Data"
msgstr "خطای داده‌ها"

#: ../iw/netconfig_dialog.py:203
#, fuzzy, python-format
msgid "A value is required for the field %s."
msgstr "مقداری برای فیلد «%s» لازم است."

#: ../iw/netconfig_dialog.py:213
#, fuzzy, python-format
msgid "An error occurred trying to bring up the %s network interface."
msgstr "هنگام نسخه‌برداری از عکس‌های ‌صفحه خطایی رخ داد."

#: ../iw/netconfig_dialog.py:215
#, fuzzy
msgid "Error Configuring Network"
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../iw/netconfig_dialog.py:237
msgid "Dynamic IP"
msgstr "‏IP‏ پویا"

#: ../iw/netconfig_dialog.py:238
#, python-format
msgid "Sending request for IP information for %s..."
msgstr "در حال فرستادن درخواست برای اطلاعات IP‏ برای %s..."

#: ../iw/netconfig_dialog.py:253 ../iw/netconfig_dialog.py:256
#: ../textw/netconfig_text.py:214 ../textw/netconfig_text.py:217
msgid "IP Address"
msgstr "نشانی IP"

#: ../iw/netconfig_dialog.py:263 ../textw/netconfig_text.py:224
#, fuzzy
msgid "IPv4 CIDR prefix must be between 0 and 32."
msgstr "نشانی‌های IP باید حاوی اعداد بین ۱ و ۲۵۵ باشند"

#: ../iw/netconfig_dialog.py:264 ../iw/netconfig_dialog.py:270
#: ../iw/netconfig_dialog.py:278 ../iw/netconfig_dialog.py:281
#: ../textw/netconfig_text.py:225 ../textw/netconfig_text.py:231
#: ../textw/netconfig_text.py:239
#, fuzzy
msgid "IPv4 Network Mask"
msgstr "‏IP‏/نقاب شبکه"

#: ../iw/netconfig_dialog.py:291 ../textw/netconfig_text.py:252
msgid "Gateway"
msgstr "دروازه"

#: ../iw/netconfig_dialog.py:301 ../textw/netconfig_text.py:262
msgid "Nameserver"
msgstr "کارگزار نام"

#: ../iw/netconfig_dialog.py:310
#, fuzzy
msgid "Error configuring network device:"
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../iw/network_gui.py:60 ../iw/network_gui.py:66
#, fuzzy
msgid "Error with Hostname"
msgstr "خطای داده‌ها"

#: ../iw/network_gui.py:61
#, fuzzy
msgid "You must enter a valid hostname for this computer."
msgstr "باید نام کارگزاری وارد کنید."

#: ../iw/network_gui.py:67
#, python-format
msgid ""
"The hostname \"%s\" is not valid for the following reason:\n"
"\n"
"%s"
msgstr ""
"نام میزبان «%s» به دلایل زیر معتبر نیست:\n"
"\n"
"‏%s"

#: ../iw/osbootwidget.py:49
#, fuzzy
msgid "Boot loader operating system list"
msgstr "گذرواژهٔ بارکنندهٔ راه‌انداز خیلی کوتاه است"

#: ../iw/osbootwidget.py:65
msgid "Default"
msgstr "پیش‌فرض"

#: ../iw/osbootwidget.py:65 ../iw/partition_gui.py:365
msgid "Label"
msgstr "برچسب"

#: ../iw/osbootwidget.py:65 ../iw/partition_gui.py:364
msgid "Device"
msgstr "دستگاه"

#: ../iw/osbootwidget.py:128
msgid "Image"
msgstr "تصویر"

#: ../iw/osbootwidget.py:135
#, fuzzy
msgid ""
"Enter a label for the boot loader menu to display. The device (or hard drive "
"and partition number) is the device from which it boots."
msgstr ""
"برچسبی را که در منوی بارکنندهٔ راه‌انداز نمایش داده می‌شود وارد کنید. دستگاه "
"(یا دیسک سخت و شمارهٔ افراز) دستگاهی است که از آن راه‌اندازی می‌شود."

#: ../iw/osbootwidget.py:143
msgid "_Label"
msgstr "بر_چسب"

#: ../iw/osbootwidget.py:151
msgid "_Device"
msgstr "_دستگاه"

#: ../iw/osbootwidget.py:181
msgid "Default Boot _Target"
msgstr "هدف راه‌اندازی _پیش‌فرض"

#: ../iw/osbootwidget.py:210
msgid "You must specify a label for the entry"
msgstr "باید برچسبی برای ورودی مشخص کنید"

#: ../iw/osbootwidget.py:219
msgid "Boot label contains illegal characters"
msgstr "برچسب راه‌اندازی دارای نویسه‌های غیرمجاز است"

#: ../iw/osbootwidget.py:243
msgid "Duplicate Label"
msgstr "تکثیر برچسب"

#: ../iw/osbootwidget.py:244
msgid "This label is already in use for another boot entry."
msgstr "این برچسب از قبل برای مدخل راه‌اندازی دیگری استفاده می‌شود."

#: ../iw/osbootwidget.py:257
msgid "Duplicate Device"
msgstr "تکثیر دستگاه"

#: ../iw/osbootwidget.py:258
msgid "This device is already being used for another boot entry."
msgstr "این دستگاه از قبل برای مدخل راه‌اندازی دیگری استفاده می‌شود."

#: ../iw/osbootwidget.py:322
msgid "Cannot Delete"
msgstr "نمی‌توان حذف کرد"

#: ../iw/osbootwidget.py:323
#, python-format
msgid ""
"This boot target cannot be deleted because it is for the %s system you are "
"about to install."
msgstr ""
"نمی‌توان این هدف راه‌اندازی را حذف کرد چون متعلق به سیستم %s است که در حال نصب "
"آن هستید."

#: ../iw/partition_dialog_gui.py:57
msgid "Additional Size Options"
msgstr "گزینه‌های اضافی اندازه"

#: ../iw/partition_dialog_gui.py:62
msgid "_Fixed size"
msgstr "اندازهٔ _ثابت"

#: ../iw/partition_dialog_gui.py:64
msgid "Fill all space _up to (MB):"
msgstr "پر کردن همهٔ فضا _تا (مگابایت):"

#: ../iw/partition_dialog_gui.py:74
msgid "Fill to maximum _allowable size"
msgstr "پر کردن تا حداکثر اندازهٔ _ممکن"

#: ../iw/partition_dialog_gui.py:276
msgid "Add Partition"
msgstr "اضافه کردن افراز"

#: ../iw/partition_dialog_gui.py:278
#, fuzzy, python-format
msgid "Edit Partition: %s"
msgstr "ویرایش افراز: ‎/dev/%s"

#: ../iw/partition_dialog_gui.py:315
msgid "File System _Type:"
msgstr "_نوع سیستم پرونده‌ای:"

#: ../iw/partition_dialog_gui.py:331
msgid "Allowable _Drives:"
msgstr "دیسک‌گردان‌های _مجاز:"

#: ../iw/partition_dialog_gui.py:400
msgid "Force to be a _primary partition"
msgstr "حتماً افراز ا_صلی باشد"

#: ../iw/partition_gui.py:317
#, python-format
msgid "Drive %s (Geom: %s/%s/%s) (Model: %s)"
msgstr ""

#: ../iw/partition_gui.py:322
#, python-format
msgid "Drive %s (%-0.f MB) (Model: %s)"
msgstr ""

#: ../iw/partition_gui.py:367
msgid "Type"
msgstr "نوع"

#: ../iw/partition_gui.py:370
msgid "Format"
msgstr "قالب‌بندی"

#: ../iw/partition_gui.py:408
msgid ""
"Mount Point/\n"
"RAID/Volume"
msgstr ""
"نقطهٔ سوار کردن/\n"
"‏RAID/جلد"

#: ../iw/partition_gui.py:410
msgid ""
"Size\n"
"(MB)"
msgstr ""
"اندازه\n"
"(مگابایت)"

#: ../iw/partition_gui.py:522
msgid "Partitioning"
msgstr "افرازبندی"

#: ../iw/partition_gui.py:612
msgid ""
"The partitioning scheme you requested caused the following critical errors."
msgstr ""

#: ../iw/partition_gui.py:614
#, fuzzy, python-format
msgid ""
"You must correct these errors before you continue your installation of %s."
msgstr "پیش از ادامهٔ نصب %s این خطاها باید برطرف شوند."

#: ../iw/partition_gui.py:620
msgid "Partitioning Errors"
msgstr "خطاهای افرازبندی"

#: ../iw/partition_gui.py:627
msgid "The partitioning scheme you requested generated the following warnings."
msgstr ""

#: ../iw/partition_gui.py:629
msgid "Would you like to continue with your requested partitioning scheme?"
msgstr "آیا می‌خواهید با همین شِمای افرازبندی درخواست شده ادامه دهید؟"

#: ../iw/partition_gui.py:634
msgid "Partitioning Warnings"
msgstr "اخطارهای افرازبندی"

#: ../iw/partition_gui.py:655
msgid "Format Warnings"
msgstr "اخطارهای قالب‌بندی"

#: ../iw/partition_gui.py:660
msgid "_Format"
msgstr "_قالب‌بندی"

#: ../iw/partition_gui.py:686
msgid "LVM Volume Groups"
msgstr "گروه‌های جلد LVM"

#: ../iw/partition_gui.py:733
msgid "RAID Devices"
msgstr "دستگاه‌های RAID"

#: ../iw/partition_gui.py:800 ../loader/hdinstall.c:231
msgid "Hard Drives"
msgstr "‌دیسک‌گردان‌های سخت"

#: ../iw/partition_gui.py:895
msgid "Extended"
msgstr "گسترش یافته"

#: ../iw/partition_gui.py:897
msgid "software RAID"
msgstr "‏RAID نرم‌افزاری"

#: ../iw/partition_gui.py:929
msgid "Free"
msgstr "آزاد"

#: ../iw/partition_gui.py:1022 ../storage/partitioning.py:174
#: ../storage/partitioning.py:207
msgid "Error Partitioning"
msgstr "خطا در افرازبندی"

#: ../iw/partition_gui.py:1023
#, python-format
msgid "Could not allocate requested partitions: %s."
msgstr "نمی‌توان افرازهای درخواست شده را تخصیص داد: %s."

#: ../iw/partition_gui.py:1032
#, python-format
msgid "Warning: %s."
msgstr "اخطار: %s."

#: ../iw/partition_gui.py:1062 ../iw/partition_gui.py:1069
msgid "Unable To Edit"
msgstr "ویرایش ممکن نیست"

#: ../iw/partition_gui.py:1063
#, fuzzy
msgid "You must select a device to edit"
msgstr "باید افرازی را برای ویرایش انتخاب کنید"

#: ../iw/partition_gui.py:1070
#, fuzzy, python-format
msgid ""
"You cannot edit this device:\n"
"\n"
"%s"
msgstr ""
"نمی‌توانید این افراز را ویرایش کنید:\n"
"\n"

#: ../iw/partition_gui.py:1177 ../iw/partition_gui.py:1189
msgid "Not supported"
msgstr "پشتیبانی نمی‌شود"

#: ../iw/partition_gui.py:1178
msgid "LVM is NOT supported on this platform."
msgstr "‏LVM در این بستر پشتیبانی نمی‌شود."

#: ../iw/partition_gui.py:1190
msgid "Software RAID is NOT supported on this platform."
msgstr "‏RAID نرم‌افزاری در این بستر پشتیبانی نمی‌شود."

#: ../iw/partition_gui.py:1197
msgid "No RAID minor device numbers available"
msgstr "هیچ شمارهٔ دستگاه RAID کوچکتری موجود نیست"

#: ../iw/partition_gui.py:1198
msgid ""
"A software RAID device cannot be created because all of the available RAID "
"minor device numbers have been used."
msgstr ""
"نمی‌توان دستگاه RAID نرم‌افزاری ایجاد کرد چون همهٔ شماره‌های کوچکتر موجود برای "
"دستگاه‌های RAID استفاده شده‌اند."

#: ../iw/partition_gui.py:1210
msgid "RAID Options"
msgstr "گزینه‌های RAID"

#: ../iw/partition_gui.py:1221
#, python-format
msgid ""
"Software RAID allows you to combine several disks into a larger RAID "
"device.  A RAID device can be configured to provide additional speed and "
"reliability compared to using an individual drive.  For more information on "
"using RAID devices please consult the %s documentation.\n"
"\n"
"You currently have %s software RAID partition(s) free to use.\n"
"\n"
msgstr ""
"‏RAID نرم‌افزاری شما را قادر می‌سازد چندین دیسک را با هم ترکیب کرده،  یک دستگاه "
"RAID بزرگتر تشکیل ‌دهید. می‌توان دستگاه‌های RAID را طوری پیکربندی کرد که در "
"مقایسه با استفاده از یک دیسک‌گردان تکی سرعت و اعتبار بیشتری داشته باشند. برای "
"اطلاعات بیشتر دربارهٔ استفاده از دستگاه‌های RAID لطفاً به مستندات %s مراجعه "
"کنید.\n"
"\n"
"شما در حال حاضر %s افراز RAID نرم‌افزاری قابل استفاده دارید.\n"
"\n"

#: ../iw/partition_gui.py:1232
#, fuzzy
msgid ""
"To use RAID you must first create at least two partitions of type 'software "
"RAID'.  Then you can create a RAID device that can be formatted and "
"mounted.\n"
"\n"
msgstr ""
"برای استفاده از RAID باید اول حداقل دو افراز از نوع «RAID نرم‌افزاری» ایجاد "
"کنید. سپس می‌توانید یک دستگاه RAID ایجاد کنید که می‌تواند قالب‌بندی و سوار "
"شود.\n"
"\n"

#: ../iw/partition_gui.py:1238
msgid "What do you want to do now?"
msgstr "حالا می‌خواهید چه‌کار کنید؟"

#: ../iw/partition_gui.py:1247
msgid "Create a software RAID _partition."
msgstr "ایجاد یک ا_فراز RAID نرم‌افزاری."

#: ../iw/partition_gui.py:1250
#, python-format
msgid "Create a RAID _device [default=/dev/md%s]."
msgstr "ایجاد _دستگاه RAID [پیش‌فرض=‎/dev/md%s]."

#: ../iw/partition_gui.py:1254
#, python-format
msgid "Clone a _drive to create a RAID device [default=/dev/md%s]."
msgstr "همانندسازی یک دیسک_گردان برای ایجاد دستگاه RAID [پیش‌فرض=‎/dev/md%s]."

#: ../iw/partition_gui.py:1296
msgid "Couldn't Create Drive Clone Editor"
msgstr "ویرایشگر همانندسازی دیسک‌گردان ایجاد نشد"

#: ../iw/partition_gui.py:1297
msgid "The drive clone editor could not be created for some reason."
msgstr "ویرایشگر همانندسازی دیسک‌گردان به دلیلی ایجاد نشد."

#: ../iw/partition_gui.py:1331
msgid "Ne_w"
msgstr "_جدید"

#: ../iw/partition_gui.py:1334
msgid "Re_set"
msgstr "_مقادیر اولیه"

#: ../iw/partition_gui.py:1335
msgid "R_AID"
msgstr "‏R_AID"

#: ../iw/partition_gui.py:1336
msgid "_LVM"
msgstr "‏_LVM"

#: ../iw/partition_gui.py:1377
msgid "Hide RAID device/LVM Volume _Group members"
msgstr "مخفی کردن دستگاه RAID/اعضای _گروه جلدی LVM"

#: ../iw/partition_ui_helpers_gui.py:106 ../iw/partition_ui_helpers_gui.py:128
#: ../iw/partition_ui_helpers_gui.py:130
msgid "<Not Applicable>"
msgstr "<مربوط نیست>"

#: ../iw/partition_ui_helpers_gui.py:306
#, fuzzy
msgid "_Format as:"
msgstr "قالب‌بندی به شکل:"

#: ../iw/partition_ui_helpers_gui.py:325
#, fuzzy
msgid "Mi_grate filesystem to:"
msgstr "کوچ‌دادن سیستم پرونده‌ای"

#: ../iw/partition_ui_helpers_gui.py:351 tmp/autopart.glade.h:9
#, fuzzy
msgid "_Resize"
msgstr "اندازهٔ _ثابت"

#: ../iw/partition_ui_helpers_gui.py:409
#, fuzzy, python-format
msgid ""
"Partitions of type '%s' must be constrained to a single drive.  To do this, "
"select the drive in the 'Allowable Drives' checklist."
msgstr ""
"افرازهایی از نوع «%s» باید درون یک دیسک‌گردان جا بگیرند. این کار با انتخاب "
"دیسک‌گردان در فهرست «دیسک‌گردان‌های مجاز» انجام می‌گیرد."

#: ../iw/progress_gui.py:37
msgid "Installing Packages"
msgstr "در حال نصب بسته‌ها"

#: ../iw/raid_dialog_gui.py:312
msgid ""
"At least two unused software RAID partitions are needed to create a RAID "
"device.\n"
"\n"
"First create at least two partitions of type \"software RAID\", and then "
"select the \"RAID\" option again."
msgstr ""
"حداقل دو افراز RAID نرم‌افزاری استفاده نشده برای ایجاد یک دستگاه RAID لازم "
"است.\n"
"\n"
"اول حداقل دو افراز از نوع «RAID نرم‌افزاری» ایجاد کنید، و سپس  دوباره گزینهٔ "
"«RAID» را انتخاب کنید."

#: ../iw/raid_dialog_gui.py:326 ../iw/raid_dialog_gui.py:763
msgid "Make RAID Device"
msgstr "ساختن دستگاه RAID"

#: ../iw/raid_dialog_gui.py:329
#, fuzzy, python-format
msgid "Edit RAID Device: %s"
msgstr "ویرایش دستگاه RAID"

#: ../iw/raid_dialog_gui.py:331
msgid "Edit RAID Device"
msgstr "ویرایش دستگاه RAID"

#: ../iw/raid_dialog_gui.py:402
msgid "RAID _Device:"
msgstr "_دستگاه RAID:"

#: ../iw/raid_dialog_gui.py:420
msgid "RAID _Level:"
msgstr "_سطح RAID:"

#: ../iw/raid_dialog_gui.py:462
msgid "_RAID Members:"
msgstr "_اعضای RAID:"

#: ../iw/raid_dialog_gui.py:479
msgid "Number of _spares:"
msgstr "تعداد  قطعات_یدکی:"

#: ../iw/raid_dialog_gui.py:489
msgid "_Format partition?"
msgstr "افراز _قالب‌بندی شود؟"

#: ../iw/raid_dialog_gui.py:563
msgid ""
"The source drive has no partitions to be cloned.  You must first define "
"partitions of type 'software RAID' on this drive before it can be cloned."
msgstr ""
"دیسک‌گردان مبدأ افرازی برای همانندسازی ندارد. باید اول افرازهایی از نوع «RAID "
"نرم‌افزاری» روی این دیسک‌گردان تعیین کنید، سپس می‌توانید آن را همانندسازی کنید."

#: ../iw/raid_dialog_gui.py:567 ../iw/raid_dialog_gui.py:573
#: ../iw/raid_dialog_gui.py:587 ../iw/raid_dialog_gui.py:600
msgid "Source Drive Error"
msgstr "خطای دیسک‌گردان مبدأ"

#: ../iw/raid_dialog_gui.py:574
#, fuzzy
msgid ""
"The source drive you selected has partitions which are not of type 'software "
"RAID'.\n"
"\n"
"You must remove these partitions before this drive can be cloned. "
msgstr ""
"دیسک‌گردان مبدأ دارای افرازهایی است که از نوع «RAID نرم‌افزاری» نیستند.\n"
"\n"
"قبل از این که بتوان این دیسک‌گردان را همانندسازی کرد باید این افرازها حذف "
"شوند."

#: ../iw/raid_dialog_gui.py:588
#, fuzzy, python-format
msgid ""
"The source drive you selected has partitions which are not constrained to "
"the drive %s.\n"
"\n"
"You must remove these partitions or restrict them to this drive before this "
"drive can be cloned. "
msgstr ""
"دیسک‌گردان مبدأ انتخاب شده دارای افرازهایی است که در دیسک‌گردان ‏/dev/%s جا "
"داده نشده‌اند.\n"
"\n"
"قبل از این که بتوان این دیسک‌گردان را همانندسازی کرد، این افرازها باید حذف یا "
"محدود به این دیسک‌گردان شوند."

#: ../iw/raid_dialog_gui.py:601
#, fuzzy
msgid ""
"The source drive you selected has software RAID partition(s) which are "
"members of an active software RAID device.\n"
"\n"
"You must remove these partitions before this drive can be cloned."
msgstr ""
"دیسک‌گردان مبدأ دارای افرازهای RAID نرم‌افزاری است که اعضای یک دستگاه RAID "
"نرم‌افزاری فعال هستند.\n"
"\n"
"قبل از این که بتوان این دیسک‌گردان را همانندسازی کرد، این افرازها باید حذف "
"شوند."

#: ../iw/raid_dialog_gui.py:615 ../iw/raid_dialog_gui.py:621
#: ../iw/raid_dialog_gui.py:637
msgid "Target Drive Error"
msgstr "خطای دیسک‌گردان هدف"

#: ../iw/raid_dialog_gui.py:616
msgid "Please select the target drives for the clone operation."
msgstr "لطفاً دیسک‌گردان‌های هدف را برای عملیات همانندسازی انتخاب کنید."

#: ../iw/raid_dialog_gui.py:622
#, fuzzy, python-format
msgid "The source drive %s cannot be selected as a target drive as well."
msgstr ""
"نمی‌توان دیسک‌گردان مبدأ ‎/dev/%s را به عنوان دیسک‌گردان هدف هم انتخاب کرد."

#: ../iw/raid_dialog_gui.py:638
#, fuzzy, python-format
msgid ""
"The target drive %s has a partition which cannot be removed for the "
"following reason:\n"
"\n"
"\"%s\"\n"
"\n"
"You must remove this partition before this drive can be a target."
msgstr ""
"دیسک‌گردان هدف ‎/dev/%s دارای افرازی است که به دلایل زیر نمی‌توان آن را حذف "
"کرد:\n"
"\n"
"«%s»\n"
"\n"
"قبل از این که این دیسک‌گردان بتواند هدف قرار گیرد، این افراز باید حذف شود."

#: ../iw/raid_dialog_gui.py:701
msgid "Please select a source drive."
msgstr "لطفاً دیسک‌گردان مبدأ را انتخاب کنید."

#: ../iw/raid_dialog_gui.py:721
#, fuzzy, python-format
msgid ""
"The drive %s will now be cloned to the following drives:\n"
"\n"
msgstr ""
"دیسک‌گردان ‎/dev/%s اکنون به دیسک‌گردان‌های زیر همانندسازی خواهد شد:\n"
"\n"

#: ../iw/raid_dialog_gui.py:726
msgid ""
"\n"
"\n"
"WARNING! ALL DATA ON THE TARGET DRIVES WILL BE DESTROYED."
msgstr ""
"\n"
"\n"
"اخطار! همهٔ داده‌های روی دیسک‌گردان‌های هدف از بین خواهد رفت."

#: ../iw/raid_dialog_gui.py:729
msgid "Final Warning"
msgstr "اخطار نهایی"

#: ../iw/raid_dialog_gui.py:731
msgid "Clone Drives"
msgstr "همانندسازی دیسک‌گردان‌ها"

#: ../iw/raid_dialog_gui.py:740
msgid "There was an error clearing the target drives.  Cloning failed."
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../iw/raid_dialog_gui.py:773
#, fuzzy
msgid ""
"Clone Drive Tool\n"
"\n"
"This tool allows you to significantly reduce the amount of effort required "
"to setup RAID arrays.  This tool uses a source drive which has been prepared "
"with the desired partitioning layout, and clones this layout onto other "
"similar sized drives.  Then a RAID device can be created.\n"
"\n"
"NOTE: The source drive must have partitions which are restricted to be on "
"that drive only, and can only contain unused software RAID partitions.  "
"Other partition types are not allowed.\n"
"\n"
"EVERYTHING on the target drive(s) will be destroyed by this process."
msgstr ""
"ابزار همانندسازی دیسک‌گردان\n"
"\n"
"این ابزار شما را قادر می‌سازد با کمترین دردسر آرایه‌های RAID را برپاسازی کنید. "
"طرح این است که دیسک‌گردان مبدأ را که با چیدمان افرازبندی مورد نظر آماده شده "
"بگیریم و این چیدمان را روی دیسک‌گردان‌های هم‌اندازهٔ دیگر همانندسازی کنیم. سپس "
"می‌توان یک دستگاه RAID ایجاد کرد.\n"
"\n"
"توجه: دیسک‌گردان مبدأ باید شامل افرازهایی باشد که فقط به همان دیسک‌گردان محدود "
"شده باشند، و می‌تواند فقط حاوی افرازهایRAID نرم‌افزاری استفاده نشده باشند. "
"دیگر انواع افراز مجاز نیستند.\n"
"\n"
"همه چیز روی دیسک‌گردان(های) مبدأ در این روند از بین خواهد رفت."

#: ../iw/raid_dialog_gui.py:793
msgid "Source Drive:"
msgstr "دیسک‌گردان مبدأ:"

#: ../iw/raid_dialog_gui.py:801
msgid "Target Drive(s):"
msgstr "دیسک‌گردان‌(های) هدف:"

#: ../iw/raid_dialog_gui.py:809
msgid "Drives"
msgstr "دیسک‌گردان‌ها"

#: ../iw/task_gui.py:64
#, python-format
msgid ""
"Unable to read package metadata from repository.  This may be due to a "
"missing repodata directory.  Please ensure that your repository has been "
"correctly generated.\n"
"\n"
"%s"
msgstr ""

#: ../iw/task_gui.py:162
#, fuzzy, python-format
msgid ""
"The repository %s has already been added.  Please choose a different "
"repository name and URL."
msgstr ""
"نقطهٔ سوار کردن «%s» از قبل مورد استفاده است، لطفاً نقطهٔ سوار کردن دیگری انتخاب "
"کنید."

#: ../iw/task_gui.py:175
#, fuzzy
msgid "Edit Repository"
msgstr "برچسب راه‌اندازی نامعتبر"

#: ../iw/task_gui.py:238
#, fuzzy
msgid "Invalid Proxy URL"
msgstr "برچسب راه‌اندازی نامعتبر"

#: ../iw/task_gui.py:239
msgid "You must provide an HTTP, HTTPS, or FTP URL to a proxy."
msgstr ""

#: ../iw/task_gui.py:250 ../iw/task_gui.py:388
#, fuzzy
msgid "Invalid Repository URL"
msgstr "برچسب راه‌اندازی نامعتبر"

#: ../iw/task_gui.py:251 ../iw/task_gui.py:389
#, fuzzy
msgid "You must provide an HTTP, HTTPS, or FTP URL to a repository."
msgstr "باید نام کارگزاری وارد کنید."

#: ../iw/task_gui.py:273 ../iw/task_gui.py:398
#, fuzzy
msgid "No Media Found"
msgstr "دیسک‌گردانی پیدا نشد"

#: ../iw/task_gui.py:274 ../iw/task_gui.py:399
msgid ""
"No installation media was found. Please insert a disc into your drive and "
"try again."
msgstr ""

#: ../iw/task_gui.py:293 ../iw/task_gui.py:415
#, fuzzy
msgid "Please enter an NFS server and path."
msgstr "لطفاً نام گروه جلد را وارد کنید."

#: ../iw/task_gui.py:325
#, fuzzy
msgid "Invalid Repository Name"
msgstr "نام میزبان نامعتبر"

#: ../iw/task_gui.py:326
#, fuzzy
msgid "You must provide a repository name."
msgstr "باید نام کارگزاری وارد کنید."

#: ../iw/task_gui.py:450 tmp/addrepo.glade.h:3
msgid "Add Repository"
msgstr ""

#: ../iw/task_gui.py:455
msgid "No Software Repos Enabled"
msgstr ""

#: ../iw/task_gui.py:456
#, fuzzy
msgid ""
"You must have at least one software repository enabled to continue "
"installation."
msgstr "پیش از ادامهٔ نصب %s این خطاها باید برطرف شوند."

#: ../iw/timezone_gui.py:63 ../textw/timezone_text.py:96
msgid "Time Zone Selection"
msgstr "انتخاب منطقهٔ زمانی"

#: ../iw/upgrade_bootloader_gui.py:36 ../textw/upgrade_bootloader_text.py:135
msgid "Upgrade Boot Loader Configuration"
msgstr "ارتقاء دادن پیکربندی بارکنندهٔ راه‌انداز"

#: ../iw/upgrade_bootloader_gui.py:122
msgid "_Update boot loader configuration"
msgstr "_به‌هنگام‌سازی پیکربندی بارکنندهٔ راه‌انداز"

#: ../iw/upgrade_bootloader_gui.py:123
msgid "This will update your current boot loader."
msgstr "این کار بارکنندهٔ راه‌انداز فعلی شما را به‌هنگام خواهد کرد."

#: ../iw/upgrade_bootloader_gui.py:127 ../textw/upgrade_bootloader_text.py:107
msgid ""
"Due to system changes, your boot loader configuration can not be "
"automatically updated."
msgstr ""

#: ../iw/upgrade_bootloader_gui.py:130 ../textw/upgrade_bootloader_text.py:111
msgid ""
"The installer is unable to detect the boot loader currently in use on your "
"system."
msgstr ""
"برنامهٔ نصب نمی‌تواند بارکنندهٔ راه‌انداز مورد استفاده در سیستم شما را تشخیص دهد."

#: ../iw/upgrade_bootloader_gui.py:137 ../textw/upgrade_bootloader_text.py:120
#, python-format
msgid ""
"The installer has detected the %s boot loader currently installed on %s."
msgstr "برنامهٔ نصب، بارکنندهٔ راه‌انداز %s را که اکنون بر %s نصب شده تشخیص داد."

#: ../iw/upgrade_bootloader_gui.py:141
msgid "This is the recommended option."
msgstr "این گزینه توصیه می‌شود."

#: ../iw/upgrade_bootloader_gui.py:146
msgid "_Create new boot loader configuration"
msgstr "ای_جاد پیکربندی بارکنندهٔ راه‌انداز جدید"

#: ../iw/upgrade_bootloader_gui.py:148
#, fuzzy
msgid ""
"This option creates a new boot loader configuration.  If you wish to switch "
"boot loaders, you should choose this."
msgstr ""
"این کار شما را قادر می‌سازد پیکربندی بارکنندهٔ راه‌انداز جدیدی ایجاد کنید. اگر "
"می‌خواهید بتوانید بارکننده‌های راه‌انداز را تعویض کنید، باید این گزینه را "
"انتخاب کنید."

#: ../iw/upgrade_bootloader_gui.py:155
msgid "_Skip boot loader updating"
msgstr "_پرش از روی به‌هنگام‌سازی بارکنندهٔ راه‌انداز"

#: ../iw/upgrade_bootloader_gui.py:156
#, fuzzy
msgid ""
"This option makes no changes to boot loader configuration.  If you are using "
"a third party boot loader, you should choose this."
msgstr ""
"این کار هیچ تغییری در پیکربندی بارکنندهٔ راه‌انداز نخواهد داد. اگر از بارکنندهٔ "
"راه‌اندازی طرف سومی استفاده می‌کنید، باید این را انتخاب کنید."

#: ../iw/upgrade_bootloader_gui.py:167
msgid "What would you like to do?"
msgstr "می‌خواهید چه‌کار کنید؟"

#: ../iw/upgrade_migratefs_gui.py:38 ../textw/upgrade_text.py:36
msgid "Migrate File Systems"
msgstr "کوچ‌دادن سیستم پرونده‌ای"

#: ../iw/upgrade_migratefs_gui.py:70
#, fuzzy, python-format
msgid ""
"This release of %s supports an updated file system, which has several "
"benefits over the file system traditionally shipped in %s.  This "
"installation program can migrate formatted partitions without data loss.\n"
"\n"
"Which of these partitions would you like to migrate?"
msgstr ""
"این انتشار %s از سیستم پرونده‌ای روزنگار ext3 پشتیبانی می‌کند. این سیستم "
"پرونده‌ای نسبت به سیستم پروندهٔ ext2 که به طور سنتی با %s ارسال می‌شود چند "
"برتری دارد. افرازهای قالب‌بندی شدهٔ ext2 را می‌توان بدون از دست دادن داده‌ها به "
"ext3 کوچ داد.\n"
"\n"
"کدام یک از این افرازها را می‌خواهید کوچ دهید؟"

#: ../iw/upgrade_swap_gui.py:35
msgid "Upgrade Swap Partition"
msgstr "ارتقاء دادن افراز حافظهٔ مبادله"

#: ../iw/upgrade_swap_gui.py:94 ../textw/upgrade_text.py:101
#, fuzzy, python-format
msgid ""
"Recent kernels (2.4 or newer) need significantly more swap than older "
"kernels, up to twice the amount of RAM on the system.  You currently have %"
"dMB of swap configured, but you may create additional swap space on one of "
"your file systems now."
msgstr ""
"هستهٔ ‎2.4 به حافظهٔ مبادلهٔ بسیار بیشتری از هسته‌های قدیمی‌تر نیاز دارد، تقریباً "
"به اندازهٔ دو برابر حافظهٔ RAM سیستم. شما در حال حاضر %d مگابایت حافظهٔ مبادله "
"پیکربندی کرده‌اید، ولی اکنون می‌توانید فضای مبادلهٔ بیشتری روی یکی از سیستم‌های "
"پرونده‌ای خود ایجاد کنید."

#: ../iw/upgrade_swap_gui.py:101
#, python-format
msgid ""
"\n"
"\n"
"The installer has detected %s MB of RAM.\n"
msgstr ""
"\n"
"\n"
"برنامهٔ نصب کننده %s مگابایت RAM تشخیص داد.\n"

#: ../iw/upgrade_swap_gui.py:113
msgid "I _want to create a swap file"
msgstr "_پروندهٔ مبادله ایجاد شود"

#: ../iw/upgrade_swap_gui.py:122
msgid "Select the _partition to put the swap file on:"
msgstr "افرازی انتخاب کنید تا پروندهٔ مبادله روی آن قرار گیرد:"

#: ../iw/upgrade_swap_gui.py:140 ../textw/upgrade_text.py:119
msgid "Partition"
msgstr "افراز"

#: ../iw/upgrade_swap_gui.py:140
msgid "Free Space (MB)"
msgstr "فضای آزاد (مگابایت)"

#: ../iw/upgrade_swap_gui.py:158
#, fuzzy, python-format
msgid ""
"A minimum swap file size of %d MB is recommended.  Please enter a size for "
"the swap file:"
msgstr ""
"توصیه می‌شود که پروندهٔ مبادله حداقل %d مگابایت باشد. لطفاً اندازهٔ پروندهٔ "
"مبادله را وارد کنید:"

#: ../iw/upgrade_swap_gui.py:173
msgid "Swap file _size (MB):"
msgstr "ا_ندازهٔ پروندهٔ مبادله (مگابایت):"

#: ../iw/upgrade_swap_gui.py:183
msgid "I _don't want to create a swap file"
msgstr "_نمی خواهم پروندهٔ مبادله ایجاد کنم"

#: ../iw/upgrade_swap_gui.py:193
#, fuzzy
msgid ""
"A swap file is strongly recommended. Failure to create one could cause the "
"installer to abort abnormally.  Are you sure you wish to continue?"
msgstr ""
"اکیداً توصیه می‌شود پروندهٔ مبادله‌ای ایجاد کنید. شکست در این کار ممکن است باعث "
"شود برنامهٔ نصب به طور غیر عادی قطع شود. آیا مطمئنید که می‌خواهید ادامه دهید؟"

#: ../iw/upgrade_swap_gui.py:201 ../textw/upgrade_text.py:188
msgid "The swap file must be between 1 and 2000 MB in size."
msgstr "اندازهٔ پروندهٔ مبادله باید بین ۱ و ۲۰۰۰ مگابایت باشد."

#: ../iw/upgrade_swap_gui.py:208 ../textw/upgrade_text.py:183
msgid ""
"There is not enough space on the device you selected for the swap partition."
msgstr ""
"روی دستگاهی که برای افراز حافظهٔ مبادله انتخاب کرده‌اید فضای کافی وجود ندارد."

#: ../iw/welcome_gui.py:56 ../textw/welcome_text.py:36
msgid "Network Install Required"
msgstr ""

#: ../iw/welcome_gui.py:57 ../textw/welcome_text.py:37
msgid ""
"Your installation source is set to a network location, but no netork devices "
"were found on your system.  To avoid a network installation, boot with the "
"full DVD, full CD set, or do not pass a repo= parameter that specifies a "
"network source."
msgstr ""

#: ../iw/welcome_gui.py:67
#, fuzzy
msgid "E_xit Installer"
msgstr "نصب کنندهٔ %s"

#: ../iw/zipl_gui.py:37
msgid "z/IPL Boot Loader Configuration"
msgstr "پیکربندی بارکنندهٔ راه‌انداز z/IPL"

#: ../iw/zipl_gui.py:61
msgid "The z/IPL boot loader will be installed on your system."
msgstr "بارکنندهٔ راه‌انداز z/IPL بر سیستم شما نصب خواهد شد."

#: ../iw/zipl_gui.py:63
msgid ""
"The z/IPL Boot Loader will now be installed on your system.\n"
"\n"
"The root partition will be the one you selected previously in the partition "
"setup.\n"
"\n"
"The kernel used to start the machine will be the one to be installed by "
"default.\n"
"\n"
"If you wish to make changes later after the installation feel free to change "
"the /etc/zipl.conf configuration file.\n"
"\n"
"You can now enter any additional kernel parameters which your machine or "
"your setup may require."
msgstr ""
"بارکنندهٔ راه‌انداز z/IPL اکنون بر سیستم شما نصب خواهد شد.\n"
"\n"
"افراز root همان افرازی خواهد بود که قبلاً در برپاسازی افراز انتخاب کردید.\n"
"\n"
"هستهٔ مورد استفاده برای راه‌اندازی رایانه همان خواهد بود که به طور پیش‌فرض نصب "
"می‌شود.\n"
"\n"
"اگر بعد از نصب خواستید تغییراتی ایجاد کنید پروندهٔ پیکربندی ‎/etc/zipl.conf را "
"تغییر دهید.\n"
"\n"
"حالا می‌توانید پارامترهای هستهٔ اضافی‌ای را که رایانه یا برپاسازی شما لازم "
"داشته باشد وارد کنید."

#: ../iw/zipl_gui.py:90 ../textw/zipl_text.py:71
msgid "Kernel Parameters"
msgstr "پارامترهای هسته"

#: ../iw/zipl_gui.py:93 ../iw/zipl_gui.py:96
msgid "Chandev Parameters"
msgstr "پارامترهای Chandev"

#: ../textw/complete_text.py:32
msgid "Reboot"
msgstr "راه‌اندازی مجدد"

#: ../textw/complete_text.py:34
msgid "<Enter> to exit"
msgstr "<ورود> برای خروج"

#: ../textw/complete_text.py:62
msgid "Complete"
msgstr "تمام شد"

#: ../textw/constants_text.py:52 ../storage/__init__.py:135
#: ../storage/devicetree.py:78 ../loader/cdinstall.c:452
#: ../loader/driverdisk.c:244 ../loader/driverdisk.c:275
#: ../loader/driverdisk.c:359 ../loader/driverselect.c:81
#: ../loader/driverselect.c:179 ../loader/driverselect.c:205
#: ../loader/hdinstall.c:231 ../loader/hdinstall.c:289 ../loader/kbd.c:138
#: ../loader/loader.c:482 ../loader/loader.c:502 ../loader/loader.c:1378
#: ../loader/loader.c:1409 ../loader/net.c:564 ../loader/net.c:937
#: ../loader/net.c:1808 ../loader/net.c:1830 ../loader/nfsinstall.c:91
#: ../loader/urls.c:292
msgid "Back"
msgstr "عقب"

#: ../textw/keyboard_text.py:48
msgid "Keyboard Selection"
msgstr "انتخاب صفحه‌کلید"

#: ../textw/keyboard_text.py:49
msgid "Which model keyboard is attached to this computer?"
msgstr "چه مدل صفحه‌کلیدی به این رایانه متصل شده است؟"

#: ../textw/netconfig_text.py:41
#, fuzzy, python-format
msgid "A value is required for the field %s"
msgstr "مقداری برای فیلد «%s» لازم است."

#: ../textw/netconfig_text.py:86 tmp/netconfig.glade.h:9
msgid "Enable network interface"
msgstr ""

#: ../textw/netconfig_text.py:89 tmp/netconfig.glade.h:10
msgid ""
"This requires that you have an active network connection during the "
"installation process.  Please configure a network interface."
msgstr ""

#: ../textw/netconfig_text.py:127
#, fuzzy
msgid "Use dynamic IP configuration (DHCP)"
msgstr "استفاده از پیکربندی پویای IP‏ (BOOTP/DHCP)"

#: ../textw/netconfig_text.py:130 ../loader/net.c:542
msgid "Enable IPv4 support"
msgstr ""

#: ../textw/netconfig_text.py:137
#, fuzzy
msgid "IPv4 Address:"
msgstr "نشانی IP:"

#: ../textw/netconfig_text.py:157 ../loader/net.c:896
msgid "Gateway:"
msgstr "دروازه:"

#: ../textw/netconfig_text.py:160
#, fuzzy
msgid "Nameserver:"
msgstr "کارگزار نام"

#: ../textw/netconfig_text.py:190
#, fuzzy
msgid "Missing Device"
msgstr "بستهٔ ناموجود"

#: ../textw/netconfig_text.py:191
#, fuzzy
msgid "You must select a network device"
msgstr "باید افرازی را برای ویرایش انتخاب کنید"

#: ../textw/netconfig_text.py:242
#, fuzzy
msgid "IPv4 Network Mask "
msgstr "‏IP‏/نقاب شبکه"

#: ../textw/netconfig_text.py:265
#, fuzzy
msgid "Configuring Network Interfaces"
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../textw/netconfig_text.py:265
#, fuzzy
msgid "Waiting for NetworkManager..."
msgstr "در انتظار برای اتصال تِلنِت..."

#: ../textw/netconfig_text.py:271
#, fuzzy
msgid "Error configuring network device"
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../textw/netconfig_text.py:271
#, fuzzy, python-format
msgid "Error configuring network device %s"
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../textw/partition_text.py:58
msgid "Partitioning Type"
msgstr ""

#: ../textw/partition_text.py:60 tmp/autopart.glade.h:2
msgid ""
"Installation requires partitioning of your hard drive.  The default layout "
"is suitable for most users.  Select what space to use and which drives to "
"use as the install target. You can also choose to create your own custom "
"layout."
msgstr ""

#: ../textw/partition_text.py:76
msgid "Which drive(s) do you want to use for this installation?"
msgstr "برای این نصب از کدام دیسک‌گردان(ها) می‌خواهید استفاده کنید؟"

#: ../textw/partition_text.py:91
#, fuzzy
msgid "<Space>,<+>,<-> selection   |   <F2> Add drive   |   <F12> next screen"
msgstr "<Space>,<+>,<-> انتخاب   |   <F2> جزئیات گروه   |   <F12> صفحهٔ بعد"

#: ../textw/partition_text.py:165 tmp/adddrive.glade.h:3
#, fuzzy
msgid "Advanced Storage Options"
msgstr "گزینه‌های اضافی اندازه"

#: ../textw/partition_text.py:166 tmp/adddrive.glade.h:5
#, fuzzy
msgid "How would you like to modify your drive configuration?"
msgstr "می‌خواهید سیستم پرونده‌ای این افراز چطور آماده شود؟"

#: ../textw/partition_text.py:189
#, fuzzy
msgid "Add FCP Device"
msgstr "اضافه کردن دستگاه FCP"

#: ../textw/partition_text.py:190 tmp/zfcp-config.glade.h:5
#, fuzzy
msgid ""
"zSeries machines can access industry-standard SCSI devices via Fibre Channel "
"(FCP). You need to provide a 16 bit device number, a 64 bit World Wide Port "
"Name (WWPN), and a 64 bit FCP LUN for each device."
msgstr ""
"رایانه‌های سری z می‌توانند از طریق کانال فیبری (FCP) به دستگاه‌های SCSI صنعتی‐"
"استاندارد دسترسی داشته باشند. برای هر دستگاه ۵ پارامتر باید داده شود: شمارهٔ "
"دستگاه ۱۶ بیتی، شناسهٔ SCSI ‏۱۶ بیتی، نام درگاه جهانی (WWPN) ‏۶۴ بیتی، "
"LUN ‏SCSI ‏۱۶ بیتی و LUN ‏FCP ‏۶۴ بیتی."

#: ../textw/partition_text.py:213 tmp/iscsi-config.glade.h:7
#, fuzzy
msgid "Configure iSCSI Parameters"
msgstr "پارامترهای Chandev"

#: ../textw/partition_text.py:214 tmp/iscsi-config.glade.h:8
msgid ""
"To use iSCSI disks, you must provide the address of your iSCSI target and "
"the iSCSI initiator name you've configured for your host."
msgstr ""

#: ../textw/partition_text.py:215
#, fuzzy
msgid "Target IP Address"
msgstr "نشانی IP"

#: ../textw/partition_text.py:216
#, fuzzy
msgid "iSCSI Initiator Name"
msgstr "نام نامعتبر گروه جلد"

#: ../textw/partition_text.py:217
#, fuzzy
msgid "CHAP username"
msgstr "نام پایگاه FTP:"

#: ../textw/partition_text.py:218
#, fuzzy
msgid "CHAP password"
msgstr "گذرواژه"

#: ../textw/partition_text.py:219
msgid "Reverse CHAP username"
msgstr ""

#: ../textw/partition_text.py:220
msgid "Reverse CHAP password"
msgstr ""

#: ../textw/progress_text.py:46
msgid "Package Installation"
msgstr "نصب بسته"

#: ../textw/timezone_text.py:75
#, fuzzy
msgid "In which time zone are you located?"
msgstr "در چه منطقهٔ زمانی‌ای قرار دارید؟"

#: ../textw/timezone_text.py:93
msgid "System clock uses UTC"
msgstr "ساعت سیستم از وقت گرینویچ استفاده می‌کند"

#: ../textw/upgrade_bootloader_text.py:115
#: ../textw/upgrade_bootloader_text.py:124
msgid "Update boot loader configuration"
msgstr "به‌هنگام‌سازی پیکربندی بارکنندهٔ راه‌انداز"

#: ../textw/upgrade_bootloader_text.py:127
msgid "Skip boot loader updating"
msgstr "پرش از روی به‌هنگام‌سازی بارکنندهٔ راه‌انداز"

#: ../textw/upgrade_bootloader_text.py:129
msgid "Create new boot loader configuration"
msgstr "ایجاد پیکربندی جدید بارکنندهٔ راه‌انداز"

#: ../textw/upgrade_text.py:38
#, fuzzy, python-format
msgid ""
"This release of %s supports the an updated file system, which has several "
"benefits over the file system traditionally shipped in %s.  This "
"installation program can migrate formatted partitions without data loss.\n"
"\n"
"Which of these partitions would you like to migrate?"
msgstr ""
"این انتشار %s از سیستم پرونده‌ای روزنگار ext3 پشتیبانی می‌کند. این سیستم "
"پرونده‌ای نسبت به سیستم پروندهٔ ext2 که به طور سنتی با %s ارسال می‌شود چند "
"برتری دارد. افرازهای قالب‌بندی شدهٔ ext2 را می‌توان بدون از دست دادن داده‌ها به "
"ext3 کوچ داد.\n"
"\n"
"کدام یک از این افرازها را می‌خواهید کوچ دهید؟"

#: ../textw/upgrade_text.py:119
msgid "Free Space"
msgstr "فضای آزاد"

#: ../textw/upgrade_text.py:137
msgid "RAM detected (MB):"
msgstr "حافظهٔ RAM تشخیص داده شده (مگابایت):"

#: ../textw/upgrade_text.py:140
msgid "Suggested size (MB):"
msgstr "اندازهٔ پیشنهادی (مگابایت):"

#: ../textw/upgrade_text.py:143
msgid "Swap file size (MB):"
msgstr "اندازهٔ پروندهٔ مبادله (مگابایت):"

#: ../textw/upgrade_text.py:151
msgid "Add Swap"
msgstr "اضافه کردن حافظهٔ مبادله"

#: ../textw/upgrade_text.py:176
msgid "The value you entered is not a valid number."
msgstr "مقداری که وارد کرده‌اید عدد معتبری نیست."

#: ../textw/upgrade_text.py:209
msgid "Reinstall System"
msgstr "نصب مجدد سیستم"

#: ../textw/upgrade_text.py:219
msgid "System to Upgrade"
msgstr "سیستمی که ارتقاء داده شود"

#: ../textw/upgrade_text.py:220
#, fuzzy
msgid ""
"There seem to be one or more existing Linux installations on your system.\n"
"\n"
"Please choose one to upgrade, or select 'Reinstall System' to freshly "
"install your system."
msgstr ""
"یک یا چند نصب موجود لینوکس روی سیستم شما پیدا شده‌اند.\n"
"\n"
"لطفاً یکی از آنها را برای ارتقاء دادن انتخاب کنید یا برای نصب تازه روی سیستم "
"خود، «نصب مجدد سیستم» را انتخاب کنید."

#: ../textw/userauth_text.py:30
msgid "Root Password"
msgstr "گذرواژهٔ root"

#: ../textw/userauth_text.py:33
#, fuzzy
msgid ""
"Pick a root password. You must type it twice to ensure you know it and do "
"not make a typing mistake. "
msgstr ""
"گذرواژهٔ root را انتخاب کنید. برای اطمینان از دانستن آن و عدم اشتباه در تایپ "
"باید آن را دوبار تایپ کنید. به یاد داشته باشید که گذرواژهٔ root بخشی بحرانی "
"از امنیت سیستم است!"

#: ../textw/userauth_text.py:67
msgid "The root password must be at least 6 characters long."
msgstr "گذرواژهٔ root باید دارای حداقل ۶ نویسه باشد."

#: ../textw/welcome_text.py:29
#, python-format
msgid "%s"
msgstr "‏%s"

#: ../textw/welcome_text.py:30
#, python-format
msgid ""
"Welcome to %s!\n"
"\n"
msgstr ""
"به %s خوش آمدید!\n"
"\n"

#: ../textw/zipl_text.py:35
#, fuzzy
msgid ""
"The z/IPL Boot Loader will be installed on your system after installation is "
"complete. You can now enter any additional kernel and chandev parameters "
"which your machine or your setup require."
msgstr ""
"بارکنندهٔ راه‌انداز z/IPL بعد از تمام شدن نصب روی سیستم شما نصب خواهد شد. "
"اکنون می‌توانید هر پارامتر اضافی chandev و هسته را که رایانه یا برپاسازی شما "
"ممکن است به آنها نیاز داشته باشد وارد کنید."

#: ../textw/zipl_text.py:67
msgid "z/IPL Configuration"
msgstr "پیکربندی z/IPL"

#: ../textw/zipl_text.py:75 ../textw/zipl_text.py:79
msgid "Chandev line "
msgstr "خط Chandev "

#: ../installclasses/fedora.py:39
msgid "_Fedora"
msgstr ""

#: ../installclasses/fedora.py:40 ../installclasses/rhel.py:45
#, python-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage. What additional tasks would you like your system to "
"include support for?"
msgstr ""

#: ../installclasses/fedora.py:49
msgid "Office and Productivity"
msgstr ""

#: ../installclasses/fedora.py:50 ../installclasses/rhel.py:57
#: ../installclasses/rhel.py:62
msgid "Software Development"
msgstr ""

#: ../installclasses/fedora.py:51
#, fuzzy
msgid "Web Server"
msgstr "کارگزار نام"

#: ../installclasses/rhel.py:44
#, fuzzy
msgid "Red Hat Enterprise Linux"
msgstr "‏Red Hat Enterprise Linux WS"

#: ../installclasses/rhel.py:54
msgid "Office"
msgstr ""

#: ../installclasses/rhel.py:55
msgid "Multimedia"
msgstr ""

#: ../installclasses/rhel.py:61
msgid "Web server"
msgstr ""

#: ../installclasses/rhel.py:66
#, fuzzy
msgid "Virtualization"
msgstr "تبریک"

#: ../installclasses/rhel.py:67
msgid "Clustering"
msgstr ""

#: ../installclasses/rhel.py:68
msgid "Storage Clustering"
msgstr ""

#: ../installclasses/rhel.py:72
#, fuzzy
msgid "Installation Number"
msgstr "نصبی که آغاز شود"

#: ../installclasses/rhel.py:73
msgid ""
"To install the full set of supported packages included in your subscription, "
"please enter your Installation Number"
msgstr ""

#: ../installclasses/rhel.py:76
msgid ""
"If you're unable to locate the Installation Number, consult http://www."
"redhat.com/apps/support/in.html.\n"
"\n"
"If you skip:\n"
"* You may not get access to the full set of packages included in your "
"subscription.\n"
"* It may result in an unsupported/uncertified installation of Red Hat "
"Enterprise Linux.\n"
"* You will not get software and security updates for packages not included "
"in your subscription."
msgstr ""

#: ../storage/__init__.py:81
#, fuzzy
msgid "Unknown Device"
msgstr "نامعلوم"

#: ../storage/__init__.py:82
#, fuzzy, python-format
msgid ""
"The installation source given by device %s could not be found.  Please check "
"your parameters and try again."
msgstr ""
"هنگام خواندن نصب از تصاویر ایزو خطایی رخ داد. لطفاً تصاویر ایزو خود را بررسی "
"کرده و دوباره امتحان کنید."

#: ../storage/__init__.py:95
msgid "Installation cannot continue."
msgstr "نمی‌توان نصب را ادامه داد."

#: ../storage/__init__.py:96
#, fuzzy
msgid ""
"The storage configuration you have chosen has already been activated. You "
"can no longer return to the disk editing screen. Would you like to continue "
"with the installation process?"
msgstr ""
"گزینه‌های افرازبندی‌ای که انتخاب کرده‌اید از قبل فعال شده‌اند. دیگر نمی‌توانید به "
"صفحهٔ ویرایش دیسک بازگردید. آیا می‌خواهید روند نصب را ادامه دهید؟"

#: ../storage/__init__.py:127
#, fuzzy
msgid "Encrypt device?"
msgstr "کلید رمزنگاری"

#: ../storage/__init__.py:128
msgid ""
"You specified block device encryption should be enabled, but you have not "
"supplied a passphrase. If you do not go back and provide a passphrase, block "
"device encryption will be disabled."
msgstr ""

#: ../storage/__init__.py:146
#, fuzzy
msgid "Writing storage configuration to disk"
msgstr "_کوچ دادن افراز به:"

#: ../storage/__init__.py:147
msgid ""
"The partitioning options you have selected will now be written to disk.  Any "
"data on deleted or reformatted partitions will be lost."
msgstr ""

#: ../storage/__init__.py:152
#, fuzzy
msgid "Go _back"
msgstr "_عقب"

#: ../storage/__init__.py:153
msgid "_Write changes to disk"
msgstr ""

#: ../storage/__init__.py:252
#, fuzzy
msgid "Finding Devices"
msgstr "بستهٔ ناموجود"

#: ../storage/__init__.py:253
msgid "Finding storage devices..."
msgstr ""

#: ../storage/__init__.py:269
msgid "Filesystem error detected, cannot continue."
msgstr ""

#: ../storage/__init__.py:480
msgid "This partition is holding the data for the hard drive install."
msgstr "این افراز داده‌های نصب از دیسک سخت را نگه می‌دارد."

#: ../storage/__init__.py:485
msgid "You cannot delete a partition of a LDL formatted DASD."
msgstr "نمی‌توانید یک افراز DASD با قالب‌بندی LDL را حذف کنید."

#: ../storage/__init__.py:491
#, fuzzy, python-format
msgid "This device is part of the RAID device %s."
msgstr "این افراز بخشی از دستگاه RAID ‏‎/dev/md%s است."

#: ../storage/__init__.py:494
#, fuzzy
msgid "This device is part of a RAID device."
msgstr "این افراز بخشی از یک دستگاه RAID است."

#: ../storage/__init__.py:499
#, fuzzy, python-format
msgid "This device is part of the LVM volume group '%s'."
msgstr "این افراز بخشی از گروه جلدی LVM‏ «%s» است."

#: ../storage/__init__.py:502
#, fuzzy
msgid "This device is part of a LVM volume group."
msgstr "این افراز بخشی از یک گروه جلدی LVM است."

#: ../storage/__init__.py:511
msgid ""
"This device is an extended partition which contains logical partitions that "
"cannot be deleted:\n"
"\n"
msgstr ""

#: ../storage/__init__.py:751
#, python-format
msgid ""
"You have not defined a root partition (/), which is required for "
"installation of %s to continue."
msgstr "شما افراز ریشه (/) را که برای ادامهٔ نصب %s ضروری است تعیین نکرده‌اید."

#: ../storage/__init__.py:756
#, python-format
msgid ""
"Your root partition is less than 250 megabytes which is usually too small to "
"install %s."
msgstr ""
"افراز ریشهٔ شما کوچکتر از ۲۵۰ مگابایت است که معمولاً کوچکتر از آن است که بتوان "
"%s را روی آن نصب کرد."

#: ../storage/__init__.py:762
#, fuzzy, python-format
msgid ""
"Your / partition is less than %s megabytes which is lower than recommended "
"for a normal %s install."
msgstr ""
"افراز %s شما کوچکتر از %s مگابایت است که کمتر از مقدار توصیه شده برای نصب "
"معمولی %s است."

#: ../storage/__init__.py:770
#, python-format
msgid ""
"Your %s partition is less than %s megabytes which is lower than recommended "
"for a normal %s install."
msgstr ""
"افراز %s شما کوچکتر از %s مگابایت است که کمتر از مقدار توصیه شده برای نصب "
"معمولی %s است."

#: ../storage/__init__.py:797
msgid ""
"Installing on a USB device.  This may or may not produce a working system."
msgstr ""

#: ../storage/__init__.py:800
msgid ""
"Installing on a FireWire device.  This may or may not produce a working "
"system."
msgstr ""

#: ../storage/__init__.py:804
#, fuzzy
msgid "You have not created a boot partition."
msgstr "شما باید یک افراز راه‌اندازی PPC PReP ایجاد کنید."

#: ../storage/__init__.py:808
msgid "Bootable partitions can only be on RAID1 devices."
msgstr "افرازهای قابل راه‌اندازی فقط می‌توانند روی دستگاه‌های RAID1 باشند."

#: ../storage/__init__.py:813
msgid "Bootable partitions cannot be on a logical volume."
msgstr "افرازهای قابل راه‌اندازی نمی‌توانند روی یک جلد منطقی باشند."

#: ../storage/__init__.py:818
#, fuzzy
msgid "Bootable partitions cannot be on a RAID device."
msgstr "افرازهای قابل راه‌اندازی فقط می‌توانند روی دستگاه‌های RAID1 باشند."

#: ../storage/__init__.py:823 ../storage/__init__.py:828
#, fuzzy, python-format
msgid "Bootable partitions cannot be on an %s filesystem."
msgstr "افرازهای قابل راه‌اندازی نمی‌توانند روی یک جلد منطقی باشند."

#: ../storage/__init__.py:833
#, fuzzy
msgid "Bootable partitions cannot be on an encrypted block device"
msgstr "افرازهای قابل راه‌اندازی نمی‌توانند روی یک جلد منطقی باشند."

#: ../storage/__init__.py:837
msgid ""
"You have not specified a swap partition.  Although not strictly required in "
"all cases, it will significantly improve performance for most installations."
msgstr ""
"شما افراز حافظهٔ مبادله‌ای مشخص نکرده‌اید. هرچند وجود چنین افرازی در همهٔ موارد "
"اجباری نیست ولی وجود آن به نحو محسوسی کارآیی بیشتر نصب‌ها را بهبود خواهد "
"بخشید."

#: ../storage/__init__.py:979 ../storage/__init__.py:988
msgid "Dirty File Systems"
msgstr "سیستم‌های پرونده‌ای کثیف"

#: ../storage/__init__.py:980
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Please boot your Linux installation, let the file systems be "
"checked and shut down cleanly to upgrade.\n"
"%s"
msgstr ""
"سیستم‌های پرونده‌ای زیر در سیستم لینوکس شما درست پیاده نشده‌اند. لطفاً نصب "
"لینوکس خود را راه‌اندازی کنید، اجازه دهید سیستم‌های پرونده‌ای کنترل شوند و "
"رایانه درست خاموش شود، سپس سیستم را ارتقاء دهید.\n"
"‏%s"

#: ../storage/__init__.py:989
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Would you like to mount them anyway?\n"
"%s"
msgstr ""
"سیستم‌های پرونده‌ای زیر در سیستم لینوکس شما درست پیاده نشده‌اند. آیا با این "
"وجود می‌خواهید آنها را سوار کنید؟\n"
"‏%s"

#: ../storage/__init__.py:1406
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. To perform an upgrade, please shut "
"down your system rather than hibernating it."
msgstr ""

#: ../storage/__init__.py:1414
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. If you are performing a new install, "
"make sure the installer is set to format all swap devices."
msgstr ""

#: ../storage/__init__.py:1428
#, fuzzy, python-format
msgid ""
"Error enabling swap device %s: %s\n"
"\n"
"The /etc/fstab on your upgrade partition does not reference a valid swap "
"device.\n"
"\n"
"Press OK to exit the installer"
msgstr ""
"خطا هنگام به کار انداختن دستگاه مبادلهٔ %s: %s\n"
"\n"
"‏‎/etc/fstab در افراز ارتقای شما به افراز مبادلهٔ معتبری ارجاع نمی‌دهد.\n"
"\n"
"برای راه‌اندازی مجدد سیستم خود روی دکمهٔ «تأیید» کلیک کنید."

#: ../storage/__init__.py:1434
#, fuzzy, python-format
msgid ""
"Error enabling swap device %s: %s\n"
"\n"
"This most likely means this swap device has not been initialized.\n"
"\n"
"Press OK to exit the installer."
msgstr ""
"خطا هنگام به کارانداختن دستگاه مبادلهٔ %s: %s\n"
"\n"
"این احتمالاً بدین معنی است که افراز مبادله راه‌اندازی نشده است.\n"
"\n"
"برای راه‌اندازی مجدد سیستم خود روی دکمهٔ «تأیید» کلیک کنید."

#: ../storage/__init__.py:1475 ../storage/__init__.py:1485
msgid "Invalid mount point"
msgstr "نقطهٔ سوار کردن نامعتبر"

#: ../storage/__init__.py:1476
#, fuzzy, python-format
msgid ""
"An error occurred when trying to create %s.  Some element of this path is "
"not a directory. This is a fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"هنگام تلاش برای ایجاد %s خطایی رخ داد. عنصری از این مسیر، شاخه نیست. این "
"خطایی مهلک است و نمی‌توان نصب را ادامه داد.\n"
"\n"
"برای راه‌اندازی مجدد سیستم خود <ورود> را فشار دهید."

#: ../storage/__init__.py:1486
#, fuzzy, python-format
msgid ""
"An error occurred when trying to create %s: %s.  This is a fatal error and "
"the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"هنگام تلاش برای ایجاد %s خطایی رخ داد: %s.  این خطایی مهلک است و نمی‌توان نصب "
"را ادامه داد.\n"
"\n"
"برای راه‌اندازی مجدد سیستم خود <ورود> را فشار دهید."

#: ../storage/__init__.py:1499 ../storage/__init__.py:1520
#, fuzzy
msgid "Unable to mount filesystem"
msgstr "بار کردن پرونده ممکن نیست!"

#: ../storage/__init__.py:1500
#, python-format
msgid ""
"An error occurred mounting device %s as %s.  You may continue installation, "
"but there may be problems."
msgstr ""

#: ../storage/__init__.py:1521
#, fuzzy, python-format
msgid ""
"An error occurred mounting device %s as %s: %s. This is a fatal error and "
"the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"هنگام تلاش برای ایجاد %s خطایی رخ داد: %s.  این خطایی مهلک است و نمی‌توان نصب "
"را ادامه داد.\n"
"\n"
"برای راه‌اندازی مجدد سیستم خود <ورود> را فشار دهید."

#: ../storage/devices.py:1059
#, fuzzy
msgid "boot flag not available for this partition"
msgstr ""
"نمی‌توانید این افراز را حذف کنید:\n"
"\n"

#: ../storage/devicetree.py:87
#, fuzzy
msgid "Confirm"
msgstr "تکرار گذرواژه:"

#: ../storage/devicetree.py:88
#, python-format
msgid ""
"Are you sure you want to skip entering a passphrase for device %s?\n"
"\n"
"If you skip this step the device's contents will not be available during "
"installation."
msgstr ""

#: ../storage/devicetree.py:126
#, python-format
msgid ""
"Error processing drive %s.\n"
"Maybe it needs to be reinitialized.YOU WILL LOSE ALL DATA ON THIS DRIVE!"
msgstr ""

#: ../storage/devicetree.py:151
#, python-format
msgid ""
"Error processing LVM.\n"
"It seems that there is inconsistent LVM data. (%s) make(s) up %s. You can "
"reinitialize all related PVs, which will erase all LVM metadata. Or ignore, "
"which will preserve contents."
msgstr ""

#: ../storage/devicetree.py:159
#, fuzzy
msgid "_Ignore drive(s)"
msgstr "دیسک‌گردان _نادیده گرفته شود"

#: ../storage/devicetree.py:160
msgid "_Re-initialize drive(s)"
msgstr ""

#: ../storage/iscsi.py:98 ../storage/iscsi.py:99
#, fuzzy
msgid "Scanning iSCSI nodes"
msgstr "در حال بار کردن گردانندهٔ SCSI"

#: ../storage/iscsi.py:172 ../storage/iscsi.py:173
#, fuzzy
msgid "Initializing iSCSI initiator"
msgstr "راه‌اندازی"

#: ../storage/iscsi.py:208
#, fuzzy
msgid "iSCSI not available"
msgstr "راهنما موجود نیست"

#: ../storage/iscsi.py:210
#, fuzzy
msgid "No initiator name set"
msgstr "نام نامعتبر گروه جلد"

#: ../storage/iscsi.py:224
msgid "No iSCSI nodes discovered"
msgstr ""

#: ../storage/iscsi.py:227 ../storage/iscsi.py:228
msgid "Logging in to iSCSI nodes"
msgstr ""

#: ../storage/iscsi.py:250
msgid "No new iSCSI nodes discovered"
msgstr ""

#: ../storage/iscsi.py:253
msgid "Could not log in to any of the discovered nodes"
msgstr ""

#: ../storage/partitioning.py:175
msgid ""
"Could not find enough free space for automatic partitioning, please use "
"another partitioning method."
msgstr ""

#: ../storage/partitioning.py:192
msgid "Warnings During Automatic Partitioning"
msgstr "اخطارهای هنگام افرازبندی خودکار"

#: ../storage/partitioning.py:194
#, python-format
msgid ""
"Following warnings occurred during automatic partitioning:\n"
"\n"
"%s"
msgstr ""
"اخطارهای زیر در حین افرازبندی خودکار رخ داده‌اند:\n"
"\n"
"‏%s"

#: ../storage/partitioning.py:206 ../storage/partitioning.py:230
#, fuzzy
msgid ""
"\n"
"\n"
"Press 'OK' to exit the installer."
msgstr ""
"\n"
"\n"
"برای راه‌اندازی مجدد سیستم خود روی دکمهٔ «تأیید» کلیک کنید."

#: ../storage/partitioning.py:208
#, python-format
msgid ""
"Could not allocate requested partitions: \n"
"\n"
"%s.%s"
msgstr ""
"تخصیص افرازهای خواسته شده ممکن نبود: \n"
"\n"
"‏%s.%s"

#: ../storage/partitioning.py:232
msgid ""
"\n"
"\n"
"Press 'OK' to choose a different partitioning option."
msgstr ""

#: ../storage/partitioning.py:234
msgid "Automatic Partitioning Errors"
msgstr "خطاهای افرازبندی خودکار"

#: ../storage/partitioning.py:235
#, fuzzy, python-format
msgid ""
"The following errors occurred with your partitioning:\n"
"\n"
"%s\n"
"\n"
"This can happen if there is not enough space on your hard drive(s) for the "
"installation. %s"
msgstr ""
"خطاهای زیر در افرازبندی دیسک شما رخ داده‌اند:\n"
"\n"
"‏%s\n"
"\n"
"ممکن است دلیل این اتفاق این باشد که در دیسک(های) شما فضای کافی برای نصب وجود "
"ندارد.%s"

#: ../storage/partitioning.py:246
msgid "Unrecoverable Error"
msgstr "خطای غیرقابل ترمیم"

#: ../storage/partitioning.py:247
msgid "Your system will now be rebooted."
msgstr "حالا سیستم شما دوباره راه‌اندازی خواهد شد."

#: ../storage/zfcp.py:52
msgid "You have not specified a device number or the number is invalid"
msgstr "شمارهٔ دستگاهی مشخص نکرده‌اید یا شماره معتبر نیست."

#: ../storage/zfcp.py:54
msgid "You have not specified a worldwide port name or the name is invalid."
msgstr "نام درگاه جهانی‌ای مشخص نکرده‌اید یا نام معتبر نیست."

#: ../storage/zfcp.py:56
msgid "You have not specified a FCP LUN or the number is invalid."
msgstr "شمارهٔ قطعهٔ منطقی FCP را مشخص نکرده‌اید یا شماره معتبر نیست."

#: ../storage/devicelibs/lvm.py:326
#, python-format
msgid "vginfo failed for %s"
msgstr ""

#: ../storage/devicelibs/lvm.py:354
#, python-format
msgid "lvs failed for %s"
msgstr ""

#: ../storage/formats/fs.py:64
msgid "attr dict must include a type"
msgstr ""

#: ../storage/formats/fs.py:111
msgid "filesystem configuration missing a type"
msgstr ""

#: ../storage/formats/fs.py:270
msgid "Formatting"
msgstr "در حال قالب‌بندی"

#: ../storage/formats/fs.py:271
#, fuzzy, python-format
msgid "Creating filesystem on %s..."
msgstr "بررسی برای بلوک‌های خراب روی ‎/dev/%s‎..."

#: ../storage/formats/fs.py:367
#, fuzzy
msgid "Resizing"
msgstr "در حال بازیابی"

#: ../storage/formats/fs.py:368
#, fuzzy, python-format
msgid "Resizing filesystem on %s..."
msgstr "در حال قالب‌بندی سیستم پرونده‌ای ‎%s..."

#: ../storage/formats/fs.py:409
#, fuzzy
msgid "Checking"
msgstr "در حال بررسی «%s»..."

#: ../storage/formats/fs.py:410
#, fuzzy, python-format
msgid "Checking filesystem on %s..."
msgstr "بررسی برای بلوک‌های خراب روی ‎/dev/%s‎..."

#: ../loader/cdinstall.c:185 ../loader/cdinstall.c:206
#: ../loader/mediacheck.c:60
msgid "Media Check"
msgstr "بررسی رسانه"

#: ../loader/cdinstall.c:185 ../loader/cdinstall.c:188
#: ../loader/cdinstall.c:206 ../loader/cdinstall.c:214 ../loader/method.c:326
msgid "Test"
msgstr "آزمایش"

#: ../loader/cdinstall.c:185 ../loader/cdinstall.c:189
#, fuzzy
msgid "Eject Disc"
msgstr "بیرون دادن سی‌دی"

#: ../loader/cdinstall.c:186
#, fuzzy, c-format
msgid ""
"Choose \"%s\" to test the disc currently in the drive, or \"%s\" to eject "
"the disc and insert another for testing."
msgstr ""
"برای آزمایش سی‌دی داخل دیسک‌گردان روی دکمهٔ «%s»، و برای بیرون دادن سی‌دی و داخل "
"کردن سی‌دی دیگری برای آزمایش روی دکمهٔ «%s» کلیک کنید."

#: ../loader/cdinstall.c:207
#, c-format
msgid ""
"If you would like to test additional media, insert the next disc and press "
"\"%s\". Testing each disc is not strictly required, however it is highly "
"recommended.  Minimally, the discs should be tested prior to using them for "
"the first time. After they have been successfully tested, it is not required "
"to retest each disc prior to using it again."
msgstr ""

#: ../loader/cdinstall.c:229
#, fuzzy, c-format
msgid ""
"The %s disc was not found in any of your drives. Please insert the %s disc "
"and press %s to retry."
msgstr ""
"سی‌دی %s در هیچ یک از سی‌دی‌گردان‌های شما پیدا نشد. لطفاً سی‌دی %s را وارد کنید و "
"برای تلاش مجدد روی دکمهٔ «%s» کلیک کنید."

#: ../loader/cdinstall.c:248
#, fuzzy
msgid "Disc Found"
msgstr "سی‌دی پیدا شد"

#: ../loader/cdinstall.c:249
#, fuzzy, c-format
msgid ""
"To begin testing the media before installation press %s.\n"
"\n"
"Choose %s to skip the media test and start the installation."
msgstr ""
"برای شروع آزمایش رسانهٔ سی‌دی قبل از نصب روی دکمهٔ %s کلیک کنید.\n"
"\n"
"برای پرش از آزمایش رسانه و شروع نصب روی دکمهٔ %s کلیک کنید."

#: ../loader/cdinstall.c:339
#, fuzzy
msgid "Scanning"
msgstr "اخطار"

#: ../loader/cdinstall.c:339 ../loader/cdinstall.c:341
#, c-format
msgid "Looking for installation images on CD device %s"
msgstr ""

#: ../loader/cdinstall.c:442
#, fuzzy, c-format
msgid ""
"The %s disc was not found in any of your CDROM drives. Please insert the %s "
"disc and press %s to retry."
msgstr ""
"سی‌دی %s در هیچ یک از سی‌دی‌گردان‌های شما پیدا نشد. لطفاً سی‌دی %s را وارد کنید و "
"برای تلاش مجدد روی دکمهٔ «%s» کلیک کنید."

#: ../loader/cdinstall.c:451
#, fuzzy
msgid "Disc Not Found"
msgstr "سی‌دی پیدا نشد"

#: ../loader/cdinstall.c:518
msgid "Cannot find kickstart file on CDROM."
msgstr "نمی‌توان پروندهٔ راه‌اندازی را روی سی‌دی یافت."

#: ../loader/copy.c:51 ../loader/method.c:280
#, fuzzy, c-format
msgid "Failed to read directory %s: %m"
msgstr "خواندن شاخهٔ %s شکست خورد: %s"

#: ../loader/driverdisk.c:139
msgid "Loading"
msgstr "در حال بار کردن"

#: ../loader/driverdisk.c:139
msgid "Reading driver disk..."
msgstr "در حال خواندن دیسک گرداننده..."

#: ../loader/driverdisk.c:238 ../loader/driverdisk.c:270
msgid "Driver Disk Source"
msgstr "مبدأ دیسک گرداننده"

#: ../loader/driverdisk.c:239
msgid ""
"You have multiple devices which could serve as sources for a driver disk.  "
"Which would you like to use?"
msgstr ""
"شما دارای چندین دستگاه هستید که می‌توانند به عنوان مبدأ دیسک گرداننده عمل "
"کنند. از کدام یک می‌خواهید استفاده کنید؟"

#: ../loader/driverdisk.c:271
msgid ""
"There are multiple partitions on this device which could contain the driver "
"disk image.  Which would you like to use?"
msgstr ""
"چند افراز روی این دستگاه است که می‌تواند حاوی تصویر دیسک گرداننده باشند. از "
"کدام یک می‌خواهید استفاده کنید؟"

#: ../loader/driverdisk.c:306
msgid "Failed to mount partition."
msgstr "سوار کردن افراز شکست خورد."

#: ../loader/driverdisk.c:311
msgid "Select driver disk image"
msgstr "انتخاب تصویر دیسک گرداننده"

#: ../loader/driverdisk.c:312
msgid "Select the file which is your driver disk image."
msgstr "پرونده‌ای را که تصویر دیسک گردانندهٔ شماست انتخاب کنید."

#: ../loader/driverdisk.c:341
msgid "Failed to load driver disk from file."
msgstr "بار کردن تصویر دیسک گرداننده از پرونده شکست خورد."

#: ../loader/driverdisk.c:353
#, c-format
msgid "Insert your driver disk into /dev/%s and press \"OK\" to continue."
msgstr ""
"دیسک گردانندهٔ خود را در ‎/dev/%s وارد کنید و  برای ادامه روی دکمهٔ «تأیید» کلیک "
"کنید."

#: ../loader/driverdisk.c:359
msgid "Insert Driver Disk"
msgstr "دیسک گرداننده را وارد کنید"

#: ../loader/driverdisk.c:372
msgid "Failed to mount driver disk."
msgstr "سوار کردن دیسک گرداننده شکست خورد."

#: ../loader/driverdisk.c:380
#, c-format
msgid "Driver disk is invalid for this release of %s."
msgstr ""

#: ../loader/driverdisk.c:443
msgid "Manually choose"
msgstr "انتخاب دستی"

#: ../loader/driverdisk.c:444
msgid "Load another disk"
msgstr "بار کردن یک دیسک دیگر"

#: ../loader/driverdisk.c:445
msgid ""
"No devices of the appropriate type were found on this driver disk.  Would "
"you like to manually select the driver, continue anyway, or load another "
"driver disk?"
msgstr ""
"هیچ دستگاهی از نوع مناسب روی این دیسک گرداننده پیدا شد. آیا می‌خواهید به طور "
"دستی گرداننده را انتخاب کنید، با وجود پیدا نشدن گرداننده ادامه دهید، یا دیسک "
"گردانندهٔ دیگری را بار کنید؟"

#: ../loader/driverdisk.c:483
msgid "Driver disk"
msgstr "دیسک گرداننده"

#: ../loader/driverdisk.c:484
msgid "Do you have a driver disk?"
msgstr "آیا دیسک گرداننده دارید؟"

#: ../loader/driverdisk.c:493
msgid "More Driver Disks?"
msgstr "دیسک گردانندهٔ دیگری هست؟"

#: ../loader/driverdisk.c:494
msgid "Do you wish to load any more driver disks?"
msgstr "آیا می‌خواهید دیسک‌های گردانندهٔ دیگری را بار کنید؟"

#: ../loader/driverdisk.c:539 ../loader/driverdisk.c:576
#: ../loader/hdinstall.c:384 ../loader/kickstart.c:132
#: ../loader/kickstart.c:142 ../loader/kickstart.c:185
#: ../loader/kickstart.c:553 ../loader/modules.c:335 ../loader/modules.c:347
#: ../loader/net.c:1541 ../loader/net.c:1564 ../loader/nfsinstall.c:335
#: ../loader/urlinstall.c:418 ../loader/urlinstall.c:427
#: ../loader/urlinstall.c:436
msgid "Kickstart Error"
msgstr "خطای راه‌اندازی"

#: ../loader/driverdisk.c:540
#, c-format
msgid "Unknown driver disk kickstart source: %s"
msgstr "مبدأ نامعلوم راه‌اندازی دیسک گرداننده: %s"

#: ../loader/driverdisk.c:577
#, c-format
msgid ""
"The following invalid argument was specified for the kickstart driver disk "
"command: %s:%s"
msgstr ""
"آرگومان‌های نامعتبر زیر برای فرمان راه‌اندازی دیسک گرداننده مشخص شده بودند: %s:"
"%s"

#: ../loader/driverselect.c:67
#, c-format
msgid ""
"Please enter any parameters which you wish to pass to the %s module "
"separated by spaces.  If you don't know what parameters to supply, skip this "
"screen by pressing the \"OK\" button."
msgstr ""

#: ../loader/driverselect.c:91
msgid "Enter Module Parameters"
msgstr "پارامترهای پیمانه را وارد کنید"

#: ../loader/driverselect.c:178
msgid "No drivers found"
msgstr "گرداننده‌ای پیدا نشد"

#: ../loader/driverselect.c:178
msgid "Load driver disk"
msgstr "بار کردن دیسک گرداننده"

#: ../loader/driverselect.c:179
msgid ""
"No drivers were found to manually insert.  Would you like to use a driver "
"disk?"
msgstr ""
"هیچ گرداننده‌ای پیدا نشد که دستی وارد شود. آیا می‌خواهید از دیسک گرداننده "
"استفاده کنید؟"

#: ../loader/driverselect.c:197
msgid ""
"Please select the driver below which you wish to load.  If it does not "
"appear and you have a driver disk, press F2."
msgstr ""
"لطفاً گرداننده‌ای را که می‌خواهید بار کنید از فهرست زیر انتخاب کنید. اگر چیزی "
"ظاهر نشد و شما دیسک گرداننده‌ای دارید، F2 را فشار دهید."

#: ../loader/driverselect.c:206
msgid "Specify optional module arguments"
msgstr "آرگومان‌های اختیاری پیمانه را مشخص کنید"

#: ../loader/driverselect.c:234
msgid "Select Device Driver to Load"
msgstr "گردانندهٔ دستگاه را انتخاب کنید تا بار شود"

#: ../loader/hdinstall.c:144
#, fuzzy
msgid ""
"An error occured finding the installation image on your hard drive.  Please "
"check your images and try again."
msgstr ""
"هنگام خواندن نصب از تصاویر ایزو خطایی رخ داد. لطفاً تصاویر ایزو خود را بررسی "
"کرده و دوباره امتحان کنید."

#: ../loader/hdinstall.c:232
msgid ""
"You don't seem to have any hard drives on your system! Would you like to "
"configure additional devices?"
msgstr ""
"به‌نظر نمی‌رسد که هیچ دیسک سختی روی سیستم‌تان داشته باشید! آیا می‌خواهید "
"دستگاه‌های اضافی را پیکربندی کنید؟"

#: ../loader/hdinstall.c:246
#, fuzzy, c-format
msgid ""
"What partition and directory on that partition holds the installation image "
"for %s?  If you don't see the disk drive you're using listed here, press F2 "
"to configure additional devices."
msgstr ""
"کدام افراز و شاخهٔ روی آن افزار حاوی تصاویر (iso9660) سی‌دی برای %s است؟ اگر "
"دیسک‌گردانی که از آن استفاده می‌کنید اینجا فهرست نشده است، F2 را برای پیکربندی "
"دستگاه‌های بیشتر فشار دهید."

#: ../loader/hdinstall.c:273
#, fuzzy
msgid "Directory holding image:"
msgstr "شاخهٔ حاوی تصاویر:"

#: ../loader/hdinstall.c:301
msgid "Select Partition"
msgstr "انتخاب افراز"

#: ../loader/hdinstall.c:353
#, fuzzy, c-format
msgid "Device %s does not appear to contain an installation image."
msgstr "به‌نظر نمی‌رسد دستگاه %s حاوی تصاویر سی‌دی %s باشد."

#: ../loader/hdinstall.c:385
#, c-format
msgid "Bad argument to HD kickstart method command %s: %s"
msgstr "آرگومان بد برای فرمان روش راه‌اندازی دیسک سخت %s : %s"

#: ../loader/hdinstall.c:455 ../loader/hdinstall.c:511
msgid "Cannot find kickstart file on hard drive."
msgstr "نمی‌توان پروندهٔ راه‌اندازی را روی دیسک سخت پیدا کرد."

#: ../loader/hdinstall.c:498
#, c-format
msgid "Cannot find hard drive for BIOS disk %s"
msgstr "نمی‌توان دیسک سخت را برای دیسک BIOS ‏%s پیدا کرد"

#: ../loader/kbd.c:136
msgid "Keyboard Type"
msgstr "نوع صفحه‌کلید"

#: ../loader/kbd.c:137
msgid "What type of keyboard do you have?"
msgstr "چه نوع صفحه‌کلیدی دارید؟"

#: ../loader/kickstart.c:133
#, fuzzy, c-format
msgid "Error opening kickstart file %s: %m"
msgstr "خطا در باز کردن پروندهٔ راه‌اندازی %s:‏ %s"

#: ../loader/kickstart.c:143
#, fuzzy, c-format
msgid "Error reading contents of kickstart file %s: %m"
msgstr "خطا در خواندن محتویات پروندهٔ راه‌اندازی %s: ‏%s"

#: ../loader/kickstart.c:186
#, c-format
msgid "Error in %s on line %d of kickstart file %s."
msgstr "خطا در %s در سطر %Id پروندهٔ راه‌اندازی %s."

#: ../loader/kickstart.c:285
#, fuzzy
msgid "Cannot find ks.cfg on removable media."
msgstr "نمی‌توان ks.cfg را در دیسک نرم راه‌اندازی پیدا کرد."

#: ../loader/kickstart.c:380
msgid ""
"Unable to download the kickstart file.  Please modify the kickstart "
"parameter below or press Cancel to proceed as an interactive installation."
msgstr ""

#: ../loader/kickstart.c:389
#, fuzzy
msgid "Error downloading kickstart file"
msgstr "خطا در باز کردن پروندهٔ راه‌اندازی %s:‏ %s"

#: ../loader/kickstart.c:554
#, c-format
msgid "Bad argument to shutdown kickstart method command %s: %s"
msgstr "آرگومان بد برای فرمان روش راه‌اندازی دیسک سخت %s : %s"

#: ../loader/lang.c:64
#, fuzzy, c-format
msgid "Welcome to %s for %s - Rescue Mode"
msgstr "به %s خوش آمدید ‐ حالت نجات"

#: ../loader/lang.c:65 ../loader/loader.c:226
msgid ""
"  <Tab>/<Alt-Tab> between elements  | <Space> selects | <F12> next screen "
msgstr "  <Tab>/<Alt-Tab> بین اجزا  | <Space> انتخاب | <F12> صفحهٔ بعد "

#: ../loader/lang.c:375
msgid "Choose a Language"
msgstr "یک زبان انتخاب کنید"

#: ../loader/loader.c:127
#, fuzzy
msgid "Local CD/DVD"
msgstr "سی‌دی محلی"

#: ../loader/loader.c:128
msgid "Hard drive"
msgstr "دیسک سخت"

#: ../loader/loader.c:129
#, fuzzy
msgid "NFS directory"
msgstr "شاخهٔ %s:"

#: ../loader/loader.c:433 ../loader/loader.c:477
msgid "Update Disk Source"
msgstr "به‌هنگام‌سازی مبدأ دیسک"

#: ../loader/loader.c:434
msgid ""
"You have multiple devices which could serve as sources for an update disk.  "
"Which would you like to use?"
msgstr ""
"شما چند دستگاه دارید که می‌توانند به عنوان مبدأ دیسک به‌هنگام‌سازی مورد استفاده "
"قرار بگیرند. از کدام یک می‌خواهید استفاده کنید؟"

#: ../loader/loader.c:478
#, fuzzy
msgid ""
"There are multiple partitions on this device which could contain the update "
"disk image.  Which would you like to use?"
msgstr ""
"چند افراز روی این دستگاه است که می‌تواند حاوی تصویر دیسک گرداننده باشند. از "
"کدام یک می‌خواهید استفاده کنید؟"

#: ../loader/loader.c:496
#, fuzzy, c-format
msgid "Insert your updates disk into %s and press \"OK\" to continue."
msgstr ""
"دیسک به‌هنگام‌سازی خود را در ‎/dev/%s وارد کنید و برای ادامه روی دکمهٔ «تأیید» "
"کلیک کنید."

#: ../loader/loader.c:502
msgid "Updates Disk"
msgstr "دیسک به‌هنگام‌سازی"

#: ../loader/loader.c:520
msgid "Failed to mount updates disk"
msgstr "سوار کردن دیسک به‌هنگام‌سازی شکست خورد"

#: ../loader/loader.c:525
msgid "Updates"
msgstr "به‌هنگام‌سازی"

#: ../loader/loader.c:525
msgid "Reading anaconda updates..."
msgstr "در حال خواندن به‌هنگام‌سازی‌های آناکوندا..."

#: ../loader/loader.c:561
msgid ""
"Unable to download the updates image.  Please modify the updates location "
"below or press Cancel to proceed without updates.."
msgstr ""

#: ../loader/loader.c:570
#, fuzzy
msgid "Error downloading updates image"
msgstr "خطا در باز کردن پروندهٔ راه‌اندازی %s:‏ %s"

#: ../loader/loader.c:1196
#, c-format
msgid "You do not have enough RAM to install %s on this machine."
msgstr "شما برای نصب %s روی این رایانه به اندازهٔ کافی حافظهٔ RAM ندارید."

#: ../loader/loader.c:1253
msgid "Media Detected"
msgstr "رسانه تشخیص داده شد"

#: ../loader/loader.c:1254
msgid "Local installation media detected..."
msgstr "رسانهٔ نصب محلی کشف شد..."

#: ../loader/loader.c:1370
msgid "Rescue Method"
msgstr "روش نجات"

#: ../loader/loader.c:1371
msgid "Installation Method"
msgstr "روش نصب"

#: ../loader/loader.c:1373
msgid "What type of media contains the rescue image?"
msgstr "چه نوع رسانه‌ای حاوی تصویر نجات است؟"

#: ../loader/loader.c:1375
#, fuzzy
msgid "What type of media contains the installation image?"
msgstr "چه نوع رسانه‌ای حاوی تصویر نجات است؟"

#: ../loader/loader.c:1408
msgid "No driver found"
msgstr "گرداننده‌ای پیدا نشد"

#: ../loader/loader.c:1408
msgid "Select driver"
msgstr "انتخاب گرداننده"

#: ../loader/loader.c:1409
msgid "Use a driver disk"
msgstr "استفاده از دیسکِ گرداننده"

#: ../loader/loader.c:1410
msgid ""
"Unable to find any devices of the type needed for this installation type.  "
"Would you like to manually select your driver or use a driver disk?"
msgstr ""
"نمی‌توان هیچ دستگاهی از نوعی که برای این نوع نصب لازم است پیدا کرد. آیا "
"می‌خواهید گردانندهٔ خود را دستی انتخاب کنید یا از یک دیسکِ گرداننده استفاده "
"کنید؟"

#: ../loader/loader.c:1630
msgid "The following devices have been found on your system."
msgstr "دستگاه‌های زیر در سیستم شما پیدا شده‌اند."

#: ../loader/loader.c:1632
msgid ""
"No device drivers have been loaded for your system.  Would you like to load "
"any now?"
msgstr ""
"هیچ گردانندهٔ دستگاهی برای سیستم‌تان بار نشده است. آیا می‌خواهید حالا یک "
"گرداننده بار کنید؟"

#: ../loader/loader.c:1636
msgid "Devices"
msgstr "دستگاه‌ها"

#: ../loader/loader.c:1637
msgid "Done"
msgstr "انجام شد"

#: ../loader/loader.c:1638
msgid "Add Device"
msgstr "اضافه کردن دستگاه"

#: ../loader/loader.c:1850
#, c-format
msgid "loader has already been run.  Starting shell.\n"
msgstr "بارکننده قبلاً اجرا شده است. پوسته آغاز می‌شود.\n"

#: ../loader/loader.c:2224
#, fuzzy, c-format
msgid "Running anaconda %s, the %s rescue mode - please wait...\n"
msgstr "در حال اجرای آناکوندا، حالت نجات %s ‐ لطفاً صبر کنید...\n"

#: ../loader/loader.c:2226
#, fuzzy, c-format
msgid "Running anaconda %s, the %s system installer - please wait...\n"
msgstr "در حال اجرای آناکوندا، برنامهٔ نصب سیستم %s ‐ لطفاً صبر کنید...\n"

#: ../loader/mediacheck.c:46
#, c-format
msgid "Unable to find install image %s"
msgstr "تصویر نصب %s پیدا نشد"

#: ../loader/mediacheck.c:52
#, c-format
msgid "Checking \"%s\"..."
msgstr "در حال بررسی «%s»..."

#: ../loader/mediacheck.c:54
#, c-format
msgid "Checking media now..."
msgstr "حالا در حال بررسی رسانه..."

#: ../loader/mediacheck.c:86
msgid ""
"Unable to read the disc checksum from the primary volume descriptor.  This "
"probably means the disc was created without adding the checksum."
msgstr ""
"خواندن مجموعِ مقابله‌ای دیسک از توصیفگرِ جلدِ اصلی ممکن نیست. این احتمالاً به این "
"معنیاست که دیسک بدون اضافه کردن مجموع مقابله‌ای ایجاد شده است."

#: ../loader/mediacheck.c:93
msgid ""
"The image which was just tested has errors. This could be due to a corrupt "
"download or a bad disc.  If applicable, please clean the disc and try "
"again.  If this test continues to fail you should not continue the install."
msgstr ""

#: ../loader/mediacheck.c:101
msgid "Success"
msgstr ""

#: ../loader/mediacheck.c:102
msgid ""
"The image which was just tested was successfully verified.  It should be OK "
"to install from this media.  Note that not all media/drive errors can be "
"detected by the media check."
msgstr ""

#: ../loader/method.c:323
#, c-format
msgid ""
"Would you like to perform a checksum test of the ISO image:\n"
"\n"
"   %s?"
msgstr ""
"آیا می‌خواهید تصویر ایزو را از نظر مجموع مقابله‌ای آزمایش کنید:\n"
"\n"
"‏   %s؟"

#: ../loader/method.c:326
msgid "Checksum Test"
msgstr "آزمایش مجموع مقابله‌ای"

#: ../loader/modules.c:336
#, c-format
msgid "Bad argument to device kickstart method command %s: %s"
msgstr "آرگومان بد برای فرمان روش راه‌اندازی دستگاه %s : %s"

#: ../loader/modules.c:348
#, fuzzy
msgid "A module name must be specified for the kickstart device command."
msgstr ""
"آرگومان‌های نامعتبر زیر برای فرمان راه‌اندازی دیسک گرداننده مشخص شده بودند: %s:"
"%s"

#: ../loader/net.c:111
#, fuzzy
msgid "Invalid Prefix"
msgstr "رشتهٔ IP‏ نامعتبر"

#: ../loader/net.c:112
msgid ""
"Prefix must be between 1 and 32 for IPv4 networks or between 1 and 128 for "
"IPv6 networks"
msgstr ""

#: ../loader/net.c:454 ../loader/net.c:510
msgid "Network Error"
msgstr ""

#: ../loader/net.c:455 ../loader/net.c:511
#, fuzzy
msgid "There was an error configuring your network interface."
msgstr "هنگام پاک کردن دیسک‌گردان‌های هدف خطایی پیش آمد. همانندسازی شکست خورد."

#: ../loader/net.c:556
msgid "Enable IPv6 support"
msgstr ""

#: ../loader/net.c:596
msgid "Configure TCP/IP"
msgstr "پیکربندی TCP/IP"

#: ../loader/net.c:655
#, fuzzy
msgid "Missing Protocol"
msgstr "گروه ناموجود"

#: ../loader/net.c:656
msgid "You must select at least one protocol (IPv4 or IPv6)."
msgstr ""

#: ../loader/net.c:663
msgid "IPv4 Needed for NFS"
msgstr ""

#: ../loader/net.c:664
msgid "NFS installation method requires IPv4 support."
msgstr ""

#: ../loader/net.c:763
#, fuzzy
msgid "IPv4 address:"
msgstr "نشانی IP:"

#: ../loader/net.c:775 ../loader/net.c:842 tmp/netconfig.glade.h:1
msgid "/"
msgstr ""

#: ../loader/net.c:830
#, fuzzy
msgid "IPv6 address:"
msgstr "نشانی IP:"

#: ../loader/net.c:904
#, fuzzy
msgid "Name Server:"
msgstr "کارگزار نام"

#: ../loader/net.c:943
msgid ""
"Enter the IPv4 and/or the IPv6 address and prefix (address / prefix).  For "
"IPv4, the dotted-quad netmask or the CIDR-style prefix are acceptable. The "
"gateway and name server fields must be valid IPv4 or IPv6 addresses."
msgstr ""

#: ../loader/net.c:963
#, fuzzy
msgid "Manual TCP/IP Configuration"
msgstr "پیکربندی z/IPL"

#: ../loader/net.c:1086 ../loader/net.c:1093
msgid "Missing Information"
msgstr "اطلاعات کم است"

#: ../loader/net.c:1087
#, fuzzy
msgid ""
"You must enter both a valid IPv4 address and a network mask or CIDR prefix."
msgstr "باید هم نشانی IP معتبر و هم نقاب شبکه را وارد کنید."

#: ../loader/net.c:1094
#, fuzzy
msgid "You must enter both a valid IPv6 address and a CIDR prefix."
msgstr "باید هم نشانی IP معتبر و هم نقاب شبکه را وارد کنید."

#: ../loader/net.c:1542
#, c-format
msgid "Bad argument to kickstart network command %s: %s"
msgstr "آرگومان بد برای فرمان شبکه‌ای راه‌اندازی %s: ‏%s"

#: ../loader/net.c:1565
#, c-format
msgid "Bad bootproto %s specified in network command"
msgstr ""

#: ../loader/net.c:1637
#, fuzzy
msgid "Seconds:"
msgstr "کارگزار نام دوم:"

#: ../loader/net.c:1803
msgid "Networking Device"
msgstr "دستگاه شبکه‌ای"

#: ../loader/net.c:1804
msgid ""
"You have multiple network devices on this system. Which would you like to "
"install through?"
msgstr ""
"شما چند دستگاه شبکهٔ مختلف روی این سیستم دارید. از طریق کدام یک می‌خواهید نصب "
"کنید؟"

#: ../loader/net.c:1808
msgid "Identify"
msgstr ""

#: ../loader/net.c:1817
msgid "You can identify the physical port for"
msgstr ""

#: ../loader/net.c:1819
msgid ""
"by flashing the LED lights for a number of seconds.  Enter a number between "
"1 and 30 to set the duration to flash the LED port lights."
msgstr ""

#: ../loader/net.c:1829
msgid "Identify NIC"
msgstr ""

#: ../loader/net.c:1842
#, fuzzy
msgid "Invalid Duration"
msgstr "اطلاعات IP‏ نامعتبر است"

#: ../loader/net.c:1843
msgid "You must enter the number of seconds as an integer between 1 and 30."
msgstr ""

#: ../loader/net.c:1855
#, c-format
msgid "Flashing %s port lights for %d seconds..."
msgstr ""

#: ../loader/net.c:2015 ../loader/net.c:2019
#, fuzzy, c-format
msgid "Waiting for NetworkManager to configure %s...\n"
msgstr "در انتظار برای اتصال تِلنِت..."

#: ../loader/nfsinstall.c:68
msgid "NFS server name:"
msgstr "نام کارگزار NFS:"

#: ../loader/nfsinstall.c:72
#, c-format
msgid "%s directory:"
msgstr "شاخهٔ %s:"

#: ../loader/nfsinstall.c:83
#, c-format
msgid "Please enter the server name and path to your %s installation image."
msgstr ""

#: ../loader/nfsinstall.c:90
msgid "NFS Setup"
msgstr "برپاسازی NFS"

#: ../loader/nfsinstall.c:249
msgid "That directory could not be mounted from the server."
msgstr "سوار کردن این شاخه از کارگزار ممکن نشد."

#: ../loader/nfsinstall.c:260
#, fuzzy, c-format
msgid "That directory does not seem to contain a %s installation image."
msgstr "به نظر نمی‌رسد که این شاخه درخت نصب %s داشته باشد."

#: ../loader/nfsinstall.c:336
#, c-format
msgid "Bad argument to NFS kickstart method command %s: %s"
msgstr "آرگومان بد برای فرمان روش راه‌اندازی NFS ‏%s : %s"

#: ../loader/telnetd.c:89 ../loader/telnetd.c:128
msgid "Telnet"
msgstr "تِلنِت"

#: ../loader/telnetd.c:89
msgid "Waiting for telnet connection..."
msgstr "در انتظار برای اتصال تِلنِت..."

#: ../loader/telnetd.c:128
msgid "Running anaconda via telnet..."
msgstr "در حال اجرای آناکوندا از طریق تِلنِت..."

#: ../loader/urlinstall.c:84
#, fuzzy, c-format
msgid "Unable to retrieve %s://%s%s."
msgstr "بازیابی ‎%s://%s/%s/%s‏ ممکن نیست."

#: ../loader/urlinstall.c:176
msgid "Unable to retrieve the install image."
msgstr "بازیابی تصویر نصب ممکن نیست."

#: ../loader/urlinstall.c:419
#, c-format
msgid "Bad argument to Url kickstart method command %s: %s"
msgstr "آرگومان بد برای فرمان روش راه‌اندازی نشانی اینترنتی %s: %s"

#: ../loader/urlinstall.c:428
msgid "Must supply a --url argument to Url kickstart method."
msgstr "باید یک آرگومان ‎--url به روش راه‌اندازی نشانی اینترنتی بدهید."

#: ../loader/urlinstall.c:437
#, c-format
msgid "Unknown Url method %s"
msgstr "روش نشانی اینترنتی نامعلوم %s"

#: ../loader/urls.c:235 ../loader/urls.c:237 ../loader/urls.c:240
msgid "Retrieving"
msgstr "در حال بازیابی"

#: ../loader/urls.c:295
#, c-format
msgid ""
"Please enter the URL containing the %s installation image on your server."
msgstr ""

#: ../loader/urls.c:321
#, fuzzy
msgid "URL Setup"
msgstr "برپاسازی NFS"

#: ../loader/urls.c:329
#, fuzzy
msgid "You must enter a URL."
msgstr "باید شاخه‌ای وارد کنید."

#: ../loader/urls.c:335
msgid "URL must be either an ftp or http URL"
msgstr ""

#: ../loader/urls.c:346
msgid "Unknown Host"
msgstr "میزبان نامعلوم"

#: ../loader/urls.c:347
#, c-format
msgid "%s is not a valid hostname."
msgstr "%s نام میزبان معتبری نیست."

#: ../loader/windows.c:65
msgid "Loading SCSI driver"
msgstr "در حال بار کردن گردانندهٔ SCSI"

#: ../loader/windows.c:66
#, c-format
msgid "Loading %s driver..."
msgstr "در حال بار کردن گردانندهٔ %s..."

#: tmp/GroupSelector.glade.h:1
msgid ""
"Some packages associated with this group are not required to be installed "
"but may provide additional functionality.  Please choose the packages which "
"you would like to have installed."
msgstr ""

#: tmp/GroupSelector.glade.h:2
#, fuzzy
msgid "_Deselect"
msgstr "_حذف"

#: tmp/GroupSelector.glade.h:3
#, fuzzy
msgid "_Deselect all optional packages"
msgstr "در حال نصب بسته‌ها"

#: tmp/GroupSelector.glade.h:4
msgid "_Optional packages"
msgstr ""

#: tmp/GroupSelector.glade.h:5
#, fuzzy
msgid "_Select"
msgstr "_حذف"

#: tmp/GroupSelector.glade.h:6
msgid "_Select all optional packages"
msgstr ""

#: tmp/GroupSelector.glade.h:7
msgid "dialog1"
msgstr ""

#: tmp/account.glade.h:1
msgid "Confirm:"
msgstr "تکرار گذرواژه:"

#: tmp/account.glade.h:2
#, fuzzy
msgid "Root Password:"
msgstr "گذرواژهٔ root"

#: tmp/account.glade.h:3
msgid ""
"The root account is used for administering the system.  Enter a password for "
"the root user."
msgstr ""
"حساب root برای مدیریت سیستم استفاده می‌شود. برای کاربر root گذرواژه‌ای وارد "
"کنید."

#: tmp/adddrive.glade.h:1
#, fuzzy
msgid "Add _ZFCP LUN"
msgstr "‏FCP LUN"

#: tmp/adddrive.glade.h:2
msgid "Add _iSCSI target"
msgstr ""

#: tmp/adddrive.glade.h:4
msgid "Disable _dmraid device"
msgstr ""

#: tmp/adddrive.glade.h:6
#, fuzzy
msgid "_Add drive"
msgstr "دیسک سخت"

#: tmp/addrepo.glade.h:1
msgid "<b>Repository _name:</b>"
msgstr ""

#: tmp/addrepo.glade.h:2
#, fuzzy
msgid "<b>Repository _type:</b>"
msgstr "کارگزار نام"

#: tmp/addrepo.glade.h:4
#, fuzzy
msgid "Configure _proxy"
msgstr "پیکربندی TCP/IP"

#: tmp/addrepo.glade.h:5
msgid ""
"HTTP/FTP\n"
"CD/DVD\n"
"NFS\n"
"Hard Drive"
msgstr ""

#: tmp/addrepo.glade.h:9
msgid ""
"Please provide the configuration information for this software repository."
msgstr ""

#: tmp/addrepo.glade.h:10
#, fuzzy
msgid "Proxy U_RL (host:port)"
msgstr "برچسب راه‌اندازی نامعتبر"

#: tmp/addrepo.glade.h:11
#, fuzzy
msgid "Proxy pass_word"
msgstr "بدون گذرواژه"

#: tmp/addrepo.glade.h:12
#, fuzzy
msgid "Proxy u_sername"
msgstr "نام پایگاه FTP:"

#: tmp/addrepo.glade.h:13
#, fuzzy
msgid "Repository _URL"
msgstr "برچسب راه‌اندازی نامعتبر"

#: tmp/addrepo.glade.h:14
#, fuzzy
msgid "Select A Directory"
msgstr "انتخاب گرداننده"

#: tmp/addrepo.glade.h:15
msgid "URL is a _mirror list"
msgstr ""

#: tmp/addrepo.glade.h:16
#, fuzzy
msgid "_Directory"
msgstr "شاخهٔ %s:"

#: tmp/addrepo.glade.h:17
#, fuzzy
msgid "_Options"
msgstr "گزینه‌های RAID"

#: tmp/addrepo.glade.h:18
#, fuzzy
msgid "_Partition"
msgstr "افراز"

#: tmp/addrepo.glade.h:19
msgid "_Path"
msgstr ""

#: tmp/addrepo.glade.h:20
#, fuzzy
msgid "_Server"
msgstr "کارگزار نام"

#: tmp/anaconda.glade.h:1
msgid "Reboo_t"
msgstr "_راه‌اندازی مجدد"

#: tmp/anaconda.glade.h:3
msgid "_Next"
msgstr "_بعد"

#: tmp/autopart.glade.h:1
#, fuzzy
msgid "<b>Resize _target (in MB):</b>"
msgstr "کارگزار نام"

#: tmp/autopart.glade.h:3
msgid "Re_view and modify partitioning layout"
msgstr ""

#: tmp/autopart.glade.h:4
msgid "Volume to Resize"
msgstr ""

#: tmp/autopart.glade.h:5
#, fuzzy
msgid "What drive would you like to _boot this installation from?"
msgstr "در طی روند نصب می‌خواهید از چه زبانی استفاده کنید؟"

#: tmp/autopart.glade.h:6
#, fuzzy
msgid ""
"Which partition would you like to resize to make room for your installation?"
msgstr "افراز ریشهٔ نصب شما در کدام افراز قرار دارد؟"

#: tmp/autopart.glade.h:7
#, fuzzy
msgid "_Advanced storage configuration"
msgstr "پیکربندی پیشرفتهٔ بارکنندهٔ راه‌انداز"

#: tmp/autopart.glade.h:8
#, fuzzy
msgid "_Encrypt system"
msgstr "کلید رمزنگاری"

#: tmp/autopart.glade.h:10
msgid "_Select the drive(s) to use for this installation."
msgstr ""

#: tmp/blwhere.glade.h:1
#, fuzzy
msgid "/boot"
msgstr "راه‌اندازی مجدد"

#: tmp/blwhere.glade.h:2
#, fuzzy
msgid "BIOS Drive Order"
msgstr "ویرایش ترتیب دیسک‌گردان‌ها"

#: tmp/blwhere.glade.h:3
#, fuzzy
msgid "Boot loader device"
msgstr "بارکنندهٔ راه‌انداز"

#: tmp/blwhere.glade.h:4
msgid "First BIOS drive:"
msgstr ""

#: tmp/blwhere.glade.h:5
msgid "Fourth BIOS drive:"
msgstr ""

#: tmp/blwhere.glade.h:6
msgid "MBR"
msgstr ""

#: tmp/blwhere.glade.h:7
msgid "Second BIOS drive:"
msgstr ""

#: tmp/blwhere.glade.h:8
msgid "Third BIOS drive:"
msgstr ""

#: tmp/blwhere.glade.h:9
#, fuzzy
msgid "Where would you like to install the boot loader for your system?"
msgstr "کجا می‌خواهید بارکنندهٔ راه‌انداز را نصب کنید؟"

#: tmp/detailed-dialog.glade.h:1
#, fuzzy
msgid "Info"
msgstr "نادیده گرفته شود"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr ""

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr ""

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr ""

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage device\n"
"Local disk\n"
"Remote server (scp)"
msgstr ""

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr ""

#: tmp/exnSave.glade.h:8
#, fuzzy
msgid "Select A File"
msgstr "انتخاب گرداننده"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr ""

#: tmp/exnSave.glade.h:10
#, fuzzy
msgid "_Password"
msgstr "_گذرواژه:"

#: tmp/exnSave.glade.h:11
#, fuzzy
msgid "_User name"
msgstr "نام کاربر"

#: tmp/instkey.glade.h:2
#, no-c-format
msgid "%(instkey)s:"
msgstr ""

#: tmp/instkey.glade.h:4
#, fuzzy, no-c-format
msgid "Please enter your %(instkey)s."
msgstr "لطفاً نام گروه جلد را وارد کنید."

#: tmp/iscsi-config.glade.h:1
#, fuzzy
msgid "<b>CHAP _Password:</b>"
msgstr "_گذرواژه:"

#: tmp/iscsi-config.glade.h:2
#, fuzzy
msgid "<b>CHAP _Username:</b>"
msgstr "نام کاربر"

#: tmp/iscsi-config.glade.h:3
#, fuzzy
msgid "<b>Reverse CHAP P_assword:</b>"
msgstr "_گذرواژه:"

#: tmp/iscsi-config.glade.h:4
#, fuzzy
msgid "<b>Reverse CHAP U_sername:</b>"
msgstr "نام کاربر"

#: tmp/iscsi-config.glade.h:5
msgid "<b>_Target IP Address:</b>"
msgstr ""

#: tmp/iscsi-config.glade.h:6
msgid "<b>iSCSI Initiator _Name:</b>"
msgstr ""

#: tmp/iscsi-config.glade.h:9
msgid "_Add target"
msgstr ""

#: tmp/liveinst.desktop.in.h:1
#, fuzzy
msgid "Install"
msgstr "_نصب %s"

#: tmp/liveinst.desktop.in.h:2
msgid "Install the live CD to your hard disk"
msgstr ""

#: tmp/liveinst.desktop.in.h:3
#, fuzzy
msgid "Install to Hard Drive"
msgstr "نصب آغاز می‌شود"

#: tmp/lukspassphrase.glade.h:1
msgid ""
"Also add this passphrase to all existing encrypted devices to streamline the "
"boot process"
msgstr ""

#: tmp/lukspassphrase.glade.h:2
msgid ""
"Choose a passphrase for this encrypted partition. You will be prompted for "
"the passphrase during system boot."
msgstr ""

#: tmp/lukspassphrase.glade.h:3
#, fuzzy
msgid "Confirm passphrase:"
msgstr "تصدیق برگرداندن به حالت پیش‌فرض"

#: tmp/lukspassphrase.glade.h:4
msgid "Enter passphrase for encrypted partition"
msgstr ""

#: tmp/lukspassphrase.glade.h:5
msgid "Enter passphrase:"
msgstr ""

#: tmp/netconfig.glade.h:2
#, fuzzy
msgid "<b>Gateway:</b>"
msgstr "دروازه:"

#: tmp/netconfig.glade.h:3
#, fuzzy
msgid "<b>IPv4 Address:</b>"
msgstr "نشانی IP"

#: tmp/netconfig.glade.h:4
#, fuzzy
msgid "<b>IPv6 Address:</b>"
msgstr "نشانی IP"

#: tmp/netconfig.glade.h:5
#, fuzzy
msgid "<b>Nameserver:</b>"
msgstr "کارگزار نام"

#: tmp/netconfig.glade.h:6
msgid "<b>_Interface:</b>"
msgstr ""

#: tmp/netconfig.glade.h:7
msgid "Enable IPv_4 support"
msgstr ""

#: tmp/netconfig.glade.h:8
msgid "Enable IPv_6 support"
msgstr ""

#: tmp/netconfig.glade.h:11
#, fuzzy
msgid "Use _dynamic IP configuration (DHCP)"
msgstr "استفاده از پیکربندی پویای IP‏ (BOOTP/DHCP)"

#: tmp/network.glade.h:1
#, fuzzy
msgid "Hostname:"
msgstr "نام میزبان"

#: tmp/network.glade.h:2
msgid ""
"Please name this computer.  The hostname identifies the computer on a "
"network."
msgstr ""

#: tmp/tasksel.glade.h:1
msgid "Customize _later"
msgstr ""

#: tmp/tasksel.glade.h:2
msgid ""
"Please select any additional repositories that you want to use for software "
"installation."
msgstr ""

#: tmp/tasksel.glade.h:4
#, no-c-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage.  What additional tasks would you like your system to "
"support?"
msgstr ""

#: tmp/tasksel.glade.h:5
msgid ""
"You can further customize the software selection now, or after install via "
"the software management application."
msgstr ""

#: tmp/tasksel.glade.h:6
msgid "_Add additional software repositories"
msgstr ""

#: tmp/tasksel.glade.h:7
msgid "_Customize now"
msgstr ""

#: tmp/tasksel.glade.h:8
#, fuzzy
msgid "_Modify repository"
msgstr "_تغییر افراز"

#: tmp/zfcp-config.glade.h:1
#, fuzzy
msgid "<b>Device number:</b>"
msgstr "شمارهٔ دستگاه"

#: tmp/zfcp-config.glade.h:2
#, fuzzy
msgid "<b>FCP LUN:</b>"
msgstr "‏FCP LUN"

#: tmp/zfcp-config.glade.h:3
#, fuzzy
msgid "<b>WWPN:</b>"
msgstr "_گذرواژه:"

#: tmp/zfcp-config.glade.h:4
msgid "Add FCP device"
msgstr "اضافه کردن دستگاه FCP"

#. generated from lang-table
msgid "Afrikaans"
msgstr "آفریکانس"

#. generated from lang-table
msgid "Arabic"
msgstr "عربی"

#. generated from lang-table
msgid "Assamese"
msgstr ""

#. generated from lang-table
msgid "Bengali"
msgstr "بنگالی"

#. generated from lang-table
msgid "Bengali(India)"
msgstr "بنگالی (هند)‏"

#. generated from lang-table
msgid "Bulgarian"
msgstr "بلغاری"

#. generated from lang-table
msgid "Catalan"
msgstr "کاتالونیایی"

#. generated from lang-table
msgid "Chinese(Simplified)"
msgstr "چینی (ساده شده)‏"

#. generated from lang-table
msgid "Chinese(Traditional)"
msgstr "چینی (سنتی)‏"

#. generated from lang-table
msgid "Croatian"
msgstr "کرواتی"

#. generated from lang-table
msgid "Czech"
msgstr "چکی"

#. generated from lang-table
msgid "Danish"
msgstr "دانمارکی"

#. generated from lang-table
msgid "Dutch"
msgstr "هلندی"

#. generated from lang-table
msgid "English"
msgstr "انگلیسی"

#. generated from lang-table
msgid "Estonian"
msgstr "استونیایی"

#. generated from lang-table
msgid "Finnish"
msgstr "فنلاندی"

#. generated from lang-table
msgid "French"
msgstr "فرانسوی"

#. generated from lang-table
msgid "German"
msgstr "آلمانی"

#. generated from lang-table
#, fuzzy
msgid "Greek"
msgstr "آزاد"

#. generated from lang-table
msgid "Gujarati"
msgstr "گجراتی"

#. generated from lang-table
msgid "Hebrew"
msgstr ""

#. generated from lang-table
msgid "Hindi"
msgstr "هندی"

#. generated from lang-table
msgid "Hungarian"
msgstr "مجاری"

#. generated from lang-table
msgid "Icelandic"
msgstr "ایسلندی"

#. generated from lang-table
msgid "Iloko"
msgstr ""

#. generated from lang-table
msgid "Indonesian"
msgstr "اندونزیایی"

#. generated from lang-table
msgid "Italian"
msgstr "ایتالیایی"

#. generated from lang-table
msgid "Japanese"
msgstr "ژاپنی"

#. generated from lang-table
msgid "Kannada"
msgstr ""

#. generated from lang-table
msgid "Korean"
msgstr "کره‌ای"

#. generated from lang-table
msgid "Macedonian"
msgstr "مقدونی"

#. generated from lang-table
#, fuzzy
msgid "Maithili"
msgstr "گجراتی"

#. generated from lang-table
msgid "Malay"
msgstr "مالزیایی"

#. generated from lang-table
#, fuzzy
msgid "Malayalam"
msgstr "مالزیایی"

#. generated from lang-table
#, fuzzy
msgid "Marathi"
msgstr "گجراتی"

#. generated from lang-table
#, fuzzy
msgid "Nepali"
msgstr "بنگالی"

#. generated from lang-table
#, fuzzy
msgid "Norwegian(Bokmål)"
msgstr "نروژی"

#. generated from lang-table
msgid "Northern Sotho"
msgstr "سوتویی شمالی"

#. generated from lang-table
msgid "Oriya"
msgstr ""

#. generated from lang-table
msgid "Persian"
msgstr "فارسی"

#. generated from lang-table
msgid "Polish"
msgstr "لهستانی"

#. generated from lang-table
msgid "Portuguese"
msgstr "پرتغالی"

#. generated from lang-table
msgid "Portuguese(Brazilian)"
msgstr "پرتغالی (برزیل)‏"

#. generated from lang-table
msgid "Punjabi"
msgstr "پنجابی"

#. generated from lang-table
#, fuzzy
msgid "Romanian"
msgstr "کرواتی"

#. generated from lang-table
msgid "Russian"
msgstr "روسی"

#. generated from lang-table
msgid "Serbian"
msgstr ""

#. generated from lang-table
msgid "Serbian(Latin)"
msgstr ""

#. generated from lang-table
msgid "Sinhala"
msgstr ""

#. generated from lang-table
msgid "Slovak"
msgstr "اسلواکی"

#. generated from lang-table
msgid "Slovenian"
msgstr "اسلوینیایی"

#. generated from lang-table
msgid "Spanish"
msgstr "اسپانیایی"

#. generated from lang-table
msgid "Swedish"
msgstr "سوئدی"

#. generated from lang-table
#, fuzzy
msgid "Tajik"
msgstr "تامیلی"

#. generated from lang-table
msgid "Tamil"
msgstr "تامیلی"

#. generated from lang-table
msgid "Telugu"
msgstr ""

#. generated from lang-table
msgid "Turkish"
msgstr "ترکی"

#. generated from lang-table
msgid "Ukrainian"
msgstr "اوکراینی"

#. generated from lang-table
msgid "Vietnamese"
msgstr "ویتنامی"

#. generated from lang-table
msgid "Welsh"
msgstr "ویلزی"

#. generated from lang-table
msgid "Zulu"
msgstr "زولویی"
