# Arpad Biro <biro_arpad@yahoo.com>, 2004, 2005, 2006, 2007.
# Széll Tamás <tomi@digiflex.hu>, 2004.
# Gabor SUVEG <gabor@suveg.hu>, 2004.
# Szentiványi Gábor <szentivanyi.gabor@ulx.hu>, 2006.
# Gábor Szentiványi <szenti@ulx.hu>, 2006.
# Sulyok Péter <peti@fedoraproject.org>, 2008.
#
#
msgid ""
msgstr ""
"Project-Id-Version: anaconda master\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-03-27 15:38-0400\n"
"PO-Revision-Date: 2009-04-02 07:19+0200\n"
"Last-Translator: Sulyok Péter <peti@fedoraproject.org>\n"
"Language-Team: Hungarian <Hungarian <fedora-trans-hu@redhat.com>>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);"

#: ../anaconda:266 ../anaconda:312
#, python-format
msgid "Error processing %%ksappend lines: %s"
msgstr "Hiba %%ksappend sorokat feldolgozván: %s"

#: ../anaconda:269 ../anaconda:315
#, python-format
msgid "Unknown error processing %%ksappend lines: %s"
msgstr "Ismeretlen hiba %%ksappend sorokat feldolgozván: %s"

#: ../anaconda:283 ../anaconda:327 ../cmdline.py:86 ../gui.py:1251
#: ../text.py:543
#, python-format
msgid ""
"The following error was found while parsing your kickstart configuration:\n"
"\n"
"%s"
msgstr ""
"A kickstart beállítást értelmezvén a következő hiba merült fel:\n"
"\n"
"%s"

#: ../anaconda:449
msgid "Press <enter> for a shell"
msgstr "Parancsértelmezőért nyomjon <Enter>-t"

#: ../anaconda:458
msgid "Fatal Error"
msgstr "Végzetes hiba"

#: ../anaconda:459
#, python-format
msgid ""
"You do not have enough RAM to install %s on this machine.\n"
"\n"
"Press <return> to reboot your system.\n"
msgstr ""
"Nincs elég RAM a gépben %s telepítéséhez.\n"
"\n"
"Nyomjon <Enter>-t, hogy újrainduljon a rendszer.\n"

#: ../anaconda:464 ../rescue.py:285 ../rescue.py:311 ../rescue.py:324
#: ../rescue.py:397 ../rescue.py:406 ../text.py:694
#: ../textw/constants_text.py:44 ../loader/cdinstall.c:228
#: ../loader/cdinstall.c:232 ../loader/cdinstall.c:248
#: ../loader/cdinstall.c:251 ../loader/cdinstall.c:445
#: ../loader/cdinstall.c:452 ../loader/cdinstall.c:517
#: ../loader/dirbrowser.c:145 ../loader/driverdisk.c:98
#: ../loader/driverdisk.c:243 ../loader/driverdisk.c:274
#: ../loader/driverdisk.c:305 ../loader/driverdisk.c:340
#: ../loader/driverdisk.c:359 ../loader/driverdisk.c:371
#: ../loader/driverdisk.c:379 ../loader/driverdisk.c:539
#: ../loader/driverdisk.c:576 ../loader/driverselect.c:81
#: ../loader/driverselect.c:205 ../loader/hdinstall.c:143
#: ../loader/hdinstall.c:289 ../loader/hdinstall.c:352
#: ../loader/hdinstall.c:384 ../loader/hdinstall.c:454
#: ../loader/hdinstall.c:497 ../loader/hdinstall.c:510 ../loader/kbd.c:138
#: ../loader/kickstart.c:132 ../loader/kickstart.c:142
#: ../loader/kickstart.c:185 ../loader/kickstart.c:284
#: ../loader/kickstart.c:375 ../loader/kickstart.c:553 ../loader/lang.c:115
#: ../loader/lang.c:378 ../loader/loader.c:402 ../loader/loader.c:438
#: ../loader/loader.c:481 ../loader/loader.c:502 ../loader/loader.c:519
#: ../loader/loader.c:556 ../loader/loader.c:1203 ../loader/loader.c:1378
#: ../loader/mediacheck.c:46 ../loader/mediacheck.c:85
#: ../loader/mediacheck.c:92 ../loader/mediacheck.c:101 ../loader/method.c:279
#: ../loader/method.c:353 ../loader/modules.c:335 ../loader/modules.c:347
#: ../loader/net.c:564 ../loader/net.c:937 ../loader/net.c:1541
#: ../loader/net.c:1564 ../loader/net.c:1808 ../loader/net.c:1830
#: ../loader/net.c:1842 ../loader/nfsinstall.c:91 ../loader/nfsinstall.c:248
#: ../loader/nfsinstall.c:267 ../loader/nfsinstall.c:335
#: ../loader/telnetd.c:92 ../loader/urlinstall.c:83 ../loader/urlinstall.c:107
#: ../loader/urlinstall.c:175 ../loader/urlinstall.c:418
#: ../loader/urlinstall.c:427 ../loader/urlinstall.c:436 ../loader/urls.c:292
#: ../loader/urls.c:328 ../loader/urls.c:334 ../loader/urls.c:346
msgid "OK"
msgstr "OK"

#: ../anaconda:471
msgid ""
"You do not have enough RAM to use the graphical installer.  Starting text "
"mode."
msgstr ""
"Nincs elég memória a grafikus telepítő használatához.  Telepítés szöveges "
"módban."

#: ../anaconda:534
msgid "Starting graphical installation..."
msgstr "Grafikus telepítő indul…"

#: ../anaconda:823
msgid "Would you like to use VNC?"
msgstr "Szeretne VNC-t használni?"

#: ../anaconda:824
msgid ""
"Text mode provides a limited set of installation options.  It does not allow "
"you to specify your own partitioning layout or package selections.  Would "
"you like to use VNC mode instead?"
msgstr ""
"A szöveges mód lekorlátozott telepítés opciókat kínál.  Nem engedi meg "
"a saját merevlemez felosztást vagy a csomagok kiválogatását.  Kívánja "
"inkább a VNC módot használni?"

#: ../anaconda:852
msgid "Install class forcing text mode installation"
msgstr "A telepítő osztály szöveges módú telepítést erőletet"

#: ../anaconda:871
msgid "Graphical installation not available...  Starting text mode."
msgstr "Grafikus telepítés nem elérhető…  Indulás szöveges módban."

#: ../anaconda:879
msgid "DISPLAY variable not set. Starting text mode!"
msgstr "DISPLAY változó nincs beállítva. Indulás szöveges módban!"

#: ../anaconda:1047
msgid "reipl configuration successful => reboot"
msgstr "sikeres reipl beállítás => újraindulás"

#: ../anaconda:1050
msgid "reipl configuration failed => halt"
msgstr "reipl beállítás elbukott => leállás"

#: ../backend.py:144
#, python-format
msgid "Upgrading %s\n"
msgstr "%s felfejlesztése\n"

#: ../backend.py:146
#, python-format
msgid "Installing %s\n"
msgstr "%s telepítése\n"

#: ../backend.py:166
msgid "Copying File"
msgstr "Fájl másolása"

#: ../backend.py:167
msgid "Transferring install image to hard drive..."
msgstr "Telepítési képmás másolása a merevlemezre..."

#: ../backend.py:177
msgid ""
"An error occurred transferring the install image to your hard drive.  This "
"is probably due to bad media."
msgstr ""
"A telepítő képmást merevlemezre másolva hiba történt.  Ezt valószínűleg "
"hibás adathordozó okozta."

#: ../backend.py:181
msgid ""
"An error occurred transferring the install image to your hard drive. You are "
"probably out of disk space."
msgstr ""
"Hiba történt a telepítési képmásnak a merevlemezre írásakor. Valószínűleg "
"kevés a szabad lemezterülete."

#: ../backend.py:185 ../image.py:285 ../livecd.py:189 ../livecd.py:382
#: ../partIntfHelpers.py:202 ../text.py:460 ../text.py:464
#: ../yuminstall.py:371 ../yuminstall.py:664 ../yuminstall.py:779
#: ../yuminstall.py:1056 ../yuminstall.py:1124 ../yuminstall.py:1312
#: ../yuminstall.py:1337 ../iw/autopart_type.py:100 ../iw/autopart_type.py:199
#: ../iw/autopart_type.py:328 ../iw/autopart_type.py:331
#: ../iw/autopart_type.py:360 ../iw/osbootwidget.py:209
#: ../iw/osbootwidget.py:218 ../iw/raid_dialog_gui.py:700
#: ../iw/raid_dialog_gui.py:739 ../iw/task_gui.py:63 ../iw/task_gui.py:161
#: ../iw/task_gui.py:292 ../iw/task_gui.py:414 ../textw/netconfig_text.py:271
#: ../textw/partition_text.py:178 ../textw/partition_text.py:184
#: ../textw/partition_text.py:206 ../textw/upgrade_text.py:175
#: ../textw/upgrade_text.py:182 ../storage/__init__.py:268
#: ../storage/__init__.py:1423 ../storage/__init__.py:1439
#: ../loader/cdinstall.c:228 ../loader/cdinstall.c:517
#: ../loader/driverdisk.c:98 ../loader/driverdisk.c:305
#: ../loader/driverdisk.c:340 ../loader/driverdisk.c:371
#: ../loader/driverdisk.c:379 ../loader/driverdisk.c:443
#: ../loader/hdinstall.c:143 ../loader/hdinstall.c:352
#: ../loader/hdinstall.c:454 ../loader/hdinstall.c:497
#: ../loader/hdinstall.c:510 ../loader/kickstart.c:284 ../loader/lang.c:115
#: ../loader/loader.c:402 ../loader/loader.c:519 ../loader/loader.c:1203
#: ../loader/mediacheck.c:46 ../loader/mediacheck.c:85
#: ../loader/mediacheck.c:92 ../loader/method.c:279 ../loader/method.c:353
#: ../loader/nfsinstall.c:248 ../loader/nfsinstall.c:267
#: ../loader/telnetd.c:92 ../loader/urlinstall.c:83 ../loader/urlinstall.c:107
#: ../loader/urlinstall.c:175 ../loader/urls.c:328 ../loader/urls.c:334
msgid "Error"
msgstr "Hiba"

#: ../bootloader.py:43 ../bootloader.py:198 ../image.py:82
#: ../partedUtils.py:169 ../partedUtils.py:199 ../partedUtils.py:835
#: ../partedUtils.py:985 ../upgrade.py:298 ../yuminstall.py:1510
#: ../yuminstall.py:1539 ../iw/autopart_type.py:209 ../iw/blpasswidget.py:151
#: ../iw/upgrade_swap_gui.py:192 ../iw/upgrade_swap_gui.py:200
#: ../iw/upgrade_swap_gui.py:207 ../textw/upgrade_text.py:187
#: ../storage/devicetree.py:125 ../storage/devicetree.py:150
msgid "Warning"
msgstr "Figyelmeztetés"

#: ../bootloader.py:44
msgid ""
"Your filesystems have already been activated.  You cannot go back past this "
"point.\n"
"\n"
"Would you like to continue with the installation?"
msgstr ""
"A fájlrendszerek elkészültek. Innen már nincs visszaút.\n"
"\n"
"Szeretné folytatni a telepítéssel?"

#: ../bootloader.py:48 ../exception.py:468 ../exception.py:485
#: ../exception.py:508 ../exception.py:523 ../exception.py:548 ../gui.py:1256
#: ../gui.py:1384 ../gui.py:1461 ../image.py:91 ../livecd.py:196
#: ../livecd.py:389 ../packages.py:127 ../packages.py:135 ../packages.py:143
#: ../packages.py:151 ../packages.py:163 ../packages.py:172 ../packages.py:180
#: ../packages.py:189 ../upgrade.py:100 ../upgrade.py:120 ../upgrade.py:253
#: ../yuminstall.py:783 ../yuminstall.py:863 ../yuminstall.py:869
#: ../yuminstall.py:1027 ../yuminstall.py:1052 ../yuminstall.py:1112
#: ../yuminstall.py:1307 ../yuminstall.py:1344 ../storage/__init__.py:85
#: ../storage/__init__.py:1508
msgid "_Exit installer"
msgstr "_Kilépés a telepítőből"

#: ../bootloader.py:48 ../image.py:92 ../image.py:248 ../kickstart.py:1214
#: ../kickstart.py:1253 ../partedUtils.py:988 ../upgrade.py:100
#: ../upgrade.py:120 ../yuminstall.py:1117 ../iw/partition_gui.py:1036
#: ../storage/__init__.py:1509
msgid "_Continue"
msgstr "_Tovább"

#: ../bootloader.py:105 ../platform.py:90 ../platform.py:253
#: ../platform.py:297 ../platform.py:358
msgid "RAID Device"
msgstr "RAID eszköz"

#: ../bootloader.py:134
msgid "Bootloader"
msgstr "Rendszerindító"

#: ../bootloader.py:134
msgid "Installing bootloader..."
msgstr "A rendszerindító telepítése..."

#: ../bootloader.py:199
msgid ""
"No kernel packages were installed on your system.  Your boot loader "
"configuration will not be changed."
msgstr ""
"Nincs rendszermag csomag telepítve a gépre, ezért a rendszerindító "
"beállításai nem változnak meg."

#: ../cmdline.py:55
msgid "Completed"
msgstr "Kész"

#: ../cmdline.py:63
msgid "In progress...   "
msgstr "Folyamatban...   "

#: ../cmdline.py:98
msgid "Can't have a question in command line mode!"
msgstr "Nem lehet kérdezni parancssoros módban!"

#: ../constants.py:74
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report"
msgstr ""
"Kezeletlen kivétel történt.  A legvalószínűbb, hogy ez programhiba.  Kérem, "
"másolja ki a kivétel teljes szövegét, és adjon fel egy hibabejelentést"

#: ../constants.py:80
msgid " with the provider of this software."
msgstr " e szoftver szállítójának."

#: ../constants.py:84
#, python-format
msgid " against anaconda at %s"
msgstr " anaconda tárggyal %s helyen"

#: ../exception.py:391
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"A hibajelentést nem sikerült iktatni, mert azt a bugzillával közölvén, a "
"következő hiba merült fel:\n"
"\n"
"%s"

#: ../exception.py:394
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in anaconda:\n"
"\n"
"%s"
msgstr ""
"A hibajelentést nem tudtam iktatni a hiba mezőkbeli hibás információ miatt.  "
"Ez legvalószínűbben egy hiba az anacondában:\n"
"\n"
"%s"

#: ../exception.py:398
msgid "Unable To File Bug"
msgstr "Nem lehet hibát iktatni"

#: ../exception.py:404
msgid "Bug Filing Not Supported"
msgstr "Hiba iktatása nem támogatott"

#: ../exception.py:405
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr ""
"E kiadáshoz nincs támogatott hibaiktató rendszert, ezért ilyen módon nem "
"mentheti el a kivételt."

#: ../exception.py:411
msgid "Invalid Bug Information"
msgstr "Érvénytelen hiba információ"

#: ../exception.py:412
msgid "Please provide a valid username, password, and short bug description."
msgstr ""
"Kérem adjon meg érvényes használó nevet, jelszót, és egy rövid leírást a "
"hibáról."

#: ../exception.py:424
msgid "Unable To Login"
msgstr "Nem lehet bejelentkezni"

#: ../exception.py:425
#, python-format
msgid ""
"There was an error logging into %s using the provided username and password."
msgstr ""
"Hiba történt %s rendszerbe bejelentkezvén a megadott használó névvel és "
"jelszóval."

#: ../exception.py:462
msgid "Bug Created"
msgstr "Hibajelentés kész"

#: ../exception.py:463
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"Új hibajelentést teremtettem a nyomkövetést csatolva. Kérem adjon meg "
"további információt: mit csinált amikor beleszaladt a hibába, "
"képernyőképeket,és bármi mást, ami helyénvaló a következő hiba kapcsán:\n"
"\n"
"%s/%s"

#: ../exception.py:479
msgid "Bug Updated"
msgstr "Hiba frissítve"

#: ../exception.py:480
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"Az ön információjával már van hibajelentés.  Az ön számláját hozzáadtam a "
"másolat listához, illetve hozzáadtam a nyomkövetést a megjegyzésként.  Kérem "
"adjon hozzá további leíró információt a következő hibához:\n"
"\n"
"%s/%s"

#: ../exception.py:504 ../exception.py:519 ../exception.py:544
msgid "Dump Written"
msgstr "Lerakás kiírva"

#: ../exception.py:505 ../exception.py:520
msgid ""
"Your system's state has been successfully written to the disk. The installer "
"will now exit."
msgstr "A rendszer állapotát sikerült lemezre írni. A telepítő kilép."

#: ../exception.py:511 ../exception.py:528 ../exception.py:551
msgid "Dump Not Written"
msgstr "Nincs lerakás kiírva"

#: ../exception.py:512 ../exception.py:529
msgid "There was a problem writing the system state to the disk."
msgstr "A rendszerállapotot lemezre írván hiba történt."

#: ../exception.py:535 ../exception.py:558 ../rescue.py:201
#: ../yuminstall.py:1022
msgid "No Network Available"
msgstr "Nincs elérhető hálózat"

#: ../exception.py:536 ../exception.py:559
msgid ""
"Cannot save a bug report since there is no active networking device "
"available."
msgstr ""
"Nem tudom elmenteni hibajelentést, mivel nem érek el működő hálózat eszközt."

#: ../exception.py:545
msgid ""
"Your system's state has been successfully written to the remote host.  The "
"installer will now exit."
msgstr "A rendszer állapotát sikerült a távoli gépre írni.  A telepítő kilép."

#: ../exception.py:552
msgid "There was a problem writing the system state to the remote host."
msgstr "Hiba történt a rendszer állapotának távoli gépre történő írása közben."

#: ../gui.py:106
msgid "An error occurred copying the screenshots over."
msgstr "A képernyőképeket átmásolván hiba történt."

#: ../gui.py:117
msgid "Screenshots Copied"
msgstr "Képernyőképek átmásolva"

#: ../gui.py:118
msgid ""
"The screenshots have been saved into the directory:\n"
"\n"
"\t/root/anaconda-screenshots/\n"
"\n"
"You can access these when you reboot and login as root."
msgstr ""
"A képernyőképek a következő mappába kerültek:\n"
"\n"
"\t/root/anaconda-screenshots/\n"
"\n"
"Újraindítás után rendszergazdaként belépve érheti el."

#: ../gui.py:161
msgid "Saving Screenshot"
msgstr "Képernyőkép mentése"

#: ../gui.py:162
#, python-format
msgid "A screenshot named '%s' has been saved."
msgstr "„%s” nevű képernyőkép elmentve."

#: ../gui.py:165
msgid "Error Saving Screenshot"
msgstr "A képernyőképet mentvén hiba történt"

#: ../gui.py:166
msgid ""
"An error occurred while saving the screenshot.  If this occurred during "
"package installation, you may need to try several times for it to succeed."
msgstr ""
"Képernyőképet mentvén hiba történt.  Ha ez csomagot telepítvén történt, "
"akkor lehet, hogy többször is meg kell próbálni, hogy sikerüljön."

#: ../gui.py:546 ../text.py:500
msgid "Installation Key"
msgstr "Telepítő kulcs"

#: ../gui.py:617 ../text.py:308
msgid ""
"Choose a passphrase for your encrypted devices. You will be prompted for the "
"passphrase during system boot."
msgstr ""
"Válasszon jelszót a titkosított eszközöknek. A rendszerindító induláskor "
"kérni fogja ezt a jelszót."

#: ../gui.py:636 ../gui.py:644 ../text.py:346 ../text.py:356
msgid "Error with passphrase"
msgstr "Jelszóhiba"

#: ../gui.py:637 ../text.py:347
msgid "The passphrases you entered were different.  Please try again."
msgstr "A megadott jelszók különböznek.  Kérem próbálja újra."

#: ../gui.py:645
msgid "The passphrase must be at least eight characters long."
msgstr "A jelszó legalább 8 jel hosszú kell legyen."

#: ../gui.py:679 ../text.py:380
#, python-format
msgid ""
"Device %s is encrypted. In order to access the device's contents during "
"installation you must enter the device's passphrase below."
msgstr ""
"%s eszköz titkosítva. Ahhoz, hogy hozzáférjek az eszköz tartalmához "
"telepítés közben, önnek alább meg kell adnia az eszköz jelszavát."

#: ../gui.py:736
#, python-format
msgid "Bugzilla (%s)"
msgstr "Bugzilla (%s)"

#: ../gui.py:766
msgid "No devices found"
msgstr "Nem találtam eszközt"

#: ../gui.py:873 ../gui.py:1461 ../partIntfHelpers.py:149
#: ../partIntfHelpers.py:304 ../text.py:98 ../text.py:99
#: ../textw/constants_text.py:48 ../loader/dirbrowser.c:145
#: ../loader/driverdisk.c:244 ../loader/kickstart.c:375 ../loader/loader.c:438
#: ../loader/loader.c:556
msgid "Cancel"
msgstr "Mégsem"

#: ../gui.py:885 ../gui.py:886 ../gui.py:998 ../gui.py:999
#: tmp/anaconda.glade.h:2
msgid "_Debug"
msgstr "Ny_omkövetés"

#: ../gui.py:1049 ../gui.py:1051 ../gui.py:1458 ../livecd.py:113
msgid "Exit installer"
msgstr "Kilépés a telepítőből"

#: ../gui.py:1051 ../text.py:283 ../text.py:291
msgid "Debug"
msgstr "Hibakeresés"

#: ../gui.py:1053 ../text.py:287
msgid "Exception Occurred"
msgstr "Kivétel történt"

#: ../gui.py:1253 ../text.py:545
msgid "Error Parsing Kickstart Config"
msgstr "Hiba történt a Kickstart beállítás feldolgozásakor"

#: ../gui.py:1293
msgid "default:LTR"
msgstr "alapértelmezés:LTR"

#: ../gui.py:1373 ../text.py:659
msgid "Error!"
msgstr "Hiba!"

#: ../gui.py:1374 ../text.py:660
#, python-format
msgid ""
"An error occurred when attempting to load an installer interface component.\n"
"\n"
"className = %s"
msgstr ""
"Telepítő felülelet komponensét betöltvén hiba történt.\n"
"\n"
"osztály = %s"

#: ../gui.py:1379 ../image.py:164 ../image.py:194 ../packages.py:428
#: ../packages.py:433
msgid "_Exit"
msgstr "_Kilépés"

#: ../gui.py:1380 ../image.py:164 ../image.py:194 ../livecd.py:196
#: ../yuminstall.py:656 ../yuminstall.py:1052 ../yuminstall.py:1112
#: ../yuminstall.py:1307
msgid "_Retry"
msgstr "Újr_a"

#: ../gui.py:1383 ../packages.py:432
msgid "The installer will now exit..."
msgstr "A telepítő most kilép..."

#: ../gui.py:1386 ../packages.py:435
msgid "Your system will now be rebooted..."
msgstr "A rendszer újraindítása következik..."

#: ../gui.py:1387 ../image.py:248 ../packages.py:436 ../partedUtils.py:987
#: ../yuminstall.py:1360
msgid "_Reboot"
msgstr "Ú_jraindítás"

#: ../gui.py:1389
msgid "Exiting"
msgstr "Kilépés"

#: ../gui.py:1459
msgid "Are you sure you wish to exit the installation?"
msgstr "Biztos, hogy ki kíván lépni a telepítőből?"

#: ../gui.py:1468
#, python-format
msgid "%s Installer"
msgstr "%s telepítő"

#: ../gui.py:1475
msgid "Unable to load title bar"
msgstr "Nem sikerült betölteni a címsort"

#: ../gui.py:1531
msgid "Install Window"
msgstr "Telepítőablak"

#: ../image.py:83
#, python-format
msgid ""
"The ISO image %s has a size which is not a multiple of 2048 bytes.  This may "
"mean it was corrupted on transfer to this computer.\n"
"\n"
"It is recommended that you exit and abort your installation, but you can "
"choose to continue if you think this is in error."
msgstr ""
"%s ISO képmás mérete nem 2048 bájt többszöröse.  Ez azt is jelentheti, hogy "
"erre a számítógépre áthozva megsérült a képmás.\n"
"\n"
"Ajánlom, hogy lépjen ki, és szakítsa meg a telepítést. Azonban választhatja "
"a folytatást is, ha úgy gondolja, hogy ez egy hiba."

#: ../image.py:156
msgid "Couldn't Mount ISO Source"
msgstr "Nem sikerült ISO forrást becsatolni"

#: ../image.py:157
#, python-format
msgid ""
"An error occurred mounting the source device %s.  This may happen if your "
"ISO images are located on an advanced storage device like LVM or RAID, or if "
"there was a problem mounting a partition.  Click exit to abort the "
"installation."
msgstr ""
"%s forráseszközt becsatolván hiba történt.  Ez megtörténhet, ha az ISO "
"képmások egy fejlett tároló eszközön vannak (mint LVM vagy RAID), vagy ha "
"baj volt a lemezrész becsatolásával.  Kattintson a kilépésre, hogy kilépjen "
"a telepítőből."

#: ../image.py:185
msgid "Missing ISO 9660 Image"
msgstr "Hiányzó ISO 9660 képmás"

#: ../image.py:186
#, python-format
msgid ""
"The installer has tried to mount image #%s, but cannot find it on the hard "
"drive.\n"
"\n"
"Please copy this image to the drive and click Retry.  Click Exit to abort "
"the installation."
msgstr ""
"A telepítő megpróbálta becsatolni #%s képet, de nem találja a merevlemezen.\n"
"\n"
"Kérem másolja e képet a merevlemezre, és kattintson az Újra gombra.  "
"Kattintson a Kilépésre, hogy kilépjen a telepítőből."

#: ../image.py:241
msgid "Required Install Media"
msgstr "Szükséges telepítő adathordozók"

#: ../image.py:242
#, python-format
msgid ""
"The software you have selected to install will require the following %s %s "
"discs:\n"
"\n"
"%s\n"
"Please have these ready before proceeding with the installation.  If you "
"need to abort the installation and exit please select \"Reboot\"."
msgstr ""
"A kiválasztott szoftverek telepítéséhez a következő %s %s lemezek \n"
"szükségesek:\n"
"\n"
"%s\n"
"Kérem készítse elő őket, mielőtt folytatná a telepítést.  Ha meg kell "
"szakítania a telepítést, válassza az „Újraindítás” gombot."

#: ../image.py:248 ../livecd.py:388 ../packages.py:382 ../packages.py:433
#: ../packages.py:436 ../upgrade.py:252 ../yuminstall.py:783
#: ../yuminstall.py:869 ../yuminstall.py:1344 ../yuminstall.py:1360
msgid "_Back"
msgstr "_Vissza"

#: ../image.py:286
#, python-format
msgid ""
"An error occurred unmounting the disc.  Please make sure you're not "
"accessing %s from the shell on tty2 and then click OK to retry."
msgstr ""
"Lemezt lecsatolván hiba történt.  Kérem győződjön meg arról, hogynem "
"használja %s eszközt egy parancsértelmezőből a tty2-n, majd kattintson az OK "
"gombra, hogy újra megpróbálja."

#: ../installclass.py:71
msgid "Install on System"
msgstr "Telepítés a rendszerre"

#: ../iutil.py:740
#, python-format
msgid "Error: On open, cannot set reIPL method to %s (%s: %s)"
msgstr "Hiba: Nyitáskor nem lehet reIPL eljárást a következőre állítani: %s (%s: %s)"

#: ../iutil.py:748
#, python-format
msgid "Error: On write, cannot set reIPL method to %s (%s: %s)"
msgstr "Hiba: Íráskor nem lehet reIPL eljárást a következőre állítani: %s (%s: %s)"

#: ../iutil.py:755
#, python-format
msgid "Error: On close, cannot set reIPL method to %s (%s: %s)"
msgstr "Hiba: Záráskor nem lehet reIPL eljárást a következőre állítani: %s (%s: %s)"

#: ../iutil.py:765 ../iutil.py:817
#, python-format
msgid "Error: %s splits into %s but not like we expect"
msgstr "Hiba: %s szétválik %s-re, de nem úgy, ahogy várjuk"

#: ../iutil.py:778
#, python-format
msgid "Error: Could not set %s as reIPL device (%s)"
msgstr "Hiba: Nem lehet %s eszközt reIPL-nek beállítani (%s)"

#: ../iutil.py:787
#, python-format
msgid "Error: Could not reset loadparm (%s)"
msgstr "Hiba: Nem lehet loadparmot törölni (%s)"

#: ../iutil.py:796
#, python-format
msgid "Warning: Could not reset parm (%s)"
msgstr "Figyelem: Nem lehet parmot törölni (%s)"

#: ../iutil.py:806
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from DASD device %s to continue "
"installation"
msgstr ""
"Leállás után, kérem kézivezérléssel végezze el az IPL-t %s DASD eszközről, "
"hogy folytassa a telepítést"

#: ../iutil.py:834
#, python-format
msgid "Error: reading FCP property %s for reIPL (%s)"
msgstr "Hiba: %s FCP tulajdonságot reIPL számára beolvasván (%s)"

#: ../iutil.py:847
#, python-format
msgid "Error: writing FCP property %s for reIPL (%s)"
msgstr "Hiba: %s FCP tulajdonságot reIPL számára kiírván (%s)"

#: ../iutil.py:860
#, python-format
msgid "Error: writing default FCP property %s for reIPL (%s)"
msgstr "Hiba: %s FCP gyári tulajdonságot reIPL számára kiírván (%s)"

#: ../iutil.py:870
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from FCP %(device)s with WWPN %"
"(wwpn)s and LUN %(lun)s to continue installation"
msgstr ""
"Leállás után, a telepítés folytatásához kérem végezze el kézivezérléssel az IPL-t "
"FCP %(device)s eszközről WWPN %(wwpn)s és LUN %(lun)s tulajdonságokkal"

#: ../iutil.py:877
msgid ""
"After shutdown, please perform a manual IPL from the device now containing /"
"boot to continue installation"
msgstr ""
"Leállás után, a telepítés folytatásához kérem végezzen IPL-t kézivezérléssel "
"a /boot eszközéről"

#: ../iutil.py:887
msgid "Could not get information for mount point /boot or /"
msgstr "A /boot vagy a / csatolási pontról nem kaptam adatokat"

#: ../iutil.py:897
msgid "Error determining mount point type"
msgstr "Hiba a csatolási pont típusát meghatározván"

#: ../iutil.py:901
msgid "The mount point /boot or / is on a disk that we are not familiar with"
msgstr "A / vagy a /boot csatolási pont számunkra ismeretlen lemezen van"

#: ../kickstart.py:96
#, python-format
msgid ""
"There was an error running the kickstart script at line %s.  You may examine "
"the output in %s.  This is a fatal error and your install will be aborted.  "
"Press the OK button to exit the installer."
msgstr ""
"A kickstart írás %s. sorában hiba történt.  %s fájlban megvizsgálhatja a "
"kimenetet.  Ez végzetes hiba. A telepítés nem folytatható.  Nyomjon OK-t, "
"hogy kilépjen a telepítőből."

#: ../kickstart.py:111 ../kickstart.py:113
msgid "Scriptlet Failure"
msgstr "Kickstart írás hiba"

#: ../kickstart.py:1155 ../kickstart.py:1172
msgid "Running..."
msgstr "Futtatás..."

#: ../kickstart.py:1156
msgid "Running post-install scripts"
msgstr "Telepítés utáni írások futtatása"

#: ../kickstart.py:1173
msgid "Running pre-install scripts"
msgstr "Telepítés előtti írások futtatása"

#: ../kickstart.py:1205
msgid "Missing Package"
msgstr "Hiányzó csomag"

#: ../kickstart.py:1206
#, python-format
msgid ""
"You have specified that the package '%s' should be installed.  This package "
"does not exist. Would you like to continue or abort your installation?"
msgstr ""
"„%s” csomagot telepítésre jelölte.  Nincs ilyen csomag. Folytatni akarja, "
"vagy megszakítja a telepítést?"

#: ../kickstart.py:1212 ../kickstart.py:1251
msgid "_Abort"
msgstr "_Megszakítás"

#: ../kickstart.py:1213 ../kickstart.py:1252
msgid "_Ignore All"
msgstr "_Mindegyik mellőzése"

#: ../kickstart.py:1243
msgid "Missing Group"
msgstr "Hiányzó csoport"

#: ../kickstart.py:1244
#, python-format
msgid ""
"You have specified that the group '%s' should be installed. This group does "
"not exist. Would you like to continue or abort your installation?"
msgstr ""
"„%s” csoportot telepítésre jelölte. Nincs ilyen csoport. Folytatni akarja, "
"vagy megszakítja a telepítést?"

#: ../kickstart.py:1350
#, python-format
msgid ""
"Your kickstart file is missing required information that anaconda cannot "
"prompt for.  Please add the following sections and try again:\n"
"%s"
msgstr ""
"A kickstart fájlból olyan adat hiányzik, amit a telepítő nem tud bekérni."
"  Kérem adja hozzá a következő szakaszokat, majd próbálja újra:\n"
"%s"

#: ../livecd.py:108
msgid "Unable to find image"
msgstr "Képmás nem található"

#: ../livecd.py:109
#, python-format
msgid ""
"The given location isn't a valid %s live CD to use as an installation source."
msgstr ""
"A megadott hely nem érvényes telepítési forrásként használható %s élő CD."

#: ../livecd.py:171
msgid "Copying live image to hard drive."
msgstr "Élő képmás másolása a merevlemezre."

#: ../livecd.py:190
msgid ""
"There was an error installing the live image to your hard drive.  This could "
"be due to bad media.  Please verify your installation media.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"require reinstallation."
msgstr ""
"Hiba történt az élő képet merevlemezre másolván.  Talán sérült hordozó "
"okozta.  Kérem ellenőrizze a telepítő hordozót.\n"
"\n"
"Ha kilép, a rendszer rendetlen marad, s emiatt újbóli telepítést igényel "
"majd."

#: ../livecd.py:220
msgid "Doing post-installation"
msgstr "Telepítés utáni műveletek"

#: ../livecd.py:221
msgid ""
"Performing post-installation filesystem changes.  This may take several "
"minutes..."
msgstr "Fájlrendszer telepítés utáni igazítása. Ez néhány percig eltarthat..."

#: ../livecd.py:383
#, python-format
msgid ""
"The root filesystem you created is not large enough for this live image "
"(%.2f MB required)."
msgstr ""
"A gyökér fájlrendszer, amit ön készített nem elég nagy ennek az élő képnek "
"(%.2f·MB·szükséges)."

#: ../network.py:58
msgid "Hostname must be 255 or fewer characters in length."
msgstr "A gazdanév legfeljebb 255 jelből állhat."

#: ../network.py:64
msgid ""
"Hostname must start with a valid character in the ranges 'a-z', 'A-Z', or '0-"
"9'"
msgstr ""
"A gazda név első betűje az „a-z”, „A-Z” vagy „0-9” intervallumban kell "
"legyen."

#: ../network.py:69
msgid ""
"Hostnames can only contain the characters 'a-z', 'A-Z', '0-9', '-', or '.'"
msgstr "A gazda nevében engedélyezett jelek: „a-z”, „A-Z”, „0-9”, „-” és „.”."

#: ../network.py:178
msgid "IP address is missing."
msgstr "IP cím hiányzik."

#: ../network.py:182
msgid ""
"IPv4 addresses must contain four numbers between 0 and 255, separated by "
"periods."
msgstr ""
"IPv4 cím 4 darab, 0 és 255 közé eső, egymástól ponttal elválasztott számot "
"kell tartalmazzon."

#: ../network.py:185
#, python-format
msgid "'%s' is not a valid IPv6 address."
msgstr "„%s” nem érvényes IPv6 cím."

#: ../network.py:187
#, python-format
msgid "'%s' is an invalid IP address."
msgstr "„%s” érvénytelen IP cím."

#: ../packages.py:122
msgid "Device Resize Failed"
msgstr "Az átméretezés elbukott"

#: ../packages.py:123
#, python-format
msgid "An error was encountered while resizing device %s."
msgstr "%s eszközt átméretezvén hiba történt."

#: ../packages.py:130
msgid "Device Creation Failed"
msgstr "Eszköz teremtés elbukott"

#: ../packages.py:131
#, python-format
msgid "An error was encountered while creating device %s."
msgstr "%s eszközt megteremtvén hiba történt."

#: ../packages.py:138
msgid "Device Removal Failed"
msgstr "Eszköz eltávolítás bukott"

#: ../packages.py:139
#, python-format
msgid "An error was encountered while removing device %s."
msgstr "%s eszközt eltávolítván hiba történt."

#: ../packages.py:146
msgid "Device Setup Failed"
msgstr "Eszköz beállítás bukott"

#: ../packages.py:147
#, python-format
msgid "An error was encountered while setting up device %s."
msgstr "%s eszközt beállítván hiba történt."

#: ../packages.py:158
msgid "Resizing Failed"
msgstr "Átméretezés elbukott"

#: ../packages.py:159
#, python-format
msgid "There was an error encountered while resizing the device %s."
msgstr "%s eszközt átméretezvén hiba történt."

#: ../packages.py:166
msgid "Migration Failed"
msgstr "A mozgatás elbukott"

#: ../packages.py:167
#, python-format
msgid "An error was encountered while migrating filesystem on device %s."
msgstr "A fájlrendszert átmozgatván %s eszközön hiba történt."

#: ../packages.py:175
msgid "Formatting Failed"
msgstr "A kialakítás elbukott"

#: ../packages.py:176
#, python-format
msgid "An error was encountered while formatting device %s."
msgstr "%s eszközt alakítván hiba történt."

#: ../packages.py:184
msgid "Storage Activation Failed"
msgstr "Tárolóeszköz bekapcsolása bukott"

#: ../packages.py:185
msgid "An error was encountered while activating your storage configuration."
msgstr "Hiba történt a tároló beállítást érvényesítvén."

#: ../packages.py:353
msgid "Invalid Key"
msgstr "Érvénytelen kulcs"

#: ../packages.py:354
msgid "The key you entered is invalid."
msgstr "A megadott kulcs érvénytelen."

#: ../packages.py:379 ../rescue.py:248 ../rescue.py:250
#: ../textw/upgrade_text.py:133 ../loader/cdinstall.c:248
#: ../loader/cdinstall.c:251 ../loader/method.c:326
msgid "Skip"
msgstr "Kihagyás"

#: ../packages.py:382
msgid "_Skip"
msgstr "K_ihagyás"

#: ../packages.py:414 ../packages.py:437
msgid "Warning! This is pre-release software!"
msgstr "Figyelmeztetés! Ez előzetes szoftver!"

#: ../packages.py:415
#, python-format
msgid ""
"Thank you for downloading this pre-release of %s.\n"
"\n"
"This is not a final release and is not intended for use on production "
"systems.  The purpose of this release is to collect feedback from testers, "
"and it is not suitable for day to day usage.\n"
"\n"
"To report feedback, please visit:\n"
"\n"
"   %s\n"
"\n"
"and file a report against '%s'.\n"
msgstr ""
"Köszönjük, hogy letöltötte %s rendszer előzetes kiadását.\n"
"\n"
"Ez még nem a végleges változat, nem ajánljuk használatát éles rendszerben.  "
"Azért van, hogy visszajelzéseket kapjunak tesztelőktől, és nem való rendes "
"használatra.\n"
"\n"
"A visszajelzéseket ide kérjük:\n"
"\n"
"   %s\n"
"\n"
"Kérjük, hogy a hibákat „%s” címen jelentse be.\n"

#: ../packages.py:428
msgid "_Install anyway"
msgstr "_Telepítés mindenképpen"

#: ../partIntfHelpers.py:41
msgid "Please enter a volume group name."
msgstr "Kérem adjon meg egy kötetcsoportnevet."

#: ../partIntfHelpers.py:45
msgid "Volume Group Names must be less than 128 characters"
msgstr "Kötet csoport név kevesebb, mint 128 jel kell legyen"

#: ../partIntfHelpers.py:48
#, python-format
msgid "Error - the volume group name %s is not valid."
msgstr "Hiba történt – %s kötet csoport név érvénytelen."

#: ../partIntfHelpers.py:53
msgid ""
"Error - the volume group name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""
"Hiba – a kötet csoport név érvénytelen jeleket vagy közöket tartalmaz. Csak "
"ékezetlen betű, számjegy, „.” és „_” használható."

#: ../partIntfHelpers.py:63
msgid "Please enter a logical volume name."
msgstr "Kérem adjon meg logikai kötet nevet."

#: ../partIntfHelpers.py:67
msgid "Logical Volume Names must be less than 128 characters"
msgstr "Logikai kötet név 128 jelnél rövidebb kell legyen"

#: ../partIntfHelpers.py:71
#, python-format
msgid "Error - the logical volume name %s is not valid."
msgstr "Hiba – %s logikai kötet név érvénytelen."

#: ../partIntfHelpers.py:77
msgid ""
"Error - the logical volume name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""
"Hiba – a logikai kötet név érvénytelen jelet vagy közt tartalmaz.  Csak "
"ékezetlen betű, számjegy, „.” vagy „_” használható."

#: ../partIntfHelpers.py:101
#, python-format
msgid ""
"The mount point %s is invalid.  Mount points must start with '/' and cannot "
"end with '/', and must contain printable characters and no spaces."
msgstr ""
"%s csatoló pont érvénytelen.  Csatoló pontnak „/” jellel kell kezdődnie, nem "
"végződhet „/” jelre, és csak nyomtatható jeleket tartalmazhat, közöket nem."

#: ../partIntfHelpers.py:108
msgid "Please specify a mount point for this partition."
msgstr "Kérem adjon meg csatoló pontot e résznek."

#: ../partIntfHelpers.py:121 ../partIntfHelpers.py:128
msgid "Unable To Delete"
msgstr "Nem sikerült törölni"

#: ../partIntfHelpers.py:122
msgid "You must first select a partition to delete."
msgstr "Először ki kell választani a törölni kívánt részt."

#: ../partIntfHelpers.py:145 ../partIntfHelpers.py:303
#: ../iw/lvm_dialog_gui.py:747
msgid "Confirm Delete"
msgstr "Törlés megerősítése"

#: ../partIntfHelpers.py:146
#, python-format
msgid "You are about to delete all partitions on the device '%s'."
msgstr "„%s” eszközön minden részt törölni fog."

#: ../partIntfHelpers.py:149 ../partIntfHelpers.py:304
#: ../iw/lvm_dialog_gui.py:750 ../iw/lvm_dialog_gui.py:1261
#: ../iw/osbootwidget.py:102 ../iw/partition_gui.py:1333
msgid "_Delete"
msgstr "Tö_rlés"

#: ../partIntfHelpers.py:169
msgid "Notice"
msgstr "Megjegyzés"

#: ../partIntfHelpers.py:170
#, python-format
msgid ""
"The following partitions were not deleted because they are in use:\n"
"\n"
"%s"
msgstr ""
"A következő részeket nem töröltem, mert használják:\n"
"\n"
"%s"

#: ../partIntfHelpers.py:185
msgid "Format as Swap?"
msgstr "Lapozó kialakítása?"

#: ../partIntfHelpers.py:186
#, python-format
msgid ""
"%s has a partition type of 0x82 (Linux swap) but does not appear to be "
"formatted as a Linux swap partition.\n"
"\n"
"Would you like to format this partition as a swap partition?"
msgstr ""
"%s rész típusa 0x82 (Linux lapozó), de úgy tűnik, nem "
"aszerint alakították ki.\n"
"\n"
"Szeretne itt lapozó részt kialakítani?"

#: ../partIntfHelpers.py:201
#, python-format
msgid "You need to select at least one hard drive to install %s."
msgstr "Legalább egy merevlemezt ki kell választani %s telepítéséhez."

#: ../partIntfHelpers.py:206
msgid ""
"You have chosen to use a pre-existing partition for this installation "
"without formatting it. We recommend that you format this partition to make "
"sure files from a previous operating system installation do not cause "
"problems with this installation of Linux. However, if this partition "
"contains files that you need to keep, such as home directories, then "
"continue without formatting this partition."
msgstr ""
"Egy már meglévő részt választott ki telepítésre megújítás nélkül. Ajánljuk, "
"hogy új fájlrendszert alakítson ki e részen, hogy az új rendszer működésében "
"biztosan ne okozzanak bajt a korábbi rendszerhez tartozó fájlok. Azonban, ha "
"ezen a részen olyan fájlok vannak, amelyeket meg szeretne őrizni, például a "
"használók saját könyvtárai, akkor folytassa megújítás nélkül."

#: ../partIntfHelpers.py:214
msgid "Format?"
msgstr "Kialakítás?"

#: ../partIntfHelpers.py:214 ../iw/partition_gui.py:1034
msgid "_Modify Partition"
msgstr "Rész _módosítása"

#: ../partIntfHelpers.py:214
msgid "Do _Not Format"
msgstr "Átalakítás _nélkül"

#: ../partIntfHelpers.py:222
msgid "Error with Partitioning"
msgstr "Átalakítván hiba történt"

#: ../partIntfHelpers.py:223
#, python-format
msgid ""
"The following critical errors exist with your requested partitioning scheme. "
"These errors must be corrected prior to continuing with your install of %s.\n"
"\n"
"%s"
msgstr ""
"A kért felosztó sémával kapcsolatos kritikus hibák a következők. E hibákat "
"ki kell javítani, mielőtt folytatná %s telepítését.\n"
"\n"
"%s"

#: ../partIntfHelpers.py:237
msgid "Partitioning Warning"
msgstr "Felosztás figyelmeztetés"

#: ../partIntfHelpers.py:238
#, python-format
msgid ""
"The following warnings exist with your requested partition scheme.\n"
"\n"
"%s\n"
"\n"
"Would you like to continue with your requested partitioning scheme?"
msgstr ""
"A következő figyelmeztetések keletkeztek a kért felosztó sémához.\n"
"\n"
"%s\n"
"\n"
"Szeretné folytatni a kért felosztó sémával?"

#: ../partIntfHelpers.py:252 ../iw/partition_gui.py:643
msgid ""
"The following pre-existing partitions have been selected to be formatted, "
"destroying all data."
msgstr ""
"A következő korábban már kialakított részet jelölte ki átalakításra minden "
"adatuk eltüntetésével."

#: ../partIntfHelpers.py:255
msgid ""
"Select 'Yes' to continue and format these partitions, or 'No' to go back and "
"change these settings."
msgstr ""
"Válassza az „Igen”-t a folytatáshoz e részek átalakításával, vagy a „Nem”-et "
"a visszalépéshez és a beállítások megváltoztatásához."

#: ../partIntfHelpers.py:261
msgid "Format Warning"
msgstr "Átalakítás figyelmeztetés"

#: ../partIntfHelpers.py:287
#, python-format
msgid ""
"You are about to delete the volume group \"%s\".\n"
"\n"
"ALL logical volumes in this volume group will be lost!"
msgstr ""
"„%s” kötet csoport törlésére készül.\n"
"\n"
"A kötet csoporthoz tartozó összes logikai kötet EL FOG VESZNI!"

#: ../partIntfHelpers.py:291
#, python-format
msgid "You are about to delete the logical volume \"%s\"."
msgstr "„%s” logikai kötet törlésére készül."

#: ../partIntfHelpers.py:294
msgid "You are about to delete a RAID device."
msgstr "RAID eszköz törlésére készül."

#: ../partIntfHelpers.py:296
#, python-format
msgid "You are about to delete the %s partition."
msgstr "%s rész törlésére készül."

#: ../partIntfHelpers.py:300
#, python-format
msgid "You are about to delete the %s %s"
msgstr "%s %s törlésére készül."

#: ../partIntfHelpers.py:311
msgid "Confirm Reset"
msgstr "Visszaállítás megerősítése"

#: ../partIntfHelpers.py:312
msgid ""
"Are you sure you want to reset the partition table to its original state?"
msgstr "Biztosan vissza akarja állítani a felosztás tábla eredeti állapotát?"

#: ../partedUtils.py:108 ../iw/partition_gui.py:779 ../iw/partition_gui.py:927
msgid "None"
msgstr "Semmi"

#: ../partedUtils.py:170
#, python-format
msgid ""
"The device %s is LDL formatted instead of CDL formatted.  LDL formatted "
"DASDs are not supported for usage during an install of %s.  If you wish to "
"use this disk for installation, it must be re-initialized causing the loss "
"of ALL DATA on this drive.\n"
"\n"
"Would you like to reformat this DASD using CDL format?"
msgstr ""
"%s eszköz LDL típusú CDL helyett. LDL DASD-k nem használhatók %s "
"telepítésekor.  Ha ezt a lemezt telepítéskor szeretné használni, újra kell "
"inicializálnia, amelynek hatására a lemezen található ÖSSZES ADAT elvész.\n"
"\n"
"Át szeretné állítani a DASD-t a CDL-re?"

#: ../partedUtils.py:200
#, python-format
msgid ""
"/dev/%s currently has a %s partition layout.  To use this drive for the "
"installation of %s, it must be re-initialized, causing the loss of ALL DATA "
"on this drive.\n"
"\n"
"Would you like to re-initialize this drive?"
msgstr ""
"/dev/%s eszközön jelenleg %s felosztás van.  Ahhoz, hogy %s telepítéséhez "
"ezt az eszközt használja, előbb inicializálnia kell, ami az eszközön meglévő "
"ÖSSZES ADAT elvesztésével jár.\n"
"\n"
"Szeretné inicializálni ezt az eszközt?"

#: ../partedUtils.py:209 ../storage/devicetree.py:130
msgid "_Ignore drive"
msgstr "Eszköz _mellőzése"

#: ../partedUtils.py:210 ../storage/devicetree.py:131
msgid "_Re-initialize drive"
msgstr "Eszköz új_rainicializálása"

#: ../partedUtils.py:740
msgid "Initializing"
msgstr "Inicializálás"

#: ../partedUtils.py:741
#, python-format
msgid "Please wait while formatting drive %s...\n"
msgstr "Kérem várjon amíg kialakítom %s eszközt...\n"

#: ../partedUtils.py:826
#, python-format
msgid ""
"The partition table on device %s (%s %-0.f MB) was unreadable.\n"
"\n"
"To create new partitions it must be initialized, causing the loss of ALL "
"DATA on this drive.\n"
"\n"
"This operation will override any previous installation choices about which "
"drives to ignore.\n"
"\n"
"Would you like to initialize this drive, erasing ALL DATA?"
msgstr ""
"%s (%s %-0.f MB) eszköz felosztás táblája olvashatatlan.\n"
"\n"
"Új részekre osztáshoz előbb inicializálni kell, ami hatására az eszközön "
"meglévő ÖSSZES ADAT elvész.\n"
"\n"
"Ez a művelet felülbírálja a korábbi választásokat a mellőzendő eszközöket "
"illetően.\n"
"\n"
"Inicializálni szeretné ezt az eszközt, MINDEN ADATot törölve?"

# 3. %s: productName
#: ../partedUtils.py:978
#, python-format
msgid ""
"The drive /dev/%s has more than 15 partitions on it.  The SCSI subsystem in "
"the Linux kernel does not allow for more than 15 partitons at this time.  "
"You will not be able to make changes to the partitioning of this disk or use "
"any partitions beyond /dev/%s15 in %s"
msgstr ""
"A /dev/%s eszközön több mint 15 rész van.  A Linux kernel jelenlegi SCSI "
"alrendszere nem engedélyez 15-nél több részt.  E lemez felosztását nem lehet "
"majd megváltoztatni, továbbá %s rendszerben a /dev/%s15 utáni részeket nem "
"lehet majd használni."

#: ../partedUtils.py:1058 ../storage/__init__.py:851
msgid "No Drives Found"
msgstr "Nincs tároló eszköz"

#: ../partedUtils.py:1059 ../storage/__init__.py:852
msgid ""
"An error has occurred - no valid devices were found on which to create new "
"file systems. Please check your hardware for the cause of this problem."
msgstr ""
"Hiba történt – nincs érvényes eszköz, amin új fájlrendszert lehetne "
"kialakítani. Kérem ellenőrizze a hardvert, hogy kiderítse a probléma okát."

#: ../platform.py:91 ../platform.py:94 ../platform.py:254 ../platform.py:298
#: ../platform.py:359 ../platform.py:362
msgid "Master Boot Record (MBR)"
msgstr "Master Boot Record (MBR)"

#: ../platform.py:93 ../platform.py:361
msgid "First sector of boot partition"
msgstr "A rendszerindító rész első szektora"

#: ../platform.py:165
msgid "EFI System Partition"
msgstr "EFI rendszer rész"

#: ../platform.py:256
msgid "PPC PReP Boot"
msgstr "PPC PReP rendszerindító"

#: ../platform.py:300 ../platform.py:303
msgid "Apple Bootstrap"
msgstr "Apple rendszerindító"

#: ../rescue.py:167
msgid "When finished please exit from the shell and your system will reboot."
msgstr ""
"Amint elkészült, kérem lépjen ki a rendszerhéjból, és a rendszer újra fog "
"indulni."

#: ../rescue.py:174
msgid "Unable to find /bin/sh to execute!  Not starting shell"
msgstr "Nem találom a futtatandó /bin/sh-t!  Nem indítok rendszerhéjt"

#: ../rescue.py:193
msgid "Setup Networking"
msgstr "Hálózat beállítása"

#: ../rescue.py:194
msgid "Do you want to start the network interfaces on this system?"
msgstr "El szeretné indítani a rendszer hálózati csatolóit?"

#: ../rescue.py:195 ../textw/constants_text.py:56 ../loader/driverdisk.c:483
#: ../loader/driverdisk.c:493 ../loader/hdinstall.c:231
msgid "Yes"
msgstr "Igen"

#: ../rescue.py:195 ../rescue.py:197 ../textw/constants_text.py:60
#: ../loader/driverdisk.c:483 ../loader/driverdisk.c:493
msgid "No"
msgstr "Nem"

#: ../rescue.py:202
msgid ""
"Unable to activate a networking device.  Networking will not be available in "
"rescue mode."
msgstr ""
"Nem lehet hálózat eszközt bekapcsolni.  Hálózat nem lesz elérhető mentő "
"módban."

#: ../rescue.py:237 ../rescue.py:306 ../rescue.py:317 ../rescue.py:392
msgid "Rescue"
msgstr "Mentés"

#: ../rescue.py:238
#, python-format
msgid ""
"The rescue environment will now attempt to find your Linux installation and "
"mount it under the directory %s.  You can then make any changes required to "
"your system.  If you want to proceed with this step choose 'Continue'.  You "
"can also choose to mount your file systems read-only instead of read-write "
"by choosing 'Read-Only'.\n"
"\n"
"If for some reason this process fails you can choose 'Skip' and this step "
"will be skipped and you will go directly to a command shell.\n"
"\n"
msgstr ""
"A mentő környezet megpróbálja megtalálni a Linux rendszert, és becsatolja "
"azt a %s mappába. Ez után elvégezhető a kívánt módosítás a rendszerben.  Ha "
"ezt választja, nyomjon „Folytatás”-t.  „Csak olvasható”-t választva csak "
"olvasható módon csatolja be a fájlrendszert írható helyett.\n"
"\n"
"Ha valamilyen okból ez a művelet nem sikerül, válassza a „Kihagyás”-t, így "
"közvetlenül a rendszerhéjba fog jutni.\n"
"\n"

#: ../rescue.py:248 ../iw/partition_gui.py:547 ../storage/__init__.py:135
#: ../storage/devicetree.py:78 ../loader/cdinstall.c:206
#: ../loader/cdinstall.c:214 ../loader/driverdisk.c:444
msgid "Continue"
msgstr "Folytatás"

#: ../rescue.py:248 ../rescue.py:253
msgid "Read-Only"
msgstr "Csak olvasható"

#: ../rescue.py:282
msgid "System to Rescue"
msgstr "Mentendő rendszer"

#: ../rescue.py:283
msgid "Which device holds the root partition of your installation?"
msgstr "Melyik rész tartalmazza a meglévő rendszer gyökerét?"

#: ../rescue.py:285 ../rescue.py:289 ../text.py:664 ../text.py:666
msgid "Exit"
msgstr "Kilépés"

#: ../rescue.py:307
msgid ""
"Your system had dirty file systems which you chose not to mount.  Press "
"return to get a shell from which you can fsck and mount your partitions.  "
"The system will reboot automatically when you exit from the shell."
msgstr ""
"A rendszerben piszkos fájlrendszerek vannak, amiket nem csatlakoztat.  "
"Nyomjon Entert, hogy a rendszerhéjban a részeket fsck-val kijavíthatja, és "
"becsatolhatja. A rendszer magától újraindul, amikor kilép a rendszerhéjból."

#: ../rescue.py:318
#, python-format
msgid ""
"Your system has been mounted under %s.\n"
"\n"
"Press <return> to get a shell. If you would like to make your system the "
"root environment, run the command:\n"
"\n"
"\tchroot %s\n"
"\n"
"The system will reboot automatically when you exit from the shell."
msgstr ""
"A rendszer becsatolva %s ponton.\n"
"\n"
"Nyomjon <Enter>-t rendszerhéj megnyitásához. Ha a rendszert gyökér "
"környezetté szeretné tenni, adja ki a következő parancsot:\n"
"\n"
"\tchroot %s\n"
"\n"
"A rendszer magától újraindul, amikor kilép a rendszerhéjból."

#: ../rescue.py:393
#, python-format
msgid ""
"An error occurred trying to mount some or all of your system. Some of it may "
"be mounted under %s.\n"
"\n"
"Press <return> to get a shell. The system will reboot automatically when you "
"exit from the shell."
msgstr ""
"A rendszer néhány részét becsatolván hiba történt. Valamennyi lehet "
"becsatolva %s alatt.\n"
"\n"
"Rendszerhéj megnyitásához nyomjon <Enter>-t. A rendszerhéjból kilépve a gép "
"magától újra fog indulni."

#: ../rescue.py:402
msgid "Rescue Mode"
msgstr "Mentő mód"

#: ../rescue.py:403
msgid ""
"You don't have any Linux partitions. Press return to get a shell. The system "
"will reboot automatically when you exit from the shell."
msgstr ""
"Nincs Linux rész. Nyomjon Entert egy rendszerhéjért. A rendszer magától "
"újraindul, amikor kilép a rendszerhéjból."

#: ../rescue.py:416
#, python-format
msgid "Your system is mounted under the %s directory."
msgstr "A rendszer becsatolva %s pontra."

#: ../text.py:196 ../text.py:280 ../text.py:293 tmp/exnSave.glade.h:7
msgid "Save"
msgstr "Mentés"

#: ../text.py:199
msgid "Save to local disk"
msgstr "Helyi lemezre mentés"

#: ../text.py:200
#, python-format
msgid "Send to bugzilla (%s)"
msgstr "Beküldés bugzillába (%s)"

#: ../text.py:201
msgid "Send to remote server (scp)"
msgstr "Távoli kiszolgálóra másolás (scp)"

#: ../text.py:215 ../text.py:228
msgid "User name"
msgstr "Használó név"

#: ../text.py:217 ../text.py:230
msgid "Password"
msgstr "Jelszó"

#: ../text.py:219
msgid "Bug Description"
msgstr "Hiba leírás"

#: ../text.py:232
msgid "Host (host:port)"
msgstr "Gazda (gazda:kapu)"

#: ../text.py:234
msgid "Destination file"
msgstr "Cél fájl"

#: ../text.py:313
msgid "Passphrase for encrypted device"
msgstr "Jelszó a titkosított részhez"

#: ../text.py:326
msgid "Also add this passphrase to all existing encrypted devices"
msgstr "E jelszó használata minden meglévő titkosított eszközhöz"

#: ../text.py:357
#, python-format
msgid "The passphrase must be at least %d characters long."
msgstr "A jelszó legalább %d jel hosszú kell legyen."

#: ../text.py:387 tmp/lukspassphrase.glade.h:6
msgid "Passphrase"
msgstr "Jelszó"

#: ../text.py:395 tmp/lukspassphrase.glade.h:7
msgid "This is a global passphrase"
msgstr "Ez globális jelszó"

#: ../text.py:461 ../text.py:465
msgid "Repository editing is not available in text mode."
msgstr "Tároló szerkesztés nem érhető el szöveges módban."

#: ../text.py:505
#, python-format
msgid "Please enter your %(instkey)s"
msgstr "Kérem adja meg ezt: %(instkey)s"

#: ../text.py:522 tmp/instkey.glade.h:6
#, no-c-format, python-format
msgid "Skip entering %(instkey)s"
msgstr "%(instkey)s megadásának kihagyása"

#: ../text.py:570 ../loader/lang.c:63 ../loader/loader.c:215
#, c-format, python-format
msgid "Welcome to %s for %s"
msgstr "Üdvözöli %s %s"

#: ../text.py:572
#, python-format
msgid "Welcome to %s"
msgstr "Üdvözöli %s"

#: ../text.py:574
msgid ""
"  <Tab>/<Alt-Tab> between elements   |  <Space> selects   |  <F12> next "
"screen"
msgstr ""
"<Tab>/<Alt-Tab> elemek közti váltás|<Szóköz> kiválasztás|<F12> köv. képernyő"

#: ../text.py:664 ../loader/net.c:111 ../loader/net.c:454 ../loader/net.c:510
#: ../loader/net.c:655 ../loader/net.c:663 ../loader/net.c:1086
#: ../loader/net.c:1093
msgid "Retry"
msgstr "Újra"

#: ../text.py:690
msgid "Cancelled"
msgstr "Törölve"

#: ../text.py:691
msgid "I can't go to the previous step from here. You will have to try again."
msgstr "Innen nem lehet visszalépni. Újra meg kell próbálnia."

#: ../upgrade.py:92 ../upgrade.py:113
msgid "Proceed with upgrade?"
msgstr "Folytatni szeretné a felfejlesztést?"

#: ../upgrade.py:93
#, python-format
msgid ""
"You have choosen the upgrade for %s architecture, but the installed system "
"is for %s architecture. \n"
"\n"
msgstr ""
"Ön %s architektúrára felfejlesztést választotta, de a telepített rendszer%s "
"architektúrára való. \n"
"\n"

#: ../upgrade.py:97
#, python-format
msgid "Would you like to upgrade  the installed system to the %s architecture?"
msgstr "Szeretné felfejleszteni a telepített rendszert %s architektúrára?"

#: ../upgrade.py:114
msgid ""
"The file systems of the Linux installation you have chosen to upgrade have "
"already been mounted. You cannot go back past this point. \n"
"\n"
msgstr ""
"A felfejleszteni kívánt Linux telepítés fájlrendszereit már csatlakoztattam. "
"Innen már nem léphet vissza. \n"
"\n"

#: ../upgrade.py:118
msgid "Would you like to continue with the upgrade?"
msgstr "Folytatni szeretné a rendszer felfejlesztését?"

#: ../upgrade.py:239
msgid "Mount failed"
msgstr "Becsatolás elbukott"

#: ../upgrade.py:240
#, python-format
msgid ""
"The following error occurred when mounting the file systems listed in /etc/"
"fstab.  Please fix this problem and try to upgrade again.\n"
"%s"
msgstr ""
"Az /etc/fstab fájlban felsorolt részeket becsatolván a következő hiba "
"történt.  Kérem javítsa ki a hibát, majd próbálja újra a felfejlesztést.\n"
"%s"

#: ../upgrade.py:247
msgid "Upgrade root not found"
msgstr "Nincs felfejlesztő gyökér"

#: ../upgrade.py:248
msgid ""
"The root for the previously installed system was not found.  You can exit "
"installer or backtrack to choose installation instead of upgrade."
msgstr ""
"Az előző rendszer gyökerét nem találtam.  Kiléphet a telepítőből, "
"vagy visszaléphet, hogy a telepítést válassza a felfejlesztés helyett."

#: ../upgrade.py:271
msgid ""
"The following files are absolute symbolic links, which we do not support "
"during an upgrade. Please change them to relative symbolic links and restart "
"the upgrade.\n"
"\n"
msgstr ""
"A következő fájlok abszolút szimbolikus linkek, melyeket a felfejlesztés nem "
"támogat. Kérem változtassa meg ezeket relatív szimbolikus linkekre, és "
"indítsa újra a frissítési folyamatot.\n"
"\n"

#: ../upgrade.py:277
msgid "Absolute Symlinks"
msgstr "Abszolút szimbolikus linkek"

#: ../upgrade.py:288
msgid ""
"The following are directories which should instead be symbolic links, which "
"will cause problems with the upgrade.  Please return them to their original "
"state as symbolic links and restart the upgrade.\n"
"\n"
msgstr ""
"A következő mappák a várttal ellentétben nem szimbolikus linkek, ami gondot "
"okoz felfejlesztés közben.  Kérem állítsa vissza az eredeti állapotukat mint "
"szimbolikus linkek, majd indítsa újra a felfejlesztést.\n"
"\n"

#: ../upgrade.py:294
msgid "Invalid Directories"
msgstr "Érvénytelen mappák"

#: ../upgrade.py:299
#, python-format
msgid "%s not found"
msgstr "Nincs %s"

#: ../vnc.py:136
#, python-format
msgid "%s %s installation on host %s"
msgstr "%s %s telepítés %s gazdára"

#: ../vnc.py:138
#, python-format
msgid "%s %s installation"
msgstr "%s %s telepítés"

#: ../vnc.py:165
#, python-format
msgid "Attempting to connect to vnc client on host %s..."
msgstr "Csatlakozás %s gazdán levő vnc ügyfélhez..."

#: ../vnc.py:179
msgid "Connected!"
msgstr "Kapcsolva!"

#: ../vnc.py:182
msgid "Will try to connect again in 15 seconds..."
msgstr "Újabb próbálkozás 15 másodperc múlva..."

#: ../vnc.py:188
#, python-format
msgid "Giving up attempting to connect after %d tries!\n"
msgstr "Feladom %d csatlakozási kísérlet után!\n"

#: ../vnc.py:197
#, python-format
msgid "Please manually connect your vnc client to %s to begin the install."
msgstr ""
"Kérem csatlakozzon a vnc ügyféllel %s gazdához, hogy megkezdje a telepítést."

#: ../vnc.py:199
msgid "Please manually connect your vnc client to begin the install."
msgstr "Kérem csatlakozzon vnc ügyféllel, hogy megkezdje a telepítést."

#: ../vnc.py:202
msgid "Starting VNC..."
msgstr "VNC indítása..."

#: ../vnc.py:227
msgid "The VNC server is now running."
msgstr "A VNC kiszolgáló elindult."

#: ../vnc.py:240
msgid ""
"\n"
"\n"
"You chose to connect to a listening vncviewer. \n"
"This does not require a password to be set.  If you \n"
"set a password, it will be used in case the connection \n"
"to the vncviewer is unsuccessful\n"
"\n"
msgstr ""
"\n"
"\n"
"Ön egy figyelő vncviewerhez csatlakozást választja. \n"
"Ez nem igényel beállított jelszót.  Ha beállít egy jelszót, \n"
"akkor azt használni fogom, amennyiben a csatlakozás \n"
"a vncviewerhez sikertelen\n"
"\n"

#: ../vnc.py:245
msgid ""
"\n"
"\n"
"WARNING!!! VNC server running with NO PASSWORD!\n"
"You can use the vncpassword=<password> boot option\n"
"if you would like to secure the server.\n"
"\n"
msgstr ""
"\n"
"\n"
"FIGYELEM!!! A VNC kiszolgáló JELSZÓ NÉLKÜL működik!\n"
"Használhatja a vncpassword=<jelszó> rendszerindító \n"
"beállítást, ha biztonságossá szeretné tenni a kiszolgálót.\n"
"\n"

#: ../vnc.py:249
msgid ""
"\n"
"\n"
"You chose to execute vnc with a password. \n"
"\n"
msgstr ""
"\n"
"\n"
"Ön vnc futtatását választja jelszóval. \n"
"\n"

#: ../vnc.py:251
msgid ""
"\n"
"\n"
"Unknown Error.  Aborting. \n"
"\n"
msgstr ""
"\n"
"\n"
"Ismeretlen hiba.  Kilépés. \n"
"\n"

#: ../vnc.py:273 ../vnc.py:366
msgid "VNC Configuration"
msgstr "VNC beállítása"

#: ../vnc.py:276 ../vnc.py:370
msgid "No password"
msgstr "Nincs jelszó"

#: ../vnc.py:278 ../vnc.py:373
msgid ""
"A password will prevent unauthorized listeners connecting and monitoring "
"your installation progress.  Please enter a password to be used for the "
"installation"
msgstr ""
"Jelszó használatával lehet megakadályozni, hogy illetéktelenek férjenek "
"hozzá a telepítési folyamathoz.  Kérem adjon meg a telepítéshez használandó "
"jelszót"

#: ../vnc.py:286 ../vnc.py:381 ../textw/userauth_text.py:47
msgid "Password:"
msgstr "Jelszó:"

#: ../vnc.py:287 ../vnc.py:382 ../textw/userauth_text.py:49
msgid "Password (confirm):"
msgstr "Jelszó (megerősítés):"

#: ../vnc.py:305 ../vnc.py:404 ../textw/userauth_text.py:70
msgid "Password Mismatch"
msgstr "Eltérő jelszavak"

#: ../vnc.py:306 ../vnc.py:405 ../textw/userauth_text.py:71
msgid "The passwords you entered were different. Please try again."
msgstr "Az ön által beírt jelszók különböznek. Kérem próbálja újra."

#: ../vnc.py:311 ../vnc.py:410 ../textw/userauth_text.py:66
msgid "Password Length"
msgstr "Jelszó hossz"

#: ../vnc.py:312 ../vnc.py:411
msgid "The password must be at least six characters long."
msgstr "A jelszó legalább 6 jel hosszú kell legyen."

#: ../vnc.py:334
msgid "Unable to Start X"
msgstr "Nem lehet X-et elindítani"

#: ../vnc.py:336
msgid ""
"X was unable to start on your machine.  Would you like to start VNC to "
"connect to this computer from another computer and perform a graphical "
"install or continue with a text mode install?"
msgstr ""
"Az X nem tudott elindulni.  El szeretné indítani a VNC-t, hogy más gépről "
"csatlakozni lehessen ehhez a géphez a grafikus módú telepítés elvégzéséhez "
"vagy inkább szöveges módban szeretné folytatni a telepítést?"

#: ../vnc.py:355
msgid "Start VNC"
msgstr "VNC elindítása"

#: ../vnc.py:356 ../vnc.py:358
msgid "Use text mode"
msgstr "Szöveges mód használata"

#: ../yuminstall.py:79
#, python-format
msgid "%s MB"
msgstr "%s MB"

#: ../yuminstall.py:82
#, python-format
msgid "%s KB"
msgstr "%s kB"

#: ../yuminstall.py:85
#, python-format
msgid "%s Byte"
msgstr "%s bájt"

#: ../yuminstall.py:87
#, python-format
msgid "%s Bytes"
msgstr "%s bájt"

#: ../yuminstall.py:131
msgid "Processing"
msgstr "Feldolgozás"

#: ../yuminstall.py:132
msgid "Preparing transaction from installation source..."
msgstr "Tranzakció előkészítése telepítő forrásból..."

#: ../yuminstall.py:163
#, python-format
msgid "<b>Installing %s</b> (%s)\n"
msgstr "<b>%s telepítése</b> (%s)\n"

#: ../yuminstall.py:212
#, python-format
msgid "%s of %s packages completed"
msgstr "%s befejezve %s csomagból"

#: ../yuminstall.py:222
msgid "Finishing upgrade"
msgstr "Felfejlesztés befejezése"

#: ../yuminstall.py:223
msgid "Finishing upgrade process.  This may take a little while..."
msgstr "Felfejlesztés befejezése.  Ez egy ideig eltarthat..."

#: ../yuminstall.py:293 ../iw/task_gui.py:301
msgid "Error Setting Up Repository"
msgstr "Hiba a tárolót beállítván"

#: ../yuminstall.py:294 ../iw/task_gui.py:302
#, python-format
msgid ""
"The following error occurred while setting up the installation repository:\n"
"\n"
"%s\n"
"\n"
"Please provide the correct information for installing %s."
msgstr ""
"A következő baj történt a telepítő tárolót beállítván:\n"
"\n"
"%s\n"
"\n"
"Kérem adja meg a helyes információt %s telepítéséhez."

#: ../yuminstall.py:353
msgid "Change Disc"
msgstr "Lemezcsere"

#: ../yuminstall.py:354
#, python-format
msgid "Please insert %s disc %d to continue."
msgstr "Helyezze be %s %d. lemezét a folytatáshoz."

#: ../yuminstall.py:364
msgid "Wrong Disc"
msgstr "Rossz lemez"

#: ../yuminstall.py:365
#, python-format
msgid "That's not the correct %s disc."
msgstr "Ez nem a megfelelő %s lemez."

#: ../yuminstall.py:372
msgid "Unable to access the disc."
msgstr "Elérhetetlen a lemez."

#: ../yuminstall.py:530
#, python-format
msgid "Repository %r is missing name in configuration, using id"
msgstr "%r tároló neve hiányzik a beállításban, id-t használók"

#: ../yuminstall.py:654 ../yuminstall.py:656
msgid "Re_boot"
msgstr "Újrain_dítás"

#: ../yuminstall.py:654
msgid "_Eject"
msgstr "L_emez kiadása"

#: ../yuminstall.py:665
#, python-format
msgid ""
"The file %s cannot be opened.  This is due to a missing file, a corrupt "
"package or corrupt media.  Please verify your installation source.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"likely require reinstallation.\n"
"\n"
msgstr ""
"%s fájlt nem sikerült megnyitni.  Valószínűleg hiányzó fájl, sérült csomag, "
"vagy sérült hordozó okozta.  Kérem ellenőrizze a telepítő forrást.\n"
"\n"
"Ha kilép, a rendszer rendetlen marad, s emiatt újbóli telepítést igényel "
"majd.\n"
"\n"

#: ../yuminstall.py:708
msgid "Retrying"
msgstr "Újrapróbálás"

#: ../yuminstall.py:708
msgid "Retrying download..."
msgstr "Letöltés újrapróbálása…"

#: ../yuminstall.py:780
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s\n"
msgstr "Az átvitelt végrehajtván hiba történt a következő okból: %s\n"

#: ../yuminstall.py:815 ../yuminstall.py:816
msgid "file conflicts"
msgstr "fájl ütközés"

#: ../yuminstall.py:817
msgid "older package(s)"
msgstr "régebbi csomag(ok)"

#: ../yuminstall.py:818
msgid "insufficient disk space"
msgstr "nem elegendő szabad lemezterület"

#: ../yuminstall.py:819
msgid "insufficient disk inodes"
msgstr "nincs elég inode"

#: ../yuminstall.py:820
msgid "package conflicts"
msgstr "csomag ütközés"

#: ../yuminstall.py:821
msgid "package already installed"
msgstr "már telepített csomag"

#: ../yuminstall.py:822
msgid "required package"
msgstr "szükséges csomag"

#: ../yuminstall.py:823
msgid "package for incorrect arch"
msgstr "nem megfelelő architektúrához készült csomag"

#: ../yuminstall.py:824
msgid "package for incorrect os"
msgstr "nem megfelelő operációs rendszerhez készült csomag"

#: ../yuminstall.py:838
msgid "You need more space on the following file systems:\n"
msgstr "Több szabad helyre van szüksége az alábbi fájlrendszereken:\n"

#: ../yuminstall.py:851
#, python-format
msgid ""
"There were file conflicts when checking the packages to be installed:\n"
"%s\n"
msgstr ""
"Fájl összeütközés történt a telepítendő csomagokat ellenőrizvén:\n"
"%s\n"

#: ../yuminstall.py:854
#, python-format
msgid ""
"There was an error running your transaction for the following reason(s): %"
"s.\n"
msgstr "Az átvitelt végrehajtván hiba történt a következő miatt: %s\n"

#: ../yuminstall.py:861 ../yuminstall.py:866
msgid "Error Running Transaction"
msgstr "Hiba az átvitelt végrehajtván"

#: ../yuminstall.py:1023
msgid ""
"Some of your software repositories require networking, but there was an "
"error enabling the network on your system."
msgstr ""
"Néhány szoftver tárolóhoz hálózat kell, de a hálózatot "
"engedélyezvén hiba történt ."

#: ../yuminstall.py:1057
msgid ""
"Unable to read group information from repositories.  This is a problem with "
"the generation of your install tree."
msgstr ""
"Nem sikerült beolvasni a csoportinformációt a tárolókból. A probléma a "
"telepítési fa készítésében lépett fel."

#: ../yuminstall.py:1095
msgid "Retrieving installation information..."
msgstr "Telepítési információk beolvasása..."

#: ../yuminstall.py:1097
#, python-format
msgid "Retrieving installation information for %s..."
msgstr "Telepítési információk beolvasása %s számára..."

#: ../yuminstall.py:1099
msgid "Installation Progress"
msgstr "Telepítés haladása"

#: ../yuminstall.py:1112 ../textw/constants_text.py:64
msgid "Edit"
msgstr "Szerkesztés"

#: ../yuminstall.py:1125 ../yuminstall.py:1313
#, python-format
msgid ""
"Unable to read package metadata. This may be due to a missing repodata "
"directory.  Please ensure that your install tree has been correctly "
"generated.\n"
"\n"
"%s"
msgstr ""
"Nem lehet beolvasni a csomagleírásokat. Ezt okozhatja a repodata mappa "
"hiánya.  Kérem ellenőrizze, hogy jól készítették-e el a telepítő fát.\n"
"\n"
"%s"

#: ../yuminstall.py:1176 ../iw/GroupSelector.py:485
msgid "Uncategorized"
msgstr "Nem besorolt"

#: ../yuminstall.py:1338
#, python-format
msgid ""
"Your selected packages require %d MB of free space for installation, but you "
"do not have enough available.  You can change your selections or exit the "
"installer."
msgstr ""
"A kiválasztott csomagoknak %d MB szabad hely kell, de nincs elég elérhető.  "
"Megváltoztathatja a kiválasztást, vagy kiléphet a telepítőből."

#: ../yuminstall.py:1357
msgid "Reboot?"
msgstr "Újraindítás?"

#: ../yuminstall.py:1358
msgid "The system will be rebooted now."
msgstr "A rendszer újraindítása következik."

#: ../yuminstall.py:1511
#, python-format
msgid ""
"You appear to be upgrading from a system which is too old to upgrade to this "
"version of %s.  Are you sure you wish to continue the upgrade process?"
msgstr ""
"Úgy tűnik, a rendszer túl régi, ezért nem fejleszthető fel %s változatra.  "
"Biztosan folytatni szeretné a felfejlesztést?"

#: ../yuminstall.py:1540
#, python-format
msgid ""
"The arch of the release of %s you are upgrading to appears to be %s which "
"does not match your previously installed arch of %s.  This is likely to not "
"succeed.  Are you sure you wish to continue the upgrade process?"
msgstr ""
"%s kiadás architektúrája, amire felfejleszt, %s, ami nem egyezik meg a "
"korábban telepített %s architektúrával.  Nem valószínű, hogy ez sikerülni "
"fog.  Biztosan folytatni akarja a felfejlesztést?"

#: ../yuminstall.py:1591
msgid "Post Upgrade"
msgstr "Felfejlesztés után"

#: ../yuminstall.py:1592
msgid "Performing post upgrade configuration..."
msgstr "Felfejlesztés utáni beállítás..."

#: ../yuminstall.py:1594
msgid "Post Install"
msgstr "Telepítés után"

#: ../yuminstall.py:1595
msgid "Performing post install configuration..."
msgstr "Telepítés utáni beállítás..."

#: ../yuminstall.py:1820
msgid "Install Starting"
msgstr "Kezdődik a telepítés"

#: ../yuminstall.py:1821
msgid "Starting install process.  This may take several minutes..."
msgstr "Telepítő indítása. Ez néhány percig eltarthat..."

#: ../yuminstall.py:1859
msgid "Dependency Check"
msgstr "Függőség ellenőrzés"

#: ../yuminstall.py:1860
msgid "Checking dependencies in packages selected for installation..."
msgstr "A telepítésre kiválasztott csomagok közötti függőségek ellenőrzése..."

#: ../iw/GroupSelector.py:147
#, python-format
msgid "Packages in %s"
msgstr "%s csomagok"

#: ../iw/GroupSelector.py:424
#, python-format
msgid "Optional packages selected: %d of %d"
msgstr "%d / %d választható csomag bejelölve."

#: ../iw/GroupSelector.py:425
#, python-format
msgid "<i>%s</i>"
msgstr "<i>%s</i>"

#: ../iw/account_gui.py:52
msgid "Root _Password:"
msgstr "_Rendszergazda jelszó:"

#: ../iw/account_gui.py:54
msgid "_Confirm:"
msgstr "_Megerősítés:"

#: ../iw/account_gui.py:97
msgid "Caps Lock is on."
msgstr "Caps Lock bekapcsolva."

#: ../iw/account_gui.py:107 ../iw/account_gui.py:115 ../iw/account_gui.py:122
#: ../iw/account_gui.py:144 ../textw/userauth_text.py:74
msgid "Error with Password"
msgstr "Jelszóhiba"

#: ../iw/account_gui.py:108
msgid ""
"You must enter your root password and confirm it by typing it a second time "
"to continue."
msgstr ""
"Meg kell adni a rendszergazda jelszót, majd megerősíteni ellenőrzésképpen, "
"mielőtt folytatja."

#: ../iw/account_gui.py:116
msgid "The passwords you entered were different.  Please try again."
msgstr "A megadott jelszók különböznek. Kérem próbálja újra."

#: ../iw/account_gui.py:123
msgid "The root password must be at least six characters long."
msgstr "Rendszergazda jelszó legalább 6 karakter hosszú kell legyen."

#: ../iw/account_gui.py:132 ../textw/userauth_text.py:83
msgid "Weak Password"
msgstr "Gyenge jelszó"

#: ../iw/account_gui.py:133 ../textw/userauth_text.py:84
#, python-format
msgid ""
"Weak password provided: %s\n"
"\n"
"Would you like to continue with this password?"
msgstr ""
"Gyenge jelszót adott: %s\n"
"\n"
"Ezzel a jelszóval szeretné folytatni?"

#: ../iw/account_gui.py:145 ../textw/userauth_text.py:75
msgid ""
"Requested password contains non-ASCII characters, which are not allowed."
msgstr "A kért jelszó tartalmaz nem ASCII jeleket, ami nem engedélyezett."

#: ../iw/autopart_type.py:101
msgid ""
"No partitions are available to resize.  Only physical partitions with "
"specific filesystems can be resized."
msgstr ""
"Nincs átméretezésre elérhető lemezrész.  Csak bizonyos fájlrendszerű "
"részeket lehet átméretezni."

#: ../iw/autopart_type.py:124
msgid "Resize FileSystem Error"
msgstr "Fájlrendszer átméretezés hiba"

#: ../iw/autopart_type.py:125 ../iw/autopart_type.py:134
#, python-format
msgid "%s: %s"
msgstr "%s: %s"

#: ../iw/autopart_type.py:133
msgid "Resize Device Error"
msgstr "Eszköz átméretezés hiba"

#: ../iw/autopart_type.py:208
msgid ""
"Do you really want to boot from a disk which is not used for installation?"
msgstr ""
"Biztos, hogy olyan lemezről akar rendszert betölteni, amit nem használ "
"telepítésre?"

#: ../iw/autopart_type.py:285
msgid "Invalid Initiator Name"
msgstr "Érvénytelen kezdeményező név"

#: ../iw/autopart_type.py:286
msgid "You must provide an initiator name."
msgstr "Meg kell adni egy kezdeményező nevet."

#: ../iw/autopart_type.py:321
msgid "Error with Data"
msgstr "Adathiba"

#: ../iw/autopart_type.py:398 ../iw/autopart_type.py:399
msgid "Rescanning disks"
msgstr "Lemezek lekérdezése ismét"

#: ../iw/autopart_type.py:452 ../textw/partition_text.py:63
msgid "Use entire drive"
msgstr "Teljes eszköz használata"

#: ../iw/autopart_type.py:453 ../textw/partition_text.py:64
msgid "Replace existing Linux system"
msgstr "Meglévő Linux rendszer lecserélése"

#: ../iw/autopart_type.py:454
msgid "Shrink current system"
msgstr "Rendszer összehúzása"

#: ../iw/autopart_type.py:455 ../textw/partition_text.py:65
msgid "Use free space"
msgstr "Szabad hely használata"

#: ../iw/autopart_type.py:456
msgid "Create custom layout"
msgstr "Egyedi felosztás teremtése"

#: ../iw/blpasswidget.py:47
msgid "_Use a boot loader password"
msgstr "Jelszó h_asználata a rendszerindítóban"

#: ../iw/blpasswidget.py:48
msgid ""
"A boot loader password prevents users from changing kernel options, "
"increasing security."
msgstr ""
"A rendszerindító jelszavas védelme a biztonságot növelendő megakadályozza a "
"használókat, hogy a rendszermag beállításait babrálják."

#: ../iw/blpasswidget.py:79
msgid "Change _password"
msgstr "_Jelszó megváltoztatása"

#: ../iw/blpasswidget.py:102
msgid "Enter Boot Loader Password"
msgstr "Adja meg a rendszerindító jelszót"

#: ../iw/blpasswidget.py:108
msgid ""
"Enter a boot loader password and then confirm it.  (Note that your BIOS "
"keymap may be different than the actual keymap you are used to.)"
msgstr ""
"Adja meg a renszerindító jelszót, és erősítse meg.  (Ne felejtse el, hogy a "
"BIOS esetleg más billentyűzetkiosztást használ, mint amit ön megszokott.)"

#: ../iw/blpasswidget.py:115
msgid "_Password:"
msgstr "J_elszó:"

#: ../iw/blpasswidget.py:121
msgid "Con_firm:"
msgstr "_Megerősítés:"

#: ../iw/blpasswidget.py:142
msgid "Passwords don't match"
msgstr "A jelszavak különböznek"

#: ../iw/blpasswidget.py:143
msgid "Passwords do not match"
msgstr "A jelszavak nem egyeznek meg"

#: ../iw/blpasswidget.py:152
msgid ""
"Your boot loader password is shorter than six characters.  We recommend a "
"longer boot loader password.\n"
"\n"
"Would you like to continue with this password?"
msgstr ""
"A rendszerindító jelszó rövidebb 6 jelnél.  Ennél hosszabb jelszót célszerű "
"választani.\n"
"\n"
"Folytatni szeretné e jelszóval?"

#: ../iw/bootloader_main_gui.py:36
msgid "Boot Loader Configuration"
msgstr "Rendszerindító beállítás"

#: ../iw/bootloader_main_gui.py:179 ../iw/bootloader_main_gui.py:184
#: ../iw/bootloader_main_gui.py:221
#, python-format
msgid "_Install boot loader on /dev/%s."
msgstr "_Rendszerindító telepítése a /dev/%s eszközre."

#: ../iw/bootloader_main_gui.py:227
msgid "_Change device"
msgstr "Eszköz_csere"

#: ../iw/congrats_gui.py:33
msgid "Congratulations"
msgstr "Gratulálok"

#: ../iw/congrats_gui.py:74 ../textw/complete_text.py:39
#, python-format
msgid ""
"Congratulations, your %s installation is complete.\n"
"\n"
msgstr ""
"Gratulálok! %s telepítése kész.\n"
"\n"
""

#: ../iw/congrats_gui.py:77 ../textw/complete_text.py:42
msgid "Shutdown"
msgstr "Leállítás"

#: ../iw/congrats_gui.py:79 ../textw/complete_text.py:44
msgid "Please shutdown to use the installed system.\n"
msgstr "Kérem állítsa le a rendszert, hogy a telepített rendszert használja.\n"

#: ../iw/congrats_gui.py:81 ../textw/complete_text.py:46
msgid "Please reboot to use the installed system.\n"
msgstr "Kérem indítsa újra a rendszert, hogy a telepített rendszert használja.\n"

#: ../iw/congrats_gui.py:86 ../textw/complete_text.py:51
msgid ""
"Note that updates may be available to ensure the proper functioning of your "
"system and installation of these updates is recommended after the reboot."
msgstr ""
"Vegye észre, hogy a rendszer hibátlan működésének biztosításához "
"frissítések lehetnek elérhetők, amiket ajánlunk az újraindulás után."

#: ../iw/congrats_gui.py:90 ../textw/complete_text.py:55
#, python-format
msgid ""
"Congratulations, your %s installation is complete.\n"
"\n"
"Please reboot to use the installed system.  Note that updates may be "
"available to ensure the proper functioning of your system and installation "
"of these updates is recommended after the reboot."
msgstr ""

#: ../iw/examine_gui.py:37
msgid "Upgrade Examine"
msgstr "Felfejlesztés vizsgálat"

#: ../iw/examine_gui.py:59
#, python-format
msgid "_Install %s"
msgstr "%s tele_pítése"

#: ../iw/examine_gui.py:61
msgid ""
"Choose this option to freshly install your system. Existing software and "
"data may be overwritten depending on your configuration choices."
msgstr ""
"Válassza ezt a lehetőséget, ha új rendszert szeretne. Az egyéb "
"beállításoktól függően a meglévő szoftvereket és fájlokat felülírom."

#: ../iw/examine_gui.py:65
msgid "_Upgrade an existing installation"
msgstr "Meglévő rendszer _felfejlesztése"

#: ../iw/examine_gui.py:67
#, python-format
msgid ""
"Choose this option if you would like to upgrade your existing %s system.  "
"This option preserves the existing data on your drives."
msgstr ""
"Ha meglévő %s rendszert szeretne felfejleszteni, akkor válassza ezt a "
"lehetőséget.  Ez megtartja az eszközökön levő adatokat."

#: ../iw/examine_gui.py:116
msgid "The following installed system will be upgraded:"
msgstr "A következő telepített rendszert fogom felfejleszteni:"

#: ../iw/examine_gui.py:129
msgid "Unknown Linux system"
msgstr "Ismeretlen Linux rendszer"

#: ../iw/language_gui.py:33 ../textw/language_text.py:46
msgid "Language Selection"
msgstr "Nyelv kiválasztása"

#: ../iw/language_gui.py:81 ../textw/language_text.py:47 ../loader/lang.c:376
msgid "What language would you like to use during the installation process?"
msgstr "Melyik nyelvet szeretné használni a telepítéskor?"

#: ../iw/lvm_dialog_gui.py:120 ../iw/lvm_dialog_gui.py:166
#: ../iw/lvm_dialog_gui.py:178 ../iw/lvm_dialog_gui.py:217
#: ../iw/lvm_dialog_gui.py:293 ../iw/lvm_dialog_gui.py:613
msgid "Not enough space"
msgstr "Nincs elég szabad hely"

#: ../iw/lvm_dialog_gui.py:121
msgid ""
"The physical extent size cannot be changed because otherwise the space "
"required by the currently defined logical volumes will be increased to more "
"than the available space."
msgstr ""
"A fizikai darab méret nem változtatható meg, mert akkor a már meglévő "
"logikai kötetek mérete meghaladná a rendelkezésre álló helyet."

#: ../iw/lvm_dialog_gui.py:130
msgid "Confirm Physical Extent Change"
msgstr "Fizikai darab méret változtatás megerősítése"

#: ../iw/lvm_dialog_gui.py:131
msgid ""
"This change in the value of the physical extent will require the sizes of "
"the current logical volume requests to be rounded up in size to an integer "
"multiple of the physical extent.\n"
"\n"
"This change will take effect immediately."
msgstr ""
"Fizikai darab értékének megváltozása megköveteli, hogy a már meglevő logikai "
"kötet kérelmek mérete a fizikai kiterjedés méretének egész számú "
"többszörösére legyen felkerekítve.\n"
"\n"
"A változás azonnal érvénybe lép."

#: ../iw/lvm_dialog_gui.py:140 ../iw/lvm_dialog_gui.py:200
msgid "C_ontinue"
msgstr "F_olytatás"

#: ../iw/lvm_dialog_gui.py:167
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected (%"
"10.2f MB) is larger than the smallest physical volume (%10.2f MB) in the "
"volume group."
msgstr ""
"Fizikai darab méret nem változtatható meg, mert a választott érték (%10.2f "
"MB) nagyobb, mint a legkisebb fizikai kötet (%10.2f MB) a kötet csoportban."

#: ../iw/lvm_dialog_gui.py:179
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected (%"
"10.2f MB) is too large compared to the size of the smallest physical volume "
"(%10.2f MB) in the volume group."
msgstr ""
"Fizikai darab méret nem változtatható meg, mert a választott érték (%10.2f "
"MB) túl nagy a legkisebb fizikai kötethez (%10.2f MB) viszonyítva a "
"kötetcsoportban."

#: ../iw/lvm_dialog_gui.py:193
msgid "Too small"
msgstr "Túl kicsi"

#: ../iw/lvm_dialog_gui.py:194
msgid ""
"This change in the value of the physical extent will waste substantial space "
"on one or more of the physical volumes in the volume group."
msgstr ""
"Ha erre az értékre változtatja a fizikai darab méret, akkor a kötet "
"csoporton belül legalább egy fizikai köteten jelentős helyet pocsékol el."

#: ../iw/lvm_dialog_gui.py:218
#, python-format
msgid ""
"The physical extent size cannot be changed because the resulting maximum "
"logical volume size (%10.2f MB) is smaller than one or more of the currently "
"defined logical volumes."
msgstr ""
"Fizikai darab méret nem változtatható meg, mert ezzel a maximális logikai "
"kötet méret (%10.2f MB) kisebb lenne, mint az egyik létező logikai kötet "
"mérete."

#: ../iw/lvm_dialog_gui.py:294
msgid ""
"You cannot remove this physical volume because otherwise the volume group "
"will be too small to hold the currently defined logical volumes."
msgstr ""
"E fizikai kötet nem távolítható el, mert akkor a logikai kötetcsoport túl "
"kicsi lenne ahhoz, hogy elférjenek rajta a most megadott logikai kötetek."

#: ../iw/lvm_dialog_gui.py:371
msgid "Make Logical Volume"
msgstr "Logikai kötet teremtése"

#: ../iw/lvm_dialog_gui.py:373
#, python-format
msgid "Edit Logical Volume: %s"
msgstr "Logikai kötet szerkesztése: %s"

#: ../iw/lvm_dialog_gui.py:407 ../iw/partition_dialog_gui.py:306
#: ../iw/raid_dialog_gui.py:364
msgid "_Mount Point:"
msgstr "_Csatoló pont:"

#: ../iw/lvm_dialog_gui.py:415 ../iw/raid_dialog_gui.py:373
msgid "_File System Type:"
msgstr "_Fájl rendszer típus:"

#: ../iw/lvm_dialog_gui.py:425 ../iw/raid_dialog_gui.py:383
msgid "Original File System Type:"
msgstr "Eredeti fájl rendszer típus:"

#: ../iw/lvm_dialog_gui.py:430 ../iw/raid_dialog_gui.py:388
msgid "Unknown"
msgstr "Ismeretlen"

#: ../iw/lvm_dialog_gui.py:436 ../iw/partition_dialog_gui.py:351
#: ../iw/raid_dialog_gui.py:394
msgid "Original File System Label:"
msgstr "Eredeti fájl rendszer címke:"

#: ../iw/lvm_dialog_gui.py:444
msgid "_Logical Volume Name:"
msgstr "_Logikai kötet név:"

#: ../iw/lvm_dialog_gui.py:452
msgid "Logical Volume Name:"
msgstr "Logikai kötet név:"

#: ../iw/lvm_dialog_gui.py:460 ../iw/partition_dialog_gui.py:361
msgid "_Size (MB):"
msgstr "Mé_ret (MB):"

#: ../iw/lvm_dialog_gui.py:465
msgid "Size (MB):"
msgstr "Méret (MB):"

#: ../iw/lvm_dialog_gui.py:474
#, python-format
msgid "(Max size is %s MB)"
msgstr "(Max. méret %s MB)"

#: ../iw/lvm_dialog_gui.py:495 ../iw/partition_dialog_gui.py:413
#: ../iw/partition_ui_helpers_gui.py:322 ../iw/raid_dialog_gui.py:345
msgid "_Encrypt"
msgstr "_Titkosítás"

#: ../iw/lvm_dialog_gui.py:540
msgid "Illegal Logical Volume Name"
msgstr "Tiltott logikai kötet név"

#: ../iw/lvm_dialog_gui.py:555
msgid "Illegal logical volume name"
msgstr "Tiltott logikai kötet név"

#: ../iw/lvm_dialog_gui.py:556
#, python-format
msgid "The logical volume name \"%s\" is already in use. Please pick another."
msgstr "„%s” logikai kötet nevet már használják. Kérem válasszon másikat."

#: ../iw/lvm_dialog_gui.py:584
msgid "Mount point in use"
msgstr "Használt csatoló pont"

#: ../iw/lvm_dialog_gui.py:585
#, python-format
msgid "The mount point \"%s\" is in use. Please pick another."
msgstr "„%s” csatoló pontot már használják. Kérem válasszon másikat."

#: ../iw/lvm_dialog_gui.py:600
msgid "Illegal size"
msgstr "Tiltott méret"

#: ../iw/lvm_dialog_gui.py:601
msgid "The requested size as entered is not a valid number greater than 0."
msgstr "A megadott méret érvényes pozitív szám kell lengyen."

#: ../iw/lvm_dialog_gui.py:614
#, python-format
msgid ""
"The current requested size (%10.2f MB) is larger than the maximum logical "
"volume size (%10.2f MB). To increase this limit you can create more Physical "
"Volumes from unpartitioned disk space and add them to this Volume Group."
msgstr ""
"A kért méret (%10.2f MB) nagyobb, mint a maximális logikai kötet méret (%"
"10.2f MB). Ha szeretné növelni ez utóbbi korlátot, akkor csináljon további "
"fizikai kötetet a még fel nem osztott helyen, és adja azt hozzá e "
"kötetcsoporthoz."

#: ../iw/lvm_dialog_gui.py:708
msgid "No free slots"
msgstr "Nincs üres aljazat"

#: ../iw/lvm_dialog_gui.py:709
#, python-format
msgid "You cannot create more than %s logical volumes per volume group."
msgstr "Egy kötet csoportban legfeljebb %s logikai kötet lehet."

#: ../iw/lvm_dialog_gui.py:715
msgid "No free space"
msgstr "Nincs szabad hely"

#: ../iw/lvm_dialog_gui.py:716
msgid ""
"There is no room left in the volume group to create new logical volumes. To "
"add a logical volume you must reduce the size of one or more of the "
"currently existing logical volumes"
msgstr ""
"Nem maradt hely a kötetcsoportban új logikai kötet létrehozásához. Logikai "
"kötet hozzáadásához legalább az egyik meglévő logikai kötet méretét le kell "
"csökkenteni."

#: ../iw/lvm_dialog_gui.py:748
#, python-format
msgid "Are you sure you want to delete the logical volume \"%s\"?"
msgstr "Biztosan törölni szeretné „%s” logikai kötetet?"

#: ../iw/lvm_dialog_gui.py:861
msgid "Invalid Volume Group Name"
msgstr "Érvénytelen kötet csoport név"

#: ../iw/lvm_dialog_gui.py:870
msgid "Name in use"
msgstr "Név használatban"

#: ../iw/lvm_dialog_gui.py:871
#, python-format
msgid "The volume group name \"%s\" is already in use. Please pick another."
msgstr "„%s” kötet csoport nevet már használják. Kérem válasszon másikat."

#: ../iw/lvm_dialog_gui.py:1095
msgid "Not enough physical volumes"
msgstr "Nincs elég fizikai kötet"

#: ../iw/lvm_dialog_gui.py:1096
msgid ""
"At least one unused physical volume partition is needed to create an LVM "
"Volume Group.\n"
"\n"
"Create a partition or RAID array of type \"physical volume (LVM)\" and then "
"select the \"LVM\" option again."
msgstr ""
"Legalább egy nem használt fizikai kötet rész szükséges LVM kötetcsoport "
"teremtéséhez.\n"
"\n"
"Teremtsen egy „fizikai kötet (LVM)” típusú részt vagy egy RAID csoportot "
"majd válassza újból az „LVM” opciót."

#: ../iw/lvm_dialog_gui.py:1107
msgid "Make LVM Volume Group"
msgstr "LVM kötet csoport teremtése"

#: ../iw/lvm_dialog_gui.py:1110
#, python-format
msgid "Edit LVM Volume Group: %s"
msgstr "LVM kötet csoport szerkesztése: %s"

#: ../iw/lvm_dialog_gui.py:1112
msgid "Edit LVM Volume Group"
msgstr "LVM kötet csoport szerkesztése"

#: ../iw/lvm_dialog_gui.py:1128
msgid "_Volume Group Name:"
msgstr "Kötet cso_port név:"

#: ../iw/lvm_dialog_gui.py:1136
msgid "Volume Group Name:"
msgstr "Kötet csoport név:"

#: ../iw/lvm_dialog_gui.py:1144
msgid "_Physical Extent:"
msgstr "_Fizikai darab:"

#: ../iw/lvm_dialog_gui.py:1159
msgid "Physical Volumes to _Use:"
msgstr "_Használandó fizikai kötetek:"

#: ../iw/lvm_dialog_gui.py:1165
msgid "Used Space:"
msgstr "Felhasznált hely:"

#: ../iw/lvm_dialog_gui.py:1182
msgid "Free Space:"
msgstr "Szabad hely:"

#: ../iw/lvm_dialog_gui.py:1200
msgid "Total Space:"
msgstr "Összes hely:"

#: ../iw/lvm_dialog_gui.py:1235
msgid "Logical Volume Name"
msgstr "Logikai kötet név"

#: ../iw/lvm_dialog_gui.py:1238 ../iw/partition_gui.py:366
#: ../iw/upgrade_swap_gui.py:140 ../textw/upgrade_text.py:118
msgid "Mount Point"
msgstr "Csatoló pont"

#: ../iw/lvm_dialog_gui.py:1241 ../iw/partition_gui.py:371
msgid "Size (MB)"
msgstr "Méret (MB)"

#: ../iw/lvm_dialog_gui.py:1255 ../iw/osbootwidget.py:94
msgid "_Add"
msgstr "_Hozzáadás"

#: ../iw/lvm_dialog_gui.py:1258 ../iw/osbootwidget.py:98
#: ../iw/partition_gui.py:1332
msgid "_Edit"
msgstr "_Szerkesztés"

#: ../iw/lvm_dialog_gui.py:1273
msgid "_Logical Volumes"
msgstr "_Logikai kötetek"

#: ../iw/netconfig_dialog.py:193 ../textw/netconfig_text.py:36
#, python-format
msgid ""
"An error occurred converting the value entered for \"%s\":\n"
"%s"
msgstr ""
"„%s” mezőben megadott adatot átalakítván hiba történt:\n"
"%s"

#: ../iw/netconfig_dialog.py:195 ../iw/netconfig_dialog.py:204
#: ../textw/netconfig_text.py:35 ../textw/netconfig_text.py:40
msgid "Error With Data"
msgstr "Hibás adat"

#: ../iw/netconfig_dialog.py:203
#, python-format
msgid "A value is required for the field %s."
msgstr "Meg kell adni egy értéket „%s” mezőnek."

#: ../iw/netconfig_dialog.py:213
#, python-format
msgid "An error occurred trying to bring up the %s network interface."
msgstr "%s hálózati csatolót bekapcsolván hiba történt."

#: ../iw/netconfig_dialog.py:215
msgid "Error Configuring Network"
msgstr "Hálózat beállítás hiba"

#: ../iw/netconfig_dialog.py:237
msgid "Dynamic IP"
msgstr "Változó IP cím"

#: ../iw/netconfig_dialog.py:238
#, python-format
msgid "Sending request for IP information for %s..."
msgstr "%s IP adatainak lekérdezése..."

#: ../iw/netconfig_dialog.py:253 ../iw/netconfig_dialog.py:256
#: ../textw/netconfig_text.py:214 ../textw/netconfig_text.py:217
msgid "IP Address"
msgstr "IP cím"

#: ../iw/netconfig_dialog.py:263 ../textw/netconfig_text.py:224
msgid "IPv4 CIDR prefix must be between 0 and 32."
msgstr "IPv4 CIDR előtag 0 és 32 közé kell essen."

#: ../iw/netconfig_dialog.py:264 ../iw/netconfig_dialog.py:270
#: ../iw/netconfig_dialog.py:278 ../iw/netconfig_dialog.py:281
#: ../textw/netconfig_text.py:225 ../textw/netconfig_text.py:231
#: ../textw/netconfig_text.py:239
msgid "IPv4 Network Mask"
msgstr "IPv4 hálózati maszk"

#: ../iw/netconfig_dialog.py:291 ../textw/netconfig_text.py:252
msgid "Gateway"
msgstr "Átjáró"

#: ../iw/netconfig_dialog.py:301 ../textw/netconfig_text.py:262
msgid "Nameserver"
msgstr "Névkiszolgáló"

#: ../iw/netconfig_dialog.py:310
msgid "Error configuring network device:"
msgstr "Hiba a hálózati eszközt beállítván:"

#: ../iw/network_gui.py:60 ../iw/network_gui.py:66
msgid "Error with Hostname"
msgstr "Hibás gazda név"

#: ../iw/network_gui.py:61
msgid "You must enter a valid hostname for this computer."
msgstr "Érvényes gazda nevet kell adni e számítógépnek."

#: ../iw/network_gui.py:67
#, python-format
msgid ""
"The hostname \"%s\" is not valid for the following reason:\n"
"\n"
"%s"
msgstr ""
"A megadott „%s” gazda név érvénytelen az alábbi ok miatt:\n"
"\n"
"%s"

#: ../iw/osbootwidget.py:49
msgid "Boot loader operating system list"
msgstr "Rendszerindító operációs rendszer lista"

#: ../iw/osbootwidget.py:65
msgid "Default"
msgstr "Alapértelmezés"

#: ../iw/osbootwidget.py:65 ../iw/partition_gui.py:365
msgid "Label"
msgstr "Címke"

#: ../iw/osbootwidget.py:65 ../iw/partition_gui.py:364
msgid "Device"
msgstr "Eszköz"

#: ../iw/osbootwidget.py:128
msgid "Image"
msgstr "Kép"

#: ../iw/osbootwidget.py:135
msgid ""
"Enter a label for the boot loader menu to display. The device (or hard drive "
"and partition number) is the device from which it boots."
msgstr ""
"Adja meg a rendszerindító menüben megjelenítendő címkét. A megadott "
"eszközről (vagy merevlemez és rész számról) indul majd a rendszer."

#: ../iw/osbootwidget.py:143
msgid "_Label"
msgstr "_Címke"

#: ../iw/osbootwidget.py:151
msgid "_Device"
msgstr "Esz_köz"

#: ../iw/osbootwidget.py:181
msgid "Default Boot _Target"
msgstr "Alapértelme_zett rendszerindító cél"

#: ../iw/osbootwidget.py:210
msgid "You must specify a label for the entry"
msgstr "Meg kell adni egy címkét a bejegyzéshez"

#: ../iw/osbootwidget.py:219
msgid "Boot label contains illegal characters"
msgstr "A rendszerindító címke tiltott jeleket tartalmaz"

#: ../iw/osbootwidget.py:243
msgid "Duplicate Label"
msgstr "Ismételt címke"

#: ../iw/osbootwidget.py:244
msgid "This label is already in use for another boot entry."
msgstr "Ezt a címkét egy másik rendszerindító bejegyzés már használja."

#: ../iw/osbootwidget.py:257
msgid "Duplicate Device"
msgstr "Ismételt eszköz"

#: ../iw/osbootwidget.py:258
msgid "This device is already being used for another boot entry."
msgstr "Ezt az eszközt egy másik rendszerindító bejegyzés már használja."

#: ../iw/osbootwidget.py:322
msgid "Cannot Delete"
msgstr "Nem lehet törölni"

#: ../iw/osbootwidget.py:323
#, python-format
msgid ""
"This boot target cannot be deleted because it is for the %s system you are "
"about to install."
msgstr ""
"Ez a rendszerindító bejegyzés nem törölhető, mert a most telepítendő %s "
"rendszerhez tartozik."

#: ../iw/partition_dialog_gui.py:57
msgid "Additional Size Options"
msgstr "További méret lehetőségek"

#: ../iw/partition_dialog_gui.py:62
msgid "_Fixed size"
msgstr "_Rögzített méret"

#: ../iw/partition_dialog_gui.py:64
msgid "Fill all space _up to (MB):"
msgstr "Összes hely kitöltése _eddig (MB):"

#: ../iw/partition_dialog_gui.py:74
msgid "Fill to maximum _allowable size"
msgstr "Kitöltés a max. _megengedett méretig"

#: ../iw/partition_dialog_gui.py:276
msgid "Add Partition"
msgstr "Rész hozzáadása"

#: ../iw/partition_dialog_gui.py:278
#, python-format
msgid "Edit Partition: %s"
msgstr "%s rész szerkesztése"

#: ../iw/partition_dialog_gui.py:315
msgid "File System _Type:"
msgstr "Fájl rendszer _típus:"

#: ../iw/partition_dialog_gui.py:331
msgid "Allowable _Drives:"
msgstr "Engedélyezett e_szközök:"

#: ../iw/partition_dialog_gui.py:400
msgid "Force to be a _primary partition"
msgstr "Kényszerített első_dleges rész legyen"

# drivetext = _("Drive %s (Geom: %s/%s/%s) "
#                          "(Model: %s)") % ('/dev/' + drive,
#: ../iw/partition_gui.py:317
#, python-format
msgid "Drive %s (Geom: %s/%s/%s) (Model: %s)"
msgstr "%s eszköz (geom.: %s/%s/%s) (modell: %s)"

#: ../iw/partition_gui.py:322
#, python-format
msgid "Drive %s (%-0.f MB) (Model: %s)"
msgstr "%s eszköz (%-0.f MB) (modell: %s)"

#: ../iw/partition_gui.py:367
msgid "Type"
msgstr "Típus"

#: ../iw/partition_gui.py:370
msgid "Format"
msgstr "Kialakítás"

#: ../iw/partition_gui.py:408
msgid ""
"Mount Point/\n"
"RAID/Volume"
msgstr ""
"Csatoló pont/\n"
"RAID/kötet"

#: ../iw/partition_gui.py:410
msgid ""
"Size\n"
"(MB)"
msgstr ""
"Méret\n"
"(MB)"

#: ../iw/partition_gui.py:522
msgid "Partitioning"
msgstr "Felosztás"

#: ../iw/partition_gui.py:612
msgid ""
"The partitioning scheme you requested caused the following critical errors."
msgstr "A kért felosztás séma a következő kritikus hibákat okozta:"

#: ../iw/partition_gui.py:614
#, python-format
msgid ""
"You must correct these errors before you continue your installation of %s."
msgstr "E hibákat ki kell javítani, mielőtt folytatná %s telepítését."

#: ../iw/partition_gui.py:620
msgid "Partitioning Errors"
msgstr "Felosztás hibák"

#: ../iw/partition_gui.py:627
msgid "The partitioning scheme you requested generated the following warnings."
msgstr "A kért felosztás séma a következő figyelmeztetéseket idézte elő:"

#: ../iw/partition_gui.py:629
msgid "Would you like to continue with your requested partitioning scheme?"
msgstr "Tovább szeretne lépni a kért felosztás sémával?"

#: ../iw/partition_gui.py:634
msgid "Partitioning Warnings"
msgstr "Felosztás figyelmeztetések"

#: ../iw/partition_gui.py:655
msgid "Format Warnings"
msgstr "Kialakítás figyelmeztetések"

#: ../iw/partition_gui.py:660
msgid "_Format"
msgstr "_Kialakítás"

#: ../iw/partition_gui.py:686
msgid "LVM Volume Groups"
msgstr "LVM kötet csoportok"

#: ../iw/partition_gui.py:733
msgid "RAID Devices"
msgstr "RAID eszközök"

#: ../iw/partition_gui.py:800 ../loader/hdinstall.c:231
msgid "Hard Drives"
msgstr "Merevlemezek"

#: ../iw/partition_gui.py:895
msgid "Extended"
msgstr "Kibővített"

#: ../iw/partition_gui.py:897
msgid "software RAID"
msgstr "szoftver RAID"

#: ../iw/partition_gui.py:929
msgid "Free"
msgstr "Szabad"

#: ../iw/partition_gui.py:1022 ../storage/partitioning.py:174
#: ../storage/partitioning.py:207
msgid "Error Partitioning"
msgstr "Hiba a felosztáskor"

#: ../iw/partition_gui.py:1023
#, python-format
msgid "Could not allocate requested partitions: %s."
msgstr "Nem sikerült lefoglalni a kért részeket: %s."

#: ../iw/partition_gui.py:1032
#, python-format
msgid "Warning: %s."
msgstr "Figyelmeztetés: %s."

#: ../iw/partition_gui.py:1062 ../iw/partition_gui.py:1069
msgid "Unable To Edit"
msgstr "Nem lehet szerkeszteni"

#: ../iw/partition_gui.py:1063
msgid "You must select a device to edit"
msgstr "Ki kell választani a szerkeszteni kívánt eszközt"

#: ../iw/partition_gui.py:1070
#, python-format
msgid ""
"You cannot edit this device:\n"
"\n"
"%s"
msgstr ""
"E rész nem szerkeszthető:\n"
"\n"
"%s"

#: ../iw/partition_gui.py:1177 ../iw/partition_gui.py:1189
msgid "Not supported"
msgstr "Nem támogatott"

#: ../iw/partition_gui.py:1178
msgid "LVM is NOT supported on this platform."
msgstr "LVM nem támogatott ezen a platformon."

#: ../iw/partition_gui.py:1190
msgid "Software RAID is NOT supported on this platform."
msgstr "Szoftver RAID nem támogatott ezen a platformon."

#: ../iw/partition_gui.py:1197
msgid "No RAID minor device numbers available"
msgstr "Nem áll rendelkezésre kis eszköz szám (minor device number)."

#: ../iw/partition_gui.py:1198
msgid ""
"A software RAID device cannot be created because all of the available RAID "
"minor device numbers have been used."
msgstr ""
"Nem lehet szoftver RAID eszközt teremteni, mert az összes felhasználható kis "
"eszköz szám már foglalt."

#: ../iw/partition_gui.py:1210
msgid "RAID Options"
msgstr "RAID beállítás"

#: ../iw/partition_gui.py:1221
#, python-format
msgid ""
"Software RAID allows you to combine several disks into a larger RAID "
"device.  A RAID device can be configured to provide additional speed and "
"reliability compared to using an individual drive.  For more information on "
"using RAID devices please consult the %s documentation.\n"
"\n"
"You currently have %s software RAID partition(s) free to use.\n"
"\n"
msgstr ""
"Szoftver RAID esetén több lemezt össze lehet vonni egy nagyobb RAID "
"eszközbe.  RAID eszköz az külön álló lemezekhez képest nagyobb sebességet, "
"és megbízhatóságot biztosítanak.  RAID eszközök használatával kapcsolatban "
"olvassa el a %s dokumentációt.\n"
"\n"
"Jelenleg %s szoftver RAID rész áll rendelkezésre.\n"
"\n"

#: ../iw/partition_gui.py:1232
msgid ""
"To use RAID you must first create at least two partitions of type 'software "
"RAID'.  Then you can create a RAID device that can be formatted and "
"mounted.\n"
"\n"
msgstr ""
"RAID használatához először csinálni kell legalább két „szoftver RAID” típusú "
"részt.  Majd teremteni kell egy RAID eszközt, ami kialakítható és "
"becsatolható.\n"
"\n"

#: ../iw/partition_gui.py:1238
msgid "What do you want to do now?"
msgstr "Most mit szeretne tenni?"

#: ../iw/partition_gui.py:1247
msgid "Create a software RAID _partition."
msgstr "Szoftver RAID _részt szeretnék teremteni."

#: ../iw/partition_gui.py:1250
#, python-format
msgid "Create a RAID _device [default=/dev/md%s]."
msgstr "RAID _eszközt szeretnék teremteni [alapértelmezés=/dev/md%s]."

#: ../iw/partition_gui.py:1254
#, python-format
msgid "Clone a _drive to create a RAID device [default=/dev/md%s]."
msgstr ""
"Másolni szeretnék egy e_szközt, hogy RAID eszközt teremtsek [alapértelmezés=/"
"dev/md%s]."

#: ../iw/partition_gui.py:1296
msgid "Couldn't Create Drive Clone Editor"
msgstr "Nem sikerült eszköz másolás szerkesztőt létrehozni"

#: ../iw/partition_gui.py:1297
msgid "The drive clone editor could not be created for some reason."
msgstr ""
"Valamilyen ok miatt nem sikerült eszköz másolás szerkesztőt létrehozni."

#: ../iw/partition_gui.py:1331
msgid "Ne_w"
msgstr "Ú_j"

#: ../iw/partition_gui.py:1334
msgid "Re_set"
msgstr "_Visszaállítás"

#: ../iw/partition_gui.py:1335
msgid "R_AID"
msgstr "R_AID"

#: ../iw/partition_gui.py:1336
msgid "_LVM"
msgstr "_LVM"

#: ../iw/partition_gui.py:1377
msgid "Hide RAID device/LVM Volume _Group members"
msgstr "RAID eszköz/LVM kötet csoport tagok elrejtése"

#: ../iw/partition_ui_helpers_gui.py:106 ../iw/partition_ui_helpers_gui.py:128
#: ../iw/partition_ui_helpers_gui.py:130
msgid "<Not Applicable>"
msgstr "<Nem jellemző>"

#: ../iw/partition_ui_helpers_gui.py:306
msgid "_Format as:"
msgstr "_Kialakítás mint:"

#: ../iw/partition_ui_helpers_gui.py:325
msgid "Mi_grate filesystem to:"
msgstr "Fájlrendszer át_alakítása:"

#: ../iw/partition_ui_helpers_gui.py:351 tmp/autopart.glade.h:9
msgid "_Resize"
msgstr "Át_méretezés"

#: ../iw/partition_ui_helpers_gui.py:409
#, python-format
msgid ""
"Partitions of type '%s' must be constrained to a single drive.  To do this, "
"select the drive in the 'Allowable Drives' checklist."
msgstr ""
"„%s” típusú részeket csak egyetlen eszközhöz lehet rendelni.  Az eszközt a "
"„Használható eszközök” listából lehet kiválasztani."

#: ../iw/progress_gui.py:37
msgid "Installing Packages"
msgstr "Csomagok telepítése"

#: ../iw/raid_dialog_gui.py:312
msgid ""
"At least two unused software RAID partitions are needed to create a RAID "
"device.\n"
"\n"
"First create at least two partitions of type \"software RAID\", and then "
"select the \"RAID\" option again."
msgstr ""
"Legalább két szoftver RAID rész szükséges RAID eszköz teremtéséhez.\n"
"\n"
"Először csináljon legalább két „szoftver RAID” részt, majd válassza újból a "
"„RAID” opciót."

#: ../iw/raid_dialog_gui.py:326 ../iw/raid_dialog_gui.py:763
msgid "Make RAID Device"
msgstr "RAID eszköz teremtése"

#: ../iw/raid_dialog_gui.py:329
#, python-format
msgid "Edit RAID Device: %s"
msgstr "%s RAID eszköz szerkesztése"

#: ../iw/raid_dialog_gui.py:331
msgid "Edit RAID Device"
msgstr "RAID eszköz szerkesztése"

#: ../iw/raid_dialog_gui.py:402
msgid "RAID _Device:"
msgstr "RAID _eszköz:"

#: ../iw/raid_dialog_gui.py:420
msgid "RAID _Level:"
msgstr "RAID _szint:"

#: ../iw/raid_dialog_gui.py:462
msgid "_RAID Members:"
msgstr "_RAID tagok:"

#: ../iw/raid_dialog_gui.py:479
msgid "Number of _spares:"
msgstr "_Tartalékok száma:"

#: ../iw/raid_dialog_gui.py:489
msgid "_Format partition?"
msgstr "Rész _kialakítása?"

#: ../iw/raid_dialog_gui.py:563
msgid ""
"The source drive has no partitions to be cloned.  You must first define "
"partitions of type 'software RAID' on this drive before it can be cloned."
msgstr ""
"A forrás eszközön nincs másolható rész.  Másolás előtt „szoftver RAID” "
"típusú részeket kell csinálni az eszközön."

#: ../iw/raid_dialog_gui.py:567 ../iw/raid_dialog_gui.py:573
#: ../iw/raid_dialog_gui.py:587 ../iw/raid_dialog_gui.py:600
msgid "Source Drive Error"
msgstr "Hibás forrás eszköz"

#: ../iw/raid_dialog_gui.py:574
msgid ""
"The source drive you selected has partitions which are not of type 'software "
"RAID'.\n"
"\n"
"You must remove these partitions before this drive can be cloned. "
msgstr ""
"A kijelölt forrás eszközön meglévő részek között nem „szoftver RAID” "
"típusúak is vannak.\n"
"\n"
"Az eszköz másolása csak e részek eltávolítása után lehetséges. "

#: ../iw/raid_dialog_gui.py:588
#, python-format
msgid ""
"The source drive you selected has partitions which are not constrained to "
"the drive %s.\n"
"\n"
"You must remove these partitions or restrict them to this drive before this "
"drive can be cloned. "
msgstr ""
"A kijelölt forrás eszközön van olyan rész, ami nem csak %s eszközre "
"korlátozódik.\n"
"\n"
"E részeket el kell távolítani, vagy erre az eszközre kell korlátozni ahhoz, "
"hogy az eszköz másolható legyen. "

#: ../iw/raid_dialog_gui.py:601
msgid ""
"The source drive you selected has software RAID partition(s) which are "
"members of an active software RAID device.\n"
"\n"
"You must remove these partitions before this drive can be cloned."
msgstr ""
"A kijelölt forrás eszköz tartalmaz szoftver RAID részeket, amik "
"aktívszoftver RAID eszköz tagjai.\n"
"\n"
"E részeket el kell távolítani ahhoz, hogy az eszköz másolható legyen."

#: ../iw/raid_dialog_gui.py:615 ../iw/raid_dialog_gui.py:621
#: ../iw/raid_dialog_gui.py:637
msgid "Target Drive Error"
msgstr "Hibás cél eszköz"

#: ../iw/raid_dialog_gui.py:616
msgid "Please select the target drives for the clone operation."
msgstr "Válasszon cél eszközöket a másolás művelethez."

#: ../iw/raid_dialog_gui.py:622
#, python-format
msgid "The source drive %s cannot be selected as a target drive as well."
msgstr "%s forrás eszköz nem választható ki cél eszköznek is egyszerre."

#: ../iw/raid_dialog_gui.py:638
#, python-format
msgid ""
"The target drive %s has a partition which cannot be removed for the "
"following reason:\n"
"\n"
"\"%s\"\n"
"\n"
"You must remove this partition before this drive can be a target."
msgstr ""
"A %s cél eszköz tartalmaz olyan részt, ami a következő okból nem "
"távolítható el:\n"
"\n"
"„%s”\n"
"\n"
"Csak e rész eltávolítása után jelölhető ki célként az eszköz."

#: ../iw/raid_dialog_gui.py:701
msgid "Please select a source drive."
msgstr "Válasszon forrás eszközt."

#: ../iw/raid_dialog_gui.py:721
#, python-format
msgid ""
"The drive %s will now be cloned to the following drives:\n"
"\n"
msgstr ""
"A %s eszközt a következő eszközökre másolom:\n"
"\n"

#: ../iw/raid_dialog_gui.py:726
msgid ""
"\n"
"\n"
"WARNING! ALL DATA ON THE TARGET DRIVES WILL BE DESTROYED."
msgstr ""
"\n"
"\n"
"FIGYELEM! A CÉL ESZKÖZÖKÖN MEGLÉVŐ ADATOK ELVESZNEK!"

#: ../iw/raid_dialog_gui.py:729
msgid "Final Warning"
msgstr "Utolsó figyelmeztetés"

#: ../iw/raid_dialog_gui.py:731
msgid "Clone Drives"
msgstr "Eszközök másolása"

#: ../iw/raid_dialog_gui.py:740
msgid "There was an error clearing the target drives.  Cloning failed."
msgstr "Hiba történt a cél eszközök törlése közben.  A másolás elbukott."

#: ../iw/raid_dialog_gui.py:773
msgid ""
"Clone Drive Tool\n"
"\n"
"This tool allows you to significantly reduce the amount of effort required "
"to setup RAID arrays.  This tool uses a source drive which has been prepared "
"with the desired partitioning layout, and clones this layout onto other "
"similar sized drives.  Then a RAID device can be created.\n"
"\n"
"NOTE: The source drive must have partitions which are restricted to be on "
"that drive only, and can only contain unused software RAID partitions.  "
"Other partition types are not allowed.\n"
"\n"
"EVERYTHING on the target drive(s) will be destroyed by this process."
msgstr ""
"Tároló eszköz másoló eszköz\n"
"\n"
"Ez az eszköz jelentősen csökkenti a RAID tömbök teremtésére illetve "
"beállítására fordítandó erőfeszítéseket.  Ez az eszköz egy forrás tároló "
"eszközt használ, amin a kívánt felosztást kialakították, és azt a felosztást "
"másolja más hasonló méretű tároló eszközökre.  Akkor RAID eszközt lehet "
"teremteni.\n"
"\n"
"Megjegyzés: A forrás eszköz részei nem nyúlhatnak át más eszközökre, továbbá "
"az eszköz csak felhasználatlan, szoftver RAID típusú részeket tartalmazhat. "
"Más résztípusok nem engedélyezettek.\n"
"\n"
"A folyamat során a cél eszközökön meglévő MINDEN adat elveszik."

#: ../iw/raid_dialog_gui.py:793
msgid "Source Drive:"
msgstr "Forrás eszköz:"

#: ../iw/raid_dialog_gui.py:801
msgid "Target Drive(s):"
msgstr "Cél eszköz(ök):"

#: ../iw/raid_dialog_gui.py:809
msgid "Drives"
msgstr "Eszközök"

#: ../iw/task_gui.py:64
#, python-format
msgid ""
"Unable to read package metadata from repository.  This may be due to a "
"missing repodata directory.  Please ensure that your repository has been "
"correctly generated.\n"
"\n"
"%s"
msgstr ""
"Nem lehet beolvasni a csomagleíró adatokat a tárolóból.  Talán hiányzik egy "
"repodata mappa.  Kérem ellenőrizze, hogy jól készítették-e el a tárolót.\n"
"\n"
"%s"

#: ../iw/task_gui.py:162
#, python-format
msgid ""
"The repository %s has already been added.  Please choose a different "
"repository name and URL."
msgstr ""
"„%s” tárolót már hozzáadta. Kérem válasszon másik tároló nevet és URL-t."

#: ../iw/task_gui.py:175
msgid "Edit Repository"
msgstr "Tároló szerkesztése"

#: ../iw/task_gui.py:238
msgid "Invalid Proxy URL"
msgstr "Érvénytelen proxy URL"

#: ../iw/task_gui.py:239
msgid "You must provide an HTTP, HTTPS, or FTP URL to a proxy."
msgstr "Meg kell adnia egy HTTP, HTTPS vagy FTP URL-t egy proxyhoz."

#: ../iw/task_gui.py:250 ../iw/task_gui.py:388
msgid "Invalid Repository URL"
msgstr "Érvénytelen tároló URL"

#: ../iw/task_gui.py:251 ../iw/task_gui.py:389
msgid "You must provide an HTTP, HTTPS, or FTP URL to a repository."
msgstr "Meg kell adnia egy HTTP, HTTPS vagy FTP URL-t egy tárolóhoz."

#: ../iw/task_gui.py:273 ../iw/task_gui.py:398
msgid "No Media Found"
msgstr "Nem találtam hordozót"

#: ../iw/task_gui.py:274 ../iw/task_gui.py:399
msgid ""
"No installation media was found. Please insert a disc into your drive and "
"try again."
msgstr ""
"Nem találtam telepítő hordozót. Kérem tegyen be egy lemezt, és próbálja újra."

#: ../iw/task_gui.py:293 ../iw/task_gui.py:415
msgid "Please enter an NFS server and path."
msgstr "Kérem adjon meg NFS kiszolgáló nevet és utat."

#: ../iw/task_gui.py:325
msgid "Invalid Repository Name"
msgstr "Érvénytelen tároló név"

#: ../iw/task_gui.py:326
msgid "You must provide a repository name."
msgstr "Meg kell adnia egy tároló nevet."

#: ../iw/task_gui.py:450 tmp/addrepo.glade.h:3
msgid "Add Repository"
msgstr "Tároló hozzáadása"

#: ../iw/task_gui.py:455
msgid "No Software Repos Enabled"
msgstr "Nincs engedélyezett szoftver tároló"

#: ../iw/task_gui.py:456
msgid ""
"You must have at least one software repository enabled to continue "
"installation."
msgstr ""
"Legalább egy szoftver tárolót engedélyezni kell, hogy folytassuk a "
"telepítést."

#: ../iw/timezone_gui.py:63 ../textw/timezone_text.py:96
msgid "Time Zone Selection"
msgstr "Időzóna választás"

#: ../iw/upgrade_bootloader_gui.py:36 ../textw/upgrade_bootloader_text.py:135
msgid "Upgrade Boot Loader Configuration"
msgstr "Rendszerbetöltő beállítások felfejlesztése"

#: ../iw/upgrade_bootloader_gui.py:122
msgid "_Update boot loader configuration"
msgstr "Rendszerbetöltő beállításainak _felfejlesztése"

#: ../iw/upgrade_bootloader_gui.py:123
msgid "This will update your current boot loader."
msgstr "Ez frissíti az aktuális rendszerbetöltőt."

#: ../iw/upgrade_bootloader_gui.py:127 ../textw/upgrade_bootloader_text.py:107
msgid ""
"Due to system changes, your boot loader configuration can not be "
"automatically updated."
msgstr ""
"A rendszerben történt módosítások miatt a rendszerindító beállításai nem "
"frissíthetők automatikusan."

#: ../iw/upgrade_bootloader_gui.py:130 ../textw/upgrade_bootloader_text.py:111
msgid ""
"The installer is unable to detect the boot loader currently in use on your "
"system."
msgstr "A telepítő nem képes érzékelni a most használt rendszerindítót."

#: ../iw/upgrade_bootloader_gui.py:137 ../textw/upgrade_bootloader_text.py:120
#, python-format
msgid ""
"The installer has detected the %s boot loader currently installed on %s."
msgstr "A telepítő %s rendszerbetöltőt talált %s rendszerben."

#: ../iw/upgrade_bootloader_gui.py:141
msgid "This is the recommended option."
msgstr "Ez a javasolt beállítás."

#: ../iw/upgrade_bootloader_gui.py:146
msgid "_Create new boot loader configuration"
msgstr "Ú_j rendszerindító beállítás teremtése"

#: ../iw/upgrade_bootloader_gui.py:148
msgid ""
"This option creates a new boot loader configuration.  If you wish to switch "
"boot loaders, you should choose this."
msgstr ""
"Ezzel új rendszerindító beállítást lehet teremteni.  Ha le szeretné cserélni "
"az eddigi rendszerindítót, válassza ezt."

#: ../iw/upgrade_bootloader_gui.py:155
msgid "_Skip boot loader updating"
msgstr "Rendszerbetöltő frissítés ki_hagyása"

#: ../iw/upgrade_bootloader_gui.py:156
msgid ""
"This option makes no changes to boot loader configuration.  If you are using "
"a third party boot loader, you should choose this."
msgstr ""
"Ebben az esetben nem változik meg a rendszerindító beállítás.  Ha külső "
"forrásból származó rendszerindítót használ, akkor válassza ezt a lehetőséget."

#: ../iw/upgrade_bootloader_gui.py:167
msgid "What would you like to do?"
msgstr "Mit szeretne tenni?"

#: ../iw/upgrade_migratefs_gui.py:38 ../textw/upgrade_text.py:36
msgid "Migrate File Systems"
msgstr "Fájlrendszerek átalakítása"

#: ../iw/upgrade_migratefs_gui.py:70
#, python-format
msgid ""
"This release of %s supports an updated file system, which has several "
"benefits over the file system traditionally shipped in %s.  This "
"installation program can migrate formatted partitions without data loss.\n"
"\n"
"Which of these partitions would you like to migrate?"
msgstr ""
"%s jelen kiadása támogat egy frissebb fájlrendszert, ami több szempontból is "
"előnyösebb hagyományosan %s rendszerekben szállítottaknál.  Ez a telepítő "
"képes a kialakított részeket adatvesztés nélkül átalakítani.\n"
"\n"
"Ezek közül mely részeket szeretné átalakítani?"

#: ../iw/upgrade_swap_gui.py:35
msgid "Upgrade Swap Partition"
msgstr "Lapozó rész felfejlesztése"

#: ../iw/upgrade_swap_gui.py:94 ../textw/upgrade_text.py:101
#, python-format
msgid ""
"Recent kernels (2.4 or newer) need significantly more swap than older "
"kernels, up to twice the amount of RAM on the system.  You currently have %"
"dMB of swap configured, but you may create additional swap space on one of "
"your file systems now."
msgstr ""
"A 2.4-es és újabb Linux rendszermagok nagyobb lapozó területet igényelnek, "
"mint a régebbi változatok - ez elérheti a RAM méretének kétszeresét.  "
"Jelenleg %d MB méretű lapozó van beállítva, de most hozzáadhat további "
"lapozó helyet is valamelyik fájl rendszeren."

#: ../iw/upgrade_swap_gui.py:101
#, python-format
msgid ""
"\n"
"\n"
"The installer has detected %s MB of RAM.\n"
msgstr ""
"\n"
"\n"
"A telepítő %s MB RAM-ot talált a gépben.\n"

#: ../iw/upgrade_swap_gui.py:113
msgid "I _want to create a swap file"
msgstr "Lapo_zó fájlt szeretnék csinálni"

#: ../iw/upgrade_swap_gui.py:122
msgid "Select the _partition to put the swap file on:"
msgstr "E _részre kerüljön a lapozó fájl:"

#: ../iw/upgrade_swap_gui.py:140 ../textw/upgrade_text.py:119
msgid "Partition"
msgstr "Rész"

#: ../iw/upgrade_swap_gui.py:140
msgid "Free Space (MB)"
msgstr "Szabad hely (MB)"

#: ../iw/upgrade_swap_gui.py:158
#, python-format
msgid ""
"A minimum swap file size of %d MB is recommended.  Please enter a size for "
"the swap file:"
msgstr ""
"A lapozó fájlt érdemes legalább %d MB-ra venni.  Kérem adja meg a lapozó "
"fájl méretét:"

#: ../iw/upgrade_swap_gui.py:173
msgid "Swap file _size (MB):"
msgstr "Lap_ozó fájl mérete (MB):"

#: ../iw/upgrade_swap_gui.py:183
msgid "I _don't want to create a swap file"
msgstr "Nem a_karok lapozó fájlt csinálni"

#: ../iw/upgrade_swap_gui.py:193
msgid ""
"A swap file is strongly recommended. Failure to create one could cause the "
"installer to abort abnormally.  Are you sure you wish to continue?"
msgstr ""
"Mindenképpen azt ajánljuk, hogy csináljon egy lapozó fájlt. Ha ezt nem teszi "
"meg, előfordulhat, hogy a telepítő váratlanul le fog állni.  Biztosan "
"folytatni kívánja?"

#: ../iw/upgrade_swap_gui.py:201 ../textw/upgrade_text.py:188
msgid "The swap file must be between 1 and 2000 MB in size."
msgstr "A lapozó fájl méretének 1 és 2000 MB közé kell esnie."

#: ../iw/upgrade_swap_gui.py:208 ../textw/upgrade_text.py:183
msgid ""
"There is not enough space on the device you selected for the swap partition."
msgstr "Nincs elég hely az eszközön a lapozó rész megteremtésére."

#: ../iw/welcome_gui.py:56 ../textw/welcome_text.py:36
msgid "Network Install Required"
msgstr ""

#: ../iw/welcome_gui.py:57 ../textw/welcome_text.py:37
msgid ""
"Your installation source is set to a network location, but no netork devices "
"were found on your system.  To avoid a network installation, boot with the "
"full DVD, full CD set, or do not pass a repo= parameter that specifies a "
"network source."
msgstr ""

#: ../iw/welcome_gui.py:67
msgid "E_xit Installer"
msgstr "_Kilépés a telepítőből"

#: ../iw/zipl_gui.py:37
msgid "z/IPL Boot Loader Configuration"
msgstr "z/IPL rendszerindító beállításai"

#: ../iw/zipl_gui.py:61
msgid "The z/IPL boot loader will be installed on your system."
msgstr "z/IPL rendszerindítót telepít a gépre."

#: ../iw/zipl_gui.py:63
msgid ""
"The z/IPL Boot Loader will now be installed on your system.\n"
"\n"
"The root partition will be the one you selected previously in the partition "
"setup.\n"
"\n"
"The kernel used to start the machine will be the one to be installed by "
"default.\n"
"\n"
"If you wish to make changes later after the installation feel free to change "
"the /etc/zipl.conf configuration file.\n"
"\n"
"You can now enter any additional kernel parameters which your machine or "
"your setup may require."
msgstr ""
"A z/IPL rendszerindító telepítése következik.\n"
"\n"
"A gyökér rész a telepítés korábbi fázisában kijelölt rész lesz.\n"
"\n"
"A rendszer indítása a kiválasztott alapértelmezett rendszermaggal történik.\n"
"\n"
"Ha később, a telepítés után szeretne módosításokat végrehajtani, akkor "
"módosítsa az /etc/zipl.conf beállítás fájlt.\n"
"\n"
"Adja meg azokat a rendszermag-paramétereket, melyek a gép vagy a "
"konfiguráció használatához szükségesek."

#: ../iw/zipl_gui.py:90 ../textw/zipl_text.py:71
msgid "Kernel Parameters"
msgstr "Rendszermag paraméterek"

#: ../iw/zipl_gui.py:93 ../iw/zipl_gui.py:96
msgid "Chandev Parameters"
msgstr "Chandev paraméterek"

#: ../textw/complete_text.py:32
msgid "Reboot"
msgstr "Újraindítás"

#: ../textw/complete_text.py:34
msgid "<Enter> to exit"
msgstr "<Enter>, hogy kilépjen"

#: ../textw/complete_text.py:62
msgid "Complete"
msgstr "Kész"

#: ../textw/constants_text.py:52 ../storage/__init__.py:135
#: ../storage/devicetree.py:78 ../loader/cdinstall.c:452
#: ../loader/driverdisk.c:244 ../loader/driverdisk.c:275
#: ../loader/driverdisk.c:359 ../loader/driverselect.c:81
#: ../loader/driverselect.c:179 ../loader/driverselect.c:205
#: ../loader/hdinstall.c:231 ../loader/hdinstall.c:289 ../loader/kbd.c:138
#: ../loader/loader.c:482 ../loader/loader.c:502 ../loader/loader.c:1378
#: ../loader/loader.c:1409 ../loader/net.c:564 ../loader/net.c:937
#: ../loader/net.c:1808 ../loader/net.c:1830 ../loader/nfsinstall.c:91
#: ../loader/urls.c:292
msgid "Back"
msgstr "Vissza"

#: ../textw/keyboard_text.py:48
msgid "Keyboard Selection"
msgstr "Billentyűzet kiválasztás"

#: ../textw/keyboard_text.py:49
msgid "Which model keyboard is attached to this computer?"
msgstr "Milyen típusú billentyűzet van a géphez kötve?"

#: ../textw/netconfig_text.py:41
#, python-format
msgid "A value is required for the field %s"
msgstr "Érték kell %s mezőnek"

#: ../textw/netconfig_text.py:86 tmp/netconfig.glade.h:9
msgid "Enable network interface"
msgstr "Hálózat csatoló engedélyezése"

#: ../textw/netconfig_text.py:89 tmp/netconfig.glade.h:10
msgid ""
"This requires that you have an active network connection during the "
"installation process.  Please configure a network interface."
msgstr ""
"Ehhez szükséges, hogy a telepítés alatt legyen aktív hálózat kapcsolat.  "
"Kérem állítson be egy hálózat csatolót."

#: ../textw/netconfig_text.py:127
msgid "Use dynamic IP configuration (DHCP)"
msgstr "Változó IP beállítás használata (DHCP)"

#: ../textw/netconfig_text.py:130 ../loader/net.c:542
msgid "Enable IPv4 support"
msgstr "IPv4 támogatás engedélyezése"

#: ../textw/netconfig_text.py:137
msgid "IPv4 Address:"
msgstr "IPv4 cím:"

#: ../textw/netconfig_text.py:157 ../loader/net.c:896
msgid "Gateway:"
msgstr "Átjáró:"

#: ../textw/netconfig_text.py:160
msgid "Nameserver:"
msgstr "Névkiszolgáló:"

#: ../textw/netconfig_text.py:190
msgid "Missing Device"
msgstr "Hiányzó eszköz"

#: ../textw/netconfig_text.py:191
msgid "You must select a network device"
msgstr "Ki kell választani egy hálózat eszközt"

#: ../textw/netconfig_text.py:242
msgid "IPv4 Network Mask "
msgstr "IPv4 hálózat maszk"

#: ../textw/netconfig_text.py:265
msgid "Configuring Network Interfaces"
msgstr "Hálózat csatolók beállítása"

#: ../textw/netconfig_text.py:265
msgid "Waiting for NetworkManager..."
msgstr "Várok a NetworkManagerre..."

#: ../textw/netconfig_text.py:271
msgid "Error configuring network device"
msgstr "Hiba történt a hálózati eszköz beállítása közben."

#: ../textw/netconfig_text.py:271
#, python-format
msgid "Error configuring network device %s"
msgstr "%s hálózati eszközt beállítván hiba történt"

#: ../textw/partition_text.py:58
msgid "Partitioning Type"
msgstr "Felosztás típusa"

#: ../textw/partition_text.py:60 tmp/autopart.glade.h:2
msgid ""
"Installation requires partitioning of your hard drive.  The default layout "
"is suitable for most users.  Select what space to use and which drives to "
"use as the install target. You can also choose to create your own custom "
"layout."
msgstr ""
"A telepítés a merevlemez felosztását igényli.  Az alapértelmezett felosztás "
"megfelel a legtöbb használónak.  Válassza ki, mely helyet használjuk, és "
"mely eszközökre telepítsünk. Választhatja azt is, hogy csinál egy saját "
"egyedi felosztást."

#: ../textw/partition_text.py:76
msgid "Which drive(s) do you want to use for this installation?"
msgstr "Mely eszközöket szeretné használni a telepítéshez?"

#: ../textw/partition_text.py:91
msgid "<Space>,<+>,<-> selection   |   <F2> Add drive   |   <F12> next screen"
msgstr "<Szóköz>,<+>,<->: kijelölés | <F2>: eszköz hozzáadás | <F12>: tovább"

#: ../textw/partition_text.py:165 tmp/adddrive.glade.h:3
msgid "Advanced Storage Options"
msgstr "További tároló lehetőségek"

#: ../textw/partition_text.py:166 tmp/adddrive.glade.h:5
msgid "How would you like to modify your drive configuration?"
msgstr "Hogyan szeretné módosítani az eszköz beállítást?"

#: ../textw/partition_text.py:189
msgid "Add FCP Device"
msgstr "FCP eszköz hozzáadása"

#: ../textw/partition_text.py:190 tmp/zfcp-config.glade.h:5
msgid ""
"zSeries machines can access industry-standard SCSI devices via Fibre Channel "
"(FCP). You need to provide a 16 bit device number, a 64 bit World Wide Port "
"Name (WWPN), and a 64 bit FCP LUN for each device."
msgstr ""
"A zSeries számítógépek hozzá tudnak férni Fibre Channel-ön (FCP) keresztül a "
"szabványos SCSI-eszközökhöz. A következőket kell megadni minden eszközhöz: "
"16 bites eszközszám, 64 bites egyedi portnév (World Wide Port Name, WWPN), "
"64 bites FCP LUN."

#: ../textw/partition_text.py:213 tmp/iscsi-config.glade.h:7
msgid "Configure iSCSI Parameters"
msgstr "iSCSI paraméterek beállítása"

#: ../textw/partition_text.py:214 tmp/iscsi-config.glade.h:8
msgid ""
"To use iSCSI disks, you must provide the address of your iSCSI target and "
"the iSCSI initiator name you've configured for your host."
msgstr ""
"Az iSCSI lemezek használatához meg kell adnia az iSCSI cél eszköz címét és "
"az iSCSI kezdeményező nevét, amit a számítógépen beállított."

#: ../textw/partition_text.py:215
msgid "Target IP Address"
msgstr "Cél IP cím"

#: ../textw/partition_text.py:216
msgid "iSCSI Initiator Name"
msgstr "iSCSI kezdeményező neve"

#: ../textw/partition_text.py:217
msgid "CHAP username"
msgstr "CHAP használó"

#: ../textw/partition_text.py:218
msgid "CHAP password"
msgstr "CHAP jelszó"

#: ../textw/partition_text.py:219
msgid "Reverse CHAP username"
msgstr "Inverz CHAP használó"

#: ../textw/partition_text.py:220
msgid "Reverse CHAP password"
msgstr "Inverz CHAP jelszó"

#: ../textw/progress_text.py:46
msgid "Package Installation"
msgstr "Csomagok telepítése"

#: ../textw/timezone_text.py:75
msgid "In which time zone are you located?"
msgstr "Melyik időzónában tartózkodik?"

#: ../textw/timezone_text.py:93
msgid "System clock uses UTC"
msgstr "UTC rendszer óra"

#: ../textw/upgrade_bootloader_text.py:115
#: ../textw/upgrade_bootloader_text.py:124
msgid "Update boot loader configuration"
msgstr "Rendszerbetöltő beállítás frissítése"

#: ../textw/upgrade_bootloader_text.py:127
msgid "Skip boot loader updating"
msgstr "Rendszerbetöltő frissítés kihagyása"

#: ../textw/upgrade_bootloader_text.py:129
msgid "Create new boot loader configuration"
msgstr "Új rendszerbetöltő beállítás megadása"

#: ../textw/upgrade_text.py:38
#, python-format
msgid ""
"This release of %s supports the an updated file system, which has several "
"benefits over the file system traditionally shipped in %s.  This "
"installation program can migrate formatted partitions without data loss.\n"
"\n"
"Which of these partitions would you like to migrate?"
msgstr ""
"%s jelen kiadása támogat egy frissebb fájlrendszert, ami több szempontból is "
"előnyösebb hagyományosan %s rendszerekben szállítottaknál.  Ez a telepítő "
"képes a kialakított részeket adatvesztés nélkül átalakítani.\n"
"\n"
"Mely részeket szeretné átalakítani?"

#: ../textw/upgrade_text.py:119
msgid "Free Space"
msgstr "Szabad hely"

#: ../textw/upgrade_text.py:137
msgid "RAM detected (MB):"
msgstr "Érzékelt memória (MB):"

#: ../textw/upgrade_text.py:140
msgid "Suggested size (MB):"
msgstr "Javasolt méret (MB):"

#: ../textw/upgrade_text.py:143
msgid "Swap file size (MB):"
msgstr "Lapozó fájl méret (MB):"

#: ../textw/upgrade_text.py:151
msgid "Add Swap"
msgstr "Lapozó hozzáadása"

#: ../textw/upgrade_text.py:176
msgid "The value you entered is not a valid number."
msgstr "A megadott érték nem érvényes szám."

#: ../textw/upgrade_text.py:209
msgid "Reinstall System"
msgstr "Rendszer újratelepítése"

#: ../textw/upgrade_text.py:219
msgid "System to Upgrade"
msgstr "Felfejlesztendő rendszer"

#: ../textw/upgrade_text.py:220
msgid ""
"There seem to be one or more existing Linux installations on your system.\n"
"\n"
"Please choose one to upgrade, or select 'Reinstall System' to freshly "
"install your system."
msgstr ""
"Legalább egy létező Linux-rendszer található a gépen.\n"
"\n"
"Válassza ki a felfejlesztendőt, vagy friss rendszer telepítéséhez válassza "
"„Rendszer újratelepítése” lehetőséget."

#: ../textw/userauth_text.py:30
msgid "Root Password"
msgstr "Rendszergazda jelszó"

#: ../textw/userauth_text.py:33
msgid ""
"Pick a root password. You must type it twice to ensure you know it and do "
"not make a typing mistake. "
msgstr ""
"Válasszon rendszergazda jelszót. A jelszót kétszer kell beírnia, hogy "
"biztosan tudja, és ne gépelje el."

#: ../textw/userauth_text.py:67
msgid "The root password must be at least 6 characters long."
msgstr "Rendszergazda jelszó legalább 6 jel hosszú kell legyen."

#: ../textw/welcome_text.py:29
#, python-format
msgid "%s"
msgstr "%s"

#: ../textw/welcome_text.py:30
#, python-format
msgid ""
"Welcome to %s!\n"
"\n"
msgstr ""
"Üdvözöli %s!\n"
"\n"

#: ../textw/zipl_text.py:35
msgid ""
"The z/IPL Boot Loader will be installed on your system after installation is "
"complete. You can now enter any additional kernel and chandev parameters "
"which your machine or your setup require."
msgstr ""
"A z/IPL rendszerindító lesz feltelepítve a telepítés végén. Most megadhatók "
"a gép illetve a konfiguráció működéséhez szükséges további rendszermag- és "
"chandev-paraméterek."

#: ../textw/zipl_text.py:67
msgid "z/IPL Configuration"
msgstr "z/IPL beállítás"

#: ../textw/zipl_text.py:75 ../textw/zipl_text.py:79
msgid "Chandev line "
msgstr "Chandev sor "

#: ../installclasses/fedora.py:39
msgid "_Fedora"
msgstr "_Fedora"

#: ../installclasses/fedora.py:40 ../installclasses/rhel.py:45
#, python-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage. What additional tasks would you like your system to "
"include support for?"
msgstr ""
"%s alapértelmezett telepítése tartalmaz egy általános internet használathoz "
"készült szoftver csoportot. Milyen további feladatokat szeretne, hogy a "
"rendszer támogasson?"

#: ../installclasses/fedora.py:49
msgid "Office and Productivity"
msgstr "Iroda és termelékenység"

#: ../installclasses/fedora.py:50 ../installclasses/rhel.py:57
#: ../installclasses/rhel.py:62
msgid "Software Development"
msgstr "Szoftver fejlesztés"

#: ../installclasses/fedora.py:51
msgid "Web Server"
msgstr "Web kiszolgáló"

#: ../installclasses/rhel.py:44
msgid "Red Hat Enterprise Linux"
msgstr "Red Hat Enterprise Linux"

#: ../installclasses/rhel.py:54
msgid "Office"
msgstr "Iroda"

#: ../installclasses/rhel.py:55
msgid "Multimedia"
msgstr "Multimédia"

#: ../installclasses/rhel.py:61
msgid "Web server"
msgstr "Webkiszolgáló"

#: ../installclasses/rhel.py:66
msgid "Virtualization"
msgstr "Virtualizáció"

#: ../installclasses/rhel.py:67
msgid "Clustering"
msgstr "Fürtözés"

#: ../installclasses/rhel.py:68
msgid "Storage Clustering"
msgstr "Tároló fürtözés"

#: ../installclasses/rhel.py:72
msgid "Installation Number"
msgstr "Telepítés szám"

#: ../installclasses/rhel.py:73
msgid ""
"To install the full set of supported packages included in your subscription, "
"please enter your Installation Number"
msgstr ""
"Az ön előfizetésében szereplő összes támogatott csomag telepítéséhez adja "
"meg a telepítés számát."

#: ../installclasses/rhel.py:76
msgid ""
"If you're unable to locate the Installation Number, consult http://www."
"redhat.com/apps/support/in.html.\n"
"\n"
"If you skip:\n"
"* You may not get access to the full set of packages included in your "
"subscription.\n"
"* It may result in an unsupported/uncertified installation of Red Hat "
"Enterprise Linux.\n"
"* You will not get software and security updates for packages not included "
"in your subscription."
msgstr ""
"Ha nem találja a telepítés számát, akkor keresse fel a következő weblapot: "
"http://www.redhat.com/apps/support/in.html\n"
"\n"
"Ha kihagyja a lépést:\n"
"* nem férhet hozzá az Ön előfizetésében szereplő összes csomaghoz\n"
"* az nem támogatott/igazolt Red Hat Enterprise Linux telepítést "
"eredményezhet.\n"
"* nem fog szoftvert és biztonsági frissítéseket kapni olyan csomagokhoz, "
"amik nincsenek az előfizetésében."

#: ../storage/__init__.py:81
msgid "Unknown Device"
msgstr "Ismeretlen eszköz"

#: ../storage/__init__.py:82
#, python-format
msgid ""
"The installation source given by device %s could not be found.  Please check "
"your parameters and try again."
msgstr ""
"A %s eszköz telepítő forrást nem találom.  Kérem ellenőrizze a "
"paramétereket, és próbálja újra."

#: ../storage/__init__.py:95
msgid "Installation cannot continue."
msgstr "A telepítés nem folytatható."

#: ../storage/__init__.py:96
msgid ""
"The storage configuration you have chosen has already been activated. You "
"can no longer return to the disk editing screen. Would you like to continue "
"with the installation process?"
msgstr ""
"A választott felosztás opciók már élnek. Már nem léphet vissza a lemez "
"szerkesztő képernyőre. Folytatni szeretné a telepítést?"

#: ../storage/__init__.py:127
msgid "Encrypt device?"
msgstr "Eszköz titkosítása?"

#: ../storage/__init__.py:128
msgid ""
"You specified block device encryption should be enabled, but you have not "
"supplied a passphrase. If you do not go back and provide a passphrase, block "
"device encryption will be disabled."
msgstr ""
"Megadta, hogy a blokk eszköz titkosítás engedélyezett legyen, de nem adott "
"meg jelszót. Ha nem megy vissza megadni egy jelszót, akkor a blokk eszköz "
"titkosítást letiltom."

#: ../storage/__init__.py:146
msgid "Writing storage configuration to disk"
msgstr "Felosztás lemezre írása"

#: ../storage/__init__.py:147
msgid ""
"The partitioning options you have selected will now be written to disk.  Any "
"data on deleted or reformatted partitions will be lost."
msgstr ""
"Az ön által kiválasztott felosztás beállítást most lemezre írom.  A törölt "
"illetve átalakított részeken meglévő adatok elvesznek."

#: ../storage/__init__.py:152
msgid "Go _back"
msgstr "_Vissza"

#: ../storage/__init__.py:153
msgid "_Write changes to disk"
msgstr "Vált_ozások lemezre írása"

#: ../storage/__init__.py:252
msgid "Finding Devices"
msgstr "Eszközök keresése"

#: ../storage/__init__.py:253
msgid "Finding storage devices..."
msgstr ""

#: ../storage/__init__.py:269
msgid "Filesystem error detected, cannot continue."
msgstr ""

#: ../storage/__init__.py:480
msgid "This partition is holding the data for the hard drive install."
msgstr "E rész tartalmazza a merevlemezes telepítéshez szükséges adatokat."

#: ../storage/__init__.py:485
msgid "You cannot delete a partition of a LDL formatted DASD."
msgstr "LDL DASD részt nem lehet törölni."

#: ../storage/__init__.py:491
#, python-format
msgid "This device is part of the RAID device %s."
msgstr "E rész a %s RAID eszközhöz tartozik."

#: ../storage/__init__.py:494
msgid "This device is part of a RAID device."
msgstr "E rész egy RAID eszközhöz tartozik."

#: ../storage/__init__.py:499
#, python-format
msgid "This device is part of the LVM volume group '%s'."
msgstr "Ez az eszköz „%s” LVM kötet csoporthoz tartozik."

#: ../storage/__init__.py:502
msgid "This device is part of a LVM volume group."
msgstr "E rész egy LVM kötetcsoporthoz tartozik."

#: ../storage/__init__.py:511
msgid ""
"This device is an extended partition which contains logical partitions that "
"cannot be deleted:\n"
"\n"
msgstr ""

#: ../storage/__init__.py:751
#, python-format
msgid ""
"You have not defined a root partition (/), which is required for "
"installation of %s to continue."
msgstr "Nem adta meg a gyökér részt (/), ami nélkül %s nem telepíthető."

#: ../storage/__init__.py:756
#, python-format
msgid ""
"Your root partition is less than 250 megabytes which is usually too small to "
"install %s."
msgstr ""
"A gyökér rész mérete kisebb 250 MB-nál, ami általában nem elég %s "
"telepítéséhez."

#: ../storage/__init__.py:762
#, python-format
msgid ""
"Your / partition is less than %s megabytes which is lower than recommended "
"for a normal %s install."
msgstr ""
"A rész kisebb %s megabájtnál, ami kevesebb, mint a normál %s telepítésre "
"ajánlott minimum."

#: ../storage/__init__.py:770
#, python-format
msgid ""
"Your %s partition is less than %s megabytes which is lower than recommended "
"for a normal %s install."
msgstr ""
"%s rész kisebb %s megabájtnál, ami kevesebb, mint a normál %s telepítésre "
"ajánlott minimum."

#: ../storage/__init__.py:797
msgid ""
"Installing on a USB device.  This may or may not produce a working system."
msgstr ""
"Telepítés USB eszközre.  Ez a megoldás működésképtelen rendszert is "
"eredményezhet."

#: ../storage/__init__.py:800
msgid ""
"Installing on a FireWire device.  This may or may not produce a working "
"system."
msgstr ""
"Telepítés FireWire eszközre.  Ez a megoldás működésképtelen rendszert is "
"eredményezhet."

#: ../storage/__init__.py:804
msgid "You have not created a boot partition."
msgstr "Nincs rendszerindító rész."

#: ../storage/__init__.py:808
msgid "Bootable partitions can only be on RAID1 devices."
msgstr "Rendszerindító rész csak RAID1 eszközön lehet."

#: ../storage/__init__.py:813
msgid "Bootable partitions cannot be on a logical volume."
msgstr "Rendszerindító rész nem lehet logikai köteten."

#: ../storage/__init__.py:818
msgid "Bootable partitions cannot be on a RAID device."
msgstr "Rendszerindító rész nem lehet RAID eszközön."

#: ../storage/__init__.py:823 ../storage/__init__.py:828
#, python-format
msgid "Bootable partitions cannot be on an %s filesystem."
msgstr "Rendszerindító rész nem lehet %s fájlrendszeren."

#: ../storage/__init__.py:833
msgid "Bootable partitions cannot be on an encrypted block device"
msgstr "Rendszerindító rész nem lehet titkosított eszközön."

#: ../storage/__init__.py:837
msgid ""
"You have not specified a swap partition.  Although not strictly required in "
"all cases, it will significantly improve performance for most installations."
msgstr ""
"Nem adott meg lapozó részt.  Erre nincs mindig szükség, de a legtöbb esetben "
"jelentősen növelheti a teljesítményt."

#: ../storage/__init__.py:979 ../storage/__init__.py:988
msgid "Dirty File Systems"
msgstr "Piszkos fájlrendszerek"

#: ../storage/__init__.py:980
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Please boot your Linux installation, let the file systems be "
"checked and shut down cleanly to upgrade.\n"
"%s"
msgstr ""
"A következő fájlrendszereket nem tisztán csatolták ki.  Indítsa el a "
"rendszert, hagyja, hogy a fájlrendszerek ellenőrzése megtörténjen, majd "
"tisztán állítsa le a rendszert a felfejlesztés megkezdése előtt.\n"
"%s"

#: ../storage/__init__.py:989
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Would you like to mount them anyway?\n"
"%s"
msgstr ""
"A rendszer következő részeit nem tisztán csatolták ki.  Biztosan be szeretné "
"csatolni őket?\n"
"%s"

#: ../storage/__init__.py:1406
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. To perform an upgrade, please shut "
"down your system rather than hibernating it."
msgstr ""
"     %s\n"
"\n"
"lapozó eszközt az /etc/fstab fájl szerint jelenleg szoftveres "
"felfüggesztéshez használják, ami annyit jelent, hogy a rendszer hibernált "
"állapotban van. A felfejlesztés elvégzéséhez inkább állítsa le a rendszert, "
"ne hibernálja."

#: ../storage/__init__.py:1414
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. If you are performing a new install, "
"make sure the installer is set to format all swap devices."
msgstr ""
"     %s\n"
"\n"
"lapozó eszközt az /etc/fstab fájl szerint jelenleg szoftveres "
"felfüggesztéshez használják, ami annyit jelent, hogy a rendszer hibernált "
"állapotban van. Ha új telepítést végez, győződjön meg arról, hogy a "
"telepítő újra alakítja az összes lapozó területet."

#: ../storage/__init__.py:1428
#, python-format
msgid ""
"Error enabling swap device %s: %s\n"
"\n"
"The /etc/fstab on your upgrade partition does not reference a valid swap "
"device.\n"
"\n"
"Press OK to exit the installer"
msgstr ""
"Hiba történt %s lapozó eszközt engedélyezvén: %s\n"
"\n"
"A felfejlesztendő részen levő /etc/fstab fájl nem hivatkozik érvényes lapozó "
"területre.\n"
"\n"
"Nyomjon OK-t, hogy kilépjen a telepítőből."

#: ../storage/__init__.py:1434
#, python-format
msgid ""
"Error enabling swap device %s: %s\n"
"\n"
"This most likely means this swap device has not been initialized.\n"
"\n"
"Press OK to exit the installer."
msgstr ""
"%s lapozó eszközt engedélyezvén hiba történt: %s\n"
"\n"
"A legvalószínűbb, hogy a lapozó terület még nincs kialakítva.\n"
"\n"
"Nyomjon OK-t, hogy kilépjen a telepítőből."

#: ../storage/__init__.py:1475 ../storage/__init__.py:1485
msgid "Invalid mount point"
msgstr "Érvénytelen becsatoló pont"

#: ../storage/__init__.py:1476
#, python-format
msgid ""
"An error occurred when trying to create %s.  Some element of this path is "
"not a directory. This is a fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"%s megteremtését megkísérelvén hiba történt.  Az elérési út néhány eleme nem "
"mappa. Ez végzetes hiba. A telepítés nem folytatható.\n"
"\n"
"Nyomjon <Enter>-t, hogy kilépjen a telepítőből."

#: ../storage/__init__.py:1486
#, python-format
msgid ""
"An error occurred when trying to create %s: %s.  This is a fatal error and "
"the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"%s megteremtését megkísérelvén hiba történt: %s.  Ez végzetes hiba. A "
"telepítés nem folytatható.\n"
"\n"
"Nyomjon <Enter>-t, hogy kilépjen a telepítőből."

#: ../storage/__init__.py:1499 ../storage/__init__.py:1520
msgid "Unable to mount filesystem"
msgstr "Nem lehet fájlrendszert becsatolni"

#: ../storage/__init__.py:1500
#, python-format
msgid ""
"An error occurred mounting device %s as %s.  You may continue installation, "
"but there may be problems."
msgstr ""
"%s eszközt %s pontra becsatolván hiba történt.  Folytathatja a telepítést, "
"de további hibák léphetnek fel."

#: ../storage/__init__.py:1521
#, python-format
msgid ""
"An error occurred mounting device %s as %s: %s. This is a fatal error and "
"the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"%s eszközt %s típusú részként becsatolván hiba történt: %s. "
"Ez végzetes hiba. A telepítés nem folytatható.\n"
"\n"
"Nyomjon <Enter>-t, hogy kilépjen a telepítőből."

#: ../storage/devices.py:1059
msgid "boot flag not available for this partition"
msgstr "nem lehet rendszerindító jelzés e részhez"

#: ../storage/devicetree.py:87
msgid "Confirm"
msgstr "Megerősítés"

#: ../storage/devicetree.py:88
#, python-format
msgid ""
"Are you sure you want to skip entering a passphrase for device %s?\n"
"\n"
"If you skip this step the device's contents will not be available during "
"installation."
msgstr ""
"Biztosan ki akarja hagyni a jelszó megadását %s eszközhöz?\n"
"\n"
"Ha átugorja e lépést, az eszköz tartalma elérhetetlen lesz a telepítés "
"közben."

#: ../storage/devicetree.py:126
#, python-format
msgid ""
"Error processing drive %s.\n"
"Maybe it needs to be reinitialized.YOU WILL LOSE ALL DATA ON THIS DRIVE!"
msgstr ""

#: ../storage/devicetree.py:151
#, python-format
msgid ""
"Error processing LVM.\n"
"It seems that there is inconsistent LVM data. (%s) make(s) up %s. You can "
"reinitialize all related PVs, which will erase all LVM metadata. Or ignore, "
"which will preserve contents."
msgstr ""

#: ../storage/devicetree.py:159
msgid "_Ignore drive(s)"
msgstr "Eszköz(ök) _mellőzése"

#: ../storage/devicetree.py:160
msgid "_Re-initialize drive(s)"
msgstr "Eszköz(ök) új_ra inicializálása"

#: ../storage/iscsi.py:98 ../storage/iscsi.py:99
msgid "Scanning iSCSI nodes"
msgstr "SCSI elemek lekérése"

#: ../storage/iscsi.py:172 ../storage/iscsi.py:173
msgid "Initializing iSCSI initiator"
msgstr "Az iSCSI kezdeményező inicializálása"

#: ../storage/iscsi.py:208
msgid "iSCSI not available"
msgstr ""

#: ../storage/iscsi.py:210
msgid "No initiator name set"
msgstr "Nincs kezdeményező név beállítva"

#: ../storage/iscsi.py:224
msgid "No iSCSI nodes discovered"
msgstr ""

#: ../storage/iscsi.py:227 ../storage/iscsi.py:228
msgid "Logging in to iSCSI nodes"
msgstr ""

#: ../storage/iscsi.py:250
msgid "No new iSCSI nodes discovered"
msgstr ""

#: ../storage/iscsi.py:253
msgid "Could not log in to any of the discovered nodes"
msgstr ""

#: ../storage/partitioning.py:175
msgid ""
"Could not find enough free space for automatic partitioning, please use "
"another partitioning method."
msgstr ""

#: ../storage/partitioning.py:192
msgid "Warnings During Automatic Partitioning"
msgstr "Figyelmeztetések az önműködő felosztás során"

#: ../storage/partitioning.py:194
#, python-format
msgid ""
"Following warnings occurred during automatic partitioning:\n"
"\n"
"%s"
msgstr ""
"A következő figyelmeztetések jöttek az önműködő felosztás közben:\n"
"\n"
"%s"

#: ../storage/partitioning.py:206 ../storage/partitioning.py:230
msgid ""
"\n"
"\n"
"Press 'OK' to exit the installer."
msgstr ""
"\n"
"\n"
"Nyomjon „OK”-t, hogy kilépjen a telepítőből."

#: ../storage/partitioning.py:208
#, python-format
msgid ""
"Could not allocate requested partitions: \n"
"\n"
"%s.%s"
msgstr ""
"Nem sikerült lefoglalni a kért részeket: \n"
"\n"
"%s.%s"

#: ../storage/partitioning.py:232
msgid ""
"\n"
"\n"
"Press 'OK' to choose a different partitioning option."
msgstr ""
"\n"
"\n"
"Nyomjon „OK” gombot, hogy más felosztó opciót válasszon."

#: ../storage/partitioning.py:234
msgid "Automatic Partitioning Errors"
msgstr "Az automatikus particionálás során fellépett hibák"

#: ../storage/partitioning.py:235
#, python-format
msgid ""
"The following errors occurred with your partitioning:\n"
"\n"
"%s\n"
"\n"
"This can happen if there is not enough space on your hard drive(s) for the "
"installation. %s"
msgstr ""
"A következő hibák jelentkeztek a felosztás miatt:\n"
"\n"
"%s\n"
"\n"
"Ez akkor fordulhat elő, ha nincs elég szabad hely a lemezeken a "
"telepítéshez. %s"

#: ../storage/partitioning.py:246
msgid "Unrecoverable Error"
msgstr "Helyrehozhatatlan hiba"

#: ../storage/partitioning.py:247
msgid "Your system will now be rebooted."
msgstr "A rendszer újraindul."

#: ../storage/zfcp.py:52
msgid "You have not specified a device number or the number is invalid"
msgstr "Nem adott meg eszközszámot, vagy a szám érvénytelen"

#: ../storage/zfcp.py:54
msgid "You have not specified a worldwide port name or the name is invalid."
msgstr "Nem adott meg világraszóló kapunevet, vagy a név érvénytelen."

#: ../storage/zfcp.py:56
msgid "You have not specified a FCP LUN or the number is invalid."
msgstr "Nem adott meg FCP LUN számot, vagy a szám érvénytelen."

#: ../storage/devicelibs/lvm.py:326
#, python-format
msgid "vginfo failed for %s"
msgstr ""

#: ../storage/devicelibs/lvm.py:354
#, python-format
msgid "lvs failed for %s"
msgstr ""

#: ../storage/formats/fs.py:64
msgid "attr dict must include a type"
msgstr ""

#: ../storage/formats/fs.py:111
msgid "filesystem configuration missing a type"
msgstr ""

#: ../storage/formats/fs.py:270
msgid "Formatting"
msgstr "Kialakítás"

#: ../storage/formats/fs.py:271
#, python-format
msgid "Creating filesystem on %s..."
msgstr "Fájlrendszer teremtése %s részen…"

#: ../storage/formats/fs.py:367
msgid "Resizing"
msgstr "Átméretezés"

#: ../storage/formats/fs.py:368
#, python-format
msgid "Resizing filesystem on %s..."
msgstr "Fájlrendszer átméretezése %s részen…"

#: ../storage/formats/fs.py:409
msgid "Checking"
msgstr "Ellenőrzés"

#: ../storage/formats/fs.py:410
#, python-format
msgid "Checking filesystem on %s..."
msgstr "Fájlrendszer ellenőrzése %s részen…"

#: ../loader/cdinstall.c:185 ../loader/cdinstall.c:206
#: ../loader/mediacheck.c:60
msgid "Media Check"
msgstr "Adathordozó ellenőrzése"

#: ../loader/cdinstall.c:185 ../loader/cdinstall.c:188
#: ../loader/cdinstall.c:206 ../loader/cdinstall.c:214 ../loader/method.c:326
msgid "Test"
msgstr "Próba"

#: ../loader/cdinstall.c:185 ../loader/cdinstall.c:189
msgid "Eject Disc"
msgstr "Lemez kiadása"

#: ../loader/cdinstall.c:186
#, c-format
msgid ""
"Choose \"%s\" to test the disc currently in the drive, or \"%s\" to eject "
"the disc and insert another for testing."
msgstr ""
"Válassza „%s” opciót az olvasóban levő lemez ellenőrzéséhez, vagy „%s” "
"opciót a lemez kivételéhez, és újabb tesztelendő lemez behelyezéséhez."

#: ../loader/cdinstall.c:207
#, c-format
msgid ""
"If you would like to test additional media, insert the next disc and press "
"\"%s\". Testing each disc is not strictly required, however it is highly "
"recommended.  Minimally, the discs should be tested prior to using them for "
"the first time. After they have been successfully tested, it is not required "
"to retest each disc prior to using it again."
msgstr ""
"Amennyiben további adathordozót is akar még ellenőrizni, helyezze be a "
"következő lemezt, és nyomjon „%s” gombot. Minden egyes lemez ellenőrzése nem "
"feltétlenül szükséges, azonban ajánlatos. Legalább az első használat előtt "
"érdemes a lemezeket ellenőrizni. Amennyiben már sikeresen ellenőrizték őket, "
"nem szükséges az újra ellenőrizni."

#: ../loader/cdinstall.c:229
#, c-format
msgid ""
"The %s disc was not found in any of your drives. Please insert the %s disc "
"and press %s to retry."
msgstr ""
"%s lemez nincs egyik olvasóban sem. Kérem tegye be %s lemezt, és nyomjon %s "
"gombot, hogy újra próbálja."

#: ../loader/cdinstall.c:248
msgid "Disc Found"
msgstr "Lemez megtalálva"

#: ../loader/cdinstall.c:249
#, c-format
msgid ""
"To begin testing the media before installation press %s.\n"
"\n"
"Choose %s to skip the media test and start the installation."
msgstr ""
"Nyomjon %s gombot, hogy leellenőrizzem az adathordozót.\n"
"\n"
"Válassza %s gombot, hogy kihagyjam az adathordozó ellenőrzését, és kezdjem a "
"telepítést."

#: ../loader/cdinstall.c:339
msgid "Scanning"
msgstr "Beolvasás"

#: ../loader/cdinstall.c:339 ../loader/cdinstall.c:341
#, c-format
msgid "Looking for installation images on CD device %s"
msgstr "Telepítő képeket keresek %s CD eszközön"

#: ../loader/cdinstall.c:442
#, c-format
msgid ""
"The %s disc was not found in any of your CDROM drives. Please insert the %s "
"disc and press %s to retry."
msgstr ""
"Egyik CD-ROM olvasóban sincs %s lemez. Kérem tegyen %s lemezt, és nyomjon %s "
"gombot, hogy újra próbálja."

#: ../loader/cdinstall.c:451
msgid "Disc Not Found"
msgstr "Nincs lemez"

#: ../loader/cdinstall.c:518
msgid "Cannot find kickstart file on CDROM."
msgstr "Nem találtam kickstart fájlt a CD-n."

#: ../loader/copy.c:51 ../loader/method.c:280
#, c-format
msgid "Failed to read directory %s: %m"
msgstr "%s mappát beolvasván hiba történt: %m"

#: ../loader/driverdisk.c:139
msgid "Loading"
msgstr "Betöltés"

#: ../loader/driverdisk.c:139
msgid "Reading driver disk..."
msgstr "Vezérlőprogram lemez olvasása..."

#: ../loader/driverdisk.c:238 ../loader/driverdisk.c:270
msgid "Driver Disk Source"
msgstr "Vezérlőprogram lemez forrás"

#: ../loader/driverdisk.c:239
msgid ""
"You have multiple devices which could serve as sources for a driver disk.  "
"Which would you like to use?"
msgstr ""
"Több olyan eszköz található a gépben, amely vezérlőprogram lemezt "
"tartalmazhat.  Melyiket szeretné használni?"

#: ../loader/driverdisk.c:271
msgid ""
"There are multiple partitions on this device which could contain the driver "
"disk image.  Which would you like to use?"
msgstr ""
"Több olyan rész található ezen az eszközön, amely tartalmazhatja a "
"vezérlőprogram lemez képmását.  Melyiket szeretné használni?"

#: ../loader/driverdisk.c:306
msgid "Failed to mount partition."
msgstr "Nem sikerült becsatolni a részt."

#: ../loader/driverdisk.c:311
msgid "Select driver disk image"
msgstr "Válasszon vezérlő lemez képmást"

#: ../loader/driverdisk.c:312
msgid "Select the file which is your driver disk image."
msgstr "Válassza ki a fájlt, amelyik a vezérlő lemez képmása."

#: ../loader/driverdisk.c:341
msgid "Failed to load driver disk from file."
msgstr "Nem sikerült betölteni a vezérlő képmást a fájlból."

#: ../loader/driverdisk.c:353
#, c-format
msgid "Insert your driver disk into /dev/%s and press \"OK\" to continue."
msgstr ""
"Tegye be a vezérlőprogram lemezt /dev/%s olvasóba, majd nyomjon „OK”-t, hogy "
"folytassam."

#: ../loader/driverdisk.c:359
msgid "Insert Driver Disk"
msgstr "Tegyen be vezérlőprogram lemezt"

#: ../loader/driverdisk.c:372
msgid "Failed to mount driver disk."
msgstr "Nem sikerült becsatolni a vezérlő lemezt."

#: ../loader/driverdisk.c:380
#, c-format
msgid "Driver disk is invalid for this release of %s."
msgstr "%s jelen kiadásában érvénytelen vezérlőprogram lemez."

#: ../loader/driverdisk.c:443
msgid "Manually choose"
msgstr "Kézi kiválasztás"

#: ../loader/driverdisk.c:444
msgid "Load another disk"
msgstr "Másik lemez betöltése"

#: ../loader/driverdisk.c:445
msgid ""
"No devices of the appropriate type were found on this driver disk.  Would "
"you like to manually select the driver, continue anyway, or load another "
"driver disk?"
msgstr ""
"Nincs megfelelő típusú eszköz a vezérlő lemezen.  Kézzel szeretné "
"kiválasztani a vezérlőprogramot, folytatja akárhogy, vagy betölt egy másik "
"vezérlő lemezt?"

#: ../loader/driverdisk.c:483
msgid "Driver disk"
msgstr "Vezérlő lemez"

#: ../loader/driverdisk.c:484
msgid "Do you have a driver disk?"
msgstr "Van vezérlőprogram lemeze?"

#: ../loader/driverdisk.c:493
msgid "More Driver Disks?"
msgstr "Van még vezérlőprogram lemez?"

#: ../loader/driverdisk.c:494
msgid "Do you wish to load any more driver disks?"
msgstr "Szeretne további vezérlő lemezt betölteni?"

#: ../loader/driverdisk.c:539 ../loader/driverdisk.c:576
#: ../loader/hdinstall.c:384 ../loader/kickstart.c:132
#: ../loader/kickstart.c:142 ../loader/kickstart.c:185
#: ../loader/kickstart.c:553 ../loader/modules.c:335 ../loader/modules.c:347
#: ../loader/net.c:1541 ../loader/net.c:1564 ../loader/nfsinstall.c:335
#: ../loader/urlinstall.c:418 ../loader/urlinstall.c:427
#: ../loader/urlinstall.c:436
msgid "Kickstart Error"
msgstr "Kickstart hiba"

#: ../loader/driverdisk.c:540
#, c-format
msgid "Unknown driver disk kickstart source: %s"
msgstr "Ismeretlen vezérlő lemez kickstart forrás: %s"

#: ../loader/driverdisk.c:577
#, c-format
msgid ""
"The following invalid argument was specified for the kickstart driver disk "
"command: %s:%s"
msgstr ""
"A következő érvénytelen argumentum volt megadva a kickstart vezérlő lemez "
"parancsában: %s:%s"

#: ../loader/driverselect.c:67
#, c-format
msgid ""
"Please enter any parameters which you wish to pass to the %s module "
"separated by spaces.  If you don't know what parameters to supply, skip this "
"screen by pressing the \"OK\" button."
msgstr ""
"Kérem adja meg %s modulnak átadni kívánt paramétereket, szóközzel "
"elválasztva.  Ha nem tudja, milyen paraméterekre van szükség, lépjen tovább "
"a következő képernyőre „OK” gombot nyomva."

#: ../loader/driverselect.c:91
msgid "Enter Module Parameters"
msgstr "Modul paraméterek megadása"

#: ../loader/driverselect.c:178
msgid "No drivers found"
msgstr "Nincs vezérlőprogram"

#: ../loader/driverselect.c:178
msgid "Load driver disk"
msgstr "Vezérlő lemez betöltése"

#: ../loader/driverselect.c:179
msgid ""
"No drivers were found to manually insert.  Would you like to use a driver "
"disk?"
msgstr ""
"Nincs kézzel beszúrható vezérlő.  Szeretne vezérlőprogram lemezt használni?"

#: ../loader/driverselect.c:197
msgid ""
"Please select the driver below which you wish to load.  If it does not "
"appear and you have a driver disk, press F2."
msgstr ""
"Kérem válassza ki alább a betöltendő vezérlőprogramot.  Ha nem jelenik meg, "
"és rendelkezik vezérlő lemez, nyomjon F2-t."

#: ../loader/driverselect.c:206
msgid "Specify optional module arguments"
msgstr "Választható modul argumentumok megadása"

#: ../loader/driverselect.c:234
msgid "Select Device Driver to Load"
msgstr "Válassza ki a betöltendő vezérlőprogramot"

#: ../loader/hdinstall.c:144
msgid ""
"An error occured finding the installation image on your hard drive.  Please "
"check your images and try again."
msgstr ""
"Hiba történt a telepítő képet keresvén a merevlemezen.  Kérem ellenőrizze a "
"képeket, és próbálkozzon újra."

#: ../loader/hdinstall.c:232
msgid ""
"You don't seem to have any hard drives on your system! Would you like to "
"configure additional devices?"
msgstr ""
"Úgy tűnik, nincs egyetlen merevlemez vezérlő sem a rendszerben. Kíván "
"további eszközöket beállítani?"

#: ../loader/hdinstall.c:246
#, c-format
msgid ""
"What partition and directory on that partition holds the installation image "
"for %s?  If you don't see the disk drive you're using listed here, press F2 "
"to configure additional devices."
msgstr ""
"Melyik részen, és azon belül melyik mappában van a telepítő képmás a %s "
"rendszerhez?  Ha nem látja a listában a használt lemezt, nyomjon F2-t "
"további eszközök beállításához."

#: ../loader/hdinstall.c:273
msgid "Directory holding image:"
msgstr "Képeket tartalmazó mappa:"

#: ../loader/hdinstall.c:301
msgid "Select Partition"
msgstr "Válasszon részt"

#: ../loader/hdinstall.c:353
#, c-format
msgid "Device %s does not appear to contain an installation image."
msgstr "Úgy tűnik %s eszköz nem tartalmaz telepítő képet."

#: ../loader/hdinstall.c:385
#, c-format
msgid "Bad argument to HD kickstart method command %s: %s"
msgstr "Hibás argumentum %s HD kickstart parancsnál: %s"

#: ../loader/hdinstall.c:455 ../loader/hdinstall.c:511
msgid "Cannot find kickstart file on hard drive."
msgstr "Nincs kickstart fájl a merevlemezen."

#: ../loader/hdinstall.c:498
#, c-format
msgid "Cannot find hard drive for BIOS disk %s"
msgstr "Nincs merevlemez %s BIOS lemezhez"

#: ../loader/kbd.c:136
msgid "Keyboard Type"
msgstr "Billentyűzet típus"

#: ../loader/kbd.c:137
msgid "What type of keyboard do you have?"
msgstr "Milyen típusú billentyűzete van?"

#: ../loader/kickstart.c:133
#, c-format
msgid "Error opening kickstart file %s: %m"
msgstr "%s kickstart fájlt megnyitván hiba történt: %m"

#: ../loader/kickstart.c:143
#, c-format
msgid "Error reading contents of kickstart file %s: %m"
msgstr "%s kickstart fájlt beolvasván hiba történt: %m"

#: ../loader/kickstart.c:186
#, c-format
msgid "Error in %s on line %d of kickstart file %s."
msgstr "%s hibás: %d. sor %s kickstart fájl."

#: ../loader/kickstart.c:285
msgid "Cannot find ks.cfg on removable media."
msgstr "Nincs ks.cfg fájl a cserélhető adathordozón."

#: ../loader/kickstart.c:380
msgid ""
"Unable to download the kickstart file.  Please modify the kickstart "
"parameter below or press Cancel to proceed as an interactive installation."
msgstr ""
"Nem sikerült letölteni a Kickstart-fájlt.  Kérem változtassa meg az alábbi "
"kickstart paramétert, vagy nyomjon Mégsemet, hogy interaktívan folytassuk a "
"telepítést."

#: ../loader/kickstart.c:389
msgid "Error downloading kickstart file"
msgstr "Kickstart fájlt letöltvén hiba történt"

#: ../loader/kickstart.c:554
#, c-format
msgid "Bad argument to shutdown kickstart method command %s: %s"
msgstr "%s lekapcsoló kickstart parancsban a hibás argumentum: %s"

#: ../loader/lang.c:64
#, c-format
msgid "Welcome to %s for %s - Rescue Mode"
msgstr "Üdvözöli %s %s – Mentő mód"

#: ../loader/lang.c:65 ../loader/loader.c:226
msgid ""
"  <Tab>/<Alt-Tab> between elements  | <Space> selects | <F12> next screen "
msgstr ""
" <Tab>/<AltTab> elemek között | <Szóköz> megjelölés | <F12> köv. képernyő "

#: ../loader/lang.c:375
msgid "Choose a Language"
msgstr "Válasszon nyelvet"

#: ../loader/loader.c:127
msgid "Local CD/DVD"
msgstr "Helyi CD/DVD"

#: ../loader/loader.c:128
msgid "Hard drive"
msgstr "Merevlemez"

#: ../loader/loader.c:129
msgid "NFS directory"
msgstr "NFS mappa"

#: ../loader/loader.c:433 ../loader/loader.c:477
msgid "Update Disk Source"
msgstr "Frissítés lemez forrás"

#: ../loader/loader.c:434
msgid ""
"You have multiple devices which could serve as sources for an update disk.  "
"Which would you like to use?"
msgstr ""
"Több eszköz van a rendszerben, ami tartalmazhat frissítés lemezt. Melyiket "
"szeretné használni?"

#: ../loader/loader.c:478
msgid ""
"There are multiple partitions on this device which could contain the update "
"disk image.  Which would you like to use?"
msgstr ""
"Több rész van ezen az eszközön, ami tartalmazhat frissítés lemez képmást.  "
"Melyiket szeretné használni?"

#: ../loader/loader.c:496
#, c-format
msgid "Insert your updates disk into %s and press \"OK\" to continue."
msgstr ""
"Tegye be a frissítés lemezt %s eszközbe, majd nyomjon „OK”-t, hogy "
"folytassam."

#: ../loader/loader.c:502
msgid "Updates Disk"
msgstr "Frissítés lemez"

#: ../loader/loader.c:520
msgid "Failed to mount updates disk"
msgstr "Nem sikerült becsatolni a frissítés lemezt."

#: ../loader/loader.c:525
msgid "Updates"
msgstr "Frissítések"

#: ../loader/loader.c:525
msgid "Reading anaconda updates..."
msgstr "Anaconda frissítések olvasása..."

#: ../loader/loader.c:561
msgid ""
"Unable to download the updates image.  Please modify the updates location "
"below or press Cancel to proceed without updates.."
msgstr ""
"Nem sikerült letölteni a frissítés képmást.  Kérem módosítsa alább "
"afrissítések helyét, vagy nyomjon Mégsemet, hogy frissítések nélkül "
"folytassam a telepítést."

#: ../loader/loader.c:570
msgid "Error downloading updates image"
msgstr "Hiba a frissítés képmást letöltvén"

#: ../loader/loader.c:1196
#, c-format
msgid "You do not have enough RAM to install %s on this machine."
msgstr "Nincs elég memória ebben a gépben %s telepítéséhez."

#: ../loader/loader.c:1253
msgid "Media Detected"
msgstr "Adathordozó érzékelve"

#: ../loader/loader.c:1254
msgid "Local installation media detected..."
msgstr "Helyi telepítő adathordozó érzékelve..."

#: ../loader/loader.c:1370
msgid "Rescue Method"
msgstr "Mentő eljárás"

#: ../loader/loader.c:1371
msgid "Installation Method"
msgstr "Telepítő eljárás"

#: ../loader/loader.c:1373
msgid "What type of media contains the rescue image?"
msgstr "Milyen típusú hordozón van a mentő képmás?"

#: ../loader/loader.c:1375
msgid "What type of media contains the installation image?"
msgstr "Milyen típusú hordozón van a telepítő képmás?"

#: ../loader/loader.c:1408
msgid "No driver found"
msgstr "Nincs vezérlő"

#: ../loader/loader.c:1408
msgid "Select driver"
msgstr "Válasszon vezérlőt"

#: ../loader/loader.c:1409
msgid "Use a driver disk"
msgstr "Vezérlő lemez használata"

#: ../loader/loader.c:1410
msgid ""
"Unable to find any devices of the type needed for this installation type.  "
"Would you like to manually select your driver or use a driver disk?"
msgstr ""
"Nem találtam a telepítés típusának megfelelő eszközt.  Szeretne vezérlőt "
"választani, vagy vezérlő lemezt használni?"

#: ../loader/loader.c:1630
msgid "The following devices have been found on your system."
msgstr "A következő eszközöket találtam a rendszerben."

#: ../loader/loader.c:1632
msgid ""
"No device drivers have been loaded for your system.  Would you like to load "
"any now?"
msgstr ""
"Nincs eszköz vezérlő betöltve a rendszerbe.  Be szeretne most tölteni egyet?"

#: ../loader/loader.c:1636
msgid "Devices"
msgstr "Eszközök"

#: ../loader/loader.c:1637
msgid "Done"
msgstr "Kész"

#: ../loader/loader.c:1638
msgid "Add Device"
msgstr "Eszköz hozzáadása"

#: ../loader/loader.c:1850
#, c-format
msgid "loader has already been run.  Starting shell.\n"
msgstr "betöltő már lefutott.  Rendszerhéj indítása.\n"

#: ../loader/loader.c:2224
#, c-format
msgid "Running anaconda %s, the %s rescue mode - please wait...\n"
msgstr "Anaconda %s, a %s mentő mód fut – kérem várjon…\n"

#: ../loader/loader.c:2226
#, c-format
msgid "Running anaconda %s, the %s system installer - please wait...\n"
msgstr "Anaconda %s, a %s rendszer telepítő fut – kérem várjon…\n"

#: ../loader/mediacheck.c:46
#, c-format
msgid "Unable to find install image %s"
msgstr "Nem találtam e telepítési képmást: %s"

#: ../loader/mediacheck.c:52
#, c-format
msgid "Checking \"%s\"..."
msgstr "„%s” ellenőrzése..."

#: ../loader/mediacheck.c:54
#, c-format
msgid "Checking media now..."
msgstr "Adathordozó ellenőrzése folyik..."

#: ../loader/mediacheck.c:86
msgid ""
"Unable to read the disc checksum from the primary volume descriptor.  This "
"probably means the disc was created without adding the checksum."
msgstr ""
"Az elsődleges kötet leíróból nem sikerült kiolvasni a lemez ellenőrző "
"összegét.  Ez valószínűleg azt jelenti, hogy a lemezt ellenőrző összeg "
"nélkül készítették."

#: ../loader/mediacheck.c:93
msgid ""
"The image which was just tested has errors. This could be due to a corrupt "
"download or a bad disc.  If applicable, please clean the disc and try "
"again.  If this test continues to fail you should not continue the install."
msgstr ""
"A tesztelt képmás hibás. Ezt okozhatta letöltési hiba vagy lemezhiba.  Ha "
"érdemes, tisztítsa meg a lemezt, és próbálja újra.  Ne folytassa a "
"telepítést, ha a teszt továbbra sem sikeres."

#: ../loader/mediacheck.c:101
msgid "Success"
msgstr "Sikerült"

#: ../loader/mediacheck.c:102
msgid ""
"The image which was just tested was successfully verified.  It should be OK "
"to install from this media.  Note that not all media/drive errors can be "
"detected by the media check."
msgstr ""
"A lemezképet – amit éppen kipróbált – sikeresen ellenőriztem.  Erről a "
"adathordozóról nyugodtan telepíthet.  Figyelem: nem tud minden hordozó/"
"olvasó hibát érzékelni a lemezellenőrzés."

#: ../loader/method.c:323
#, c-format
msgid ""
"Would you like to perform a checksum test of the ISO image:\n"
"\n"
"   %s?"
msgstr ""
"El szeretné végezni az ellenőrző összeg vizsgálatát ezen ISO képmásra:\n"
"\n"
"   %s?"

#: ../loader/method.c:326
msgid "Checksum Test"
msgstr "Ellenőrző összeg vizsgálata"

#: ../loader/modules.c:336
#, c-format
msgid "Bad argument to device kickstart method command %s: %s"
msgstr "%s device kickstart parancsban hibás argumentum: %s"

#: ../loader/modules.c:348
msgid "A module name must be specified for the kickstart device command."
msgstr "Modul nevet is meg kell adni a kickstart device parancsában."

#: ../loader/net.c:111
msgid "Invalid Prefix"
msgstr "Érvénytelen előtag"

#: ../loader/net.c:112
msgid ""
"Prefix must be between 1 and 32 for IPv4 networks or between 1 and 128 for "
"IPv6 networks"
msgstr ""
"Az előtag 1 és 32 közé kell essen IPv4 hálózatnál, vagy 1 és 128 közé IPv6 "
"hálózatnál."

#: ../loader/net.c:454 ../loader/net.c:510
msgid "Network Error"
msgstr "Hálózat hiba"

#: ../loader/net.c:455 ../loader/net.c:511
msgid "There was an error configuring your network interface."
msgstr "Hálózat csatolót beállítván hiba történt."

#: ../loader/net.c:556
msgid "Enable IPv6 support"
msgstr "IPv6 támogatás engedélyezése"

#: ../loader/net.c:596
msgid "Configure TCP/IP"
msgstr "TCP/IP beállítás"

#: ../loader/net.c:655
msgid "Missing Protocol"
msgstr "Hiányzó protokoll"

#: ../loader/net.c:656
msgid "You must select at least one protocol (IPv4 or IPv6)."
msgstr "Legalább egy protokollt (IPv4 vagy IPv6) ki kell választani."

#: ../loader/net.c:663
msgid "IPv4 Needed for NFS"
msgstr "NFS-hez IPv4 kell"

#: ../loader/net.c:664
msgid "NFS installation method requires IPv4 support."
msgstr "NFS telepítő eljárás IPv4 támogatást igényel."

#: ../loader/net.c:763
msgid "IPv4 address:"
msgstr "IPv4 cím:"

#: ../loader/net.c:775 ../loader/net.c:842 tmp/netconfig.glade.h:1
msgid "/"
msgstr "/"

#: ../loader/net.c:830
msgid "IPv6 address:"
msgstr "IPv6 cím:"

#: ../loader/net.c:904
msgid "Name Server:"
msgstr "Névkiszolgáló:"

#: ../loader/net.c:943
msgid ""
"Enter the IPv4 and/or the IPv6 address and prefix (address / prefix).  For "
"IPv4, the dotted-quad netmask or the CIDR-style prefix are acceptable. The "
"gateway and name server fields must be valid IPv4 or IPv6 addresses."
msgstr ""
"Adjon meg IPv4 és/vagy IPv6 címet és előtagot (cím / előtag).  IPv4 esetén "
"használható a négytagú, pontokkal elválasztott hálózat maszk, vagy a CIDR "
"stílusú előtag. Az átjáró és a névkiszolgáló mezőkben érvényes IPv4 vagy "
"IPv6 címeknek kell szerepelni."

#: ../loader/net.c:963
msgid "Manual TCP/IP Configuration"
msgstr "Kézi TCP/IP beállítás"

#: ../loader/net.c:1086 ../loader/net.c:1093
msgid "Missing Information"
msgstr "Hiányzó információ"

#: ../loader/net.c:1087
msgid ""
"You must enter both a valid IPv4 address and a network mask or CIDR prefix."
msgstr ""
"Meg kell adnia egy érvényes IPv4 címet, valamint vagy egy hálózat maszkot, "
"vagy egy CIDR-előtagot."

#: ../loader/net.c:1094
msgid "You must enter both a valid IPv6 address and a CIDR prefix."
msgstr "Meg kell adni egy érvényes IPv6 címet és egy CIDR-előtagot."

#: ../loader/net.c:1542
#, c-format
msgid "Bad argument to kickstart network command %s: %s"
msgstr "%s network kickstart parancsban hibás argumentum: %s"

#: ../loader/net.c:1565
#, c-format
msgid "Bad bootproto %s specified in network command"
msgstr "Network parancsban hibás a bootproto %s"

#: ../loader/net.c:1637
msgid "Seconds:"
msgstr "Másodpercek:"

#: ../loader/net.c:1803
msgid "Networking Device"
msgstr "Hálózat eszköz"

#: ../loader/net.c:1804
msgid ""
"You have multiple network devices on this system. Which would you like to "
"install through?"
msgstr ""
"Több hálózat eszköz van a rendszerben. Melyiken át szeretné elvégezni a "
"telepítést?"

#: ../loader/net.c:1808
msgid "Identify"
msgstr "Azonosítás"

#: ../loader/net.c:1817
msgid "You can identify the physical port for"
msgstr "Azonosíthat egy fizikai kaput "

#: ../loader/net.c:1819
msgid ""
"by flashing the LED lights for a number of seconds.  Enter a number between "
"1 and 30 to set the duration to flash the LED port lights."
msgstr ""
"eszközhöz a LED lámpácskát villogtatva egy megadott ideig.  Adjon meg egy "
"számot 1 és 30 között, hogy beállítsa a LED kapu fény villogás idejét."

#: ../loader/net.c:1829
msgid "Identify NIC"
msgstr "Hálózat csatoló azonosítása"

#: ../loader/net.c:1842
msgid "Invalid Duration"
msgstr "Érvénytelen időtartam"

#: ../loader/net.c:1843
msgid "You must enter the number of seconds as an integer between 1 and 30."
msgstr "Meg kell adnia a másodpercek számát 1 és 30 közötti egészként."

#: ../loader/net.c:1855
#, c-format
msgid "Flashing %s port lights for %d seconds..."
msgstr "%s kapu fények villogtatása %d másodpercig…"

#: ../loader/net.c:2015 ../loader/net.c:2019
#, c-format
msgid "Waiting for NetworkManager to configure %s...\n"
msgstr "Várok NetworkManager %s beállítására...\n"

#: ../loader/nfsinstall.c:68
msgid "NFS server name:"
msgstr "NFS kiszolgáló név:"

#: ../loader/nfsinstall.c:72
#, c-format
msgid "%s directory:"
msgstr "%s mappa:"

#: ../loader/nfsinstall.c:83
#, c-format
msgid "Please enter the server name and path to your %s installation image."
msgstr ""
"Kérem adja meg a kiszolgáló nevét és az utat az ön %s telepítő képéhez."

#: ../loader/nfsinstall.c:90
msgid "NFS Setup"
msgstr "NFS beállítás"

#: ../loader/nfsinstall.c:249
msgid "That directory could not be mounted from the server."
msgstr "Azt a mappát nem sikerült becsatolni"

#: ../loader/nfsinstall.c:260
#, c-format
msgid "That directory does not seem to contain a %s installation image."
msgstr "Úgy tűnik, az a mappa nem tartalmaz %s telepítő képet."

#: ../loader/nfsinstall.c:336
#, c-format
msgid "Bad argument to NFS kickstart method command %s: %s"
msgstr "%s NFS kickstart parancsban hibás argumentum: %s"

#: ../loader/telnetd.c:89 ../loader/telnetd.c:128
msgid "Telnet"
msgstr "Telnet"

#: ../loader/telnetd.c:89
msgid "Waiting for telnet connection..."
msgstr "Várakozás a telnet kapcsolatra..."

#: ../loader/telnetd.c:128
msgid "Running anaconda via telnet..."
msgstr "Anaconda elindítása telneten át..."

#: ../loader/urlinstall.c:84
#, c-format
msgid "Unable to retrieve %s://%s%s."
msgstr "Nem tudok letölteni %s://%s/%s helyről."

#: ../loader/urlinstall.c:176
msgid "Unable to retrieve the install image."
msgstr "Nem tudtam letölteni a telepítő képet."

#: ../loader/urlinstall.c:419
#, c-format
msgid "Bad argument to Url kickstart method command %s: %s"
msgstr "%s Url kickstart parancsban hibás argumentum: %s"

#: ../loader/urlinstall.c:428
msgid "Must supply a --url argument to Url kickstart method."
msgstr "Meg kell adni egy --url argumentumot az Url kickstart parancsnak."

#: ../loader/urlinstall.c:437
#, c-format
msgid "Unknown Url method %s"
msgstr "Ismeretlen Url parancs %s"

#: ../loader/urls.c:235 ../loader/urls.c:237 ../loader/urls.c:240
msgid "Retrieving"
msgstr "Letöltés"

#: ../loader/urls.c:295
#, c-format
msgid ""
"Please enter the URL containing the %s installation image on your server."
msgstr ""
"Kérem, adja meg az URL-t, ami %s telepítő képeket tartalmazza a kiszolgálón."

#: ../loader/urls.c:321
msgid "URL Setup"
msgstr "URL beállítás"

#: ../loader/urls.c:329
msgid "You must enter a URL."
msgstr "Meg kell adni egy URL-t."

#: ../loader/urls.c:335
msgid "URL must be either an ftp or http URL"
msgstr "Az URL vagy ftp vagy http URL kell legyen."

#: ../loader/urls.c:346
msgid "Unknown Host"
msgstr "Ismeretlen gazda"

#: ../loader/urls.c:347
#, c-format
msgid "%s is not a valid hostname."
msgstr "%s nem érvényes gazdanév."

#: ../loader/windows.c:65
msgid "Loading SCSI driver"
msgstr "SCSI vezérlő betöltése"

#: ../loader/windows.c:66
#, c-format
msgid "Loading %s driver..."
msgstr "%s vezérlő betöltése..."

#: tmp/GroupSelector.glade.h:1
msgid ""
"Some packages associated with this group are not required to be installed "
"but may provide additional functionality.  Please choose the packages which "
"you would like to have installed."
msgstr ""
"E csoportban néhány csomagot nem szükséges telepíteni, de további "
"szolgáltatásokat tehetnek lehetővé.  Kérem válassza ki a telepíteni kívánt "
"csomagokat."

#: tmp/GroupSelector.glade.h:2
msgid "_Deselect"
msgstr "Ki_húzás"

#: tmp/GroupSelector.glade.h:3
msgid "_Deselect all optional packages"
msgstr "Minden választható csomag ki_húzása"

#: tmp/GroupSelector.glade.h:4
msgid "_Optional packages"
msgstr "_Választható csomagok"

#: tmp/GroupSelector.glade.h:5
msgid "_Select"
msgstr "_Bejelölés"

#: tmp/GroupSelector.glade.h:6
msgid "_Select all optional packages"
msgstr "_Minden választható csomag megjelölése"

#: tmp/GroupSelector.glade.h:7
msgid "dialog1"
msgstr "dialog1"

#: tmp/account.glade.h:1
msgid "Confirm:"
msgstr "Megerősítés:"

#: tmp/account.glade.h:2
msgid "Root Password:"
msgstr "Rendszergazda jelszó:"

#: tmp/account.glade.h:3
msgid ""
"The root account is used for administering the system.  Enter a password for "
"the root user."
msgstr ""
"A root számlát rendszer adminisztrációra használják.  Adja jelszót a root "
"használónak."

#: tmp/adddrive.glade.h:1
msgid "Add _ZFCP LUN"
msgstr "_ZFCP LUN hozzáadása"

#: tmp/adddrive.glade.h:2
msgid "Add _iSCSI target"
msgstr "_iSCSI cél hozzáadása"

#: tmp/adddrive.glade.h:4
msgid "Disable _dmraid device"
msgstr "A _dmraid eszköz letiltása"

#: tmp/adddrive.glade.h:6
msgid "_Add drive"
msgstr "_Vezérlő hozzáadása"

#: tmp/addrepo.glade.h:1
msgid "<b>Repository _name:</b>"
msgstr "<b>Tároló _név:</b>"

#: tmp/addrepo.glade.h:2
msgid "<b>Repository _type:</b>"
msgstr "<b>Tároló _típus:</b>"

#: tmp/addrepo.glade.h:4
msgid "Configure _proxy"
msgstr "_Proxy beállítás"

#: tmp/addrepo.glade.h:5
msgid ""
"HTTP/FTP\n"
"CD/DVD\n"
"NFS\n"
"Hard Drive"
msgstr ""
"HTTP/FTP\n"
"CD/DVD\n"
"NFS\n"
"merevlemez"

#: tmp/addrepo.glade.h:9
msgid ""
"Please provide the configuration information for this software repository."
msgstr "Kérem, adja meg beállítás információkat e szoftver tárolóhoz."

#: tmp/addrepo.glade.h:10
msgid "Proxy U_RL (host:port)"
msgstr "Átjátszó URL (gazda:kapu)"

#: tmp/addrepo.glade.h:11
msgid "Proxy pass_word"
msgstr "Proxy jel_szó"

#: tmp/addrepo.glade.h:12
msgid "Proxy u_sername"
msgstr "Proxy _használó"

#: tmp/addrepo.glade.h:13
msgid "Repository _URL"
msgstr "Tároló _URL"

#: tmp/addrepo.glade.h:14
msgid "Select A Directory"
msgstr "Mappa választás"

#: tmp/addrepo.glade.h:15
msgid "URL is a _mirror list"
msgstr "URL egy _tükör lista"

#: tmp/addrepo.glade.h:16
msgid "_Directory"
msgstr "_Mappa"

#: tmp/addrepo.glade.h:17
msgid "_Options"
msgstr "_Beállítás"

#: tmp/addrepo.glade.h:18
msgid "_Partition"
msgstr "_Rész"

#: tmp/addrepo.glade.h:19
msgid "_Path"
msgstr "_Út"

#: tmp/addrepo.glade.h:20
msgid "_Server"
msgstr "_Kiszolgáló"

#: tmp/anaconda.glade.h:1
msgid "Reboo_t"
msgstr "Ú_jraindítás"

#: tmp/anaconda.glade.h:3
msgid "_Next"
msgstr "_Tovább"

#: tmp/autopart.glade.h:1
msgid "<b>Resize _target (in MB):</b>"
msgstr "<b>_Cél átméretezése (MB-ban):</b>"

#: tmp/autopart.glade.h:3
msgid "Re_view and modify partitioning layout"
msgstr "Felosztás felül_vizsgálata és megváltoztatása"

#: tmp/autopart.glade.h:4
msgid "Volume to Resize"
msgstr ""

#: tmp/autopart.glade.h:5
msgid "What drive would you like to _boot this installation from?"
msgstr "Melyik eszközről szeretné in_dítani e telepítést?"

#: tmp/autopart.glade.h:6
msgid ""
"Which partition would you like to resize to make room for your installation?"
msgstr ""
"Melyik részt szeretné átméretezni, hogy helyet csináljon a telepítésnek?"

#: tmp/autopart.glade.h:7
msgid "_Advanced storage configuration"
msgstr "_Haladó tároló eszköz beállítás"

#: tmp/autopart.glade.h:8
msgid "_Encrypt system"
msgstr "Rendszer _titkosítása"

#: tmp/autopart.glade.h:10
msgid "_Select the drive(s) to use for this installation."
msgstr "_Válassza ki a telepítéshez használt eszközöket."

#: tmp/blwhere.glade.h:1
msgid "/boot"
msgstr "/boot"

#: tmp/blwhere.glade.h:2
msgid "BIOS Drive Order"
msgstr "BIOS eszköz sorrend"

#: tmp/blwhere.glade.h:3
msgid "Boot loader device"
msgstr "Rendszerindító eszköz"

#: tmp/blwhere.glade.h:4
msgid "First BIOS drive:"
msgstr "Első BIOS eszköz:"

#: tmp/blwhere.glade.h:5
msgid "Fourth BIOS drive:"
msgstr "Negyedik BIOS eszköz:"

#: tmp/blwhere.glade.h:6
msgid "MBR"
msgstr "MBR"

#: tmp/blwhere.glade.h:7
msgid "Second BIOS drive:"
msgstr "Második BIOS eszköz:"

#: tmp/blwhere.glade.h:8
msgid "Third BIOS drive:"
msgstr "Harmadik BIOS eszköz:"

#: tmp/blwhere.glade.h:9
msgid "Where would you like to install the boot loader for your system?"
msgstr "Hova szeretné telepíteni a rendszerindítót?"

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "Infó"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "_Részletek"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "Hiba l_eírás"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "Cél _fájl"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage device\n"
"Local disk\n"
"Remote server (scp)"
msgstr ""
"Helyi tároló eszköz\n"
"Helyi lemez\n"
"Távoli kiszolgáló (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "Kérem válassza ki a célt a nyomkövetés mentésének."

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "Fájl választás"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "_Gazda (gazda:kapu)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "J_elszó"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "_Használó név"

#: tmp/instkey.glade.h:2
#, no-c-format
msgid "%(instkey)s:"
msgstr "%(instkey)s:"

#: tmp/instkey.glade.h:4
#, no-c-format
msgid "Please enter your %(instkey)s."
msgstr "Adja meg ezt: %(instkey)s"

#: tmp/iscsi-config.glade.h:1
msgid "<b>CHAP _Password:</b>"
msgstr "<b>CHAP _Jelszó:</b>"

#: tmp/iscsi-config.glade.h:2
msgid "<b>CHAP _Username:</b>"
msgstr "<b>CHAP _Használónév:</b>"

#: tmp/iscsi-config.glade.h:3
msgid "<b>Reverse CHAP P_assword:</b>"
msgstr "<b>Inverz CHAP J_elszó:</b>"

#: tmp/iscsi-config.glade.h:4
msgid "<b>Reverse CHAP U_sername:</b>"
msgstr "<b>Inverz CHAP H_asználónév:</b>"

#: tmp/iscsi-config.glade.h:5
msgid "<b>_Target IP Address:</b>"
msgstr "<b>_Cél IP cím:</b>"

#: tmp/iscsi-config.glade.h:6
msgid "<b>iSCSI Initiator _Name:</b>"
msgstr "<b>iSCSI kezdeményező _név:</b>"

#: tmp/iscsi-config.glade.h:9
msgid "_Add target"
msgstr "_Cél hozzáadása"

#: tmp/liveinst.desktop.in.h:1
msgid "Install"
msgstr "Telepítés"

#: tmp/liveinst.desktop.in.h:2
msgid "Install the live CD to your hard disk"
msgstr "Élő CD telepítése a merevlemezre"

#: tmp/liveinst.desktop.in.h:3
msgid "Install to Hard Drive"
msgstr "Telepítés merevlemezre"

#: tmp/lukspassphrase.glade.h:1
msgid ""
"Also add this passphrase to all existing encrypted devices to streamline the "
"boot process"
msgstr ""
"E jelszó használata minden meglévő titkosított eszközhöz, hogy meggyorsítsuk "
"a betöltés folyamatát"

#: tmp/lukspassphrase.glade.h:2
msgid ""
"Choose a passphrase for this encrypted partition. You will be prompted for "
"the passphrase during system boot."
msgstr ""
"Válasszon jelszót e titkosított résznek. A rendszerindító induláskor kérni "
"fogja ezt a jelszót."

#: tmp/lukspassphrase.glade.h:3
msgid "Confirm passphrase:"
msgstr "Jelszó megerősítése:"

#: tmp/lukspassphrase.glade.h:4
msgid "Enter passphrase for encrypted partition"
msgstr "Adja meg a titkosított rész jelszavát"

#: tmp/lukspassphrase.glade.h:5
msgid "Enter passphrase:"
msgstr "Jelszó megadása:"

#: tmp/netconfig.glade.h:2
msgid "<b>Gateway:</b>"
msgstr "<b>Átjáró:</b>"

#: tmp/netconfig.glade.h:3
msgid "<b>IPv4 Address:</b>"
msgstr "<b>IPv4 cím:</b>"

#: tmp/netconfig.glade.h:4
msgid "<b>IPv6 Address:</b>"
msgstr "<b>IPv6 cím:</b>"

#: tmp/netconfig.glade.h:5
msgid "<b>Nameserver:</b>"
msgstr "<b>Névkiszolgáló:</b>"

#: tmp/netconfig.glade.h:6
msgid "<b>_Interface:</b>"
msgstr "<b>_Csatoló:</b>"

#: tmp/netconfig.glade.h:7
msgid "Enable IPv_4 support"
msgstr "IPv_4 támogatás engedélyezése"

#: tmp/netconfig.glade.h:8
msgid "Enable IPv_6 support"
msgstr "IPv_6 támogatás engedélyezése"

#: tmp/netconfig.glade.h:11
msgid "Use _dynamic IP configuration (DHCP)"
msgstr "_Változó IP beállítás (DHCP)"

#: tmp/network.glade.h:1
msgid "Hostname:"
msgstr "Gazdanév:"

#: tmp/network.glade.h:2
msgid ""
"Please name this computer.  The hostname identifies the computer on a "
"network."
msgstr ""
"Kérem nevezze el e számítógépet.  Hálózatban a gazda név azonosítja a "
"számítógépet."

#: tmp/tasksel.glade.h:1
msgid "Customize _later"
msgstr "Testreszabás _később"

#: tmp/tasksel.glade.h:2
msgid ""
"Please select any additional repositories that you want to use for software "
"installation."
msgstr ""
"Kérem válasszon ki minden további tárolót, amit használni akar a szoftver "
"telepítéséhez."

#: tmp/tasksel.glade.h:4
#, no-c-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage.  What additional tasks would you like your system to "
"support?"
msgstr ""
"%s alapértelmezett telepítése tartalmaz egy általános Internet használathoz "
"készült szoftver csoportot.  Milyen további feladatokat szeretne, hogy a "
"rendszer támogassa?"

#: tmp/tasksel.glade.h:5
msgid ""
"You can further customize the software selection now, or after install via "
"the software management application."
msgstr ""
"Még tovább testreszabhatja a szoftver válogatást most vagy később a "
"telepítés után a szoftverkezelő alkalmazással."

#: tmp/tasksel.glade.h:6
msgid "_Add additional software repositories"
msgstr "További szoftver tárolók _hozzáadása"

#: tmp/tasksel.glade.h:7
msgid "_Customize now"
msgstr "_Testreszabás most"

#: tmp/tasksel.glade.h:8
msgid "_Modify repository"
msgstr "_Tároló megváltoztatása"

#: tmp/zfcp-config.glade.h:1
msgid "<b>Device number:</b>"
msgstr "<b>Eszköz szám:</b>"

#: tmp/zfcp-config.glade.h:2
msgid "<b>FCP LUN:</b>"
msgstr "<b>FCP LUN:</b>"

#: tmp/zfcp-config.glade.h:3
msgid "<b>WWPN:</b>"
msgstr "<b>WWPN:</b>"

#: tmp/zfcp-config.glade.h:4
msgid "Add FCP device"
msgstr "FCP eszköz hozzáadása"

#. generated from lang-table
msgid "Afrikaans"
msgstr "afrikán (Dél-Afrika-i holland)"

#. generated from lang-table
msgid "Arabic"
msgstr "arab"

#. generated from lang-table
msgid "Assamese"
msgstr "asszám (India)"

#. generated from lang-table
msgid "Bengali"
msgstr "bengáli"

#. generated from lang-table
msgid "Bengali(India)"
msgstr "bengáli (India)"

#. generated from lang-table
msgid "Bulgarian"
msgstr "bolgár"

#. generated from lang-table
msgid "Catalan"
msgstr "katalán"

#. generated from lang-table
msgid "Chinese(Simplified)"
msgstr "kínai (egyszerűsített)"

#. generated from lang-table
msgid "Chinese(Traditional)"
msgstr "kínai (hagyományos)"

#. generated from lang-table
msgid "Croatian"
msgstr "horvát"

#. generated from lang-table
msgid "Czech"
msgstr "cseh"

#. generated from lang-table
msgid "Danish"
msgstr "dán"

#. generated from lang-table
msgid "Dutch"
msgstr "holland"

#. generated from lang-table
msgid "English"
msgstr "angol"

#. generated from lang-table
msgid "Estonian"
msgstr "észt"

#. generated from lang-table
msgid "Finnish"
msgstr "finn"

#. generated from lang-table
msgid "French"
msgstr "francia"

#. generated from lang-table
msgid "German"
msgstr "német"

#. generated from lang-table
msgid "Greek"
msgstr "görög"

#. generated from lang-table
msgid "Gujarati"
msgstr "gudzsarati (India)"

#. generated from lang-table
msgid "Hebrew"
msgstr "héber"

#. generated from lang-table
msgid "Hindi"
msgstr "hindi (India)"

#. generated from lang-table
msgid "Hungarian"
msgstr "magyar"

#. generated from lang-table
msgid "Icelandic"
msgstr "izlandi"

#. generated from lang-table
msgid "Iloko"
msgstr "iloko (Fülöp-szk.)"

#. generated from lang-table
msgid "Indonesian"
msgstr "indonéz"

#. generated from lang-table
msgid "Italian"
msgstr "olasz"

#. generated from lang-table
msgid "Japanese"
msgstr "japán"

#. generated from lang-table
msgid "Kannada"
msgstr "kanada (India)"

#. generated from lang-table
msgid "Korean"
msgstr "koreai"

#. generated from lang-table
msgid "Macedonian"
msgstr "macedón"

#. generated from lang-table
msgid "Maithili"
msgstr "majtili (India/Nepál)"

#. generated from lang-table
msgid "Malay"
msgstr "maláj"

#. generated from lang-table
msgid "Malayalam"
msgstr "malajalam (India)"

#. generated from lang-table
msgid "Marathi"
msgstr "marati (India)"

#. generated from lang-table
msgid "Nepali"
msgstr "nepáli"

#. generated from lang-table
msgid "Norwegian(Bokmål)"
msgstr "ónorvég"

#. generated from lang-table
msgid "Northern Sotho"
msgstr "északszoto (Dél-Afrika)"

#. generated from lang-table
msgid "Oriya"
msgstr "orija (India)"

#. generated from lang-table
msgid "Persian"
msgstr "perzsa"

#. generated from lang-table
msgid "Polish"
msgstr "lengyel"

#. generated from lang-table
msgid "Portuguese"
msgstr "portugál"

#. generated from lang-table
msgid "Portuguese(Brazilian)"
msgstr "portugál (brazil)"

#. generated from lang-table
msgid "Punjabi"
msgstr "pandzsab (India/Pakisztán)"

#. generated from lang-table
msgid "Romanian"
msgstr "román"

#. generated from lang-table
msgid "Russian"
msgstr "orosz"

#. generated from lang-table
msgid "Serbian"
msgstr "szerb"

#. generated from lang-table
msgid "Serbian(Latin)"
msgstr "szerb (latin)"

#. generated from lang-table
msgid "Sinhala"
msgstr "szinala (Sri Lanka)"

#. generated from lang-table
msgid "Slovak"
msgstr "szlovák"

#. generated from lang-table
msgid "Slovenian"
msgstr "szlovén"

#. generated from lang-table
msgid "Spanish"
msgstr "spanyol"

#. generated from lang-table
msgid "Swedish"
msgstr "svéd"

#. generated from lang-table
msgid "Tajik"
msgstr "tadzsik"

#. generated from lang-table
msgid "Tamil"
msgstr "tamil (India/Sri Lanka)"

#. generated from lang-table
msgid "Telugu"
msgstr "telugu (India)"

#. generated from lang-table
msgid "Turkish"
msgstr "török"

#. generated from lang-table
msgid "Ukrainian"
msgstr "ukrán"

#. generated from lang-table
msgid "Vietnamese"
msgstr "vietnámi"

#. generated from lang-table
msgid "Welsh"
msgstr "velszi"

#. generated from lang-table
msgid "Zulu"
msgstr "zulu (Dél-Afrika)"

